<?php $rpg_tab='progress';include APPPATH.'views/learn/english_rpg/_tabs.php'; ?>
<div class="container-xl">
  <div class="page-header mb-3"><div><div class="page-pretitle">PEMBELAJARAN · ENGLISH RPG</div><h2 class="page-title">Progres Pengguna RPG</h2><p class="text-secondary mb-0">Kelola perjalanan, capaian chapter, dan riwayat setiap pemain khusus English RPG.</p></div></div>
  <div class="row row-cards mb-3">
    <?php foreach([['Pemain RPG',$summary['players'],'users'],['Aktif 30 hari',$summary['active'],'activity'],['Chapter selesai',$summary['completed'],'trophy'],['Total percobaan',$summary['attempts'],'swords']] as $s): ?>
    <div class="col-6 col-lg-3"><div class="card"><div class="card-body"><div class="d-flex align-items-center"><span class="avatar bg-blue-lt me-3"><i class="ti ti-<?= $s[2]; ?>"></i></span><div><div class="h2 mb-0"><?= number_format($s[1]); ?></div><div class="text-secondary"><?= $s[0]; ?></div></div></div></div></div></div>
    <?php endforeach; ?>
  </div>
  <div class="card mb-3"><div class="card-body"><?= form_open('learn-english-rpg/progress',['method'=>'get']); ?><div class="row g-2"><div class="col-md"><input class="form-control" name="q" value="<?= html_escape($filters['q']); ?>" placeholder="Cari nama, username, atau nama hero"></div><div class="col-md-3"><select class="form-select" name="status"><option value="">Semua status</option><option value="playing" <?= $filters['status']==='playing'?'selected':''; ?>>Sedang bermain</option><option value="completed" <?= $filters['status']==='completed'?'selected':''; ?>>Pernah menamatkan chapter</option></select></div><div class="col-auto"><button class="btn btn-primary"><i class="ti ti-search"></i> Tampilkan</button></div></div><?= form_close(); ?></div></div>
  <div class="card"><div class="table-responsive"><table class="table table-vcenter card-table"><thead><tr><th>Pemain</th><th>Perjalanan</th><th>Chapter</th><th>Statistik</th><th>Aktivitas terakhir</th><th></th></tr></thead><tbody>
  <?php foreach($players as $p): ?><tr><td><div class="d-flex align-items-center"><span class="avatar avatar-sm bg-purple-lt me-2"><?= html_escape($p['avatar']); ?></span><div><strong><?= html_escape($p['full_name']?:$p['hero_name']); ?></strong><small class="d-block text-secondary">@<?= html_escape($p['username']); ?> · Hero: <?= html_escape($p['hero_name']); ?></small></div></div></td><td><?= $p['latest_chapter']?html_escape($p['latest_chapter']):'<span class="text-secondary">Belum mulai</span>'; ?></td><td><strong><?= (int)$p['chapters_completed']; ?></strong> selesai / <?= (int)$p['chapters_started']; ?> dimulai</td><td><span class="text-success"><?= (int)$p['total_correct']; ?> benar</span> · <span class="text-danger"><?= (int)$p['total_wrong']; ?> salah</span><small class="d-block text-secondary"><?= number_format((int)$p['total_xp']); ?> XP</small></td><td><?= $p['last_progress_at']?html_escape(date('d M Y H:i',strtotime($p['last_progress_at']))):'—'; ?></td><td><a class="btn btn-primary btn-sm" href="<?= base_url('learn-english-rpg/progress/user/'.$p['user_id']); ?>"><i class="ti ti-list-details"></i> Kelola & Riwayat</a></td></tr><?php endforeach; ?>
  </tbody></table></div><?php if(!$players): ?><div class="card-body text-center text-secondary py-5">Belum ada pemain RPG yang cocok dengan filter.</div><?php endif; ?></div>
</div>
