<?php $rpg_tab='progress';include APPPATH.'views/learn/english_rpg/_tabs.php';$u=$data['user']; ?>
<div class="container-xl">
  <div class="page-header mb-3"><div><div class="page-pretitle"><a href="<?= base_url('learn-english-rpg/progress'); ?>">Progres Pengguna RPG</a> · Kelola & Riwayat</div><h2 class="page-title"><?= html_escape($u['avatar'].' '.($u['full_name']?:$u['hero_name'])); ?></h2><p class="text-secondary mb-0">@<?= html_escape($u['username']); ?> · Hero <?= html_escape($u['hero_name']); ?> · <?= (int)$u['total_correct']; ?> benar · <?= (int)$u['total_wrong']; ?> salah · reputasi <?= (int)$u['reputation']; ?></p></div><div class="ms-auto"><a class="btn btn-outline-secondary" href="<?= base_url('learn-english-rpg/progress'); ?>"><i class="ti ti-arrow-left"></i> Semua pemain</a></div></div>
  <?php foreach(['success','error'] as $f)if($this->session->flashdata($f)): ?><div class="alert alert-<?= $f==='success'?'success':'danger'; ?>"><?= html_escape($this->session->flashdata($f)); ?></div><?php endif; ?>
  <div class="alert alert-info"><div class="d-flex"><i class="ti ti-info-circle fs-2 me-2"></i><div><strong>Reset bertingkat per chapter</strong><div>Reset mulai Chapter N akan menghapus progres Chapter N dan semua chapter setelahnya. Chapter sebelumnya tetap utuh, sehingga pemain memulai kembali dari awal Chapter N.</div></div></div></div>
  <?php $s2=$season2??null; $s2q=$s2['quest']??null; $s2qs=$s2['quest_state']??[]; $s2state=$s2['state']??null; ?>
  <?php if($s2): ?>
  <div class="card mb-3 border-primary">
    <div class="card-header bg-primary-lt"><div><h3 class="card-title mb-1"><i class="ti ti-world me-1"></i> Season 2 · <?= html_escape($s2['map']['title']); ?></h3><div class="text-secondary">Progres dunia interaktif, quest, dialog, dan riwayat pengguna ini.</div></div><span class="badge bg-primary-lt text-primary"><?= html_escape(ucfirst((string)($s2qs['status']??'not_started'))); ?></span></div>
    <div class="card-body">
      <div class="row g-3">
        <div class="col-md-4"><div class="text-secondary small text-uppercase fw-bold">Posisi terakhir</div><strong><?= $s2state ? 'X '.(int)$s2state['x'].' · Y '.(int)$s2state['y'] : 'Belum mulai'; ?></strong><small class="d-block text-secondary"><?= $s2state && !empty($s2state['last_seen_at']) ? html_escape(date('d M Y H:i',strtotime($s2state['last_seen_at']))) : 'Belum ada sesi'; ?></small></div>
        <div class="col-md-4"><div class="text-secondary small text-uppercase fw-bold">Quest Chapter 1</div><strong><?= html_escape($s2q['title']??'—'); ?></strong><small class="d-block"><?= (int)($s2qs['progress']??0); ?>/<?= (int)($s2q['objective_target']??0); ?> clue · <?= html_escape(ucfirst((string)($s2qs['status']??'not_started'))); ?></small></div>
        <div class="col-md-4"><div class="text-secondary small text-uppercase fw-bold">World XP</div><strong><?= number_format((int)($s2state['world_xp']??0)); ?> XP</strong><small class="d-block text-secondary"><?= $s2qs['status']==='claimed'?'Chapter selesai':'Belum selesai'; ?></small></div>
      </div>
      <div class="d-flex flex-wrap gap-2 align-items-center mt-3 pt-3 border-top"><small class="text-secondary flex-grow-1">Reset akan menghapus koordinat, pertanyaan, clue, interaksi, XP Season 2, dan hadiah Lantern Sigil. Progres Season 1 tetap aman.</small><?= form_open('learn-english-rpg/progress/user/'.$u['id'].'/reset-season2',['class'=>'d-inline','onsubmit'=>"return confirm('Reset seluruh progres Season 2 pengguna ini?');"]); ?><button type="submit" class="btn btn-outline-danger btn-sm" <?= (!$s2state && ($s2qs['status']??'not_started')==='not_started')?'disabled':''; ?>><i class="ti ti-rewind-backward-10 me-1"></i> Reset Season 2</button><?= form_close(); ?></div>
      <div class="mt-3 pt-3 border-top"><div class="text-secondary small text-uppercase fw-bold mb-2">Riwayat sesi, dialog, dan jawaban Season 2</div><div class="table-responsive" style="max-height:280px"><table class="table table-sm table-vcenter mb-0"><thead><tr><th>Waktu</th><th>NPC</th><th>Aksi</th><th>Detail</th></tr></thead><tbody><?php foreach(($s2['interactions']??[]) as $interaction): $payload=$interaction['payload']??[]; ?><tr><td class="text-secondary"><?= html_escape(date('d M H:i',strtotime($interaction['created_at']))); ?></td><td><?= html_escape($interaction['npc_name']??'—'); ?></td><td><span class="badge bg-blue-lt"><?= html_escape(str_replace('_',' ',ucfirst($interaction['interaction_type']))); ?></span></td><td><?= isset($payload['stage'])?'Stage '.html_escape($payload['stage']):''; ?><?= array_key_exists('correct',$payload)?' · '.($payload['correct']?'Benar':'Salah'):''; ?><?= isset($payload['progress'])?' · '.(int)$payload['progress'].' clue':''; ?></td></tr><?php endforeach; ?><?php if(empty($s2['interactions'])): ?><tr><td colspan="4" class="text-secondary">Belum ada aktivitas Season 2.</td></tr><?php endif; ?></tbody></table></div></div>
    </div>
  </div>
  <?php endif; ?>
  <div class="card mb-3"><div class="card-header"><h3 class="card-title">Perjalanan per Chapter</h3></div><div class="table-responsive"><table class="table table-vcenter card-table"><thead><tr><th>Chapter</th><th>Progres</th><th>Jawaban / attempt</th><th>XP & nyawa</th><th>Waktu</th><th>Reset dari sini</th></tr></thead><tbody>
  <?php foreach($data['episodes'] as $i=>$e):$pct=$e['total_scenes']?min(100,round((int)$e['current_scene']*100/(int)$e['total_scenes'])):0; ?><tr class="<?= $e['progress_id']?'':'text-secondary'; ?>"><td><span class="badge bg-purple-lt mb-1">Chapter <?= $i+1; ?></span><strong class="d-block text-body"><?= html_escape($e['title']); ?></strong><small><?= html_escape($e['subtitle']); ?></small></td><td><div class="d-flex justify-content-between"><span><?= (int)$e['current_scene']; ?>/<?= (int)$e['total_scenes']; ?> adegan</span><span><?= $pct; ?>%</span></div><div class="progress progress-sm"><div class="progress-bar <?= $e['is_completed']?'bg-success':'bg-blue'; ?>" style="width:<?= $pct; ?>%"></div></div><span class="badge mt-1 bg-<?= $e['is_completed']?'success':'blue'; ?>-lt"><?= $e['is_completed']?'Tamat':($e['progress_id']?'Berjalan':'Belum mulai'); ?></span></td><td><span class="text-success"><?= (int)$e['correct_attempts']; ?> benar</span> · <span class="text-danger"><?= (int)$e['wrong_attempts']; ?> salah</span><small class="d-block"><?= (int)$e['attempts']; ?> attempt tercatat</small></td><td><?= number_format((int)$e['xp']); ?> XP<small class="d-block">❤️ <?= (int)($e['hearts']??0); ?></small></td><td><small>Mulai: <?= $e['first_attempt_at']?html_escape(date('d M Y H:i',strtotime($e['first_attempt_at']))):'—'; ?><br>Terakhir: <?= $e['last_at']?html_escape(date('d M Y H:i',strtotime($e['last_at']))):'—'; ?></small></td><td><?php if($e['can_reset']):$names=implode('|||',$e['affected_titles']); ?><?= form_open('learn-english-rpg/progress/user/'.$u['id'].'/reset-from/'.$e['id'],['class'=>'rpg-reset-form']); ?><button type="button" class="btn btn-outline-danger btn-sm js-rpg-reset" data-bs-toggle="modal" data-bs-target="#rpgResetModal" data-chapter="<?= $i+1; ?>" data-title="<?= html_escape($e['title']); ?>" data-safe="<?= $i; ?>" data-impact="<?= html_escape($names); ?>"><i class="ti ti-rewind-backward-10"></i> Mulai ulang dari sini</button><small class="d-block mt-1 text-danger">Dampak: <?= count($e['affected_titles']); ?> chapter</small><?= form_close(); ?><?php else: ?>—<?php endif; ?></td></tr><?php endforeach; ?>
  </tbody></table></div></div>
  <div class="row row-cards"><div class="col-lg-7"><div class="card"><div class="card-header"><h3 class="card-title">Riwayat Attempt Terbaru</h3></div><div class="table-responsive" style="max-height:520px"><table class="table table-sm card-table"><thead><tr><th>Waktu</th><th>Chapter / adegan</th><th>Jenis</th><th>Hasil</th><th>Kosakata</th></tr></thead><tbody><?php foreach($data['activity'] as $a): ?><tr><td><?= html_escape(date('d M H:i',strtotime($a['created_at']))); ?></td><td><?= html_escape($a['episode_title']); ?> · #<?= (int)$a['scene_number']; ?></td><td><?= html_escape(ucfirst($a['challenge_type'])); ?></td><td><span class="badge bg-<?= $a['is_correct']?'success':'danger'; ?>-lt"><?= $a['is_correct']?'Benar':'Salah'; ?></span></td><td><?= html_escape($a['vocabulary_word']?:'—'); ?></td></tr><?php endforeach; ?></tbody></table></div><?php if(!$data['activity']): ?><div class="card-body text-secondary">Belum ada attempt.</div><?php endif; ?></div></div>
  <div class="col-lg-5"><div class="card"><div class="card-header"><h3 class="card-title">Riwayat Pilihan Cerita</h3></div><div class="list-group list-group-flush" style="max-height:520px;overflow:auto"><?php foreach($data['choices'] as $c): ?><div class="list-group-item"><div class="d-flex justify-content-between"><strong><?= html_escape($c['episode_title']); ?> · adegan <?= (int)$c['scene_number']; ?></strong><span class="badge bg-<?= $c['reputation_delta']>=0?'green':'orange'; ?>-lt"><?= $c['reputation_delta']>=0?'+':''; ?><?= (int)$c['reputation_delta']; ?> reputasi</span></div><div><?= html_escape($c['choice_text']); ?></div><small class="text-secondary"><?= html_escape(date('d M Y H:i',strtotime($c['created_at']))); ?></small></div><?php endforeach; ?><?php if(!$data['choices']): ?><div class="list-group-item text-secondary">Belum ada pilihan cerita.</div><?php endif; ?></div></div></div></div>
</div>

<div class="modal modal-blur fade" id="rpgResetModal" tabindex="-1" aria-labelledby="rpgResetTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered"><div class="modal-content overflow-hidden border-0 shadow-lg">
    <div class="p-4 text-white" style="background:linear-gradient(135deg,#7c3aed,#dc2626)"><div class="d-flex align-items-center"><span class="avatar avatar-lg bg-white text-danger rounded-circle me-3"><i class="ti ti-rewind-backward-10 fs-1"></i></span><div><div class="text-uppercase small opacity-75 fw-bold">Reset perjalanan RPG</div><h2 class="modal-title text-white mb-0" id="rpgResetTitle">Mulai ulang chapter</h2></div><button type="button" class="btn-close btn-close-white ms-auto align-self-start" data-bs-dismiss="modal" aria-label="Tutup"></button></div></div>
    <div class="modal-body p-4"><p class="fs-3 mb-3">Pemain akan kembali ke awal <strong id="resetChapterName"></strong>.</p><div class="alert alert-danger mb-3"><div class="d-flex"><i class="ti ti-alert-triangle fs-2 me-2"></i><div><strong>Progres berikut akan dihapus permanen</strong><div class="small">Jawaban, attempt, pilihan cerita, XP, kosakata, dan hadiah dari chapter terdampak akan disesuaikan.</div></div></div></div><div class="mb-3"><div class="text-secondary text-uppercase small fw-bold mb-2">Chapter terdampak</div><div id="resetImpactList" class="d-flex flex-wrap gap-2"></div></div><div class="rounded-3 bg-green-lt p-3"><i class="ti ti-shield-check text-success me-1"></i> <strong id="resetSafeText"></strong> tetap aman dan tidak berubah.</div></div>
    <div class="modal-footer bg-light"><button type="button" class="btn btn-link link-secondary" data-bs-dismiss="modal">Batal, jangan reset</button><button type="button" id="confirmRpgReset" class="btn btn-danger"><i class="ti ti-rewind-backward-10 me-1"></i> Ya, reset perjalanan</button></div>
  </div></div>
</div>
<script>
document.addEventListener('DOMContentLoaded',function(){
  var selectedForm=null,modal=document.getElementById('rpgResetModal');
  document.querySelectorAll('.js-rpg-reset').forEach(function(button){button.addEventListener('click',function(){
    selectedForm=button.closest('form');
    document.getElementById('rpgResetTitle').textContent='Reset mulai Chapter '+button.dataset.chapter+'?';
    document.getElementById('resetChapterName').textContent='Chapter '+button.dataset.chapter+' — '+button.dataset.title;
    var list=document.getElementById('resetImpactList');list.innerHTML='';
    button.dataset.impact.split('|||').filter(Boolean).forEach(function(name,index){var badge=document.createElement('span');badge.className='badge bg-red-lt fs-6';badge.textContent='Chapter '+(Number(button.dataset.chapter)+index)+' · '+name;list.appendChild(badge);});
    var safe=Number(button.dataset.safe);document.getElementById('resetSafeText').textContent=safe>0?'Chapter 1–'+safe:'Belum ada chapter sebelumnya yang';
  });});
  document.getElementById('confirmRpgReset').addEventListener('click',function(){if(!selectedForm)return;this.disabled=true;this.innerHTML='<span class="spinner-border spinner-border-sm me-2"></span>Mereset progres...';selectedForm.submit();});
  modal.addEventListener('hidden.bs.modal',function(){selectedForm=null;var button=document.getElementById('confirmRpgReset');button.disabled=false;button.innerHTML='<i class="ti ti-rewind-backward-10 me-1"></i> Ya, reset perjalanan';});
});
</script>
