<?php
defined('BASEPATH') OR exit('No direct script access allowed');
$query = $_GET; unset($query['page']);
$page_url = function ($page) use ($query) { return base_url('members/cards?' . http_build_query(array_merge($query, ['page' => $page]))); };
?>
<style>
	.member-card-gallery{display:grid;grid-template-columns:repeat(auto-fill,minmax(275px,1fr));gap:1rem}.member-card-gallery-item{overflow:hidden;border:1px solid #d5e6f5;border-radius:18px;background:#fff;box-shadow:0 9px 22px #0d528013}.member-card-gallery-item .member-card-v2{border-radius:0}.member-card-gallery-copy{padding:.8rem}.member-card-gallery-copy h3{overflow:hidden;margin:0;color:#0a315e;font-size:.9rem;white-space:nowrap;text-overflow:ellipsis}.member-card-gallery-copy p{margin:.25rem 0 0;color:#68829c;font-size:.72rem}.member-card-gallery-actions{display:flex;gap:.5rem;margin-top:.7rem}.member-card-gallery-actions .btn{flex:1}.member-card-gallery-filter{padding:1rem;border:1px solid #d7e7f4;border-radius:18px;background:#fff;box-shadow:0 8px 22px #0f527d0d}.member-card-gallery-tip{display:flex;gap:.65rem;align-items:center;padding:1rem;border:1px solid #d4e9f9;border-radius:16px;background:#eff9ff;color:#346281}.member-card-gallery-tip i{color:#0873be;font-size:1.3rem}@media(max-width:575px){.member-card-gallery{grid-template-columns:1fr}.member-card-gallery-actions{flex-wrap:wrap}.member-card-gallery-actions .btn{min-width:46%}}
</style>
<div class="page-header d-print-none"><div class="container-xl"><div class="row g-2 align-items-center"><div class="col"><div class="page-pretitle">Keanggotaan</div><h1 class="page-title">Kartu Anggota</h1></div><div class="col-auto"><div class="btn-list"><a href="<?= base_url('members/cards/design'); ?>" class="btn btn-primary"><i class="ti ti-palette me-1"></i>Studio Desain Kartu</a><a href="<?= base_url('members'); ?>" class="btn btn-outline-secondary"><i class="ti ti-users me-1"></i>Data Member</a></div></div></div></div></div>
<div class="page-body"><div class="container-xl">
	<?php if ($this->session->flashdata('success')): ?><div class="alert alert-success"><?= html_escape($this->session->flashdata('success')); ?></div><?php endif; ?>
	<div class="member-card-gallery-tip mb-3"><i class="ti ti-id-badge-2"></i><div><strong>Galeri kartu siap cetak.</strong><div class="small">Cari anggota, tinjau tampilan kartu, kemudian cetak atau buka profilnya. Desain yang tampak di sini mengikuti Studio Desain Kartu.</div></div></div>
	<div class="member-card-gallery-filter mb-3"><?= form_open('members/cards', ['method' => 'get', 'class' => 'row g-2 align-items-end']); ?><div class="col-md-5"><label class="form-label">Cari member</label><input class="form-control" name="q" value="<?= html_escape($filters['q'] ?? ''); ?>" placeholder="Nama atau nomor anggota"></div><div class="col-md-3"><label class="form-label">Status membership</label><select class="form-select" name="status"><option value="">Semua status</option><?php foreach (['active'=>'Aktif','inactive'=>'Nonaktif','blocked'=>'Diblokir','expired'=>'Kedaluwarsa','unknown'=>'Belum dipetakan'] as $key=>$label): ?><option value="<?= $key; ?>" <?= ($filters['status'] ?? '') === $key ? 'selected' : ''; ?>><?= $label; ?></option><?php endforeach; ?></select></div><div class="col-md-2"><label class="form-label">Kartu per halaman</label><select class="form-select" name="per_page"><?php foreach ([12,24,48] as $limit): ?><option value="<?= $limit; ?>" <?= (int)($filters['per_page']??24)===$limit?'selected':''; ?>><?= $limit; ?></option><?php endforeach; ?></select></div><div class="col-md-2 d-flex gap-2"><button class="btn btn-primary flex-fill"><i class="ti ti-search me-1"></i>Cari</button><a class="btn btn-outline-secondary" href="<?= base_url('members/cards'); ?>"><i class="ti ti-refresh"></i></a></div><?= form_close(); ?></div>
	<div class="d-flex justify-content-between align-items-center mb-2"><div class="text-secondary small">Menampilkan <?= number_format($pagination['total'] ? (($pagination['page'] - 1) * $pagination['per_page']) + 1 : 0, 0, ',', '.'); ?>–<?= number_format(min($pagination['page'] * $pagination['per_page'], $pagination['total']), 0, ',', '.'); ?> dari <?= number_format($pagination['total'], 0, ',', '.'); ?> member</div></div>
	<div class="member-card-gallery"><?php $render_card_styles = true; if (empty($members)): ?><div class="empty w-100"><div class="empty-icon"><i class="ti ti-id-off"></i></div><p class="empty-title">Kartu tidak ditemukan</p><p class="empty-subtitle text-secondary">Ubah kata kunci atau filter status.</p></div><?php endif; ?><?php foreach ($members as $member): ?><?php $verify_url = base_url('membership/verify/' . (int)$member['id'] . '/' . $this->Member_model->digital_card_token($member)); ?><article class="member-card-gallery-item"><?php $card_size='full'; include APPPATH . 'views/members/_digital_card.php'; ?><div class="member-card-gallery-copy"><h3><?= html_escape($member['full_name']); ?></h3><p><?= html_escape($member['member_no'] ?: '-'); ?> · <?= html_escape($member['status'] ?? '-'); ?></p><div class="member-card-gallery-actions"><a class="btn btn-outline-primary btn-sm" href="<?= base_url('members/detail/' . (int)$member['id']); ?>"><i class="ti ti-user-search me-1"></i>Profil</a><a class="btn btn-primary btn-sm" target="_blank" href="<?= base_url('members/cards/print/' . (int)$member['id']); ?>"><i class="ti ti-printer me-1"></i>Cetak</a></div></div></article><?php endforeach; ?></div>
	<?php if ($pagination['pages'] > 1): ?><div class="d-flex justify-content-center mt-4"><ul class="pagination"><?php for($p=max(1,$pagination['page']-2);$p<=min($pagination['pages'],$pagination['page']+2);$p++): ?><li class="page-item <?= $p===$pagination['page']?'active':''; ?>"><a class="page-link" href="<?= $page_url($p); ?>"><?= $p; ?></a></li><?php endfor; ?></ul></div><?php endif; ?>
</div></div>
