<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>
<div class="page-header"><div class="container-xl"><h1>Aktivasi &amp; Moderasi Perpustakaan</h1></div></div>
<div class="page-body"><div class="container-xl">
<?php foreach(['error'=>'danger','success'=>'success']as$key=>$color): if($this->session->flashdata($key)): ?><div class="alert alert-<?= $color; ?>"><?= html_escape($this->session->flashdata($key)); ?></div><?php endif;endforeach; ?>
<div class="card card-body mb-3"><h2>Aktivasi mandiri, tanpa menunggu kabupaten</h2><p>Pengelola memilih perpustakaan, mengisi nama dan telepon, membuat password, lalu langsung masuk. Kabupaten tidak perlu menerbitkan kode atau menyetujui pendaftaran terlebih dahulu.</p><a class="btn btn-primary align-self-start" href="<?= base_url('aktivasi-perpustakaan'); ?>" target="_blank" rel="noopener">Buka halaman aktivasi mandiri</a><p class="text-secondary mt-3 mb-0">Pendaftaran adalah pernyataan pengelola, bukan bukti kepemilikan yang sudah diverifikasi. Jika ada sengketa, periksa identitas di luar aplikasi, tangguhkan akses, lalu pulihkan akun untuk pengelola yang benar. Akun yang sudah diaktifkan tidak dibuka untuk klaim ulang publik.</p></div>
<?php if($reset_result): ?><div class="card card-body border-warning mb-3"><h2>Password sementara hasil reset</h2><p>Username: <strong><?= html_escape($reset_result['username']); ?></strong></p><label class="form-label" for="reset-password">Salin dan sampaikan secara pribadi kepada pengelola yang telah Anda periksa</label><input id="reset-password" class="form-control font-monospace" readonly value="<?= html_escape($reset_result['temporary_password']); ?>" onclick="this.select()"><p class="small mt-2 mb-0">Hanya tampil pada respons ini. Password lama dan sesi lama sudah tidak berlaku. Pengelola wajib mengganti password setelah login. Jangan mengirimkannya ke grup umum.</p></div><?php endif; ?>
<form method="get" class="d-flex gap-2 mb-3"><input name="q" class="form-control" maxlength="180" placeholder="Nama perpustakaan / sekolah / NPSN" value="<?= html_escape($q); ?>"><button class="btn btn-outline-primary">Cari</button></form><p><?= (int)$total; ?> perpustakaan selain pusat</p>
<div class="card"><div class="table-responsive"><table class="table"><thead><tr><th>Perpustakaan</th><th>Status &amp; pengelola pendaftar</th><th>Akun / moderasi</th></tr></thead><tbody>
<?php foreach($rows as$r): ?><tr>
<td><strong><?= html_escape($r['name']); ?></strong><small class="d-block text-secondary"><?= html_escape($r['code'].' · '.$r['village'].' · '.$r['district']); ?></small></td>
<td><span class="badge <?= $r['claimed']?'bg-green-lt':'bg-blue-lt'; ?>"><?= $r['claimed']?'Sudah digunakan / diaktifkan':'Siap aktivasi mandiri'; ?></span>
<?php if($r['registration']): ?><div class="mt-2"><?= html_escape($r['registration']['registrant_name']); ?><small class="d-block"><?= html_escape($r['registration']['registrant_phone']); ?></small><small class="d-block text-secondary"><?= html_escape($r['registration']['created_at']); ?> WIB · Pernyataan pengelola</small></div><?php endif; ?></td>
<td><?php if(!$r['accounts']): ?><small class="text-secondary">Akun dibuat otomatis saat pengelola mendaftar.</small><?php endif; ?>
<?php foreach($r['accounts'] as$account): ?><div class="mb-3"><strong><?= html_escape($account['username']); ?></strong><span class="badge ms-2 <?= $account['status']==='active'?'bg-green-lt':'bg-red-lt'; ?>"><?= html_escape($account['status']); ?></span>
<?php if($can_moderate): ?><details class="mt-2"><summary>Moderasi / reset akun</summary><form method="post" action="<?= base_url('library-activation/moderate'); ?>" class="mt-2" style="min-width:240px">
<input type="hidden" name="activation_admin_csrf" value="<?= html_escape($csrf); ?>"><input type="hidden" name="library_id" value="<?= (int)$r['id']; ?>"><input type="hidden" name="user_id" value="<?= (int)$account['id']; ?>">
<label class="form-label" for="moderation-note-<?= (int)$account['id']; ?>">Alasan / hasil pemeriksaan</label><input id="moderation-note-<?= (int)$account['id']; ?>" name="note" class="form-control form-control-sm mb-2" minlength="5" maxlength="500" required>
<div class="d-flex gap-2 flex-wrap"><?php if($account['status']==='active'): ?><button name="action" value="suspend" class="btn btn-sm btn-outline-danger" onclick="return confirm('Tangguhkan akses akun ini? Password dan sesi lama akan dibatalkan.');">Tangguhkan</button><button name="action" value="reset" class="btn btn-sm btn-outline-primary" onclick="return confirm('Reset password? Pastikan identitas pengelola sudah diperiksa. Password lama dan sesi lama tidak berlaku lagi.');">Reset password</button><?php else: ?><button name="action" value="restore" class="btn btn-sm btn-outline-primary">Aktifkan kembali</button><?php endif; ?></div>
</form></details><?php endif; ?></div><?php endforeach; ?></td></tr><?php endforeach; ?>
</tbody></table></div></div>
<div class="d-flex gap-2 mt-3"><span>Halaman <?= (int)$page; ?>/<?= (int)$pages; ?></span><?php foreach([$page-1=>'Sebelumnya',$page+1=>'Berikutnya']as$p=>$label): if($p<1||$p>$pages)continue; ?><a class="btn btn-sm" href="<?= base_url('library-activation?'.http_build_query(['q'=>$q,'page'=>$p])); ?>"><?= $label; ?></a><?php endforeach; ?></div>
</div></div>
