<?php $this->load->view('library_workspace/header'); ?>
<section class="network-profile-flare mb-3" aria-labelledby="profile-flare-title">
 <div><span class="badge bg-white text-primary mb-2">Profil & pendataan</span><h2 id="profile-flare-title">Lengkapi cerita perpustakaan Anda</h2><p>Isi contact person dan nomor HP aktif, lengkapi profil, lalu periksa pendataan tahun 2026.</p>
 <?php if(empty($library['manager_name'])||!preg_match('/^(?:\+?62|0)8[0-9]{7,12}$/D',preg_replace('/[\s().-]/','',(string)($library['phone']??'')))): ?><p class="fw-bold">Contact person atau nomor HP Anda belum lengkap.</p><?php endif; ?>
 <div class="network-actions"><a class="btn btn-light" href="<?= html_escape($network_url('profile')); ?>">Lengkapi profil</a><a class="btn btn-light" href="<?= html_escape($network_url('survey')); ?>">Pendataan tambahan</a><a class="btn btn-light" href="<?= base_url('iplm'); ?>">Pendataan IPLM</a><a class="btn btn-outline-light" href="<?= html_escape($network_url('guide')); ?>">Baca panduan</a></div></div>
 <i class="ti ti-books" aria-hidden="true"></i>
</section>

<div class="network-stats mb-3"><?php foreach(['physical'=>'Judul fisik','digital'=>'Judul digital','items'=>'Eksemplar','members'=>'Anggota lokal','active_loans'=>'Pinjaman aktif','overdue'=>'Terlambat']as$key=>$label): ?><div class="network-stat"><span><?= $label; ?></span><strong><?= number_format($report['stats'][$key],0,',','.'); ?></strong></div><?php endforeach; ?></div>
<div class="card"><div class="card-body"><h2>Mulai mengelola perpustakaan</h2><p>Tambahkan katalog, lalu eksemplar dan anggota lokal. Peminjaman menggunakan nomor anggota dan barcode dari perpustakaan ini.</p><div class="network-actions"><a class="btn btn-primary" href="<?= html_escape($network_url('edit/books')); ?>">Tambah katalog</a><a class="btn btn-outline-primary" href="<?= html_escape($network_url('edit/members')); ?>">Tambah anggota</a><a class="btn btn-outline-primary" href="<?= html_escape($network_url('loans')); ?>">Catat peminjaman</a><a class="btn btn-outline-primary" href="<?= base_url('jejaring/katalog?library_id='.(int)$scope); ?>">Lihat katalog publik</a></div><p class="network-muted mt-3 mb-0">Aturan saat ini: <?= (int)$settings['loan_days']; ?> hari, maksimal <?= (int)$settings['max_loans']; ?> pinjaman aktif, <?= (int)$settings['max_renewals']; ?> kali perpanjangan. Anggota lokal tidak otomatis dibuatkan akun pemustaka kabupaten.</p></div></div>
<?php $this->load->view('library_workspace/footer'); ?>
