<?php $this->load->view('library_workspace/header'); ?>
<div class="card"><div class="card-body"><span class="badge bg-blue-lt">Panduan pengelola</span><h2 class="mt-3">Profil lengkap, pendataan lebih mudah</h2>
<ol class="network-guide">
<li><h3>Periksa identitas institusi</h3><p>Nama sekolah dan NPSN mengacu Dapodik. Nama perpustakaan boleh berbeda. Jika institusi, NPSN, kecamatan/desa atau lokasi salah, hubungi pengelola kabupaten. Jangan menggunakan identitas sekolah lain.</p></li>
<li><h3>Lengkapi profil dan kontak</h3><p>Buka <a href="<?= html_escape($network_url('profile')); ?>">Profil</a>. Contact person adalah petugas yang dapat dihubungi, bukan otomatis kepala sekolah. Nama contact person dan nomor HP aktif wajib diisi; gunakan 08… atau +628…. Lengkapi alamat, email, website HTTPS, jam layanan, fasilitas dan deskripsi, kemudian simpan.</p></li>
<li><h3>Isi pendataan tambahan</h3><p>Buka <a href="<?= html_escape($network_url('survey')); ?>">Pendataan tambahan</a>. Konfirmasi apakah unit sudah memiliki perpustakaan. Lengkapi legalitas, kepala perpustakaan, visi/misi, akreditasi, layanan, teknologi dan angka pendataan. Angka lama tidak otomatis dianggap data 2026. Isi tahun acuan dan catatan sumber. Kosong berarti belum diketahui; nol hanya bila benar-benar tidak ada. Data ini tidak masuk perhitungan IPLM.</p></li>
<li><h3>Isi formulir IPLM sesuai periode</h3><p>Buka <a href="<?= base_url('iplm'); ?>">Pendataan IPLM</a> jika perpustakaan berada dalam cakupan. Pengukuran 2026 memakai data 1 Januari–31 Desember 2026. Tahun berjalan belum lengkap: periksa kembali angka sebelum mengirim. Lengkapi identitas pengisi, koleksi, tenaga, pelayanan, pengelolaan, dan bukti dukung sesuai definisi tiap kolom. Anggaran diisi dalam rupiah penuh tanpa pemisah ribuan.</p></li>
<li><h3>Simpan draf, periksa bukti, lalu kirim</h3><p>Gunakan simpan draf selama data belum lengkap. Tautan bukti harus HTTPS dan dapat dibaca verifikator. Jangan menganggap kunjungan sama dengan jumlah orang unik. Angka katalog hanya dipakai setelah diperiksa. Jika periode masih persiapan atau unit di luar cakupan, pengiriman belum tersedia. Kabupaten memeriksa isian; jika diminta revisi, baca catatan dan perbarui sebelum mengirim ulang.</p></li>
</ol><div class="alert alert-info mb-0">Jumlah sekolah dalam master bukan populasi IPLM. Kabupaten menetapkan unit yang memiliki perpustakaan dan sesuai kewenangan; populasi periode dapat dihitung otomatis dari unit yang dipilih atau ditetapkan manual beserta alasan.</div></div></div>
<?php $this->load->view('library_workspace/footer'); ?>
