<?php defined('BASEPATH') OR exit('No direct script access allowed'); ?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Temukan Perpustakaan Anda · Pustaka Rembang</title><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/core@1.4.0/dist/css/tabler.min.css"><?php $this->load->view('partials/network_map_styles'); ?><style>dialog{border:0;border-radius:20px;padding:28px;max-width:540px;width:calc(100% - 32px);box-shadow:0 24px 80px #10254444}dialog::backdrop{background:#102544aa}.discovery-results{max-height:360px;overflow:auto}.discovery-hero{background:linear-gradient(120deg,#16355d,#116e75);color:white;border-radius:24px;padding:32px;margin:24px 0}.discovery-hero p{max-width:700px}</style></head>
<body><main class="container-xl py-3"><nav class="d-flex gap-2"><a class="btn btn-outline-primary" href="<?= base_url(); ?>">Beranda</a><a class="btn btn-outline-primary" href="<?= base_url('login'); ?>">Sudah punya akses? Masuk</a></nav><header class="discovery-hero"><span>JEJARING PERPUSTAKAAN REMBANG</span><h1 class="mt-2">Temukan perpustakaan Anda</h1><p class="mb-0">Cari nama perpustakaan, sekolah, atau NPSN. Anda juga dapat memilih lokasi pada peta. Halaman ini untuk pengelola perpustakaan selain perpustakaan pusat.</p></header>
<section class="card card-body mb-3"><label class="form-label" for="library-search">Nama perpustakaan / sekolah / NPSN</label><input type="search" id="library-search" class="form-control form-control-lg" autocomplete="off" maxlength="180" placeholder="Ketik minimal 2 karakter" aria-describedby="search-status"><p id="search-status" class="text-secondary mt-2 mb-2" role="status" aria-live="polite">Peta tetap menampilkan semua lokasi; pencarian tidak menghilangkan titik lain.</p><div class="list-group discovery-results" id="search-results"></div></section>
<?php if($this->session->flashdata('activation_error')): ?><div class="alert alert-danger" role="alert"><?= html_escape($this->session->flashdata('activation_error')); ?></div><?php endif; ?>
<?php $this->load->view('partials/network_map',get_defined_vars()); ?>
<dialog id="ownership-dialog" aria-labelledby="ownership-title"><h2 id="ownership-title">Aktivasi mandiri perpustakaan</h2><h3 id="selected-name"></h3><p id="selected-identity" class="text-secondary"></p><div class="alert alert-warning">Pastikan perpustakaan yang dipilih benar. Pendaftaran ini khusus pengelola resmi, bukan anggota/pemustaka. Identitas pengelola dicatat untuk moderasi kabupaten.</div>
<?php if($activation_ready&&!$this->session->userdata('auth_user')): ?>
<form method="post" action="<?= base_url('aktivasi-perpustakaan/klaim'); ?>" id="activation-form">
<input type="hidden" name="activation_csrf" value="<?= html_escape($activation_csrf); ?>"><input type="hidden" name="library_id" id="activation-library">
<label class="form-label" for="registrant-name">Nama lengkap pengelola</label><input id="registrant-name" name="registrant_name" class="form-control mb-3" minlength="3" maxlength="180" autocomplete="name" required>
<label class="form-label" for="registrant-phone">Telepon pengelola</label><input id="registrant-phone" name="registrant_phone" type="tel" class="form-control mb-3" maxlength="26" autocomplete="tel" required>
<label class="form-label" for="activation-password">Buat password pribadi</label><input id="activation-password" name="password" type="password" class="form-control mb-3" minlength="10" maxlength="72" autocomplete="new-password" required>
<label class="form-label" for="activation-confirmation">Ulangi password</label><input id="activation-confirmation" name="confirmation" type="password" class="form-control mb-3" minlength="10" maxlength="72" autocomplete="new-password" required>
<label class="form-check mb-3"><input type="checkbox" name="ownership" value="1" class="form-check-input" required><span class="form-check-label">Saya pengelola resmi perpustakaan ini, bertanggung jawab atas kebenaran data, dan bersedia dihubungi untuk moderasi.</span></label>
<p class="small text-secondary">Tidak memerlukan kode atau persetujuan awal admin kabupaten. Username dibuat dari nama sekolah/perpustakaan (atau memakai username akun awal yang sudah disediakan) dan ditampilkan setelah berhasil. Akun yang sudah digunakan tidak dapat diklaim ulang.</p>
<button class="btn btn-primary w-100 mb-3">Aktifkan akun &amp; masuk</button></form>
<?php elseif($this->session->userdata('auth_user')): ?><p>Anda sedang login. Keluar terlebih dahulu jika ingin melakukan aktivasi akun lain.</p><?php else: ?><p>Pendaftaran sedang dalam pemeliharaan. Silakan coba lagi nanti.</p><?php endif; ?>
<div class="d-flex gap-2 flex-wrap"><button class="btn btn-outline-secondary" id="close-ownership" type="button">Pilih ulang</button><a class="btn btn-primary" href="<?= base_url('login'); ?>">Sudah aktif? Masuk</a></div></dialog>
</main><?php $this->load->view('partials/network_map_scripts'); ?>
<script>
(()=>{'use strict';const search=document.getElementById('library-search'),results=document.getElementById('search-results'),status=document.getElementById('search-status'),dialog=document.getElementById('ownership-dialog');let timer,request,sequence=0;
function choose(p){const form=document.getElementById('activation-form');if(form){form.reset();document.getElementById('activation-library').value=p.id;}document.getElementById('selected-name').textContent=p.name;document.getElementById('selected-identity').textContent=[p.code,p.address,p.village,p.district].filter(Boolean).join(' · ');if(!dialog.open)dialog.showModal();}
document.getElementById('close-ownership').addEventListener('click',()=>dialog.close());document.addEventListener('library:selected',e=>choose(e.detail));
search.addEventListener('input',()=>{clearTimeout(timer);if(request)request.abort();const current=++sequence,q=search.value.trim();results.replaceChildren();if(q.length<2){status.textContent='Ketik minimal 2 karakter untuk mencari.';return;}status.textContent='Mencari perpustakaan…';timer=setTimeout(async()=>{request=new AbortController();try{const url=new URL(<?= json_encode(base_url('aktivasi-perpustakaan/cari'),JSON_HEX_TAG); ?>);url.searchParams.set('q',q);const response=await fetch(url,{signal:request.signal,headers:{Accept:'application/json'}});if(!response.ok)throw Error('search');const data=await response.json();if(current!==sequence)return;for(const p of data.results){const button=document.createElement('button');button.type='button';button.className='list-group-item list-group-item-action text-start';const title=document.createElement('strong'),detail=document.createElement('small');title.textContent=p.name;detail.textContent=[p.code,p.district,p.village].filter(Boolean).join(' · ');detail.className='d-block text-secondary';button.append(title,detail);button.addEventListener('click',()=>choose(p));results.append(button);}status.textContent=data.results.length?data.results.length+' hasil. Pilih perpustakaan Anda.'+(data.results.length===data.limit?' Persempit pencarian untuk hasil lainnya.':''):'Tidak ada hasil. Coba nama atau NPSN lain; hubungi admin kabupaten jika belum terdaftar.';}catch(e){if(e.name!=='AbortError'&&current===sequence)status.textContent='Pencarian belum berhasil. Silakan coba lagi.'}},300);});})();
</script></body></html>
