<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class English_course extends CI_Controller
{
    private $user=[];
    public function __construct(){parent::__construct();$this->user=(array)$this->session->userdata('auth_user');if(empty($this->user['id'])){$this->session->set_flashdata('redirect_after_login',uri_string());redirect('login');return;}$this->load->model('English_course_model');if($this->English_course_model->is_blocked((int)$this->user['id'])){$this->session->set_flashdata('error','Akses Kelas Bahasa Inggris sedang dinonaktifkan. Silakan hubungi admin.');redirect('belajar');return;}}
    public function index(){$settings=$this->English_course_model->settings();$levels=$this->English_course_model->levels((int)$this->user['id']);$previousPassed=true;foreach($levels as &$level){$level['unlocked']=($settings['require_level_test']??'1')!=='1'||$previousPassed;$level['test_ready']=$this->English_course_model->test_ready((int)$level['id'],(int)$this->user['id']);$level['reviews']=$this->English_course_model->review_progress((int)$level['id'],(int)$this->user['id']);foreach($level['units'] as &$unit)$unit['progress']=$this->English_course_model->unit_progress((int)$unit['id'],(int)$this->user['id']);unset($unit);$previousPassed=$level['best_test']!==null&&(int)$level['best_test']>=(int)$level['pass_score'];}unset($level);$this->load->view('learn/english_course/player/home',['title'=>'Kelas Bahasa Inggris','user'=>$this->user,'levels'=>$levels,'settings'=>$settings,'mastery'=>$this->English_course_model->mastery((int)$this->user['id'])]);}
    public function lesson($id){$lesson=$this->English_course_model->lesson((int)$id,(int)$this->user['id']);if(!$lesson){show_404();return;}if(!$this->English_course_model->level_unlocked((int)$lesson['level_id'],(int)$this->user['id'])){$this->session->set_flashdata('error','Selesaikan tes level sebelumnya untuk membuka materi ini.');redirect('belajar/bahasa-inggris');return;}$this->load->view('learn/english_course/player/lesson',['title'=>$lesson['title'],'user'=>$this->user,'lesson'=>$lesson,'settings'=>$this->English_course_model->settings()]);}
    public function activity($id){if(strtoupper($this->input->method())!=='POST')show_404();$ok=$this->English_course_model->save_activity((int)$id,(int)$this->user['id'],(int)$this->input->post('step_no'),(string)$this->input->post('activity_type',true),(string)$this->input->post('answer_text',true),(int)$this->input->post('score'),(int)$this->input->post('is_correct')===1);return $this->output->set_content_type('application/json')->set_output(json_encode(['ok'=>$ok]));}
    public function complete($id){if(strtoupper($this->input->method())!=='POST')show_404();$lesson=$this->English_course_model->lesson((int)$id,(int)$this->user['id']);if(!$lesson){show_404();return;}$this->English_course_model->complete_lesson((int)$id,(int)$this->user['id'],(int)$this->input->post('score'));$next=$this->English_course_model->next_lesson((int)$id);$this->session->set_flashdata('success','Lesson selesai. Hebat! Progresmu sudah disimpan.');redirect($next?'belajar/bahasa-inggris/lesson/'.$next:'belajar/bahasa-inggris');}
    public function test($levelId){$test=$this->English_course_model->test((int)$levelId);if(!$test){show_404();return;}if(!$this->English_course_model->level_unlocked((int)$levelId,(int)$this->user['id'])){$this->session->set_flashdata('error','Level ini belum terbuka.');redirect('belajar/bahasa-inggris');return;}if(!$this->English_course_model->test_ready((int)$levelId,(int)$this->user['id'])){$this->session->set_flashdata('error','Selesaikan seluruh lesson Stage 1 sebelum membuka final assessment.');redirect('belajar/bahasa-inggris');return;}$this->load->view('learn/english_course/player/test',['title'=>$test['title'],'user'=>$this->user,'test'=>$test,'result'=>null]);}
    public function submit_test($levelId){if(strtoupper($this->input->method())!=='POST')show_404();if(!$this->English_course_model->test_ready((int)$levelId,(int)$this->user['id'])){$this->session->set_flashdata('error','Final assessment belum terbuka.');redirect('belajar/bahasa-inggris');return;}$test=$this->English_course_model->test((int)$levelId);if(!$test){show_404();return;}$result=$this->English_course_model->submit_test($test,(int)$this->user['id'],(array)$this->input->post('answers'));$this->load->view('learn/english_course/player/test',['title'=>'Hasil '.$test['title'],'user'=>$this->user,'test'=>$test,'result'=>$result]);}
    public function checkpoint($unitId){$data=$this->English_course_model->checkpoint((int)$unitId);if(!$data){show_404();return;}if(!$this->English_course_model->chapter_ready((int)$unitId,(int)$this->user['id'])){$this->session->set_flashdata('error','Selesaikan lima lesson chapter ini terlebih dahulu.');redirect('belajar/bahasa-inggris');return;}$this->load->view('learn/english_course/player/checkpoint',['title'=>'Checkpoint '.$data['unit']['title'],'user'=>$this->user,'checkpoint'=>$data,'result'=>null]);}
    public function submit_checkpoint($unitId){if(strtoupper($this->input->method())!=='POST')show_404();if(!$this->English_course_model->chapter_ready((int)$unitId,(int)$this->user['id'])){show_error('Checkpoint belum terbuka.',403);return;}$data=$this->English_course_model->checkpoint((int)$unitId);if(!$data){show_404();return;}$result=$this->English_course_model->submit_checkpoint($data,(int)$this->user['id'],(array)$this->input->post('answers'));$this->load->view('learn/english_course/player/checkpoint',['title'=>'Hasil Checkpoint','user'=>$this->user,'checkpoint'=>$data,'result'=>$result]);}
    public function stage_review($levelId,$part){$data=$this->English_course_model->stage_review((int)$levelId,(int)$part);if(!$data){show_404();return;}if(!$this->English_course_model->stage_review_ready((int)$levelId,(int)$part,(int)$this->user['id'])){$this->session->set_flashdata('error','Selesaikan enam chapter pada bagian ini terlebih dahulu.');redirect('belajar/bahasa-inggris');return;}$this->load->view('learn/english_course/player/stage_review',['title'=>$data['title'],'user'=>$this->user,'review'=>$data,'result'=>null]);}
    public function submit_stage_review($levelId,$part){if(strtoupper($this->input->method())!=='POST')show_404();if(!$this->English_course_model->stage_review_ready((int)$levelId,(int)$part,(int)$this->user['id'])){show_error('Review belum terbuka.',403);return;}$data=$this->English_course_model->stage_review((int)$levelId,(int)$part);if(!$data){show_404();return;}$result=$this->English_course_model->submit_stage_review($data,(int)$this->user['id'],(array)$this->input->post('answers'));$this->load->view('learn/english_course/player/stage_review',['title'=>'Hasil '.$data['title'],'user'=>$this->user,'review'=>$data,'result'=>$result]);}
}
