<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Learn_module_progress extends MY_Controller
{
    private $module_config=[
        'flashcard'=>['permission'=>'learn_flashcards.index','base'=>'learn-flashcards','title'=>'Flashcard','unit'=>'Deck'],
        'story'=>['permission'=>'learn_story.index','base'=>'learn-story','title'=>'Story Quiz','unit'=>'Bacaan'],
        'mini_games'=>['permission'=>'learn_games.index','base'=>'learn-games','title'=>'Mini Game','unit'=>'Set/Level'],
        'battle'=>['permission'=>'learn_battle.index','base'=>'learn-battle','title'=>'Mode Battle','unit'=>'Sesi Battle'],
        'english_course'=>['permission'=>'learn_english_course.index','base'=>'learn-english-course','title'=>'Kelas Bahasa Inggris','unit'=>'Level'],
    ];
    public function __construct(){parent::__construct();$this->load->model('Learn_module_progress_model');}
    private function cfg($module){if(!isset($this->module_config[$module]))show_404();return $this->module_config[$module];}
    private function require_post(){if(strtoupper((string)$this->input->method())!=='POST')show_error('Metode tidak diizinkan.',405);}
    public function index($module){$c=$this->cfg($module);$this->require_permission($c['permission'],'view');$q=trim((string)$this->input->get('q',true));$this->render('learn/module_progress/index',['title'=>'Progres '.$c['title'],'active_menu'=>$c['permission'],'module'=>$module,'config'=>$c,'players'=>$this->Learn_module_progress_model->players($module,$q),'summary'=>$this->Learn_module_progress_model->summary($module),'battle_runs'=>$module==='battle'?$this->Learn_module_progress_model->battle_runs($q):[],'q'=>$q]);}
    public function user($module,$uid){$c=$this->cfg($module);$this->require_permission($c['permission'],'view');$d=$this->Learn_module_progress_model->detail($module,(int)$uid);if(!$d)show_404();$this->render('learn/module_progress/user',['title'=>'Riwayat '.$c['title'],'active_menu'=>$c['permission'],'module'=>$module,'config'=>$c,'data'=>$d]);}
    public function battle_run($room_id){$c=$this->cfg('battle');$this->require_permission($c['permission'],'view');$d=$this->Learn_module_progress_model->battle_run((int)$room_id);if(!$d){show_404();return;}$this->render('learn/module_progress/battle_run',['title'=>'Hasil Battle '.$d['room']['code'],'active_menu'=>$c['permission'],'config'=>$c,'data'=>$d]);}
    public function battle_stop($room_id){$c=$this->cfg('battle');$this->require_permission($c['permission'],'edit');$this->require_post();$result=$this->Learn_module_progress_model->stop_battle((int)$room_id);$this->audit_event('learn_battle.room_stop','learn_battle_rooms',(int)$room_id,null,['result'=>$result]);$this->session->set_flashdata($result['ok']?'success':'error',$result['message']);redirect('learn-battle/progress/run/'.(int)$room_id);}
    public function access($module,$uid){$c=$this->cfg($module);$this->require_permission($c['permission'],'edit');$this->require_post();$blocked=(int)$this->input->post('blocked')===1;$ok=$this->Learn_module_progress_model->set_access((int)$uid,$module,$blocked,(string)$this->input->post('reason',true),(int)$this->current_user['id']);$this->audit_event('learn_'.$module.'.access','auth_user',(int)$uid,null,['blocked'=>$blocked]);$this->session->set_flashdata($ok?'success':'error',$ok?($blocked?'Akses pengguna dinonaktifkan.':'Akses pengguna diaktifkan.'):'Perubahan gagal.');redirect($c['base'].'/progress/user/'.(int)$uid);}
    public function reset_all($module,$uid){$c=$this->cfg($module);$this->require_permission($c['permission'],'delete');$this->require_post();$ok=$this->Learn_module_progress_model->reset($module,(int)$uid);$this->audit_event('learn_'.$module.'.progress_reset','auth_user',(int)$uid,null,['scope'=>'all']);$this->session->set_flashdata($ok?'success':'error',$ok?'Seluruh progres '.$c['title'].' pengguna berhasil direset.':'Reset gagal.');redirect($c['base'].'/progress/user/'.(int)$uid);}
    public function reset_scope($module,$uid,$scope_id){$c=$this->cfg($module);$this->require_permission($c['permission'],'delete');$this->require_post();$result=$this->Learn_module_progress_model->reset($module,(int)$uid,(int)$scope_id);$this->audit_event('learn_'.$module.'.scope_reset','auth_user',(int)$uid,null,['scope_id'=>(int)$scope_id]);$this->session->set_flashdata($result?'success':'error',$result?$c['unit'].' terpilih berhasil direset.':'Reset gagal.');redirect($c['base'].'/progress/user/'.(int)$uid);}
}
