<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Learn_progress extends MY_Controller
{
 public function __construct(){parent::__construct();$this->load->model('Learn_progress_model');$this->load->model('Learn_scope_progress_model');}
 public function index(){$this->require_permission('learn_progress.index','view');$q=trim((string)$this->input->get('q',true));$this->render('learn/progress/index',['title'=>'Progres Pengguna','active_menu'=>'learn_progress','users'=>$this->Learn_progress_model->users($q),'modules'=>Learn_progress_model::MODULES,'q'=>$q]);}
 public function detail($uid){$this->require_permission('learn_progress.index','view');$d=$this->Learn_progress_model->detail((int)$uid);if(!$d)show_404();$this->render('learn/progress/detail',['title'=>'Riwayat Progres','active_menu'=>'learn_progress','data'=>$d,'modules'=>Learn_progress_model::MODULES]);}
 public function access($uid){$this->require_permission('learn_progress.index','edit');$m=(string)$this->input->post('module');$blocked=(int)$this->input->post('blocked')===1;$before=$this->Learn_progress_model->blocked((int)$uid,$m);$ok=$this->Learn_progress_model->set_block((int)$uid,$m,$blocked,(string)$this->input->post('reason',true),(int)$this->session->userdata('auth_user')['id']);$this->audit_event('learn_progress.access','auth_user',(int)$uid,$before,['module'=>$m,'blocked'=>$blocked]);$this->session->set_flashdata($ok?'success':'error',$ok?($blocked?'Akses game dinonaktifkan.':'Akses game diaktifkan kembali.'):'Perubahan gagal.');redirect('learn-progress/user/'.$uid);}
 public function reset($uid){$this->require_permission('learn_progress.index','delete');$m=(string)$this->input->post('module');$ok=$this->Learn_progress_model->reset((int)$uid,$m);$this->audit_event('learn_progress.reset','auth_user',(int)$uid,null,['module'=>$m]);$this->session->set_flashdata($ok?'success':'error',$ok?'Progres modul berhasil direset.':'Reset progres gagal.');redirect('learn-progress/user/'.$uid);}
 public function rpg_episode($id){$this->require_permission('learn_progress.index','view');$d=$this->Learn_progress_model->rpg_episode_progress((int)$id);if(!$d)show_404();$this->render('learn/progress/rpg_episode',['title'=>'Progres Chapter RPG','active_menu'=>'learn_english_rpg','data'=>$d]);}
 public function reset_rpg_episode($id,$uid){$this->require_permission('learn_progress.index','delete');$res=$this->Learn_progress_model->reset_rpg_episode((int)$uid,(int)$id);$this->audit_event('learn_progress.reset_rpg_chapter','auth_user',(int)$uid,null,['episode_id'=>(int)$id,'ok'=>$res['ok']]);$this->session->set_flashdata($res['ok']?'success':'error',$res['message']);redirect('learn-progress/rpg/episode/'.$id);}
 public function scope($m,$id){$this->require_permission('learn_progress.index','view');$d=$this->Learn_scope_progress_model->get($m,(int)$id);if(!$d)show_404();$this->render('learn/progress/scope',['title'=>'Progres Sesi','active_menu'=>'learn_progress','data'=>$d]);}
 public function reset_scope($m,$id,$uid){$this->require_permission('learn_progress.index','delete');$ok=$this->Learn_scope_progress_model->reset($m,(int)$id,(int)$uid);$this->audit_event('learn_progress.reset_scope','auth_user',(int)$uid,null,['module'=>$m,'scope_id'=>(int)$id]);$this->session->set_flashdata($ok?'success':'error',$ok?'Progres sesi direset.':'Reset gagal.');redirect('learn-progress/scope/'.$m.'/'.$id);}
}
