<?php
defined('BASEPATH') OR exit('No direct script access allowed');
class Learn_english_rpg extends MY_Controller
{
    public function __construct(){parent::__construct();$this->load->model('Learn_english_rpg_model');}
    public function index(){$this->require_permission('learn_english_rpg.index','view');$this->render('learn/english_rpg/list',['title'=>'English RPG','active_menu'=>'learn_english_rpg','episodes'=>$this->Learn_english_rpg_model->episodes(),'can_manage'=>$this->can('learn_english_rpg.index','create')]);}
    public function detail($id){$this->require_permission('learn_english_rpg.index','view');$episode=$this->Learn_english_rpg_model->admin_episode($id);if(!$episode){show_404();return;}$this->render('learn/english_rpg/index',['title'=>$episode['title'],'active_menu'=>'learn_english_rpg','episode'=>$episode,'scenes'=>$this->Learn_english_rpg_model->admin_scenes($episode['id']),'can_manage'=>$this->can('learn_english_rpg.index','create')]);}
    public function save_episode($id=null){$this->require_permission('learn_english_rpg.index',$id?'edit':'create');$data=$this->input->post();if(trim((string)($data['title']??''))===''||(!$id&&trim((string)($data['code']??''))==='')){$this->session->set_flashdata('error','Kode dan judul episode wajib diisi.');redirect('learn-english-rpg');return;}try{$episode_id=$this->Learn_english_rpg_model->save_episode($data,$id);$this->session->set_flashdata('success',$id?'Episode diperbarui.':'Episode ditambahkan.');redirect('learn-english-rpg/episode/'.$episode_id);}catch(Throwable $e){$this->session->set_flashdata('error','Gagal menyimpan: '.$e->getMessage());redirect('learn-english-rpg');}}
    public function save_scene($episode_id,$id=null){$this->require_permission('learn_english_rpg.index',$id?'edit':'create');$data=$this->input->post();if(trim((string)($data['dialogue']??''))===''||trim((string)($data['choice_text'][0]??''))===''||trim((string)($data['choice_text'][1]??''))===''){$this->session->set_flashdata('error','Dialog dan minimal pilihan A-B wajib diisi.');redirect('learn-english-rpg/episode/'.$episode_id);return;}$this->Learn_english_rpg_model->save_scene($id,$data,$episode_id);$this->session->set_flashdata('success',$id?'Adegan diperbarui.':'Adegan ditambahkan.');redirect('learn-english-rpg/episode/'.$episode_id);}
    public function delete_scene($episode_id,$id){$this->require_permission('learn_english_rpg.index','delete');$this->Learn_english_rpg_model->delete_scene($id);$this->session->set_flashdata('success','Adegan dihapus.');redirect('learn-english-rpg/episode/'.$episode_id);}
}
