<?php
defined('BASEPATH') OR exit('No direct script access allowed');
class Learn_english_rpg extends MY_Controller
{
    public function __construct(){parent::__construct();$this->load->model('Learn_english_rpg_model');}
    public function index(){$this->require_permission('learn_english_rpg.index','view');$seasons=array_values(array_filter($this->Learn_english_rpg_model->seasons(),static fn($season)=>(($season['code']??'')!=='season_2')));$this->render('learn/english_rpg/list',['title'=>'English RPG','active_menu'=>'learn_english_rpg','episodes'=>$this->Learn_english_rpg_model->episodes(),'seasons'=>$seasons,'can_manage'=>$this->can('learn_english_rpg.index','create')]);}
    public function detail($id){$this->require_permission('learn_english_rpg.index','view');$episode=$this->Learn_english_rpg_model->admin_episode($id);if(!$episode){show_404();return;}$seasons=array_values(array_filter($this->Learn_english_rpg_model->seasons(),static fn($season)=>(($season['code']??'')!=='season_2')));$this->render('learn/english_rpg/index',['title'=>$episode['title'],'active_menu'=>'learn_english_rpg','episode'=>$episode,'seasons'=>$seasons,'scenes'=>$this->Learn_english_rpg_model->admin_scenes($episode['id']),'can_manage'=>$this->can('learn_english_rpg.index','create')]);}
    public function save_episode($id=null){$this->require_permission('learn_english_rpg.index',$id?'edit':'create');$data=$this->input->post();$season=$this->Learn_english_rpg_model->season((int)($data['season_id']??0));if(($season['code']??'')==='season_2'){$this->session->set_flashdata('error','Season 2 is a code-managed world. Add content in the Season 2 implementation instead of the Season 1 editor.');redirect('learn-english-rpg');return;}if(trim((string)($data['title']??''))===''||(!$id&&trim((string)($data['code']??''))==='')){$this->session->set_flashdata('error','Kode dan judul episode wajib diisi.');redirect('learn-english-rpg');return;}try{$episode_id=$this->Learn_english_rpg_model->save_episode($data,$id);$this->session->set_flashdata('success',$id?'Episode diperbarui.':'Episode ditambahkan.');redirect('learn-english-rpg/episode/'.$episode_id);}catch(Throwable $e){$this->session->set_flashdata('error','Gagal menyimpan: '.$e->getMessage());redirect('learn-english-rpg');}}
    public function save_season(){ $this->require_permission('learn_english_rpg.index','create');$data=$this->input->post();if(trim((string)($data['title']??''))===''||trim((string)($data['code']??''))===''){$this->session->set_flashdata('error','Kode dan judul season wajib diisi.');redirect('learn-english-rpg');return;}try{$this->Learn_english_rpg_model->save_season($data);$this->session->set_flashdata('success','Season baru berhasil dibuat.');}catch(Throwable $e){$this->session->set_flashdata('error','Gagal membuat season: '.$e->getMessage());}redirect('learn-english-rpg');}
    public function save_scene($episode_id,$id=null){$this->require_permission('learn_english_rpg.index',$id?'edit':'create');$data=$this->input->post();$type=(string)($data['challenge_type']??'choice');$choices=array_values(array_filter(array_map('trim',(array)($data['choice_text']??[])),static function($v){return $v!=='';}));$sentence_words=preg_split('/\s+/u',trim((string)($data['sentence_answer']??'')),-1,PREG_SPLIT_NO_EMPTY);if(trim((string)($data['dialogue']??''))===''||trim((string)($data['prompt']??''))===''||count($choices)<2){$this->session->set_flashdata('error','Dialog, pertanyaan, dan minimal pilihan A-B wajib diisi.');redirect('learn-english-rpg/episode/'.$episode_id);return;}if(count($choices)!==count(array_unique(array_map('mb_strtolower',$choices)))){$this->session->set_flashdata('error','Pilihan jawaban tidak boleh duplikat.');redirect('learn-english-rpg/episode/'.$episode_id);return;}if($type==='sentence'&&count($sentence_words)<3){$this->session->set_flashdata('error','Sentence Forge harus memiliki jawaban minimal tiga kata.');redirect('learn-english-rpg/episode/'.$episode_id);return;}$this->Learn_english_rpg_model->save_scene($id,$data,$episode_id);$this->session->set_flashdata('success',$id?'Adegan diperbarui.':'Adegan ditambahkan.');redirect('learn-english-rpg/episode/'.$episode_id);}
    public function delete_scene($episode_id,$id){$this->require_permission('learn_english_rpg.index','delete');$this->Learn_english_rpg_model->delete_scene($id);$this->session->set_flashdata('success','Adegan dihapus.');redirect('learn-english-rpg/episode/'.$episode_id);}
}
