<?php defined('BASEPATH') OR exit('No direct script access allowed');$r=$selected?:[]; ?>
<div class="page-header"><div class="container-xl"><h1 class="page-title"><?= html_escape($title); ?></h1></div></div><div class="page-body"><div class="container-xl">
<?php if($this->session->flashdata('success')): ?><div class="alert alert-success"><?= html_escape($this->session->flashdata('success')); ?></div><?php endif; ?><?php if($error): ?><div class="alert alert-danger"><?= html_escape($error); ?></div><?php endif; ?>
<div class="alert alert-info">Jenis lama dipertahankan setelah pilihan IPLM. TK dan SKB adalah perluasan lokal. Hapus dilakukan dengan menonaktifkan master yang tidak digunakan; data historis tidak dihapus. Jenis/subjenis yang sedang dipakai tidak dapat dihapus atau dipindahkan.</div>
<div class="btn-list mb-3"><a class="btn btn-outline-primary" href="<?= base_url('library-types'); ?>">Tambah jenis</a><a class="btn btn-outline-primary" href="<?= base_url('library-types?entity=subtype'); ?>">Tambah subjenis</a><a class="btn btn-outline-secondary" href="<?= base_url('libraries'); ?>">Data perpustakaan</a></div>
<form class="card card-body mb-3" method="post"><h2><?= $r?'Edit':'Tambah'; ?> <?= $entity==='type'?'jenis':'subjenis'; ?></h2><input type="hidden" name="taxonomy_csrf" value="<?= html_escape($csrf); ?>"><input type="hidden" name="entity" value="<?= $entity; ?>"><input type="hidden" name="id" value="<?= (int)($r['id']??0); ?>"><div class="row g-3">
<?php if($entity==='subtype'): ?><div class="col-md-6"><label class="form-label">Jenis induk</label><select class="form-select" name="library_type_id" required><?php foreach($types as$t): ?><option value="<?= (int)$t['id']; ?>" <?= ($r['library_type_id']??0)==$t['id']?'selected':''; ?>><?= html_escape($t['name']); ?></option><?php endforeach; ?></select></div><?php endif; ?>
<?php foreach(['code'=>'Kode stabil','name'=>'Nama','description'=>'Keterangan','sort_order'=>'Urutan']as$key=>$label): ?><div class="col-md-6"><label class="form-label"><?= $label; ?></label><input class="form-control" name="<?= $key; ?>" type="<?= $key==='sort_order'?'number':'text'; ?>" value="<?= html_escape($r[$key]??($key==='sort_order'?100:'')); ?>" <?= $key==='code'&&$r?'readonly':''; ?> <?= in_array($key,['name','code'],true)?'required':''; ?>></div><?php endforeach; ?>
<?php if($entity==='type'): ?><div class="col-md-6"><label class="form-label">Warna penanda peta</label><input class="form-control form-control-color" type="color" name="marker_color" value="<?= html_escape($r['marker_color']??'#2563eb'); ?>"></div><?php else: ?><div class="col-md-6"><label class="form-check"><input type="checkbox" name="iplm_eligible" class="form-check-input" value="1" <?= !empty($r['iplm_eligible'])?'checked':''; ?>><span class="form-check-label">Termasuk cakupan IPLM kabupaten (perlu dasar penetapan)</span></label></div><?php endif; ?>
<div class="col-md-6"><label class="form-check"><input class="form-check-input" type="checkbox" name="is_active" value="1" <?= !$r||!empty($r['is_active'])?'checked':''; ?>><span class="form-check-label">Aktif — kosongkan untuk menghapus logis</span></label></div></div><div class="mt-3"><button class="btn btn-primary">Simpan master</button></div></form>
<?php foreach(['type'=>$types,'subtype'=>$subtypes]as$kind=>$rows): ?><div class="card mb-3"><div class="card-header"><h2 class="card-title"><?= $kind==='type'?'Jenis':'Subjenis'; ?> perpustakaan</h2></div><div class="table-responsive"><table class="table"><thead><tr><th>Nama</th><th>Kode / jenis</th><th>Status</th><th></th></tr></thead><tbody><?php foreach($rows as$item): ?><tr><td><?= html_escape($item['name']); ?></td><td><?= html_escape($kind==='type'?$item['code']:$item['type_name']); ?></td><td><?= $item['is_active']?'Aktif':'Diarsipkan'; ?><?= $kind==='subtype'&&!$item['iplm_eligible']?' · perluasan lokal':''; ?></td><td><a class="btn btn-sm btn-outline-primary" href="<?= base_url('library-types?entity='.$kind.'&id='.(int)$item['id']); ?>">Edit</a></td></tr><?php endforeach; ?></tbody></table></div></div><?php endforeach; ?></div></div>
