<?php defined('BASEPATH') OR exit('No direct script access allowed');
$query = $_GET; unset($query['page']);
$types = ['' => 'Semua pengunjung', 'guest' => 'Tamu', 'member' => 'Member', 'staff' => 'Petugas'];
$devices = ['' => 'Semua perangkat', 'mobile' => 'Ponsel', 'tablet' => 'Tablet', 'desktop' => 'Desktop', 'bot' => 'Bot', 'other' => 'Lainnya'];
?>
<div class="page-header d-print-none"><div class="container-xl"><div class="row g-2 align-items-center"><div class="col"><div class="page-pretitle">Keamanan Sistem</div><h1 class="page-title">Monitor Akses Pustaka</h1></div></div></div></div>
<div class="page-body"><div class="container-xl">
    <div class="row g-2 mb-3"><?php foreach ([['total','Akses hari ini','ti ti-activity'],['guest','Tamu','ti ti-user-question'],['member','Member','ti ti-id-badge-2'],['staff','Petugas','ti ti-shield-check'],['unique_ips','IP unik','ti ti-world']] as $card): ?><div class="col-6 col-md"><div class="card card-sm"><div class="card-body d-flex gap-2 align-items-center"><i class="<?= $card[2]; ?> text-primary fs-2"></i><div><div class="h3 mb-0"><?= number_format((int) ($stats[$card[0]] ?? 0), 0, ',', '.'); ?></div><div class="text-secondary small"><?= $card[1]; ?></div></div></div></div></div><?php endforeach; ?></div>
    <div class="alert alert-info py-2"><i class="ti ti-info-circle me-1"></i>Lokasi hanya berupa kode negara dari proxy/CDN bila tersedia. Sistem tidak mengambil lokasi GPS presisi pengunjung.</div>
    <div class="card admin-card mb-3"><div class="card-body"><?= form_open('access-monitor', ['method' => 'get', 'class' => 'row g-2 align-items-end']); ?>
        <div class="col-lg-3 col-md-6"><label class="form-label">Cari</label><input class="form-control" name="q" value="<?= html_escape($filters['q']); ?>" placeholder="Nama, member, IP, halaman"></div>
        <div class="col-lg-2 col-md-3"><label class="form-label">Pengunjung</label><select class="form-select" name="visitor_type"><?php foreach ($types as $value => $label): ?><option value="<?= $value; ?>" <?= $filters['visitor_type'] === $value ? 'selected' : ''; ?>><?= $label; ?></option><?php endforeach; ?></select></div>
        <div class="col-lg-2 col-md-3"><label class="form-label">Perangkat</label><select class="form-select" name="device_type"><?php foreach ($devices as $value => $label): ?><option value="<?= $value; ?>" <?= $filters['device_type'] === $value ? 'selected' : ''; ?>><?= $label; ?></option><?php endforeach; ?></select></div>
        <div class="col-lg-2 col-md-4"><label class="form-label">Halaman</label><select class="form-select" name="uri_path"><option value="">Semua halaman</option><?php foreach ($route_options as $route): ?><option value="<?= html_escape($route['uri_path']); ?>" <?= $filters['uri_path'] === $route['uri_path'] ? 'selected' : ''; ?>><?= html_escape($route['uri_path']); ?></option><?php endforeach; ?></select></div>
        <div class="col-lg-1 col-md-4"><label class="form-label">Dari</label><input type="date" class="form-control" name="date_from" value="<?= html_escape($filters['date_from']); ?>"></div><div class="col-lg-1 col-md-4"><label class="form-label">Sampai</label><input type="date" class="form-control" name="date_to" value="<?= html_escape($filters['date_to']); ?>"></div>
        <div class="col-lg-1 col-md-4"><label class="form-label">Baris</label><select class="form-select" name="per_page"><?php foreach ([10,25,50,100] as $n): ?><option value="<?= $n; ?>" <?= (int) $pagination['per_page'] === $n ? 'selected' : ''; ?>><?= $n; ?></option><?php endforeach; ?></select></div><div class="col-12 d-flex gap-2"><button class="btn btn-primary"><i class="ti ti-filter me-1"></i>Terapkan Filter</button><a class="btn btn-outline-secondary" href="<?= base_url('access-monitor'); ?>">Reset</a></div><?= form_close(); ?></div></div>
    <div class="card admin-card data-workspace"><div class="card-header workspace-header"><h2 class="card-title">Aktivitas Akses</h2><div class="text-secondary small"><?= number_format((int) $pagination['total'], 0, ',', '.'); ?> catatan</div></div><div class="table-responsive"><table class="table table-vcenter card-table"><thead><tr><th>Waktu</th><th>Identitas</th><th>Halaman</th><th>IP / Lokasi</th><th>Perangkat</th><th>Referrer</th></tr></thead><tbody>
        <?php if (empty($logs)): ?><tr><td colspan="6" class="text-center text-secondary py-4">Belum ada akses sesuai filter.</td></tr><?php endif; ?>
        <?php foreach ($logs as $log): ?><tr><td data-label="Waktu" class="text-secondary small"><?= html_escape($log['created_at']); ?><div><?= html_escape($log['request_method']); ?> · <?= (int) $log['http_status']; ?></div></td><td data-label="Identitas"><span class="badge <?= $log['visitor_type'] === 'member' ? 'bg-green-lt' : ($log['visitor_type'] === 'staff' ? 'bg-blue-lt' : 'bg-secondary-lt'); ?>"><?= html_escape($types[$log['visitor_type']] ?? $log['visitor_type']); ?></span><div class="fw-semibold mt-1"><?= html_escape($log['identity_label'] ?: 'Tamu tidak dikenal'); ?></div><div class="text-secondary small"><?= html_escape($log['member_no'] ?: $log['username'] ?: '-'); ?></div></td><td data-label="Halaman"><code><?= html_escape($log['uri_path']); ?></code><div class="text-secondary small mt-1"><?= html_escape($log['route_name']); ?></div></td><td data-label="IP / Lokasi"><div><?= html_escape($log['ip_address'] ?: '-'); ?></div><div class="text-secondary small"><?= html_escape($log['country_code'] ?: 'Lokasi tidak tersedia'); ?></div></td><td data-label="Perangkat"><div><?= html_escape($devices[$log['device_type']] ?? $log['device_type']); ?></div><div class="text-secondary small"><?= html_escape($log['browser_name']); ?> · <?= html_escape($log['os_name']); ?></div><div class="text-secondary small text-truncate" style="max-width:240px" title="<?= html_escape($log['user_agent']); ?>"><?= html_escape($log['user_agent']); ?></div></td><td data-label="Referrer" class="small text-secondary text-break"><?= html_escape($log['referrer'] ?: '-'); ?></td></tr><?php endforeach; ?></tbody></table></div>
        <?php if ($pagination['pages'] > 1): ?><div class="card-footer d-flex flex-wrap gap-2 align-items-center"><span class="text-secondary small">Halaman <?= $pagination['page']; ?> dari <?= $pagination['pages']; ?></span><ul class="pagination ms-auto mb-0"><?php for ($p=max(1,$pagination['page']-2); $p<=min($pagination['pages'],$pagination['page']+2); $p++): $href=base_url('access-monitor?'.http_build_query(array_merge($query,['page'=>$p]))); ?><li class="page-item <?= $p === $pagination['page'] ? 'active' : ''; ?>"><a class="page-link" href="<?= $href; ?>"><?= $p; ?></a></li><?php endfor; ?></ul></div><?php endif; ?>
    </div></div></div>
