<?php defined('BASEPATH') OR exit('No direct script access allowed');
$rows=$report['rows'];$summary=$report['summary'];
$chart=json_encode(['labels'=>array_column($rows,'month_name'),'total'=>array_column($rows,'total'),'male'=>array_column($rows,'male'),'female'=>array_column($rows,'female'),'online'=>array_column($rows,'online'),'offline'=>array_column($rows,'offline')],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
?>
<div class="page-header d-print-none"><div class="container-xl"><div class="row g-2 align-items-center"><div class="col"><div class="page-pretitle">Laporan & Analitik</div><h1 class="page-title">Perkembangan Anggota Baru</h1><div class="text-secondary mt-1">Rekap bulanan berdasarkan tanggal pendaftaran anggota.</div></div><div class="col-auto"><a class="btn btn-outline-primary" href="<?=base_url('reports/visits');?>"><i class="ti ti-chart-bar me-1"></i>Laporan Kunjungan</a></div></div></div></div>
<div class="container-xl mt-3"><div class="nav workspace-tabs"><a class="nav-link" href="<?=base_url('reports/visits');?>"><i class="ti ti-chart-bar me-1"></i>Kunjungan</a><a class="nav-link" href="<?=base_url('reports/visits?tab=format');?>"><i class="ti ti-table-options me-1"></i>Format Laporan</a><a class="nav-link active" href="<?=base_url('reports/members');?>"><i class="ti ti-users-plus me-1"></i>Anggota Baru</a></div></div>
<div class="page-body"><div class="container-xl">
	<div class="card admin-card mb-3"><div class="card-body"><?=form_open('reports/members',['method'=>'get','class'=>'row g-2 align-items-end']);?><div class="col-md-4"><label class="form-label">Tahun laporan</label><select class="form-select" name="year"><?php for($option=$current_year;$option>=2000;$option--):?><option value="<?=$option;?>" <?=$year===$option?'selected':'';?>><?=$option;?></option><?php endfor;?></select></div><div class="col-md-3"><button class="btn btn-primary w-100"><i class="ti ti-filter me-1"></i>Tampilkan</button></div><?=form_close();?></div></div>
	<div class="report-kpi-grid mb-3"><div class="report-kpi"><span>Anggota Baru <?=$year;?></span><strong><?=number_format($summary['total'],0,',','.');?></strong><small>Total pendaftaran</small></div><div class="report-kpi"><span>Laki-laki</span><strong><?=number_format($summary['male'],0,',','.');?></strong><small><?= $summary['total']?number_format($summary['male']*100/$summary['total'],1,',','.'):'0';?>%</small></div><div class="report-kpi"><span>Perempuan</span><strong><?=number_format($summary['female'],0,',','.');?></strong><small><?= $summary['total']?number_format($summary['female']*100/$summary['total'],1,',','.'):'0';?>%</small></div><div class="report-kpi"><span>Perubahan Tahunan</span><strong><?=$summary['growth_percent']===null?'—':(($summary['growth_percent']>0?'+':'').number_format($summary['growth_percent'],1,',','.').'%');?></strong><small>Dibanding <?=$year-1;?>: <?=number_format($summary['previous_year_total'],0,',','.');?></small></div></div>
	<div class="row g-3"><div class="col-xl-8"><div class="card admin-card h-100"><div class="card-header"><div><h2 class="card-title">Grafik Perkembangan Bulanan</h2><div class="text-secondary small">Total dan pemisahan jenis kelamin</div></div></div><div class="card-body"><canvas id="member-growth-chart" height="115"></canvas></div></div></div><div class="col-xl-4"><div class="card admin-card h-100"><div class="card-header"><div><h2 class="card-title">Metode Pendaftaran</h2><div class="text-secondary small">Online dan admin/offline</div></div></div><div class="card-body"><canvas id="member-method-chart" height="230"></canvas><div class="row text-center mt-3"><div class="col"><div class="text-secondary small">Online</div><strong class="h2"><?=number_format($summary['online'],0,',','.');?></strong></div><div class="col"><div class="text-secondary small">Offline</div><strong class="h2"><?=number_format($summary['offline'],0,',','.');?></strong></div></div></div></div></div></div>
	<div class="card admin-card data-workspace mt-3"><div class="card-header"><div><h2 class="card-title">Rekap Anggota Baru per Bulan</h2><div class="text-secondary small">Online berasal dari pendaftaran publik yang diverifikasi; selain itu dicatat sebagai admin/offline, termasuk data integrasi.</div></div></div><div class="table-responsive"><table class="table table-vcenter card-table"><thead><tr><th>Bulan</th><th class="text-end">Total</th><th class="text-end">Laki-laki</th><th class="text-end">Perempuan</th><th class="text-end">Belum diketahui</th><th class="text-end">Online</th><th class="text-end">Offline</th></tr></thead><tbody><?php foreach($rows as $row):?><tr><td class="fw-semibold"><?=html_escape($row['month_name']);?></td><td class="text-end fw-bold"><?=number_format($row['total'],0,',','.');?></td><td class="text-end"><?=number_format($row['male'],0,',','.');?></td><td class="text-end"><?=number_format($row['female'],0,',','.');?></td><td class="text-end"><?=number_format($row['unknown_gender'],0,',','.');?></td><td class="text-end"><span class="badge bg-green-lt"><?=number_format($row['online'],0,',','.');?></span></td><td class="text-end"><span class="badge bg-blue-lt"><?=number_format($row['offline'],0,',','.');?></span></td></tr><?php endforeach;?></tbody><tfoot><tr class="fw-bold"><td>Total <?=$year;?></td><td class="text-end"><?=number_format($summary['total'],0,',','.');?></td><td class="text-end"><?=number_format($summary['male'],0,',','.');?></td><td class="text-end"><?=number_format($summary['female'],0,',','.');?></td><td class="text-end"><?=number_format($summary['unknown_gender'],0,',','.');?></td><td class="text-end"><?=number_format($summary['online'],0,',','.');?></td><td class="text-end"><?=number_format($summary['offline'],0,',','.');?></td></tr></tfoot></table></div></div>
</div></div>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.9/dist/chart.umd.min.js"></script><script>document.addEventListener('DOMContentLoaded',function(){var p=<?=$chart?:'{}';?>;if(!window.Chart)return;new Chart(document.getElementById('member-growth-chart'),{type:'line',data:{labels:p.labels,datasets:[{label:'Total',data:p.total,borderColor:'#0057a8',backgroundColor:'rgba(0,87,168,.12)',fill:true,tension:.3,borderWidth:3},{label:'Laki-laki',data:p.male,borderColor:'#2f80ed',tension:.3},{label:'Perempuan',data:p.female,borderColor:'#d9468f',tension:.3}]},options:{responsive:true,plugins:{legend:{position:'bottom'}},scales:{y:{beginAtZero:true,ticks:{precision:0}}}}});new Chart(document.getElementById('member-method-chart'),{type:'doughnut',data:{labels:['Online','Admin / Offline'],datasets:[{data:[<?= (int)$summary['online'];?>,<?= (int)$summary['offline'];?>],backgroundColor:['#0b8f6a','#0057a8'],borderColor:'#fff',borderWidth:3}]},options:{responsive:true,plugins:{legend:{position:'bottom'}},cutout:'62%'}})});</script>
