<?php
defined('BASEPATH') OR exit('No direct script access allowed');
$labels = ['active' => 'Sedang dipinjam', 'overdue' => 'Terlambat', 'returned' => 'Dikembalikan', 'history' => 'Histori'];
$classes = ['active' => 'bg-blue-lt text-blue', 'overdue' => 'bg-red-lt text-red', 'returned' => 'bg-green-lt text-green', 'history' => 'bg-secondary-lt'];
$base = $_GET; unset($base['page']);
$page_url = function ($page) use ($base) { return base_url('catalog/loans?' . http_build_query(array_merge($base, ['page' => $page]))); };
?>
<div class="page-header d-print-none"><div class="container-xl"><div class="row g-2 align-items-center"><div class="col"><div class="page-pretitle">Sirkulasi</div><h1 class="page-title">Transaksi Peminjaman</h1></div><div class="col-auto ms-auto btn-list"><a href="<?= base_url('catalog/requests'); ?>" class="btn btn-outline-secondary"><i class="ti ti-list-details me-1"></i>Request Buku</a><?php if ($can_return_loan): ?><?= form_open('catalog/loans/reconcile', ['class' => 'd-inline']); ?><button class="btn btn-outline-primary" data-confirm="Selaraskan status seluruh eksemplar dengan transaksi peminjaman efektif? Status reservasi, hilang, dan perbaikan tidak diubah." data-confirm-title="Sinkronkan Ketersediaan" data-confirm-ok="Ya, Selaraskan"><i class="ti ti-refresh me-1"></i>Selaraskan Eksemplar</button><?= form_close(); ?><?php endif; ?><?php if ($can_create_loan): ?><button class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#manual-loan-modal"><i class="ti ti-scan me-1"></i>Catat Pinjam Manual</button><?php endif; ?></div></div></div></div>
<div class="page-body"><div class="container-xl">
    <?php if ($this->session->flashdata('success')): ?><div class="alert alert-success"><?= html_escape($this->session->flashdata('success')); ?></div><?php endif; ?>
    <?php if ($this->session->flashdata('error')): ?><div class="alert alert-danger"><?= html_escape($this->session->flashdata('error')); ?></div><?php endif; ?>
    <div class="alert alert-info py-2 mb-3"><i class="ti ti-info-circle me-1"></i><strong>Satu riwayat sirkulasi.</strong> Request Buku adalah antrean layanan aplikasi; setelah buku diserahkan, transaksinya tampil di sini bersama histori INLISLite. Untuk buku lama yang kembali, gunakan tombol <strong>Terima Kembali (Lokal)</strong>; data sumber INLISLite tetap utuh dan eksemplar langsung tersedia kembali.</div>
    <div class="row row-cards mb-3">
        <div class="col-6 col-lg-3"><div class="card card-sm"><div class="card-body"><div class="text-secondary small">Sedang dipinjam</div><div class="h2 mb-0 text-blue"><?= number_format((int) ($stats['active'] ?? 0), 0, ',', '.'); ?></div></div></div></div>
        <div class="col-6 col-lg-3"><div class="card card-sm"><div class="card-body"><div class="text-secondary small">Terlambat</div><div class="h2 mb-0 text-danger"><?= number_format((int) ($stats['overdue'] ?? 0), 0, ',', '.'); ?></div></div></div></div>
        <div class="col-6 col-lg-3"><div class="card card-sm"><div class="card-body"><div class="text-secondary small">Kembali hari ini</div><div class="h2 mb-0 text-success"><?= number_format((int) ($stats['returned_today'] ?? 0), 0, ',', '.'); ?></div></div></div></div>
        <div class="col-6 col-lg-3"><div class="card card-sm"><div class="card-body"><div class="text-secondary small">Semua riwayat</div><div class="h2 mb-0"><?= number_format((int) ($stats['total'] ?? 0), 0, ',', '.'); ?></div></div></div></div>
    </div>
    <div class="card admin-card data-workspace"><div class="card-body workspace-filter">
        <?= form_open('catalog/loans', ['method' => 'get', 'class' => 'row g-2 align-items-end']); ?>
            <div class="col-md-4"><label class="form-label">Cari</label><input class="form-control" name="q" value="<?= html_escape($filters['q'] ?? ''); ?>" placeholder="Member, nomor anggota, judul, barcode"></div>
            <div class="col-6 col-md-2"><label class="form-label">Status</label><select class="form-select" name="status"><option value="">Semua</option><?php foreach ($labels as $key => $label): ?><option value="<?= $key; ?>" <?= ($filters['status'] ?? '') === $key ? 'selected' : ''; ?>><?= $label; ?></option><?php endforeach; ?></select></div>
            <div class="col-6 col-md-2"><label class="form-label">Sumber</label><select class="form-select" name="source"><option value="">Semua</option><option value="pustaka" <?= ($filters['source'] ?? '') === 'pustaka' ? 'selected' : ''; ?>>Aplikasi</option><option value="inlislite_v3" <?= ($filters['source'] ?? '') === 'inlislite_v3' ? 'selected' : ''; ?>>INLISLite</option></select></div>
            <div class="col-6 col-md-2"><label class="form-label">Dari</label><input type="date" class="form-control" name="date_from" value="<?= html_escape($filters['date_from'] ?? ''); ?>"></div>
            <div class="col-6 col-md-2"><label class="form-label">Sampai</label><input type="date" class="form-control" name="date_to" value="<?= html_escape($filters['date_to'] ?? ''); ?>"></div>
            <div class="col-auto btn-list"><button class="btn btn-primary"><i class="ti ti-filter me-1"></i>Filter</button><a href="<?= base_url('catalog/loans'); ?>" class="btn btn-outline-secondary"><i class="ti ti-x me-1"></i>Clear Filter</a></div>
        <?= form_close(); ?>
    </div>
    <div class="table-responsive"><table class="table table-vcenter card-table"><thead><tr><th>Buku / Eksemplar</th><th>Member</th><th>Tanggal</th><th>Status</th><th>Sisa / Terlambat</th><th>Aksi</th></tr></thead><tbody>
        <?php if (empty($loans)): ?><tr><td colspan="6" class="text-center text-secondary py-4">Belum ada data transaksi dengan filter ini.</td></tr><?php endif; ?>
        <?php foreach ($loans as $loan): $state = $loan['circulation_status'] ?? 'history'; ?>
        <tr><td><div class="fw-semibold"><?= html_escape($loan['title'] ?: ('Koleksi #' . $loan['source_collection_id'])); ?></div><div class="text-secondary small"><code><?= html_escape($loan['barcode'] ?: $loan['inventory_number'] ?: '-'); ?></code> · <?= ($loan['source_system'] ?? '') === 'pustaka' ? 'Aplikasi' : 'INLISLite'; ?><?= ! empty($loan['local_return_at']) ? ' · <span class="text-success">kembali lokal</span>' : ''; ?></div></td>
            <td><div class="fw-semibold"><?= html_escape($loan['member_name'] ?: '-'); ?></div><div class="text-secondary small"><?= html_escape($loan['member_no'] ?: '-'); ?></div></td>
            <td><div>Pinjam: <?= ! empty($loan['loan_date']) ? date('d M Y', strtotime($loan['loan_date'])) : '-'; ?></div><div class="text-secondary small">Tempo: <?= ! empty($loan['due_date']) ? date('d M Y', strtotime($loan['due_date'])) : '-'; ?><?= ! empty($loan['actual_return_at']) ? ' · Kembali: ' . date('d M Y', strtotime($loan['actual_return_at'])) : (! empty($loan['local_return_at']) ? ' · Kembali lokal: ' . date('d M Y', strtotime($loan['local_return_at'])) : ''); ?></div></td>
            <td><span class="badge <?= $classes[$state] ?? 'bg-secondary-lt'; ?>"><?= $labels[$state] ?? 'Histori'; ?></span></td>
            <td><?php if ($state === 'active'): ?><span class="text-blue"><?= (int) $loan['days_remaining']; ?> hari lagi</span><?php elseif ($state === 'overdue'): ?><span class="text-danger"><?= abs((int) $loan['days_remaining']); ?> hari terlambat</span><?php elseif ($state === 'returned'): ?><span class="text-success"><?= (int) ($loan['late_days'] ?? 0) > 0 ? (int) $loan['late_days'] . ' hari terlambat' : 'Tepat waktu'; ?></span><?php else: ?>-<?php endif; ?></td>
            <td><?php if ($state === 'active' || $state === 'overdue'): ?><?php if ($can_return_loan): ?><?= form_open('catalog/loans/return/' . (int) $loan['id'], ['class' => 'd-inline']); ?><button class="btn btn-sm btn-success" data-confirm="Catat buku fisik ini sudah dikembalikan? Untuk data INLISLite, keputusan disimpan sebagai pengembalian lokal dan tidak mengubah data sumber." data-confirm-title="Pengembalian Buku" data-confirm-ok="Ya, Kembalikan"><i class="ti ti-book-upload me-1"></i><?= ($loan['source_system'] ?? '') === 'pustaka' ? 'Terima Kembali' : 'Terima Kembali (Lokal)'; ?></button><?= form_close(); ?><?php else: ?><span class="text-secondary small">Butuh izin persetujuan</span><?php endif; ?><?php else: ?><span class="text-secondary small">—</span><?php endif; ?></td>
        </tr><?php endforeach; ?>
    </tbody></table></div>
    <div class="card-footer responsive-footer"><p class="m-0 text-secondary">Menampilkan <?= number_format($pagination['total_rows'] > 0 ? $pagination['offset'] + 1 : 0, 0, ',', '.'); ?>–<?= number_format(min($pagination['offset'] + $pagination['per_page'], $pagination['total_rows']), 0, ',', '.'); ?> dari <?= number_format($pagination['total_rows'], 0, ',', '.'); ?> transaksi</p><ul class="pagination m-0"><li class="page-item <?= $pagination['page'] <= 1 ? 'disabled' : ''; ?>"><a class="page-link" href="<?= $page_url(max(1, $pagination['page'] - 1)); ?>">Prev</a></li><li class="page-item <?= $pagination['page'] >= $pagination['total_pages'] ? 'disabled' : ''; ?>"><a class="page-link" href="<?= $page_url(min($pagination['total_pages'], $pagination['page'] + 1)); ?>">Next</a></li></ul></div>
    </div>
</div></div>
<?php if ($can_create_loan): ?><div class="modal modal-blur fade" id="manual-loan-modal" tabindex="-1"><div class="modal-dialog"><div class="modal-content"><?= form_open('catalog/loans/issue'); ?><div class="modal-header"><h5 class="modal-title">Catat Peminjaman Manual</h5><button class="btn-close" type="button" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="alert alert-info py-2 small"><i class="ti ti-scan me-1"></i>Gunakan scanner barcode pada kolom eksemplar. Member dapat dicari dengan nomor anggota, NIK, atau nomor HP.</div><label class="form-label required">Member</label><input class="form-control mb-3" name="member_lookup" required placeholder="Nomor anggota, NIK, atau nomor HP"><label class="form-label required">Barcode / No. Induk Eksemplar</label><input class="form-control mb-3" name="item_lookup" required placeholder="Pindai barcode atau ketik nomor induk"><label class="form-label">Jatuh Tempo</label><input type="date" class="form-control" name="due_date" min="<?= date('Y-m-d'); ?>"></div><div class="modal-footer"><button class="btn btn-outline-secondary" type="button" data-bs-dismiss="modal">Batal</button><button class="btn btn-primary"><i class="ti ti-book-download me-1"></i>Catat Peminjaman</button></div><?= form_close(); ?></div></div></div><?php endif; ?>
<?php if ($can_create_loan && $this->input->get('open', true) === 'manual'): ?><script>document.addEventListener('DOMContentLoaded', function(){ var modal = document.getElementById('manual-loan-modal'); if (modal && window.bootstrap) new bootstrap.Modal(modal).show(); });</script><?php endif; ?>
