<?php
defined('BASEPATH') OR exit('No direct script access allowed');
$url_path = function ($path) { return implode('/', array_map('rawurlencode', explode('/', str_replace('\\', '/', trim((string) $path, '/'))))); };
$cover_url = function ($book) use ($url_path) {
	if (! empty($book['cover_local_path'])) return base_url($url_path($book['cover_local_path']));
	if (! empty($book['cover_source_path'])) return base_url($url_path('assets/uploads/inlislite/source_mirror/' . $book['cover_source_path']));
	return base_url('assets/img/book-cover-default.webp');
};
$query_base = $_GET; unset($query_base['page']);
$page_url = function ($page) use ($query_base) { return base_url('buku-pelajaran?' . http_build_query(array_merge($query_base, ['page' => $page]))); };
$auth_user = (array) $this->session->userdata('auth_user');
?>
<!doctype html>
<html lang="id">
<head>
	<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
	<title><?= html_escape($title); ?></title>
	<link rel="icon" href="<?= base_url('img/favicon.ico'); ?>" type="image/x-icon">
	<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;500;600;700;800;900&family=Fraunces:opsz,wght@9..144,650;9..144,750;9..144,850&display=swap" rel="stylesheet">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/core@1.4.0/dist/css/tabler.min.css">
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@3.34.1/dist/tabler-icons.min.css">
	<link rel="stylesheet" href="<?= base_url('assets/css/pustaka.css'); ?>"><link rel="stylesheet" href="<?= base_url('assets/css/pustaka-polish.css?v=20260812b'); ?>">
	<style>
		.textbook-page{min-height:100vh;background:linear-gradient(180deg,#edf8ff 0,#f9fcff 29rem,#fff 29rem)}
		.textbook-hero{padding:3.25rem 0 2.25rem;background:radial-gradient(circle at 86% 14%,rgba(32,160,104,.2),transparent 18rem),linear-gradient(135deg,#06295a,#075aa9 58%,#147f71);color:#fff}
		.textbook-hero h1{font-family:Fraunces,serif;font-size:clamp(2.15rem,4.5vw,4.2rem);line-height:1.01;max-width:720px;margin:.35rem 0 .75rem}.textbook-hero p{max-width:650px;font-size:1rem;opacity:.9}
		.textbook-kicker{font-size:.72rem;font-weight:900;text-transform:uppercase;letter-spacing:.12em;color:#8cffe0}.textbook-total{display:inline-flex;gap:.55rem;align-items:center;border:1px solid rgba(255,255,255,.32);padding:.65rem .9rem;border-radius:12px;font-weight:800;background:rgba(255,255,255,.08)}
		.textbook-filter{position:relative;margin-top:-1.05rem;border:1px solid #cbe1f5;border-radius:20px;padding:1rem;background:#fff;box-shadow:0 16px 42px rgba(22,73,118,.12)}.textbook-filter .form-label{font-size:.72rem;font-weight:800;text-transform:uppercase;color:#315b84;margin-bottom:.3rem}.textbook-filter .form-control,.textbook-filter .form-select{border-color:#c7dcef;min-height:44px}
		.textbook-summary{display:flex;align-items:center;justify-content:space-between;gap:1rem;margin:2rem 0 1rem}.textbook-summary h2{font-size:1.25rem;margin:0;color:#092d5b}.textbook-book-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(210px,1fr));gap:1rem}.textbook-card{height:100%;display:flex;flex-direction:column;border:1px solid #d6e5f5;border-radius:18px;overflow:hidden;background:#fff;box-shadow:0 8px 24px rgba(13,61,105,.06);transition:transform .18s,box-shadow .18s}.textbook-card:hover{transform:translateY(-4px);box-shadow:0 16px 32px rgba(13,61,105,.13)}.textbook-cover{height:230px;display:block;background:#edf5fc;overflow:hidden}.textbook-cover img{width:100%;height:100%;object-fit:contain;padding:.6rem}.textbook-body{display:flex;flex-direction:column;gap:.55rem;padding:1rem;height:100%}.textbook-body h2{font-size:.92rem;line-height:1.35;margin:0}.textbook-body h2 a{text-decoration:none;color:#092d5b}.textbook-byline{font-size:.75rem;color:#66809c;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.textbook-tags{display:flex;flex-wrap:wrap;gap:.3rem;min-height:24px}.textbook-tags .badge{white-space:normal;text-align:left;font-size:.66rem}.textbook-actions{margin-top:auto;display:flex;gap:.5rem}.textbook-actions .btn{flex:1}.textbook-help{border-radius:18px;background:#e8f8f2;border:1px solid #b6e8d5;padding:1rem;color:#0e5b4d}.textbook-nav-link{color:#064d90!important;font-weight:800!important}
		@media(max-width:767px){.textbook-hero{padding:2.1rem 0 1.9rem}.textbook-filter{border-radius:14px}.textbook-summary{align-items:flex-start;flex-direction:column;margin-top:1.5rem}.textbook-book-grid{grid-template-columns:repeat(2,minmax(0,1fr));gap:.65rem}.textbook-cover{height:170px}.textbook-body{padding:.75rem}.textbook-actions{flex-direction:column}.textbook-page{padding-bottom:5.6rem}}
	</style>
</head>
<body class="public-page textbook-page">
	<header class="public-nav">
		<a class="public-brand" href="<?= base_url(); ?>"><span class="brand-logo-shell"><img class="brand-logo" src="<?= base_url('img/logo-small.jpeg'); ?>" alt="Logo Kabupaten Rembang"></span><span class="public-brand-text">Pustaka Digital Rembang</span></a>
		<nav class="public-links"><a href="<?= base_url(); ?>">Beranda</a><a href="<?= base_url('katalog'); ?>">Katalog</a><a class="textbook-nav-link" href="<?= base_url('buku-pelajaran'); ?>">Buku Pelajaran</a><?php if (! empty($auth_user['id'])): ?><a href="<?= base_url('user/dashboard'); ?>">Dashboard</a><a href="<?= base_url('logout'); ?>" class="btn btn-primary btn-sm">Logout</a><?php else: ?><a href="<?= base_url('login'); ?>" class="btn btn-primary btn-sm">Masuk</a><?php endif; ?></nav>
	</header>
	<nav class="public-mobile-nav"><a href="<?= base_url(); ?>"><i class="ti ti-home"></i><span>Beranda</span></a><a href="<?= base_url('katalog'); ?>"><i class="ti ti-books"></i><span>Katalog</span></a><a class="active" href="<?= base_url('buku-pelajaran'); ?>"><i class="ti ti-school"></i><span>Pelajaran</span></a><a href="<?= ! empty($auth_user['id']) ? base_url('user/dashboard') : base_url('login'); ?>"><i class="ti ti-user"></i><span><?= ! empty($auth_user['id']) ? 'Dashboard' : 'Masuk'; ?></span></a></nav>
	<main>
		<section class="textbook-hero"><div class="container-xl"><div class="row align-items-end g-3"><div class="col-lg-8"><div class="textbook-kicker">Rak belajar terkurasi</div><h1>Buku pelajaran, lebih mudah ditemukan.</h1><p>Telusuri buku siswa dan panduan guru berdasarkan kelas serta mata pelajaran. Semua tetap menjadi bagian dari katalog terpadu Pustaka Digital Rembang.</p></div><div class="col-lg-4 text-lg-end"><span class="textbook-total"><i class="ti ti-books"></i><?= number_format((int) $pagination['total_rows'], 0, ',', '.'); ?> judul tersedia</span></div></div></div></section>
		<section class="container-xl"><form method="get" action="<?= base_url('buku-pelajaran'); ?>" class="textbook-filter"><div class="row g-2 align-items-end"><div class="col-lg-4"><label class="form-label">Cari buku</label><input class="form-control" name="q" value="<?= html_escape($filters['q'] ?? ''); ?>" placeholder="Judul, penulis, atau kata kunci"></div><div class="col-md-4 col-lg-3"><label class="form-label">Jenjang / Kelas</label><select class="form-select" name="grade"><option value="">Semua kelas</option><?php foreach ($filter_options['grade_levels'] as $grade): ?><option value="<?= (int) $grade['id']; ?>" <?= (int) ($filters['textbook_grade_id'] ?? 0) === (int) $grade['id'] ? 'selected' : ''; ?>><?= html_escape($grade['name']); ?> (<?= number_format((int) $grade['total'], 0, ',', '.'); ?>)</option><?php endforeach; ?></select></div><div class="col-md-4 col-lg-3"><label class="form-label">Mata pelajaran</label><select class="form-select" name="subject"><option value="">Semua mata pelajaran</option><?php foreach ($filter_options['subjects'] as $subject): ?><option value="<?= (int) $subject['id']; ?>" <?= (int) ($filters['textbook_subject_id'] ?? 0) === (int) $subject['id'] ? 'selected' : ''; ?>><?= html_escape($subject['name']); ?> (<?= number_format((int) $subject['total'], 0, ',', '.'); ?>)</option><?php endforeach; ?></select></div><div class="col-md-4 col-lg-2"><label class="form-label">Akses</label><select class="form-select" name="availability"><option value="">Semua akses</option><option value="digital" <?= ($filters['availability'] ?? '') === 'digital' ? 'selected' : ''; ?>>Baca digital</option><option value="available" <?= ($filters['availability'] ?? '') === 'available' ? 'selected' : ''; ?>>Tersedia dipinjam</option></select></div><div class="col-md-8 col-lg-8"><div class="textbook-help"><i class="ti ti-info-circle me-1"></i>Filter kelas dan mapel memakai tag khusus Buku Pelajaran—bukan sekadar pencarian kata pada judul.</div></div><div class="col-md-4 col-lg-4 text-md-end"><button class="btn btn-primary px-4" type="submit"><i class="ti ti-search me-1"></i>Terapkan Filter</button><a class="btn btn-outline-primary ms-1" href="<?= base_url('buku-pelajaran'); ?>">Reset</a></div></div></form>
			<div class="textbook-summary"><h2><?= ! empty($filters['textbook_grade_id']) || ! empty($filters['textbook_subject_id']) || ! empty($filters['q']) ? 'Hasil pilihanmu' : 'Jelajahi semua buku pelajaran'; ?></h2><span class="text-secondary small">Menampilkan <?= number_format($pagination['total_rows'] ? $pagination['offset'] + 1 : 0, 0, ',', '.'); ?>–<?= number_format(min($pagination['offset'] + $pagination['per_page'], $pagination['total_rows']), 0, ',', '.'); ?> dari <?= number_format($pagination['total_rows'], 0, ',', '.'); ?> judul</span></div>
			<div class="textbook-book-grid"><?php if (empty($books)): ?><div class="empty w-100"><div class="empty-icon"><i class="ti ti-books-off"></i></div><p class="empty-title">Buku belum ditemukan</p><p class="empty-subtitle text-secondary">Coba ganti kelas, mapel, atau kata pencarian.</p></div><?php endif; ?><?php foreach ($books as $book): ?><article class="textbook-card"><a class="textbook-cover" href="<?= base_url('katalog/detail/' . (int) $book['id']); ?>"><img src="<?= html_escape($cover_url($book)); ?>" alt="Cover <?= html_escape($book['title']); ?>" loading="lazy"></a><div class="textbook-body"><h2><a href="<?= base_url('katalog/detail/' . (int) $book['id']); ?>"><?= html_escape($book['title']); ?></a></h2><div class="textbook-byline"><?= html_escape($book['statement_responsibility'] ?: 'Koleksi Buku Pelajaran'); ?></div><div class="textbook-tags"><?php if (! empty($book['textbook_grade_names'])): ?><span class="badge bg-blue-lt"><i class="ti ti-school me-1"></i><?= html_escape($book['textbook_grade_names']); ?></span><?php endif; ?><?php if (! empty($book['textbook_subject_names'])): ?><span class="badge bg-green-lt"><i class="ti ti-notebook me-1"></i><?= html_escape($book['textbook_subject_names']); ?></span><?php endif; ?><?php if ((int) ($book['digital_asset_count'] ?? 0) > 0): ?><span class="badge bg-azure-lt">Baca digital</span><?php endif; ?></div><div class="textbook-actions"><a class="btn btn-outline-primary btn-sm" href="<?= base_url('katalog/detail/' . (int) $book['id']); ?>">Detail</a><?php if ((int) ($book['first_digital_asset_id'] ?? 0) > 0): ?><a class="btn btn-primary btn-sm" href="<?= base_url('reader/read/' . (int) $book['first_digital_asset_id']); ?>"><i class="ti ti-book-reader me-1"></i>Baca</a><?php endif; ?></div></div></article><?php endforeach; ?></div>
			<?php if ($pagination['total_pages'] > 1): ?><div class="d-flex justify-content-center py-4"><ul class="pagination"><li class="page-item <?= $pagination['page'] <= 1 ? 'disabled' : ''; ?>"><a class="page-link" href="<?= $page_url(max(1, $pagination['page'] - 1)); ?>">‹</a></li><?php for ($n = max(1, $pagination['page'] - 2); $n <= min($pagination['total_pages'], $pagination['page'] + 2); $n++): ?><li class="page-item <?= $n === (int) $pagination['page'] ? 'active' : ''; ?>"><a class="page-link" href="<?= $page_url($n); ?>"><?= $n; ?></a></li><?php endfor; ?><li class="page-item <?= $pagination['page'] >= $pagination['total_pages'] ? 'disabled' : ''; ?>"><a class="page-link" href="<?= $page_url(min($pagination['total_pages'], $pagination['page'] + 1)); ?>">›</a></li></ul></div><?php endif; ?>
		</section>
	</main>
</body></html>
