<?php defined('BASEPATH') OR exit('No direct script access allowed');
$labels=['draft'=>'Draft','published'=>'Tayang','archived'=>'Arsip']; $access=['public'=>'Publik','member'=>'Member','internal'=>'Internal']; $query=$_GET; unset($query['page']); $page_url=function($p)use($query){return base_url('manuscripts?'.http_build_query(array_merge($query,['page'=>$p])));};
$success_message = $this->session->flashdata('success');
?>
<style>
.manuscript-success-modal{position:fixed;inset:0;z-index:2050;display:none;place-items:center;padding:1rem;background:rgba(8,25,45,.42);backdrop-filter:blur(4px)}.manuscript-success-modal.is-open{display:grid}.manuscript-success-dialog{position:relative;overflow:hidden;width:min(100%,24rem);padding:2.2rem 1.75rem;text-align:center;border:1px solid #d4f2df;border-radius:20px;background:#fff;box-shadow:0 28px 70px rgba(0,72,42,.28)}.manuscript-success-dialog h2{position:relative;margin:0 0 .45rem;color:#12643a;font-size:1.25rem;font-weight:800}.manuscript-success-dialog p{position:relative;margin:0;color:#587165;font-size:.84rem;line-height:1.6}.manuscript-success-check{position:relative;display:grid;place-items:center;width:62px;height:62px;margin:0 auto 1rem;border-radius:50%;background:#dcfce7;color:#15803d;font-size:2rem;box-shadow:0 0 0 9px #f0fdf4}.manuscript-flare{position:absolute;inset:0;pointer-events:none}.manuscript-flare i{position:absolute;top:50%;left:50%;width:8px;height:8px;border-radius:2px;background:#f59e0b;transform:translate(-50%,-50%);animation:manuscript-flare .9s ease-out forwards}.manuscript-flare i:nth-child(2n){background:#22c55e}.manuscript-flare i:nth-child(3n){background:#38bdf8}.manuscript-flare i:nth-child(1){--x:-100px;--y:-70px}.manuscript-flare i:nth-child(2){--x:102px;--y:-52px}.manuscript-flare i:nth-child(3){--x:-112px;--y:43px}.manuscript-flare i:nth-child(4){--x:108px;--y:64px}.manuscript-flare i:nth-child(5){--x:-37px;--y:-102px}.manuscript-flare i:nth-child(6){--x:44px;--y:104px}@keyframes manuscript-flare{from{opacity:1;transform:translate(-50%,-50%) scale(.3) rotate(0)}to{opacity:0;transform:translate(calc(-50% + var(--x)),calc(-50% + var(--y))) scale(1.4) rotate(160deg)}}
</style>
<div class="page-header d-print-none"><div class="container-xl"><div class="row g-2 align-items-center"><div class="col"><div class="page-pretitle">Pelestarian Koleksi</div><h1 class="page-title">Naskah Kuno</h1></div><?php if(!empty($can_create)):?><div class="col-auto ms-auto"><a href="<?= base_url('manuscripts/create'); ?>" class="btn btn-primary"><i class="ti ti-feather me-1"></i>Input Naskah</a></div><?php endif;?></div></div></div>
<div class="page-body"><div class="container-xl">
	<?php if($success_message):?><div class="alert alert-success"><?= html_escape($success_message);?></div><?php endif;?><?php if($this->session->flashdata('error')):?><div class="alert alert-danger"><?=html_escape($this->session->flashdata('error'));?></div><?php endif;?>
	<div class="ops-summary-strip"><div><div class="section-kicker">Memori budaya</div><h2>Rawat asal-usul naskah sebelum mempublikasikan salinan digital.</h2><p>Catat identitas fisik, riwayat koleksi, kondisi konservasi, hak akses, serta berkas hasil digitalisasi dalam satu rekam.</p></div><a class="btn btn-outline-primary" href="<?=base_url('naskah-kuno');?>" target="_blank"><i class="ti ti-external-link me-1"></i>Lihat Koleksi Publik</a></div>
	<div class="metric-ribbon service-metric-ribbon"><?php foreach([['total','Total','ti ti-feather'],['published','Tayang','ti ti-world'],['digitized','Digital','ti ti-scan'],['featured','Unggulan','ti ti-sparkles']] as $m):?><div class="metric-ribbon-item"><span class="metric-icon"><i class="<?= $m[2];?>"></i></span><div><div class="metric-value"><?=number_format((int)$stats[$m[0]],0,',','.');?></div><div class="metric-label"><?=$m[1];?></div></div></div><?php endforeach;?></div>
	<div class="card admin-card data-workspace"><div class="card-body workspace-filter"><?=form_open('manuscripts',['method'=>'get','class'=>'row g-2 align-items-end']);?><div class="col-md-4"><label class="form-label">Cari</label><input class="form-control" name="q" value="<?=html_escape($filters['q']??'');?>" placeholder="Inventaris, judul, asal, bahasa"></div><div class="col-md-2"><label class="form-label">Status</label><select class="form-select" name="status"><option value="">Semua</option><?php foreach($labels as $k=>$v):?><option value="<?=$k;?>" <?=($filters['status']??'')===$k?'selected':'';?>><?=$v;?></option><?php endforeach;?></select></div><div class="col-md-2"><label class="form-label">Akses</label><select class="form-select" name="access_level"><option value="">Semua</option><?php foreach($access as $k=>$v):?><option value="<?=$k;?>" <?=($filters['access_level']??'')===$k?'selected':'';?>><?=$v;?></option><?php endforeach;?></select></div><div class="col-md-2"><label class="form-label">Baris</label><select class="form-select" name="per_page"><?php foreach([10,25,50,100]as$n):?><option value="<?=$n;?>" <?=($filters['per_page']??25)==$n?'selected':'';?>><?=$n;?></option><?php endforeach;?></select></div><div class="col-md-2"><button class="btn btn-primary w-100"><i class="ti ti-filter me-1"></i>Filter</button></div><?=form_close();?></div>
	<div class="table-responsive"><table class="table table-vcenter card-table"><thead><tr><th>Naskah</th><th>Identitas Fisik</th><th>Digitalisasi</th><th>Akses</th><th>Status</th><th>Aksi</th></tr></thead><tbody><?php if(empty($items)):?><tr><td colspan="6" class="text-center text-secondary py-4">Belum ada data naskah sesuai filter.</td></tr><?php endif;?><?php foreach($items as $item):?><tr><td><div class="fw-semibold"><?=html_escape($item['title']);?></div><code><?=html_escape($item['inventory_number']);?></code><div class="small text-secondary"><?=html_escape($item['alternate_title']?:'-');?></div></td><td><div><?=html_escape(implode(' · ',array_filter([$item['language'],$item['script'],$item['material']]))?:'-');?></div><div class="small text-secondary"><?=html_escape(($item['page_count']?$item['page_count'].' hlm':'').($item['dimensions']?' · '.$item['dimensions']:''));?></div></td><td><div><?=!empty($item['preview_file_path'])?'<span class="badge bg-green-lt text-green">Ada preview</span>':'<span class="text-secondary">Belum ada berkas</span>';?></div><div class="small text-secondary"><?=html_escape($item['digitized_at']?:'-');?></div></td><td><span class="badge bg-azure-lt text-azure"><?=html_escape($access[$item['access_level']]??$item['access_level']);?></span></td><td><span class="badge <?= $item['status']==='published'?'bg-success-lt text-success':($item['status']==='archived'?'bg-secondary-lt':'bg-yellow-lt text-yellow');?>"><?=html_escape($labels[$item['status']]??$item['status']);?></span></td><td class="text-nowrap"><?php if(!empty($can_edit)):?><a class="btn btn-sm btn-action btn-action-primary" href="<?=base_url('manuscripts/edit/'.(int)$item['id']);?>"><i class="ti ti-edit"></i><span>Edit</span></a><?php endif;?><?php if(!empty($item['preview_file_path'])):?><a class="btn btn-sm btn-outline-secondary" target="_blank" href="<?=base_url('naskah-kuno/preview/'.(int)$item['id']);?>"><i class="ti ti-eye"></i></a><?php endif;?></td></tr><?php endforeach;?></tbody></table></div>
	<div class="card-footer responsive-footer"><p class="m-0 text-secondary">Menampilkan <?=number_format($pagination['total']?$pagination['offset']+1:0,0,',','.');?>–<?=number_format(min($pagination['offset']+$pagination['per_page'],$pagination['total']),0,',','.');?> dari <?=number_format($pagination['total'],0,',','.');?> data</p><ul class="pagination m-0"><li class="page-item <?=$pagination['page']<=1?'disabled':'';?>"><a class="page-link" href="<?=$page_url(max(1,$pagination['page']-1));?>">Prev</a></li><?php for($p=max(1,$pagination['page']-2);$p<=min($pagination['pages'],$pagination['page']+2);$p++):?><li class="page-item <?=$p===$pagination['page']?'active':'';?>"><a class="page-link" href="<?=$page_url($p);?>"><?=$p;?></a></li><?php endfor;?><li class="page-item <?=$pagination['page']>=$pagination['pages']?'disabled':'';?>"><a class="page-link" href="<?=$page_url(min($pagination['pages'],$pagination['page']+1));?>">Next</a></li></ul></div></div>
</div></div>
<?php if ($success_message): ?>
<div class="manuscript-success-modal" id="manuscript-success-modal" role="dialog" aria-modal="true" aria-labelledby="manuscript-success-title"><div class="manuscript-success-dialog"><div class="manuscript-flare" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i><i></i></div><div class="manuscript-success-check"><i class="ti ti-check"></i></div><h2 id="manuscript-success-title">Rekam berhasil disimpan</h2><p><?= html_escape($success_message); ?></p><button type="button" class="btn btn-success mt-3" id="manuscript-success-close">Lanjutkan</button></div></div>
<script>(function(){var modal=document.getElementById('manuscript-success-modal'),button=document.getElementById('manuscript-success-close');if(!modal)return;setTimeout(function(){modal.classList.add('is-open');},90);button.addEventListener('click',function(){modal.classList.remove('is-open');});modal.addEventListener('click',function(event){if(event.target===modal)modal.classList.remove('is-open');});})();</script>
<?php endif; ?>
