<?php
defined('BASEPATH') OR exit('No direct script access allowed');
$is_member = ! empty($auth_user['id']);
$pages = $this->Manuscript_model->get_pages((int) $item['id']);
$has_pages = ! empty($pages);
?>
<!doctype html><html lang="id"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?= html_escape($title); ?> — Naskah Kuno Rembang</title><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/core@1.4.0/dist/css/tabler.min.css"><link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@tabler/icons-webfont@3.34.1/dist/tabler-icons.min.css"><link href="https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,650;9..144,750;9..144,850&family=Plus+Jakarta+Sans:wght@400;500;600;700;800&display=swap" rel="stylesheet"><style>body{margin:0;background:#f7f3ea;color:#34251c;font-family:'Plus Jakarta Sans',sans-serif}.top{padding:15px max(20px,calc((100vw - 960px)/2));background:#fffdf9;border-bottom:1px solid #e2d5c2}.top a{color:#5e4433;font-size:.84rem;font-weight:800;text-decoration:none}.wrap{max-width:960px;margin:auto;padding:42px 16px 70px}.eyebrow{color:#956437;font-size:.7rem;font-weight:800;letter-spacing:.13em;text-transform:uppercase}.title{margin:9px 0 14px;font:800 clamp(2rem,5vw,3.6rem)/1.08 Fraunces,serif;letter-spacing:-.045em;color:#352217}.lead{max-width:720px;color:#6c584b;line-height:1.75}.artifact{display:grid;grid-template-columns:230px 1fr;gap:25px;padding:25px;margin:30px 0;border:1px solid #e2d5c2;border-radius:20px;background:#fffdf9;box-shadow:0 12px 28px #3321110c}.cover{display:grid;place-items:center;min-height:280px;border-radius:7px 13px 13px 7px;background:linear-gradient(135deg,#d6bb82,#765039);color:#fff0c4;font-size:4rem;box-shadow:10px 8px 0 #54372162;overflow:hidden}.cover img{width:100%;height:100%;object-fit:cover}.meta{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:15px}.meta div{padding:10px 0;border-bottom:1px solid #ede3d5}.meta span{display:block;color:#8d7765;font-size:.67rem;font-weight:800;letter-spacing:.07em;text-transform:uppercase}.meta strong{display:block;margin-top:4px;font-size:.88rem}.section{padding:24px;margin-top:17px;border:1px solid #e2d5c2;border-radius:17px;background:#fffdf9}.section h2{margin:0 0 10px;font:800 1.45rem Fraunces,serif}.section p{margin:0;white-space:pre-line;color:#5d4b3e;line-height:1.8}.preview{display:flex;align-items:center;justify-content:space-between;gap:16px;border-color:#c7ae83;background:linear-gradient(135deg,#fff9eb,#f6ead1)}.preview .btn{background:#5e4433;color:#fff;font-weight:800}@media(max-width:650px){.wrap{padding-top:25px}.artifact{grid-template-columns:1fr;padding:18px}.cover{min-height:185px}.meta{grid-template-columns:1fr}.section{padding:19px}.preview{align-items:flex-start;flex-direction:column}}</style></head><body>
<header class="top"><a href="<?= base_url('naskah-kuno'); ?>"><i class="ti ti-arrow-left me-1"></i>Kembali ke Koleksi Naskah Kuno</a></header>
<main class="wrap"><div class="eyebrow"><?= html_escape($item['inventory_number']); ?></div><h1 class="title"><?= html_escape($item['title']); ?></h1>
<?php if ($item['alternate_title']): ?><p class="lead"><em><?= html_escape($item['alternate_title']); ?></em></p><?php endif; ?>
<section class="artifact"><div class="cover"><?php if ($item['cover_path']): ?><img src="<?= base_url(html_escape($item['cover_path'])); ?>" alt="Cover <?= html_escape($item['title']); ?>"><?php else: ?><i class="ti ti-feather"></i><?php endif; ?></div><div><div class="eyebrow mb-2">Identitas naskah</div><div class="meta"><?php foreach (['Bahasa'=>'language','Aksara'=>'script','Media'=>'material','Jumlah halaman'=>'page_count','Ukuran'=>'dimensions','Kondisi'=>'condition_state','Asal'=>'origin','Periode'=>'estimated_period','Penulis / Penyalin'=>'author_scribe','Lokasi simpan'=>'current_location'] as $label=>$key): ?><?php if ($item[$key]): ?><div><span><?= $label; ?></span><strong><?= html_escape($item[$key] . ($key === 'page_count' ? ' halaman' : '')); ?></strong></div><?php endif; ?><?php endforeach; ?></div></div></section>
<?php foreach (['Deskripsi Isi'=>'description','Riwayat Koleksi'=>'collection_history','Catatan Konservasi'=>'conservation_notes','Digitalisasi'=>'digitization_notes','Hak dan Pemanfaatan'=>'rights_note'] as $heading=>$key): ?><?php if ($item[$key]): ?><section class="section"><h2><?= $heading; ?></h2><p><?= html_escape($item[$key]); ?></p><?php if ($key === 'digitization_notes' && $item['digitized_at']): ?><p class="mt-2 small"><strong>Digitalisasi dilakukan:</strong> <?= html_escape($item['digitized_at']); ?><?= $item['digitized_by'] ? ' · ' . html_escape($item['digitized_by']) : ''; ?></p><?php endif; ?></section><?php endif; ?><?php endforeach; ?>
<section class="section preview"><div><div class="eyebrow">Preview koleksi</div><h2 class="mb-1"><?= $is_member && $has_pages ? 'Naskah digital siap dibaca' : 'Masuk untuk membaca isi naskah'; ?></h2><p class="small"><?= $is_member && $has_pages ? 'Viewer halaman menyediakan navigasi dan zoom tanpa tombol unduh.' : 'Pengunjung dapat melihat cover, identitas, dan deskripsi. Isi naskah hanya tersedia bagi member yang telah login.'; ?></p></div><?php if ($is_member && $has_pages): ?><a class="btn" href="<?= base_url('naskah-kuno/baca/' . (int) $item['id']); ?>"><i class="ti ti-books me-1"></i>Baca <?= count($pages); ?> Halaman</a><?php elseif (! $is_member && ($has_pages || ! empty($item['preview_file_path']))): ?><a class="btn" href="<?= base_url('login'); ?>"><i class="ti ti-user-plus me-1"></i>Daftar / Masuk Member</a><?php else: ?><span class="badge bg-secondary-lt">Digitalisasi sedang diproses</span><?php endif; ?></section></main></body></html>
