<?php defined('BASEPATH') OR exit('No direct script access allowed');
$f=$report['filters'];$s=$report['summary'];$o=$report['options'];$query=$f;if($query['library_id']===-1)$query['library_id']='unassigned';
$groups=['library'=>'Perpustakaan','type'=>'Jenis perpustakaan','district'=>'Kecamatan','village'=>'Desa / kelurahan'];
$months=[1=>'Januari',2=>'Februari',3=>'Maret',4=>'April',5=>'Mei',6=>'Juni',7=>'Juli',8=>'Agustus',9=>'September',10=>'Oktober',11=>'November',12=>'Desember'];
$number=function($n){return number_format((int)$n,0,',','.');};
$page_url=function($p)use($query,$per){return base_url('reports/network?'.http_build_query($query+['per_page'=>$per,'page'=>$p]));};
?>
<link rel="stylesheet" href="<?= base_url('assets/css/network-report.css'); ?>?v=<?= filemtime(FCPATH.'assets/css/network-report.css'); ?>">
<div class="page-header"><div class="container-xl"><div class="page-pretitle">Pengawasan Kabupaten Rembang</div><h1 class="page-title">Laporan Gabungan Perpustakaan</h1><div class="text-secondary mt-1">Transaksi <?= $f['month']?html_escape($months[$f['month']]).' ':''; ?><?= $f['year']; ?> · koleksi, keanggotaan dan pinjaman aktif adalah posisi saat ini.</div></div></div>
<div class="page-body network-report"><div class="container-xl">
<form class="card mb-3" method="get" action="<?= base_url('reports/network'); ?>"><div class="card-body"><div class="row g-3">
<div class="col-6 col-lg-2"><label class="form-label" for="nr-year">Tahun transaksi</label><input class="form-control" id="nr-year" type="number" min="2000" max="2100" name="year" value="<?= $f['year']; ?>"></div>
<div class="col-6 col-lg-2"><label class="form-label" for="nr-month">Bulan</label><select class="form-select" id="nr-month" name="month"><option value="0">Seluruh tahun</option><?php foreach($months as$id=>$name): ?><option value="<?= $id; ?>" <?= $f['month']===$id?'selected':''; ?>><?= $name; ?></option><?php endforeach; ?></select></div>
<div class="col-md-6 col-lg-4"><label class="form-label" for="nr-source">Sumber data</label><select class="form-select" id="nr-source" name="source"><?php foreach(['all'=>'Kabupaten + jejaring','legacy'=>'Kabupaten / data lama','network'=>'Operasional jejaring']as$id=>$name): ?><option value="<?= $id; ?>" <?= $f['source']===$id?'selected':''; ?>><?= $name; ?></option><?php endforeach; ?></select></div>
<div class="col-md-6 col-lg-4"><label class="form-label" for="nr-group">Kelompokkan menurut</label><select class="form-select" id="nr-group" name="group"><?php foreach($groups as$id=>$name): ?><option value="<?= $id; ?>" <?= $f['group']===$id?'selected':''; ?>><?= $name; ?></option><?php endforeach; ?></select></div>
<div class="col-md-4"><label class="form-label" for="nr-type">Jenis perpustakaan</label><select class="form-select" id="nr-type" name="type_id"><option value="0">Semua jenis</option><?php foreach($o['types']as$id=>$name): ?><option value="<?= (int)$id; ?>" <?= $f['type_id']===(int)$id?'selected':''; ?>><?= html_escape($name); ?></option><?php endforeach; ?></select></div>
<div class="col-md-4"><label class="form-label" for="nr-district">Kecamatan</label><select class="form-select" id="nr-district" name="district_id"><option value="0">Semua kecamatan</option><?php foreach($o['districts']as$id=>$name): ?><option value="<?= (int)$id; ?>" <?= $f['district_id']===(int)$id?'selected':''; ?>><?= html_escape($name); ?></option><?php endforeach; ?></select></div>
<div class="col-md-4"><label class="form-label" for="nr-village">Desa / kelurahan</label><select class="form-select" id="nr-village" name="village_id"><option value="0">Semua desa</option><?php foreach($o['villages']as$id=>$v): ?><option data-district="<?= (int)$v['district_id']; ?>" value="<?= (int)$id; ?>" <?= $f['village_id']===(int)$id?'selected':''; ?>><?= html_escape($v['name'].' — '.$v['district']); ?></option><?php endforeach; ?></select></div>
<div class="col-md-6"><label class="form-label" for="nr-library">Perpustakaan</label><select class="form-select" id="nr-library" name="library_id"><option value="0">Semua, termasuk belum terpetakan</option><option value="unassigned" <?= $f['library_id']===-1?'selected':''; ?>>Hanya belum terpetakan</option><?php foreach($o['libraries']as$l): ?><option value="<?= (int)$l['id']; ?>" <?= $f['library_id']===(int)$l['id']?'selected':''; ?>><?= html_escape($l['name']); ?></option><?php endforeach; ?></select></div>
<div class="col-6 col-md-3"><label class="form-label" for="nr-status">Status lembaga</label><select class="form-select" id="nr-status" name="status"><?php foreach(['all'=>'Semua status','active'=>'Aktif','inactive'=>'Nonaktif','pending'=>'Menunggu']as$id=>$name): ?><option value="<?= $id; ?>" <?= $f['status']===$id?'selected':''; ?>><?= $name; ?></option><?php endforeach; ?></select></div>
<div class="col-6 col-md-3"><label class="form-label" for="nr-per">Baris tampil</label><select class="form-select" id="nr-per" name="per_page"><?php foreach([10,25,50,100]as$n): ?><option <?= $per===$n?'selected':''; ?>><?= $n; ?></option><?php endforeach; ?></select></div>
<div class="col-md-8"><label class="form-label" for="nr-q">Cari lembaga / NPSN / wilayah</label><input class="form-control" id="nr-q" name="q" value="<?= html_escape($f['q']); ?>" maxlength="180"></div><div class="col-md-4 d-flex align-items-end gap-2"><button class="btn btn-primary">Terapkan filter</button><a class="btn btn-outline-secondary" href="<?= base_url('reports/network'); ?>">Reset</a></div>
</div></div></form>
<div class="network-report-stats mb-3">
<?php foreach(['Perpustakaan'=>$report['libraries'],'Judul lokal'=>$s['titles'],'Eksemplar fisik'=>$s['items'],'Catatan keanggotaan'=>$s['members'],'Dipinjam dalam periode'=>$s['loans'],'Kembali dalam periode'=>$s['returns'],'Kunjungan offline'=>$s['offline'],'Kunjungan online'=>$s['online']]as$label=>$value): ?><div class="card"><div class="card-body"><div class="text-secondary"><?= $label; ?></div><strong><?= $number($value); ?></strong></div></div><?php endforeach; ?>
</div>
<details class="card mb-3" open><summary class="card-header">Definisi angka dan data belum terpetakan</summary><div class="card-body">
<p>Jumlah judul lokal menjumlahkan kepemilikan per perpustakaan, bukan jumlah karya unik. Filter ini mencakup <strong><?= $number($report['unique_records']); ?> rekaman katalog berbeda</strong>, <strong><?= $number($report['valid_isbns']); ?> ISBN valid berbeda</strong>, dan <?= $number($report['unidentified_records']); ?> rekaman tanpa ISBN valid. ISBN-10/13 setara dinormalisasi; judul atau nama anggota yang sama tidak otomatis digabung.</p>
<p>Keanggotaan adalah jumlah catatan anggota, <strong>bukan orang unik lintas perpustakaan</strong>. Anggota data lama tidak memiliki kolom perpustakaan pemilik, sehingga masuk <em>Belum terpetakan</em>. Alamat tempat tinggal tidak dipakai untuk menentukan pemilik anggota. Filter lembaga/wilayah tidak menyertakan data yang belum terpetakan.</p>
<p class="mb-0">Pinjam/kembali dihitung per eksemplar dengan tanggal transaksi dalam periode; bukan jumlah header transaksi lama. Kunjungan menggunakan jumlah orang (rombongan bisa lebih dari satu orang per entri). Tujuan layanan digital tidak menentukan kanal online. Judul hibrida termasuk dalam fisik dan digital: fisik + digital − hibrida + belum diketahui = judul lokal. Data lama dan jejaring tetap terpisah di database; laporan ini tidak memigrasikan data.</p>
</div></details>
<div class="card mb-3"><div class="card-header flex-wrap gap-2"><h2 class="card-title">Rekap per <?= html_escape(strtolower($groups[$f['group']])); ?></h2><?php if($can_export): ?><div class="ms-auto d-flex gap-2"><?php foreach(['csv'=>'CSV','xlsx'=>'Excel']as$ext=>$label): ?><a class="btn nr-export-<?= $ext; ?>" href="<?= html_escape(base_url('reports/network/export/'.$ext.'?'.http_build_query($query))); ?>"><i class="ti ti-download me-1"></i><?= $label; ?></a><?php endforeach; ?></div><?php endif; ?></div>
<div class="table-responsive nr-detail-table"><table class="table table-vcenter"><thead><tr><th><?= $groups[$f['group']]; ?></th><th>Perpustakaan</th><?php foreach($metrics as$label): ?><th><?= $label; ?></th><?php endforeach; ?></tr></thead><tbody>
<?php foreach(array_slice($report['groups'],($page-1)*$per,$per)as$row): ?><tr><td><?= html_escape($row['label']); ?></td><td><?= $number($row['libraries']); ?></td><?php foreach($metrics as$key=>$label): ?><td><?= $number($row[$key]); ?></td><?php endforeach; ?></tr><?php endforeach; ?>
<?php if(!$report['groups']): ?><tr><td colspan="<?= count($metrics)+2; ?>" class="text-center py-4">Tidak ada data yang cocok.</td></tr><?php endif; ?></tbody><tfoot><tr><th>Total seluruh hasil filter</th><th><?= $number($report['libraries']); ?></th><?php foreach($metrics as$key=>$label): ?><th><?= $number($s[$key]); ?></th><?php endforeach; ?></tr></tfoot></table></div>
<div class="card-footer d-flex flex-wrap gap-2"><span><?= count($report['groups']); ?> kelompok · halaman <?= $page; ?>/<?= $pages; ?> · unduhan mencakup seluruh hasil filter</span><div class="ms-auto d-flex gap-2"><?php if($page>1): ?><a class="btn btn-sm" href="<?= html_escape($page_url($page-1)); ?>">Sebelumnya</a><?php endif; ?><?php if($page<$pages): ?><a class="btn btn-sm" href="<?= html_escape($page_url($page+1)); ?>">Berikutnya</a><?php endif; ?></div></div></div>
<div class="row g-3"><div class="col-lg-7"><div class="card"><div class="card-header"><h2 class="card-title">Tren dalam periode terpilih</h2></div><div class="table-responsive"><table class="table"><thead><tr><th>Bulan</th><th>Pinjam</th><th>Kembali</th><th>Offline (orang)</th><th>Online (orang)</th><th>Entri kunjungan</th></tr></thead><tbody><?php foreach($report['months']as$month=>$row): ?><tr><td><?= $month; ?></td><?php foreach($row as$value): ?><td><?= $number($value); ?></td><?php endforeach; ?></tr><?php endforeach; ?></tbody></table></div></div></div>
<div class="col-lg-5"><div class="card"><div class="card-header"><h2 class="card-title">Kontribusi sumber data</h2></div><div class="table-responsive"><table class="table"><thead><tr><th>Sumber</th><th>Judul lokal</th><th>Anggota</th><th>Pinjam</th><th>Kunjungan (orang)</th></tr></thead><tbody><?php foreach($report['sources']as$row): ?><tr><td><?= html_escape($row['name']); ?></td><td><?= $number($row['titles']); ?></td><td><?= $number($row['members']); ?></td><td><?= $number($row['loans']); ?></td><td><?= $number($row['offline']+$row['online']); ?></td></tr><?php endforeach; ?></tbody></table></div></div></div></div>
</div></div>
<script>
(function(){var district=document.getElementById('nr-district'),village=document.getElementById('nr-village');function sync(clear){if(clear)village.value='0';Array.from(village.options).forEach(function(option){var invalid=option.value!=='0'&&district.value!=='0'&&option.dataset.district!==district.value;option.hidden=invalid;option.disabled=invalid;});}district.addEventListener('change',function(){sync(true);});sync(false);}());
</script>
