<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class English_course_model extends CI_Model
{
    public function __construct()
    {
        parent::__construct();
        $this->ensure_schema();
        $this->seed_curriculum();
        $this->normalize_answer_positions();
        $this->expand_curriculum_v3();
        $this->build_stage1_v1();
        $this->improve_stage1_v2();
        $this->balance_stage1_assessment_v3();
        $this->add_stage1_varied_practice_v4();
    }

    private function ensure_schema()
    {
        $queries = [
            "CREATE TABLE IF NOT EXISTS english_course_levels (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,code VARCHAR(40) NOT NULL UNIQUE,title VARCHAR(120) NOT NULL,cefr VARCHAR(20) NULL,subtitle VARCHAR(180) NULL,description TEXT NULL,color VARCHAR(20) NOT NULL DEFAULT '#2476d3',icon VARCHAR(80) NOT NULL DEFAULT 'ti ti-language',sort_order INT UNSIGNED NOT NULL DEFAULT 1,pass_score TINYINT UNSIGNED NOT NULL DEFAULT 70,is_active TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NULL ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
            "CREATE TABLE IF NOT EXISTS english_course_units (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,level_id INT UNSIGNED NOT NULL,code VARCHAR(60) NOT NULL UNIQUE,title VARCHAR(140) NOT NULL,subtitle VARCHAR(180) NULL,description TEXT NULL,emoji VARCHAR(20) NULL,sort_order INT UNSIGNED NOT NULL DEFAULT 1,is_active TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_ecu_level(level_id),CONSTRAINT fk_ecu_level FOREIGN KEY(level_id) REFERENCES english_course_levels(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
            "CREATE TABLE IF NOT EXISTS english_course_lessons (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,unit_id INT UNSIGNED NOT NULL,code VARCHAR(80) NOT NULL UNIQUE,title VARCHAR(160) NOT NULL,context_label VARCHAR(180) NULL,introduction TEXT NULL,content_json LONGTEXT NOT NULL,sort_order INT UNSIGNED NOT NULL DEFAULT 1,xp_reward INT UNSIGNED NOT NULL DEFAULT 20,is_active TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,KEY idx_ecl_unit(unit_id),CONSTRAINT fk_ecl_unit FOREIGN KEY(unit_id) REFERENCES english_course_units(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
            "CREATE TABLE IF NOT EXISTS english_course_tests (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,level_id INT UNSIGNED NOT NULL UNIQUE,title VARCHAR(160) NOT NULL,instructions TEXT NULL,pass_score TINYINT UNSIGNED NOT NULL DEFAULT 70,is_active TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT fk_ect_level FOREIGN KEY(level_id) REFERENCES english_course_levels(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
            "CREATE TABLE IF NOT EXISTS english_course_test_questions (id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,test_id INT UNSIGNED NOT NULL,prompt TEXT NOT NULL,audio_text VARCHAR(255) NULL,choices_json TEXT NOT NULL,correct_index TINYINT UNSIGNED NOT NULL DEFAULT 0,explanation TEXT NULL,sort_order INT UNSIGNED NOT NULL DEFAULT 1,KEY idx_ectq_test(test_id),CONSTRAINT fk_ectq_test FOREIGN KEY(test_id) REFERENCES english_course_tests(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
            "CREATE TABLE IF NOT EXISTS english_course_lesson_progress (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,lesson_id INT UNSIGNED NOT NULL,status ENUM('started','completed') NOT NULL DEFAULT 'started',score TINYINT UNSIGNED NOT NULL DEFAULT 0,completed_at DATETIME NULL,last_opened_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE KEY uq_eclp_user_lesson(user_id,lesson_id),KEY idx_eclp_user(user_id),CONSTRAINT fk_eclp_lesson FOREIGN KEY(lesson_id) REFERENCES english_course_lessons(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
            "CREATE TABLE IF NOT EXISTS english_course_test_attempts (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,test_id INT UNSIGNED NOT NULL,score TINYINT UNSIGNED NOT NULL,correct_count INT UNSIGNED NOT NULL,total_questions INT UNSIGNED NOT NULL,is_passed TINYINT(1) NOT NULL DEFAULT 0,answers_json LONGTEXT NULL,started_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,completed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_ecta_user(user_id),KEY idx_ecta_test(test_id),CONSTRAINT fk_ecta_test FOREIGN KEY(test_id) REFERENCES english_course_tests(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
            "CREATE TABLE IF NOT EXISTS english_course_activity_attempts (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,lesson_id INT UNSIGNED NOT NULL,step_no SMALLINT UNSIGNED NOT NULL,activity_type VARCHAR(40) NOT NULL,answer_text TEXT NULL,score TINYINT UNSIGNED NOT NULL DEFAULT 0,is_correct TINYINT(1) NOT NULL DEFAULT 0,attempt_count INT UNSIGNED NOT NULL DEFAULT 1,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NULL ON UPDATE CURRENT_TIMESTAMP,UNIQUE KEY uq_ecaa_user_step(user_id,lesson_id,step_no),KEY idx_ecaa_user(user_id),CONSTRAINT fk_ecaa_lesson FOREIGN KEY(lesson_id) REFERENCES english_course_lessons(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
            "CREATE TABLE IF NOT EXISTS english_course_checkpoint_attempts (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,unit_id INT UNSIGNED NOT NULL,score TINYINT UNSIGNED NOT NULL,correct_count INT UNSIGNED NOT NULL,total_questions INT UNSIGNED NOT NULL,is_passed TINYINT(1) NOT NULL DEFAULT 0,answers_json LONGTEXT NULL,completed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_ecca_user(user_id),KEY idx_ecca_unit(unit_id),CONSTRAINT fk_ecca_unit FOREIGN KEY(unit_id) REFERENCES english_course_units(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
            "CREATE TABLE IF NOT EXISTS english_course_stage_review_attempts (id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED NOT NULL,level_id INT UNSIGNED NOT NULL,review_part TINYINT UNSIGNED NOT NULL,score TINYINT UNSIGNED NOT NULL,correct_count INT UNSIGNED NOT NULL,total_questions INT UNSIGNED NOT NULL,is_passed TINYINT(1) NOT NULL DEFAULT 0,answers_json LONGTEXT NULL,completed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,KEY idx_ecsra_user(user_id),KEY idx_ecsra_level(level_id,review_part),CONSTRAINT fk_ecsra_level FOREIGN KEY(level_id) REFERENCES english_course_levels(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci",
            "CREATE TABLE IF NOT EXISTS english_course_settings (setting_key VARCHAR(80) PRIMARY KEY,setting_value TEXT NULL,updated_at DATETIME NULL ON UPDATE CURRENT_TIMESTAMP) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci"
        ];
        foreach ($queries as $sql) $this->db->query($sql);
        if(!$this->db->field_exists('stage_no','english_course_units'))$this->db->query("ALTER TABLE english_course_units ADD stage_no TINYINT UNSIGNED NOT NULL DEFAULT 1 AFTER level_id, ADD KEY idx_ecu_stage(stage_no)");
        if(!$this->db->field_exists('lesson_type','english_course_lessons'))$this->db->query("ALTER TABLE english_course_lessons ADD lesson_type VARCHAR(30) NOT NULL DEFAULT 'dialogue' AFTER context_label");
        if(!$this->db->field_exists('question_type','english_course_test_questions'))$this->db->query("ALTER TABLE english_course_test_questions ADD question_type VARCHAR(30) NOT NULL DEFAULT 'comprehension' AFTER audio_text");
        $defaults=['course_title'=>'English Learning Course','tts_voice'=>'us_female','tts_rate'=>'0.88','show_translation'=>'1','require_level_test'=>'1'];
        foreach($defaults as $key=>$value)$this->db->query("INSERT IGNORE INTO english_course_settings(setting_key,setting_value) VALUES(?,?)",[$key,$value]);
        $this->db->query("UPDATE english_course_settings SET setting_value='us_female' WHERE setting_key='tts_voice' AND setting_value='female'");
    }

    private function seed_curriculum()
    {
        if ((int)$this->db->count_all('english_course_levels') > 0) return;
        $levels = [
            ['starter','Beginner – Starter','Pre-A1','Mulai berbicara dari situasi terdekat.','Salam, kelas, keluarga, angka, warna, dan instruksi dasar.','#2583e8','ti ti-seedling'],
            ['daily','Elementary – Daily Life','A1','Bangun kebiasaan berbahasa setiap hari.','Rutinitas, waktu, makanan, tempat, belanja, dan simple present.','#13a684','ti ti-sun'],
            ['conversation','Pre-Intermediate – Conversation','A2','Berani terlibat dalam percakapan.','Rencana, pengalaman, perjalanan, layanan publik, dan past tense.','#805ad5','ti ti-messages'],
            ['communication','Intermediate – Communication','B1','Sampaikan gagasan dengan lebih jelas.','Pendapat, cerita, pesan, presentasi, dan listening kontekstual.','#e79024','ti ti-microphone'],
            ['expression','Advanced – Fluent Expression','B2','Gunakan bahasa secara luwes dan tepat.','Diskusi, idiom, teks formal, argumentasi, dan presentasi.','#e15375','ti ti-sparkles'],
            ['professional','Expert – Academic & Professional','C1','Berkomunikasi untuk dunia akademik dan kerja.','Debat, laporan, korespondensi, public speaking, dan critical reading.','#233a73','ti ti-school']
        ];
        $curriculum = [
            'starter'=>[
                ['at-school','At School','Di sekolah','🏫',[['Good morning, Teacher.','Selamat pagi, Bu/Pak Guru.','Teacher','A cheerful greeting before class starts.'],['May I enter?','Bolehkah saya masuk?','Student','Use this sentence to ask permission politely.'],['Please open your notebook.','Tolong buka buku catatanmu.','Teacher','Please makes an instruction sound polite.'],['Raise your hand.','Angkat tanganmu.','Teacher','A common classroom instruction.'],['See you tomorrow.','Sampai jumpa besok.','Student','A friendly way to end the school day.']]],
                ['my-world','My World','Keluarga dan benda sekitar','🏡',[['This is my mother.','Ini ibu saya.','Student','Use this is to introduce one person or thing.'],['I have a blue bag.','Saya mempunyai tas biru.','Student','Have shows possession.'],['The book is on the table.','Buku itu berada di atas meja.','Teacher','On tells us the position.'],['How many pencils do you have?','Berapa pensil yang kamu punya?','Teacher','How many asks about countable things.'],['I have three pencils.','Saya mempunyai tiga pensil.','Student','Use a number before a plural noun.']]]
            ],
            'daily'=>[
                ['daily-routine','My Daily Routine','Rutinitas harian','⏰',[['I wake up at six.','Saya bangun pukul enam.','Nina','Use at before a specific time.'],['I brush my teeth.','Saya menyikat gigi.','Nina','A daily routine in simple present.'],['She goes to school by bus.','Dia pergi ke sekolah naik bus.','Narrator','Add -es to go for she/he.'],['We study in the library.','Kami belajar di perpustakaan.','Nina','We describes a group including the speaker.'],['I usually sleep at nine.','Saya biasanya tidur pukul sembilan.','Nina','Usually describes frequency.']]],
                ['food-shopping','Food and Shopping','Makanan dan berbelanja','🛒',[['I would like a bowl of soup.','Saya ingin semangkuk sup.','Customer','Would like is a polite request.'],['How much is this?','Berapa harga ini?','Customer','Use how much to ask a price.'],['The apples are fresh.','Apel-apel itu segar.','Seller','Are is used with plural nouns.'],['Can I pay by card?','Bisakah saya membayar dengan kartu?','Customer','Can I asks if something is possible.'],['Here is your change.','Ini uang kembalian Anda.','Seller','A useful phrase after payment.']]]
            ],
            'conversation'=>[
                ['travel-plans','Travel Plans','Rencana perjalanan','🚌',[['I am going to visit Yogyakarta.','Saya akan mengunjungi Yogyakarta.','Dina','Going to expresses a plan.'],['What time does the train leave?','Pukul berapa keretanya berangkat?','Dina','Use does with a singular subject.'],['Could you show me the way?','Bisakah Anda menunjukkan jalannya?','Traveler','Could you is a polite request.'],['I booked a room yesterday.','Saya memesan kamar kemarin.','Traveler','Booked is the past form of book.'],['We had a wonderful trip.','Kami mengalami perjalanan yang menyenangkan.','Dina','Had is the past form of have.']]],
                ['public-service','At a Public Service','Di layanan publik','🏛️',[['I would like to apply for a library card.','Saya ingin mendaftar kartu perpustakaan.','Visitor','A formal and polite request.'],['Please fill in this form.','Silakan isi formulir ini.','Officer','Fill in means complete a form.'],['Which document should I bring?','Dokumen mana yang harus saya bawa?','Visitor','Should asks for advice or requirement.'],['Your application has been approved.','Permohonan Anda telah disetujui.','Officer','Present perfect passive describes a completed process.'],['Thank you for your assistance.','Terima kasih atas bantuan Anda.','Visitor','A formal expression of gratitude.']]]
            ],
            'communication'=>[
                ['sharing-opinions','Sharing Opinions','Menyampaikan pendapat','💬',[['In my opinion, reading builds empathy.','Menurut saya, membaca membangun empati.','Arif','A clear phrase to introduce an opinion.'],['I agree with your main point.','Saya setuju dengan gagasan utama Anda.','Maya','Agree with is followed by a person or idea.'],['However, we should consider the cost.','Namun, kita harus mempertimbangkan biayanya.','Arif','However introduces a contrast.'],['Could you explain what you mean?','Bisakah Anda menjelaskan maksud Anda?','Maya','Ask for clarification politely.'],['Let us find a practical solution.','Mari kita cari solusi yang praktis.','Arif','Let us invites people to act together.']]],
                ['presentation','Giving a Presentation','Melakukan presentasi','📊',[['Today I am going to talk about literacy.','Hari ini saya akan membahas literasi.','Presenter','A useful presentation opening.'],['First, let us look at the data.','Pertama, mari kita lihat datanya.','Presenter','Sequence markers organize ideas.'],['This chart shows a steady increase.','Grafik ini menunjukkan kenaikan yang stabil.','Presenter','Shows describes information in a visual.'],['The key takeaway is simple.','Kesimpulan utamanya sederhana.','Presenter','Takeaway means the most important message.'],['Thank you. I am happy to answer questions.','Terima kasih. Saya siap menjawab pertanyaan.','Presenter','A professional closing.']]]
            ],
            'expression'=>[
                ['thoughtful-discussion','Thoughtful Discussion','Diskusi mendalam','🧠',[['The issue is more nuanced than it appears.','Masalah ini lebih bernuansa daripada kelihatannya.','Speaker','Nuanced means having subtle distinctions.'],['That argument rests on a false assumption.','Argumen itu bertumpu pada asumsi yang keliru.','Speaker','Rest on means depend on.'],['We need to weigh the benefits against the risks.','Kita perlu menimbang manfaat dan risikonya.','Speaker','Weigh against means compare carefully.'],['I see where you are coming from.','Saya memahami sudut pandang Anda.','Speaker','An idiomatic way to acknowledge perspective.'],['The evidence supports a different conclusion.','Buktinya mendukung kesimpulan yang berbeda.','Speaker','Academic phrasing for disagreement.']]],
                ['formal-writing','Formal Writing','Penulisan formal','✍️',[['I am writing to inquire about the program.','Saya menulis untuk menanyakan program tersebut.','Writer','A formal email opening.'],['Please find the document attached.','Dokumen terlampir bersama pesan ini.','Writer','Common professional email phrase.'],['The findings indicate a significant change.','Temuan menunjukkan perubahan yang signifikan.','Researcher','Indicate is formal for show.'],['This matter requires further consideration.','Hal ini memerlukan pertimbangan lebih lanjut.','Writer','A measured formal statement.'],['I look forward to your response.','Saya menantikan tanggapan Anda.','Writer','A polite formal closing.']]]
            ],
            'professional'=>[
                ['academic-argument','Academic Argument','Argumentasi akademik','🎓',[['The study challenges the prevailing assumption.','Studi ini menantang asumsi yang dominan.','Researcher','Prevailing means generally accepted.'],['Correlation should not be mistaken for causation.','Korelasi tidak boleh dianggap sebagai sebab-akibat.','Researcher','A core critical-thinking distinction.'],['The methodology warrants closer scrutiny.','Metodologinya memerlukan pemeriksaan lebih dekat.','Reviewer','Warrants means deserves or requires.'],['This interpretation is consistent with the evidence.','Interpretasi ini selaras dengan bukti.','Researcher','Consistent with means in agreement with.'],['Further research is needed to substantiate the claim.','Penelitian lanjutan diperlukan untuk menguatkan klaim.','Researcher','Substantiate means support with evidence.']]],
                ['leadership','Professional Leadership','Kepemimpinan profesional','🤝',[['Let us align our priorities before proceeding.','Mari selaraskan prioritas sebelum melanjutkan.','Manager','Align means bring into agreement.'],['I appreciate your candid feedback.','Saya menghargai masukan Anda yang terus terang.','Manager','Candid means honest and direct.'],['We need a contingency plan.','Kita memerlukan rencana cadangan.','Manager','A plan for possible problems.'],['Could you elaborate on the projected impact?','Bisakah Anda menguraikan dampak yang diproyeksikan?','Manager','Elaborate means explain in more detail.'],['The proposal strikes a balance between ambition and feasibility.','Usulan ini menyeimbangkan ambisi dan kelayakan.','Manager','Strike a balance is a professional idiom.']]]
            ]
        ];
        $this->db->trans_start();
        foreach($levels as $li=>$lv){
            $this->db->insert('english_course_levels',['code'=>$lv[0],'title'=>$lv[1],'cefr'=>$lv[2],'subtitle'=>$lv[3],'description'=>$lv[4],'color'=>$lv[5],'icon'=>$lv[6],'sort_order'=>$li+1,'pass_score'=>70]);$levelId=(int)$this->db->insert_id();
            foreach($curriculum[$lv[0]] as $ui=>$unit){
                $this->db->insert('english_course_units',['level_id'=>$levelId,'code'=>$unit[0],'title'=>$unit[1],'subtitle'=>$unit[2],'description'=>'Pelajari ungkapan penting melalui situasi, audio, terjemahan, dan latihan singkat.','emoji'=>$unit[3],'sort_order'=>$ui+1]);$unitId=(int)$this->db->insert_id();
                $cards=[];foreach($unit[4] as $i=>$p)$cards[]=['number'=>$i+1,'english'=>$p[0],'translation'=>$p[1],'speaker'=>$p[2],'note'=>$p[3],'emoji'=>$unit[3]];
                $this->db->insert('english_course_lessons',['unit_id'=>$unitId,'code'=>$unit[0].'-lesson','title'=>$unit[1].' Essentials','context_label'=>$unit[2],'introduction'=>'Dengarkan setiap kalimat, buka hint bila diperlukan, lalu ucapkan kembali dengan percaya diri.','content_json'=>json_encode($cards,JSON_UNESCAPED_UNICODE),'sort_order'=>1,'xp_reward'=>20]);
            }
            $this->db->insert('english_course_tests',['level_id'=>$levelId,'title'=>'Tes Akhir '.$lv[1],'instructions'=>'Pilih jawaban terbaik untuk mengulas ungkapan yang telah dipelajari.','pass_score'=>70]);$testId=(int)$this->db->insert_id();
            $phrases=array_merge($curriculum[$lv[0]][0][4],$curriculum[$lv[0]][1][4]);
            foreach(array_slice($phrases,0,5) as $qi=>$p){$wrong1=$phrases[($qi+2)%count($phrases)][1];$wrong2=$phrases[($qi+4)%count($phrases)][1];$choices=[$p[1],$wrong1,$wrong2,'Tidak ada jawaban yang tepat'];$this->db->insert('english_course_test_questions',['test_id'=>$testId,'prompt'=>'Apa arti yang paling tepat dari: “'.$p[0].'”','audio_text'=>$p[0],'choices_json'=>json_encode($choices,JSON_UNESCAPED_UNICODE),'correct_index'=>0,'explanation'=>$p[3].' Arti: '.$p[1],'sort_order'=>$qi+1]);}
        }
        $this->db->trans_complete();
    }

    private function normalize_answer_positions()
    {
        if ($this->db->get_where('english_course_settings',['setting_key'=>'answer_positions_v2'])->row_array()) return;
        $positions=[1,3,0,2,1];
        $tests=$this->db->get('english_course_tests')->result_array();
        foreach($tests as $test){
            $questions=$this->db->order_by('sort_order')->get_where('english_course_test_questions',['test_id'=>$test['id']])->result_array();
            foreach($questions as $i=>$q){
                $choices=json_decode($q['choices_json'],true)?:[];
                if(!$choices)continue;
                $correct=$choices[(int)$q['correct_index']]??$choices[0];
                array_splice($choices,(int)$q['correct_index'],1);
                $position=min($positions[$i%count($positions)],count($choices));
                array_splice($choices,$position,0,[$correct]);
                $this->db->where('id',$q['id'])->update('english_course_test_questions',['choices_json'=>json_encode(array_values($choices),JSON_UNESCAPED_UNICODE),'correct_index'=>$position]);
            }
        }
        $this->db->replace('english_course_settings',['setting_key'=>'answer_positions_v2','setting_value'=>'1']);
    }

    private function expand_curriculum_v3()
    {
        if($this->db->get_where('english_course_settings',['setting_key'=>'curriculum_v3'])->row_array())return;
        $extra=require APPPATH.'models/data/english_course_expansion.php';
        $motions=['float','bounce','wave','zoom','slide','nod','sway','pop','glow','drift'];
        $existing=$this->db->select('l.*,u.code unit_code,u.level_id,lv.code level_code')->from('english_course_lessons l')->join('english_course_units u','u.id=l.unit_id')->join('english_course_levels lv','lv.id=u.level_id')->get()->result_array();
        $this->db->trans_start();
        foreach($existing as $lesson){
            $cards=json_decode($lesson['content_json'],true)?:[];
            $scene=in_array($lesson['level_code'],['starter'],true)?'classroom':(in_array($lesson['level_code'],['daily'],true)?'home':'library');
            foreach($cards as $i=>&$card){$card['scene']=$scene;$card['motion']=$motions[$i%count($motions)];$card['bubble_side']=$scene==='home'?'left':'right';}unset($card);
            $tail=[['Can we practise these expressions together?','Bisakah kita melatih ungkapan-ungkapan ini bersama?','Learner'],['Of course. Listen first, then speak clearly.','Tentu. Dengarkan dahulu, lalu ucapkan dengan jelas.','Coach'],['I understand them better now.','Sekarang saya memahaminya dengan lebih baik.','Learner']];
            foreach($tail as $x){$i=count($cards);$cards[]=['number'=>$i+1,'english'=>$x[0],'translation'=>$x[1],'speaker'=>$x[2],'note'=>'Closing practice: use the expressions again in your own situation.','emoji'=>'💬','scene'=>$scene,'motion'=>$motions[$i%count($motions)],'bubble_side'=>$scene==='home'?'left':'right'];}
            $this->db->where('id',$lesson['id'])->update('english_course_lessons',['content_json'=>json_encode($cards,JSON_UNESCAPED_UNICODE),'xp_reward'=>30]);
        }
        foreach($extra as $levelCode=>$chapter){
            $level=$this->db->get_where('english_course_levels',['code'=>$levelCode])->row_array();if(!$level)continue;
            $this->db->insert('english_course_units',['level_id'=>$level['id'],'code'=>$chapter[0],'title'=>$chapter[1],'subtitle'=>$chapter[2],'description'=>'Chapter percakapan utuh dengan pergantian pembicara, audio, hint, dan visual kontekstual.','emoji'=>$chapter[3],'sort_order'=>3]);$unitId=(int)$this->db->insert_id();
            $scene=$levelCode==='starter'?'classroom':($levelCode==='daily'?'home':'library');$cards=[];
            foreach($chapter[4] as $i=>$line)$cards[]=['number'=>$i+1,'english'=>$line[0],'translation'=>$line[1],'speaker'=>$line[2],'note'=>'Notice how this sentence connects naturally to the previous turn.','emoji'=>$chapter[3],'scene'=>$scene,'motion'=>$motions[$i%count($motions)],'bubble_side'=>$scene==='home'?'left':'right'];
            $this->db->insert('english_course_lessons',['unit_id'=>$unitId,'code'=>$chapter[0].'-lesson','title'=>$chapter[1].' Conversation','context_label'=>$chapter[2],'introduction'=>'Ikuti percakapan dari awal sampai akhir. Dengarkan perubahan pembicara dan tirukan intonasinya.','content_json'=>json_encode($cards,JSON_UNESCAPED_UNICODE),'sort_order'=>1,'xp_reward'=>40]);
            $test=$this->db->get_where('english_course_tests',['level_id'=>$level['id']])->row_array();
            foreach(array_slice($chapter[4],0,3) as $qi=>$line){$others=[$chapter[4][($qi+3)%10][1],$chapter[4][($qi+6)%10][1],$line[1]];$correctAt=[2,0,1][$qi];$correct=array_pop($others);array_splice($others,$correctAt,0,[$correct]);$this->db->insert('english_course_test_questions',['test_id'=>$test['id'],'prompt'=>'Apa arti yang paling tepat dari: “'.$line[0].'”','audio_text'=>$line[0],'choices_json'=>json_encode($others,JSON_UNESCAPED_UNICODE),'correct_index'=>$correctAt,'explanation'=>'Ungkapan ini dipakai dalam chapter '.$chapter[1].'. Arti: '.$line[1],'sort_order'=>6+$qi]);}
        }
        $this->db->replace('english_course_settings',['setting_key'=>'curriculum_v3','setting_value'=>'1']);
        $this->db->trans_complete();
    }

    private function build_stage1_v1()
    {
        if($this->db->get_where('english_course_settings',['setting_key'=>'stage1_v1'])->row_array())return;
        $chapters=require APPPATH.'models/data/english_course_stage1.php';$level=$this->db->get_where('english_course_levels',['code'=>'starter'])->row_array();if(!$level)return;
        $motions=['float','bounce','wave','zoom','slide','nod','sway','pop','glow','drift'];$lessonMap=[];
        $this->db->trans_start();
        foreach($chapters as $ci=>$chapter){
            $unitCode='s1-ch'.str_pad($ci+1,2,'0',STR_PAD_LEFT).'-'.$chapter[0];$unit=$this->db->get_where('english_course_units',['code'=>$unitCode])->row_array();
            if(!$unit){$this->db->insert('english_course_units',['level_id'=>$level['id'],'stage_no'=>1,'code'=>$unitCode,'title'=>$chapter[1],'subtitle'=>$chapter[2],'description'=>'Stage 1 · Chapter '.($ci+1).' — '.$chapter[4].'. Fokus kosakata: '.$chapter[5].'.','emoji'=>$chapter[3],'sort_order'=>$ci+1,'is_active'=>1]);$unitId=(int)$this->db->insert_id();}else{$unitId=(int)$unit['id'];}
            $types=[['dialogue','Context Story','Ikuti percakapan dan pahami maknanya.'],['grammar','Language Focus','Temukan pola: '.$chapter[4].'.'],['vocabulary','Vocabulary & Sound','Bangun kosakata dan pengucapan: '.$chapter[5].'.'],['skills','Guided Skills Lab','Latih listening, memilih, menyusun, dan mengoreksi kalimat.'],['mission','Communication Mission','Gunakan seluruh materi chapter dalam misi singkat.']];
            foreach($types as $li=>$type){$code=$unitCode.'-'.$type[0];$steps=$this->stage1_steps($chapter,$type[0],$motions);$row=$this->db->get_where('english_course_lessons',['code'=>$code])->row_array();$data=['unit_id'=>$unitId,'code'=>$code,'title'=>($li+1).'. '.$type[1],'context_label'=>$chapter[2],'lesson_type'=>$type[0],'introduction'=>$type[2],'content_json'=>json_encode($steps,JSON_UNESCAPED_UNICODE),'sort_order'=>$li+1,'xp_reward'=>20+($li*5),'is_active'=>1];if($row){$this->db->where('id',$row['id'])->update('english_course_lessons',$data);$lessonId=(int)$row['id'];}else{$this->db->insert('english_course_lessons',$data);$lessonId=(int)$this->db->insert_id();}if($li===0)$lessonMap[$ci+1]=$lessonId;}
        }
        $legacy=$this->db->where('level_id',$level['id'])->not_like('code','s1-ch','after')->get('english_course_units')->result_array();
        foreach($legacy as $old){$target=strpos($old['code'],'at-school')!==false?3:(strpos($old['code'],'my-world')!==false?5:9);$oldLessons=$this->db->select('id')->get_where('english_course_lessons',['unit_id'=>$old['id']])->result_array();foreach($oldLessons as $ol){$progress=$this->db->get_where('english_course_lesson_progress',['lesson_id'=>$ol['id']])->result_array();foreach($progress as $p){$exists=$this->db->get_where('english_course_lesson_progress',['user_id'=>$p['user_id'],'lesson_id'=>$lessonMap[$target]])->row_array();$data=['status'=>$p['status'],'score'=>$p['score'],'completed_at'=>$p['completed_at'],'last_opened_at'=>$p['last_opened_at']];if($exists)$this->db->where('id',$exists['id'])->update('english_course_lesson_progress',$data);else{$data['user_id']=$p['user_id'];$data['lesson_id']=$lessonMap[$target];$this->db->insert('english_course_lesson_progress',$data);}}}$this->db->where('id',$old['id'])->update('english_course_units',['is_active'=>0]);}
        $this->db->where('id',$level['id'])->update('english_course_levels',['title'=>'Stage 1 — First Words','subtitle'=>'Fondasi Bahasa Inggris · Pre-A1','description'=>'12 chapter, 60 lesson, dan latihan grammar, vocabulary, listening, pronunciation, reading, writing, serta speaking.','pass_score'=>75,'is_active'=>1]);$this->db->where('id !=',$level['id'])->update('english_course_levels',['is_active'=>0]);
        $test=$this->db->get_where('english_course_tests',['level_id'=>$level['id']])->row_array();if($test){$this->db->where('test_id',$test['id'])->delete('english_course_test_questions');$qNo=1;foreach($chapters as $ci=>$chapter){$take=$ci<6?3:2;foreach(array_slice($chapter[6],0,$take) as $ei=>$example){$wrong1=$chapters[($ci+2)%count($chapters)][6][$ei%5][1];$wrong2=$chapters[($ci+5)%count($chapters)][6][($ei+1)%5][1];$choices=[$example[1],$wrong1,$wrong2,'Maknanya tidak tersedia'];$correctAt=($qNo*3+1)%4;$correct=array_shift($choices);array_splice($choices,$correctAt,0,[$correct]);$this->db->insert('english_course_test_questions',['test_id'=>$test['id'],'prompt'=>'Pilih arti yang tepat: “'.$example[0].'”','audio_text'=>$example[0],'choices_json'=>json_encode($choices,JSON_UNESCAPED_UNICODE),'correct_index'=>$correctAt,'explanation'=>$chapter[4].' — '.$example[1],'sort_order'=>$qNo++]);}}$this->db->where('id',$test['id'])->update('english_course_tests',['title'=>'Stage 1 Final Assessment','instructions'=>'30 soal untuk mengulas struktur, kosakata, listening, dan pemahaman situasional Stage 1.','pass_score'=>75]);}
        $this->db->replace('english_course_settings',['setting_key'=>'stage1_v1','setting_value'=>'1']);$this->db->trans_complete();
    }

    private function stage1_steps(array $chapter,$type,array $motions)
    {
        $examples=$chapter[6];$steps=[];$scene=in_array($chapter[0],['people-around-me','my-body-feelings','my-home','food-drinks','my-day'],true)?'home':'classroom';
        for($i=0;$i<10;$i++){$ex=$examples[$i%count($examples)];$kind=$type;$note=$chapter[4];$prompt='Dengarkan dan pahami kalimat ini.';
            if($type==='grammar'){$prompt=$i%2?'Perhatikan susunan dan kata kerja pada contoh.':'Temukan pola grammar yang digunakan.';$note='Grammar focus: '.$chapter[4].'. Bandingkan subject, verb, dan pelengkapnya.';}
            elseif($type==='vocabulary'){$prompt=$i%2?'Ucapkan kembali dengan tekanan kata yang jelas.':'Hubungkan kata penting dengan konteks gambarnya.';$note='Vocabulary focus: '.$chapter[5].'. Dengarkan lalu tirukan tanpa terburu-buru.';}
            elseif($type==='skills'){$kind=$i%3===0?'listen_choice':($i%3===1?'sentence_builder':'error_check');$prompt=$kind==='listen_choice'?'Dengarkan, lalu pilih makna yang sesuai.':($kind==='sentence_builder'?'Susun kembali kalimat ini dengan urutan yang benar.':'Periksa apakah susunan kalimat sudah tepat.');$note='Guided practice untuk '.$chapter[4];}
            elseif($type==='mission'){$kind=$i<5?'guided_response':'independent_mission';$prompt=$i<5?'Pilih atau ucapkan respons yang sesuai.':'Gunakan pola ini untuk menceritakan dirimu sendiri.';$note='Mission: ubah bagian penting kalimat agar sesuai dengan keadaanmu.';}
            $steps[]=['number'=>$i+1,'activity_type'=>$kind,'prompt'=>$prompt,'english'=>$ex[0],'translation'=>$ex[1],'speaker'=>$i%2?'Learner':'Coach','note'=>$note,'emoji'=>$chapter[3],'scene'=>$scene,'motion'=>$motions[$i%count($motions)],'bubble_side'=>$scene==='home'?'left':'right','choices'=>[$ex[1],'Coba dengarkan kembali','Gunakan hint bila perlu']];}
        return $steps;
    }

    private function improve_stage1_v2()
    {
        if($this->db->get_where('english_course_settings',['setting_key'=>'stage1_v2_unique_lessons'])->row_array())return;
        $chapters=require APPPATH.'models/data/english_course_stage1.php';$enrichment=require APPPATH.'models/data/english_course_stage1_enrichment.php';$motions=['float','bounce','wave','zoom','slide','nod','sway','pop','glow','drift'];
        $this->db->trans_start();
        foreach($chapters as $ci=>$chapter){$slug=$chapter[0];if(empty($enrichment[$slug]))continue;$extra=$enrichment[$slug];$unit=$this->db->like('code','s1-ch'.str_pad($ci+1,2,'0',STR_PAD_LEFT).'-'.$slug,'after')->get('english_course_units')->row_array();if(!$unit)continue;$scene=in_array($slug,['people-around-me','my-body-feelings','my-home','food-drinks','my-day'],true)?'home':'classroom';$base=$chapter[6];$dialogue=[];foreach($base as $i=>$line){$dialogue[]=$this->course_step($line[0],$line[1],$i%2?'Learner':'Coach','dialogue','Dengarkan giliran percakapan ini.','Perhatikan salam, respons, dan intonasinya.',$chapter,$scene,$motions,count($dialogue));$reply=$extra['replies'][$i];$dialogue[]=$this->course_step($reply[0],$reply[1],$i%2?'Coach':'Learner','dialogue','Apa respons berikutnya dalam percakapan?','Respons ini menyambung langsung dengan kalimat sebelumnya.',$chapter,$scene,$motions,count($dialogue));}
            $grammar=[];foreach($extra['rules'] as $i=>$line)$grammar[]=$this->course_step($line[0],$line[1],'Grammar Coach','grammar',$i===0?'Amati pola utama chapter ini.':'Bandingkan subject dan bentuk verb pada contoh.','Grammar: '.$chapter[4].'.',$chapter,$scene,$motions,count($grammar));foreach($base as $i=>$line)$grammar[]=$this->course_step($line[0],$line[1],'Grammar Lab','grammar',$i%2?'Tentukan fungsi setiap bagian kalimat.':'Bangun kembali kalimat dengan susunan yang benar.','Gunakan pola '.$chapter[4].'.',$chapter,$scene,$motions,count($grammar),$i%2?'error_check':'sentence_builder');
            $vocab=[];$pairs=[];foreach(explode('|',$extra['vocab']) as $item){$parts=explode('=',$item,2);if(count($parts)===2)$pairs[]=$parts;}foreach($pairs as $i=>$pair)$vocab[]=$this->course_step($pair[0],$pair[1],'Sound Coach','vocabulary',$i%2?'Ucapkan kata ini, lalu gunakan dalam frasa pendek.':'Dengarkan bunyi dan tekanan katanya.','Vocabulary chapter: '.$chapter[5].'.',$chapter,$scene,$motions,count($vocab),'vocabulary');
            $skills=[];$skillSource=array_merge($extra['rules'],$extra['replies']);foreach(array_slice($skillSource,0,10) as $i=>$line){$kind=['listen_choice','sentence_builder','error_check'][$i%3];$prompt=$kind==='listen_choice'?'Dengarkan tanpa melihat arti, lalu pilih maknanya.':($kind==='sentence_builder'?'Susun kata menjadi kalimat yang benar.':'Periksa subject dan verb pada kalimat ini.');$step=$this->course_step($line[0],$line[1],'Skills Coach',$kind,$prompt,'Gunakan kembali grammar dan kosakata chapter ini.',$chapter,$scene,$motions,count($skills),$kind);if($kind==='listen_choice')$step['choices']=[$line[1],$skillSource[($i+2)%10][1],$skillSource[($i+5)%10][1]];$skills[]=$step;}
            $mission=[];foreach($extra['missions'] as $i=>$line)$mission[]=$this->course_step($line[0],$line[1],'Mission Guide','guided_response','Lakukan tugas komunikasi ini.','Jawaban harus sesuai dengan keadaanmu sendiri.',$chapter,$scene,$motions,count($mission),'guided_response');foreach($base as $i=>$line)$mission[]=$this->course_step($line[0],$line[1],'Your Turn','independent_mission','Ubah contoh menjadi kalimat tentang dirimu.','Jangan sekadar meniru; ganti nama, benda, tempat, atau kegiatannya.',$chapter,$scene,$motions,count($mission),'independent_mission');
            foreach(['dialogue'=>$dialogue,'grammar'=>$grammar,'vocabulary'=>$vocab,'skills'=>$skills,'mission'=>$mission] as $type=>$steps)$this->db->where(['unit_id'=>$unit['id'],'lesson_type'=>$type])->update('english_course_lessons',['content_json'=>json_encode($steps,JSON_UNESCAPED_UNICODE)]);
        }
        $this->db->replace('english_course_settings',['setting_key'=>'stage1_v2_unique_lessons','setting_value'=>'1']);$this->db->trans_complete();
    }

    private function course_step($english,$translation,$speaker,$activityType,$prompt,$note,array $chapter,$scene,array $motions,$index,$overrideType=null)
    {
        return ['number'=>$index+1,'activity_type'=>$overrideType?:$activityType,'prompt'=>$prompt,'english'=>$english,'translation'=>$translation,'speaker'=>$speaker,'note'=>$note,'emoji'=>$chapter[3],'scene'=>$scene,'motion'=>$motions[$index%count($motions)],'bubble_side'=>$scene==='home'?'left':'right','choices'=>[$translation,'Makna lain yang tidak sesuai','Dengarkan sekali lagi']];
    }

    private function balance_stage1_assessment_v3()
    {
        if($this->db->get_where('english_course_settings',['setting_key'=>'stage1_assessment_v3'])->row_array())return;
        $level=$this->db->get_where('english_course_levels',['code'=>'starter'])->row_array();if(!$level)return;
        $test=$this->db->get_where('english_course_tests',['level_id'=>$level['id']])->row_array();if(!$test)return;
        $chapters=require APPPATH.'models/data/english_course_stage1.php';$enrichment=require APPPATH.'models/data/english_course_stage1_enrichment.php';$items=[];
        foreach($chapters as $ci=>$chapter){$line=$chapter[6][$ci%count($chapter[6])];$items[]=['type'=>$ci%2?'meaning':'listening','prompt'=>($ci%2?'Pilih arti yang tepat: ':'Dengarkan, lalu pilih arti: ').'“'.$line[0].'”','audio'=>$ci%2?'':$line[0],'correct'=>$line[1],'pool'=>'translations','explanation'=>$chapter[4].' — '.$line[1]];}
        foreach(array_slice($chapters,0,6) as $ci=>$chapter){$pairs=[];foreach(explode('|',$enrichment[$chapter[0]]['vocab']) as $raw){$p=explode('=',$raw,2);if(count($p)===2)$pairs[]=$p;}$pair=$pairs[$ci%count($pairs)];$items[]=['type'=>'vocabulary','prompt'=>'Apa arti kata/frasa “'.$pair[0].'”?','audio'=>$pair[0],'correct'=>$pair[1],'pool'=>'vocab','explanation'=>$pair[0].' berarti '.$pair[1].'.'];}
        foreach(array_slice($chapters,6,6) as $ci=>$chapter){$rule=$enrichment[$chapter[0]]['rules'][$ci%count($enrichment[$chapter[0]]['rules'])];$items[]=['type'=>'grammar','prompt'=>'Pilih kalimat Inggris yang sesuai dengan arti: “'.$rule[1].'”','audio'=>'','correct'=>$rule[0],'pool'=>'english','explanation'=>'Pola: '.$chapter[4].'.'];}
        foreach(array_slice($chapters,0,6) as $ci=>$chapter){$base=$chapter[6][$ci%5];$reply=$enrichment[$chapter[0]]['replies'][$ci%5];$items[]=['type'=>'situation','prompt'=>'Respons yang paling sesuai setelah “'.$base[0].'” adalah …','audio'=>$base[0],'correct'=>$reply[0],'pool'=>'replies','explanation'=>$reply[0].' — '.$reply[1]];}
        $translationPool=[];$vocabPool=[];$englishPool=[];$replyPool=[];foreach($chapters as $chapter){foreach($chapter[6] as $l){$translationPool[]=$l[1];$englishPool[]=$l[0];}foreach($enrichment[$chapter[0]]['rules'] as $l)$englishPool[]=$l[0];foreach($enrichment[$chapter[0]]['replies'] as $l)$replyPool[]=$l[0];foreach(explode('|',$enrichment[$chapter[0]]['vocab']) as $raw){$p=explode('=',$raw,2);if(count($p)===2)$vocabPool[]=$p[1];}}
        $pools=['translations'=>$translationPool,'vocab'=>$vocabPool,'english'=>$englishPool,'replies'=>$replyPool];$this->db->trans_start();$this->db->where('test_id',$test['id'])->delete('english_course_test_questions');
        foreach($items as $i=>$item){$pool=array_values(array_unique(array_filter($pools[$item['pool']],function($v)use($item){return $v!==$item['correct'];})));$choices=[$pool[($i*5)%count($pool)],$pool[($i*5+7)%count($pool)],$pool[($i*5+13)%count($pool)]];$correctAt=($i*7+2)%4;array_splice($choices,$correctAt,0,[$item['correct']]);$this->db->insert('english_course_test_questions',['test_id'=>$test['id'],'prompt'=>$item['prompt'],'audio_text'=>$item['audio'],'question_type'=>$item['type'],'choices_json'=>json_encode($choices,JSON_UNESCAPED_UNICODE),'correct_index'=>$correctAt,'explanation'=>$item['explanation'],'sort_order'=>$i+1]);}
        $this->db->replace('english_course_settings',['setting_key'=>'stage1_assessment_v3','setting_value'=>'1']);$this->db->trans_complete();
    }

    private function add_stage1_varied_practice_v4()
    {
        if($this->db->get_where('english_course_settings',['setting_key'=>'stage1_varied_practice_v4'])->row_array())return;
        $lessons=$this->db->get_where('english_course_lessons',['lesson_type'=>'skills','is_active'=>1])->result_array();$this->db->trans_start();foreach($lessons as $lesson){$cards=json_decode($lesson['content_json'],true)?:[];foreach($cards as $i=>&$card){if(in_array($i,[2,6],true)){$card['activity_type']='dictation';$card['prompt']='Dengarkan audio, lalu ketik persis kalimat yang kamu dengar.';}elseif(in_array($i,[1,7],true)){$card['activity_type']='image_choice';$card['prompt']='Amati adegan dan pilih makna yang paling sesuai.';}}unset($card);$this->db->where('id',$lesson['id'])->update('english_course_lessons',['content_json'=>json_encode($cards,JSON_UNESCAPED_UNICODE)]);}$this->db->replace('english_course_settings',['setting_key'=>'stage1_varied_practice_v4','setting_value'=>'1']);$this->db->trans_complete();
    }

    public function settings(){ $rows=$this->db->get('english_course_settings')->result_array();$out=[];foreach($rows as $r)$out[$r['setting_key']]=$r['setting_value'];return $out; }
    public function save_settings(array $data){foreach(['course_title','tts_voice','tts_rate','show_translation','require_level_test'] as $key)if(array_key_exists($key,$data))$this->db->replace('english_course_settings',['setting_key'=>$key,'setting_value'=>(string)$data[$key]]);}
    public function levels($userId=0,$admin=false){$rows=$this->db->order_by('sort_order')->get_where('english_course_levels',$admin?[]:['is_active'=>1])->result_array();foreach($rows as &$l){$l['units']=$this->db->where('level_id',$l['id'])->where($admin?'1=1':'is_active=1',null,false)->order_by('sort_order')->get('english_course_units')->result_array();$lessonIds=[];foreach($l['units'] as &$u){$u['lessons']=$this->db->where('unit_id',$u['id'])->where($admin?'1=1':'is_active=1',null,false)->order_by('sort_order')->get('english_course_lessons')->result_array();foreach($u['lessons'] as $lesson)$lessonIds[]=(int)$lesson['id'];}unset($u);$l['lesson_total']=count($lessonIds);$l['completed_lessons']=0;$l['best_test']=null;if($userId&&$lessonIds)$l['completed_lessons']=(int)$this->db->where('user_id',$userId)->where('status','completed')->where_in('lesson_id',$lessonIds)->count_all_results('english_course_lesson_progress');$test=$this->db->get_where('english_course_tests',['level_id'=>$l['id']])->row_array();$l['test']=$test;if($userId&&$test)$l['best_test']=$this->db->select_max('score','score')->where(['user_id'=>$userId,'test_id'=>$test['id']])->get('english_course_test_attempts')->row('score');}unset($l);return $rows;}
    public function lesson($id,$userId=0){$row=$this->db->select('l.*,u.title unit_title,u.emoji,u.level_id,lv.title level_title,lv.code level_code')->from('english_course_lessons l')->join('english_course_units u','u.id=l.unit_id')->join('english_course_levels lv','lv.id=u.level_id')->where('l.id',(int)$id)->get()->row_array();if(!$row)return null;$row['cards']=json_decode($row['content_json'],true)?:[];$row['progress']=$userId?$this->db->get_where('english_course_lesson_progress',['user_id'=>$userId,'lesson_id'=>$id])->row_array():null;return $row;}
    public function save_activity($lessonId,$userId,$stepNo,$type,$answer,$score,$correct){$lesson=$this->db->get_where('english_course_lessons',['id'=>$lessonId,'is_active'=>1])->row_array();if(!$lesson)return false;$where=['user_id'=>$userId,'lesson_id'=>$lessonId,'step_no'=>$stepNo];$row=$this->db->get_where('english_course_activity_attempts',$where)->row_array();$data=['activity_type'=>substr($type,0,40),'answer_text'=>mb_substr(trim($answer),0,4000),'score'=>max(0,min(100,$score)),'is_correct'=>$correct?1:0];if($row)return $this->db->where('id',$row['id'])->update('english_course_activity_attempts',$data+['attempt_count'=>(int)$row['attempt_count']+1]);return $this->db->insert('english_course_activity_attempts',$data+$where);}
    public function chapter_ready($unitId,$userId){$ids=array_column($this->db->select('id')->get_where('english_course_lessons',['unit_id'=>$unitId,'is_active'=>1])->result_array(),'id');if(!$ids)return false;return (int)$this->db->where('user_id',$userId)->where('status','completed')->where_in('lesson_id',$ids)->count_all_results('english_course_lesson_progress')===count($ids);}
    public function unit_progress($unitId,$userId){$ids=array_column($this->db->select('id')->get_where('english_course_lessons',['unit_id'=>$unitId,'is_active'=>1])->result_array(),'id');$done=$ids?(int)$this->db->where('user_id',$userId)->where('status','completed')->where_in('lesson_id',$ids)->count_all_results('english_course_lesson_progress'):0;$best=$this->db->select_max('score','score')->where(['user_id'=>$userId,'unit_id'=>$unitId])->get('english_course_checkpoint_attempts')->row('score');return ['total'=>count($ids),'completed'=>$done,'ready'=>count($ids)>0&&$done===count($ids),'best'=>$best];}
    public function checkpoint($unitId){$unit=$this->db->get_where('english_course_units',['id'=>$unitId,'is_active'=>1])->row_array();if(!$unit)return null;$lessons=$this->db->order_by('sort_order')->get_where('english_course_lessons',['unit_id'=>$unitId,'is_active'=>1])->result_array();$pool=[];foreach($lessons as $lesson){foreach((json_decode($lesson['content_json'],true)?:[]) as $card){if(!empty($card['english'])&&!empty($card['translation']))$pool[$card['english']]=[$card['english'],$card['translation'],$card['note']??'',$lesson['id'],$lesson['title']];}}$pool=array_values($pool);$questions=$this->questions_from_pool($pool,12);return ['unit'=>$unit,'questions'=>$questions,'pass_score'=>75];}
    public function submit_checkpoint(array $checkpoint,$userId,array $answers){$correct=0;$review=[];foreach($checkpoint['questions'] as $q){$answer=isset($answers[$q['id']])?(int)$answers[$q['id']]:-1;$ok=$answer===(int)$q['correct_index'];if($ok)$correct++;$review[]=$q+['answer'=>$answer,'ok'=>$ok];}$total=count($checkpoint['questions']);$score=$total?(int)round($correct*100/$total):0;$passed=$score>=75;$this->db->insert('english_course_checkpoint_attempts',['user_id'=>$userId,'unit_id'=>$checkpoint['unit']['id'],'score'=>$score,'correct_count'=>$correct,'total_questions'=>$total,'is_passed'=>$passed?1:0,'answers_json'=>json_encode($review,JSON_UNESCAPED_UNICODE)]);return ['score'=>$score,'correct'=>$correct,'total'=>$total,'passed'=>$passed,'review'=>$review];}
    private function questions_from_pool(array $pool,$limit=20){$questions=[];$count=min($limit,count($pool));if(!$count)return $questions;for($i=0;$i<$count;$i++){$line=$pool[($i*7)%count($pool)];$choices=array_values(array_unique([$line[1],$pool[($i*7+3)%count($pool)][1],$pool[($i*7+11)%count($pool)][1],$pool[($i*7+19)%count($pool)][1]]));for($j=1;count($choices)<4&&$j<count($pool);$j++)if(!in_array($pool[$j][1],$choices,true))$choices[]=$pool[$j][1];$correct=$line[1];$choices=array_values(array_filter($choices,function($v)use($correct){return $v!==$correct;}));$correctAt=($i*5+1)%4;array_splice($choices,$correctAt,0,[$correct]);$questions[]=['id'=>$i,'prompt'=>($i%3===0?'Dengarkan dan pilih arti: ':'Pilih arti yang tepat: ').'“'.$line[0].'”','audio_text'=>$i%3===0?$line[0]:'','choices'=>array_slice($choices,0,4),'correct_index'=>$correctAt,'explanation'=>$line[2].' Arti: '.$line[1],'lesson_id'=>$line[3]??0,'lesson_title'=>$line[4]??'Materi terkait'];}return $questions;}
    public function stage_review_ready($levelId,$part,$userId){$units=$this->db->select('id')->where(['level_id'=>$levelId,'is_active'=>1])->order_by('sort_order')->limit(6,$part===2?6:0)->get('english_course_units')->result_array();if(count($units)<6)return false;foreach($units as $unit)if(!$this->chapter_ready((int)$unit['id'],$userId))return false;return true;}
    public function stage_review($levelId,$part){$level=$this->db->get_where('english_course_levels',['id'=>$levelId,'is_active'=>1])->row_array();if(!$level||!in_array((int)$part,[1,2],true))return null;$units=$this->db->where(['level_id'=>$levelId,'is_active'=>1])->order_by('sort_order')->limit(6,$part===2?6:0)->get('english_course_units')->result_array();$pool=[];foreach($units as $unit){$lessons=$this->db->get_where('english_course_lessons',['unit_id'=>$unit['id'],'is_active'=>1])->result_array();foreach($lessons as $lesson)foreach((json_decode($lesson['content_json'],true)?:[]) as $card)if(!empty($card['english'])&&!empty($card['translation']))$pool[$card['english']]=[$card['english'],$card['translation'],$card['note']??'',$lesson['id'],$lesson['title']];}return ['level'=>$level,'part'=>(int)$part,'title'=>$part===1?'Mid-Stage Review · Chapter 1–6':'Stage Review · Chapter 7–12','questions'=>$this->questions_from_pool(array_values($pool),20),'pass_score'=>75];}
    public function submit_stage_review(array $review,$userId,array $answers){$correct=0;$details=[];foreach($review['questions'] as $q){$answer=isset($answers[$q['id']])?(int)$answers[$q['id']]:-1;$ok=$answer===(int)$q['correct_index'];if($ok)$correct++;$details[]=$q+['answer'=>$answer,'ok'=>$ok];}$total=count($details);$score=$total?(int)round($correct*100/$total):0;$passed=$score>=75;$this->db->insert('english_course_stage_review_attempts',['user_id'=>$userId,'level_id'=>$review['level']['id'],'review_part'=>$review['part'],'score'=>$score,'correct_count'=>$correct,'total_questions'=>$total,'is_passed'=>$passed?1:0,'answers_json'=>json_encode($details,JSON_UNESCAPED_UNICODE)]);return ['score'=>$score,'correct'=>$correct,'total'=>$total,'passed'=>$passed,'review'=>$details];}
    public function review_progress($levelId,$userId){$out=[];foreach([1,2] as $part){$best=$this->db->select_max('score','score')->where(['user_id'=>$userId,'level_id'=>$levelId,'review_part'=>$part])->get('english_course_stage_review_attempts')->row('score');$out[$part]=['ready'=>$this->stage_review_ready($levelId,$part,$userId),'best'=>$best];}return $out;}
    public function mastery($userId){$map=['listening'=>['listen_choice','dictation'],'grammar'=>['grammar','sentence_builder','error_check'],'vocabulary'=>['vocabulary','image_choice'],'speaking'=>['pronunciation'],'writing'=>['guided_response','independent_mission','dictation']];$out=[];foreach($map as $skill=>$types){$row=$this->db->select('ROUND(AVG(score)) score,COUNT(*) attempts',false)->where('user_id',$userId)->where_in('activity_type',$types)->get('english_course_activity_attempts')->row_array();$out[$skill]=['score'=>$row&&$row['score']!==null?(int)$row['score']:0,'attempts'=>$row?(int)$row['attempts']:0];}return $out;}
    public function complete_lesson($lessonId,$userId,$score=100){$data=['status'=>'completed','score'=>max(0,min(100,(int)$score)),'completed_at'=>date('Y-m-d H:i:s'),'last_opened_at'=>date('Y-m-d H:i:s')];$existing=$this->db->get_where('english_course_lesson_progress',['user_id'=>$userId,'lesson_id'=>$lessonId])->row_array();if($existing)$this->db->where('id',$existing['id'])->update('english_course_lesson_progress',$data);else $this->db->insert('english_course_lesson_progress',$data+['user_id'=>$userId,'lesson_id'=>$lessonId]);}
    public function next_lesson($lessonId){$current=$this->db->select('u.level_id,u.sort_order unit_order,l.sort_order lesson_order')->from('english_course_lessons l')->join('english_course_units u','u.id=l.unit_id')->where('l.id',$lessonId)->get()->row_array();if(!$current)return null;$row=$this->db->select('l.id')->from('english_course_lessons l')->join('english_course_units u','u.id=l.unit_id')->where(['u.level_id'=>$current['level_id'],'u.is_active'=>1,'l.is_active'=>1])->group_start()->where('u.sort_order >',$current['unit_order'])->or_group_start()->where('u.sort_order',$current['unit_order'])->where('l.sort_order >',$current['lesson_order'])->group_end()->group_end()->order_by('u.sort_order')->order_by('l.sort_order')->limit(1)->get()->row_array();return $row?(int)$row['id']:null;}
    public function test_ready($levelId,$userId){$ids=array_column($this->db->select('l.id')->from('english_course_lessons l')->join('english_course_units u','u.id=l.unit_id')->where(['u.level_id'=>$levelId,'u.is_active'=>1,'l.is_active'=>1])->get()->result_array(),'id');if(!$ids)return false;$done=(int)$this->db->where('user_id',$userId)->where('status','completed')->where_in('lesson_id',$ids)->count_all_results('english_course_lesson_progress');return $done===count($ids);}
    public function test($levelId){$test=$this->db->get_where('english_course_tests',['level_id'=>(int)$levelId,'is_active'=>1])->row_array();if(!$test)return null;$test['level']=$this->db->get_where('english_course_levels',['id'=>(int)$levelId])->row_array();$test['questions']=$this->db->order_by('sort_order')->get_where('english_course_test_questions',['test_id'=>$test['id']])->result_array();foreach($test['questions'] as &$q)$q['choices']=json_decode($q['choices_json'],true)?:[];unset($q);return $test;}
    public function level_unlocked($levelId,$userId){$level=$this->db->get_where('english_course_levels',['id'=>(int)$levelId])->row_array();if(!$level)return false;$settings=$this->settings();if(($settings['require_level_test']??'1')!=='1'||(int)$level['sort_order']===1)return true;$prev=$this->db->where('sort_order <',(int)$level['sort_order'])->order_by('sort_order','DESC')->limit(1)->get('english_course_levels')->row_array();if(!$prev)return true;$test=$this->db->get_where('english_course_tests',['level_id'=>$prev['id']])->row_array();return $test&&(int)$this->db->where(['user_id'=>$userId,'test_id'=>$test['id'],'is_passed'=>1])->count_all_results('english_course_test_attempts')>0;}
    public function submit_test(array $test,$userId,array $answers){$correct=0;$review=[];foreach($test['questions'] as $q){$answer=isset($answers[$q['id']])?(int)$answers[$q['id']]:-1;$ok=$answer===(int)$q['correct_index'];if($ok)$correct++;$review[]=['question'=>$q['prompt'],'answer'=>$answer,'correct'=>(int)$q['correct_index'],'ok'=>$ok,'choices'=>$q['choices'],'explanation'=>$q['explanation']];}$total=count($test['questions']);$score=$total?(int)round($correct*100/$total):0;$passed=$score>=(int)$test['pass_score'];$this->db->insert('english_course_test_attempts',['user_id'=>$userId,'test_id'=>$test['id'],'score'=>$score,'correct_count'=>$correct,'total_questions'=>$total,'is_passed'=>$passed?1:0,'answers_json'=>json_encode($review,JSON_UNESCAPED_UNICODE)]);return ['attempt_id'=>$this->db->insert_id(),'score'=>$score,'correct'=>$correct,'total'=>$total,'passed'=>$passed,'review'=>$review];}
    public function admin_stats(){return ['levels'=>(int)$this->db->where('is_active',1)->count_all_results('english_course_levels'),'units'=>(int)$this->db->where(['is_active'=>1,'stage_no'=>1,'level_id'=>1])->count_all_results('english_course_units'),'lessons'=>(int)$this->db->select('l.id')->from('english_course_lessons l')->join('english_course_units u','u.id=l.unit_id')->where(['l.is_active'=>1,'u.is_active'=>1,'u.stage_no'=>1,'u.level_id'=>1])->count_all_results(),'learners'=>$this->db->distinct()->select('user_id')->get('english_course_lesson_progress')->num_rows(),'attempts'=>$this->db->count_all('english_course_test_attempts')];}
    public function learners(){return $this->db->select('u.id,u.full_name,u.username,COUNT(DISTINCT p.lesson_id) lessons,MAX(p.last_opened_at) last_activity,MAX(a.score) best_score,SUM(CASE WHEN a.is_passed=1 THEN 1 ELSE 0 END) passed_tests')->from('auth_user u')->join('english_course_lesson_progress p','p.user_id=u.id')->join('english_course_test_attempts a','a.user_id=u.id','left')->group_by('u.id')->order_by('last_activity','DESC')->limit(100)->get()->result_array();}
    public function toggle($type,$id){$table=$type==='level'?'english_course_levels':($type==='unit'?'english_course_units':'english_course_lessons');$row=$this->db->get_where($table,['id'=>(int)$id])->row_array();if($row)$this->db->where('id',(int)$id)->update($table,['is_active'=>empty($row['is_active'])?1:0]);return (bool)$row;}
    public function is_blocked($userId){$row=$this->db->get_where('learn_game_user_access',['user_id'=>(int)$userId,'module_code'=>'english_course','is_blocked'=>1])->row_array();return $row?:false;}
}
