<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Learn_module_progress_model extends CI_Model
{
    public function battle_runs($q='')
    {
        $this->db->select('r.*,COALESCE(s.title,"Battle Bebas") session_title,s.code session_code,s.access_mode,(SELECT COUNT(*) FROM learn_battle_participants p WHERE p.room_id=r.id) participant_count,(SELECT COUNT(*) FROM learn_battle_participants p WHERE p.room_id=r.id AND p.user_id IS NULL) guest_count,(SELECT MAX(p.score) FROM learn_battle_participants p WHERE p.room_id=r.id) top_score',false)->from('learn_battle_rooms r')->join('learn_battle_sessions s','s.id=r.battle_session_id','left');
        if($q!=='')$this->db->group_start()->like('s.title',$q)->or_like('r.code',$q)->group_end();
        return $this->db->order_by('r.created_at','DESC')->limit(300)->get()->result_array();
    }
    public function battle_run($room_id)
    {
        $room=$this->db->select('r.*,COALESCE(s.title,"Battle Bebas") session_title,s.code session_code,s.access_mode')->from('learn_battle_rooms r')->join('learn_battle_sessions s','s.id=r.battle_session_id','left')->where('r.id',(int)$room_id)->get()->row_array();if(!$room)return null;
        $players=$this->db->select('p.*,u.full_name,u.username')->from('learn_battle_participants p')->join('auth_user u','u.id=p.user_id','left')->where('p.room_id',(int)$room_id)->order_by('p.score','DESC')->order_by('p.progress','DESC')->order_by('p.finished_at','ASC')->order_by('p.id','ASC')->get()->result_array();
        $start=$this->epoch($room['started_at']);foreach($players as $i=>&$p){$p['rank']=$i+1;$finish=$this->epoch($p['finished_at']);$p['elapsed_seconds']=$start!==null&&$finish!==null?round(max(0,$finish-$start),3):null;$p['is_winner']=(int)$room['winner_participant_id']===(int)$p['id']||($room['winner_participant_id']===null&&$p['user_id']!==null&&(int)$room['winner_user_id']===(int)$p['user_id']);}unset($p);
        return ['room'=>$room,'players'=>$players];
    }
    private function epoch($value){if(!$value)return null;$d=DateTimeImmutable::createFromFormat('Y-m-d H:i:s.u',$value)?:new DateTimeImmutable($value);return (float)$d->format('U.u');}
    public function stop_battle($room_id)
    {
        $room=$this->db->get_where('learn_battle_rooms',['id'=>(int)$room_id])->row_array();if(!$room)return ['ok'=>false,'message'=>'Room Battle tidak ditemukan.'];if(!in_array($room['status'],['waiting','playing'],true))return ['ok'=>false,'message'=>'Room ini sudah ditutup sebelumnya.'];
        $players=$this->db->where('room_id',(int)$room_id)->order_by('score','DESC')->order_by('progress','DESC')->order_by('finished_at','ASC')->order_by('id','ASC')->get('learn_battle_participants')->result_array();$winner=$players?$players[0]:null;$stamp=(new DateTime('now'))->format('Y-m-d H:i:s.u');
        $this->db->trans_start();$this->db->where('room_id',(int)$room_id)->where('finished',0)->update('learn_battle_participants',['finished'=>1,'finished_at'=>$stamp]);$this->db->where('id',(int)$room_id)->where_in('status',['waiting','playing'])->update('learn_battle_rooms',['status'=>'finished','winner_user_id'=>$winner&&$winner['user_id']!==null?(int)$winner['user_id']:null,'winner_participant_id'=>$winner?(int)$winner['id']:null,'finished_at'=>$stamp,'end_reason'=>'stopped']);$this->db->trans_complete();
        return ['ok'=>$this->db->trans_status(),'message'=>$this->db->trans_status()?'Battle dihentikan. Ranking akhir dihitung dari skor dan progres terakhir.':'Battle gagal dihentikan.'];
    }
    public function summary($m)
    {
        $map=['flashcard'=>['learn_flashcard_progress','last_reviewed_at'],'story'=>['learn_story_attempts','created_at'],'mini_games'=>['learn_game_sessions','played_at'],'battle'=>['learn_battle_participants','joined_at'],'english_course'=>['english_course_lesson_progress','last_opened_at']];if(!isset($map[$m]))return [];$t=$map[$m][0];
        return ['players'=>(int)$this->db->select('COUNT(DISTINCT user_id) n',false)->get($t)->row()->n,'records'=>(int)$this->db->count_all($t),'active'=>(int)$this->db->select('COUNT(DISTINCT user_id) n',false)->where($map[$m][1].' >=',date('Y-m-d H:i:s',strtotime('-30 days')))->get($t)->row()->n];
    }
    public function players($m,$q='')
    {
        if($m==='flashcard')$sql="SELECT p.user_id,u.full_name,u.username,COUNT(DISTINCT p.deck_id) units,COUNT(*) records,SUM(p.status='known') success,SUM(p.review_count) activity,MAX(p.last_reviewed_at) last_at FROM learn_flashcard_progress p JOIN auth_user u ON u.id=p.user_id";
        elseif($m==='story')$sql="SELECT a.user_id,u.full_name,u.username,COUNT(DISTINCT a.passage_id) units,COUNT(*) records,SUM(a.score_percent>=80) success,ROUND(MAX(a.score_percent),1) activity,MAX(a.created_at) last_at FROM learn_story_attempts a JOIN auth_user u ON u.id=a.user_id";
        elseif($m==='mini_games')$sql="SELECT s.user_id,u.full_name,u.username,COUNT(DISTINCT COALESCE(s.content_set_id,0)) units,COUNT(*) records,SUM(s.completed=1) success,MAX(s.score) activity,MAX(s.played_at) last_at FROM learn_game_sessions s JOIN auth_user u ON u.id=s.user_id";
        elseif($m==='battle')$sql="SELECT p.user_id,u.full_name,u.username,COUNT(DISTINCT COALESCE(r.battle_session_id,0)) units,COUNT(*) records,SUM(r.winner_user_id=p.user_id) success,MAX(p.score) activity,MAX(p.joined_at) last_at FROM learn_battle_participants p JOIN learn_battle_rooms r ON r.id=p.room_id JOIN auth_user u ON u.id=p.user_id";
        elseif($m==='english_course')$sql="SELECT p.user_id,u.full_name,u.username,COUNT(DISTINCT lv.id) units,COUNT(DISTINCT p.lesson_id) records,SUM(p.status='completed') success,COALESCE((SELECT MAX(a.score) FROM english_course_test_attempts a WHERE a.user_id=p.user_id),0) activity,MAX(p.last_opened_at) last_at FROM english_course_lesson_progress p JOIN english_course_lessons l ON l.id=p.lesson_id JOIN english_course_units un ON un.id=l.unit_id JOIN english_course_levels lv ON lv.id=un.level_id JOIN auth_user u ON u.id=p.user_id";else return [];
        $bind=[];if($q!==''){$sql.=" WHERE (u.full_name LIKE ? OR u.username LIKE ?)";$bind=['%'.$q.'%','%'.$q.'%'];}$sql.=' GROUP BY p.user_id,u.full_name,u.username ORDER BY last_at DESC LIMIT 300';if($m==='story')$sql=str_replace('GROUP BY p.user_id','GROUP BY a.user_id',$sql);if($m==='mini_games')$sql=str_replace('GROUP BY p.user_id','GROUP BY s.user_id',$sql);
        $rows=$this->db->query($sql,$bind)->result_array();foreach($rows as &$r)$r['access']=$this->db->get_where('learn_game_user_access',['user_id'=>$r['user_id'],'module_code'=>$m])->row_array();return $rows;
    }
    public function detail($m,$uid)
    {
        $u=$this->db->get_where('auth_user',['id'=>$uid])->row_array();if(!$u)return null;
        if($m==='flashcard'){$units=$this->db->select("d.id,d.name title,COUNT(p.id) records,SUM(p.status='known') success,SUM(p.review_count) activity,MAX(p.last_reviewed_at) last_at,(SELECT COUNT(*) FROM learn_flashcard_cards c WHERE c.deck_id=d.id AND c.is_active=1) total",false)->from('learn_flashcard_decks d')->join('learn_flashcard_progress p','p.deck_id=d.id AND p.user_id='.$uid,'left')->group_by('d.id')->having('records >',0)->order_by('last_at','DESC')->get()->result_array();$history=$this->db->select('p.*,d.name unit_title,c.front detail')->from('learn_flashcard_progress p')->join('learn_flashcard_decks d','d.id=p.deck_id')->join('learn_flashcard_cards c','c.id=p.card_id','left')->where('p.user_id',$uid)->order_by('p.last_reviewed_at','DESC')->limit(200)->get()->result_array();}
        elseif($m==='story'){$units=$this->db->select('p.id,p.title,COUNT(a.id) records,MAX(a.score_percent) success,SUM(a.correct_count) activity,MAX(a.created_at) last_at,MAX(a.total_questions) total',false)->from('learn_story_passages p')->join('learn_story_attempts a','a.passage_id=p.id AND a.user_id='.$uid,'left')->group_by('p.id')->having('records >',0)->order_by('last_at','DESC')->get()->result_array();$history=$this->db->select('a.*,p.title unit_title,p.summary detail')->from('learn_story_attempts a')->join('learn_story_passages p','p.id=a.passage_id')->where('a.user_id',$uid)->order_by('a.created_at','DESC')->limit(200)->get()->result_array();}
        elseif($m==='mini_games'){$history=$this->db->select("s.*,t.name game_name,t.code game_code,COALESCE(c.name,t.description) detail",false)->from('learn_game_sessions s')->join('learn_game_types t','t.id=s.game_type_id','left')->join('learn_game_content_sets c','c.id=s.content_set_id','left')->where('s.user_id',$uid)->order_by('s.played_at','DESC')->limit(200)->get()->result_array();$group=[];foreach($history as &$h){$cfg=json_decode($h['config']?:'{}',true)?:[];$level=max(0,(int)($cfg['level']??0));if($h['content_set_id']){$key='set:'.$h['content_set_id'];$id=(int)$h['content_set_id'];$title=$h['detail'];}else{$key='level:'.$h['game_type_id'].':'.$level;$id=100000+(int)$h['game_type_id']*100+$level;$title=$h['game_name'].' · Level '.$level;}$h['unit_title']=$title;if(!isset($group[$key]))$group[$key]=['id'=>$id,'title'=>$title,'records'=>0,'success'=>0,'activity'=>0,'last_at'=>$h['played_at'],'total'=>0];$group[$key]['records']++;$group[$key]['success']=max($group[$key]['success'],(int)$h['score']);$group[$key]['activity']+=(int)$h['completed'];$group[$key]['total']=max($group[$key]['total'],(int)$h['max_score']);}unset($h);$units=array_values($group);}
        elseif($m==='battle'){$units=$this->db->select('COALESCE(bs.id,0) id,COALESCE(bs.title,"Battle Bebas") title,COUNT(p.id) records,SUM(r.winner_user_id=p.user_id) success,MAX(p.score) activity,MAX(p.joined_at) last_at,MAX(r.question_count) total',false)->from('learn_battle_participants p')->join('learn_battle_rooms r','r.id=p.room_id')->join('learn_battle_sessions bs','bs.id=r.battle_session_id','left')->where('p.user_id',$uid)->group_by('COALESCE(bs.id,0),COALESCE(bs.title,"Battle Bebas")')->order_by('last_at','DESC')->get()->result_array();$history=$this->db->select('p.*,r.id room_id,r.code room_code,r.status room_status,r.play_mode,r.winner_user_id,r.winner_participant_id,r.question_count,bs.title unit_title')->from('learn_battle_participants p')->join('learn_battle_rooms r','r.id=p.room_id')->join('learn_battle_sessions bs','bs.id=r.battle_session_id','left')->where('p.user_id',$uid)->order_by('p.joined_at','DESC')->limit(200)->get()->result_array();foreach($history as &$h){$run=$this->battle_run((int)$h['room_id']);$h['rank']=null;$h['participant_count']=count($run['players']);foreach($run['players'] as $rp)if((int)$rp['id']===(int)$h['id']){$h['rank']=$rp['rank'];$h['elapsed_seconds']=$rp['elapsed_seconds'];break;}}unset($h);}
        elseif($m==='english_course'){$units=$this->db->select("lv.id,CONCAT(lv.title,' · ',lv.cefr) title,COUNT(DISTINCT p.lesson_id) records,SUM(p.status='completed') success,COALESCE((SELECT MAX(a.score) FROM english_course_test_attempts a JOIN english_course_tests t ON t.id=a.test_id WHERE a.user_id=".$uid." AND t.level_id=lv.id),0) activity,MAX(p.last_opened_at) last_at,COUNT(DISTINCT l.id) total",false)->from('english_course_levels lv')->join('english_course_units un','un.level_id=lv.id')->join('english_course_lessons l','l.unit_id=un.id')->join('english_course_lesson_progress p','p.lesson_id=l.id AND p.user_id='.$uid,'left')->group_by('lv.id')->having('records >',0)->order_by('lv.sort_order')->get()->result_array();$history=$this->db->select("p.*,l.title unit_title,l.context_label detail,IF(p.status='completed',p.score,0) score",false)->from('english_course_lesson_progress p')->join('english_course_lessons l','l.id=p.lesson_id')->where('p.user_id',$uid)->order_by('p.last_opened_at','DESC')->limit(200)->get()->result_array();}else return null;
        return ['user'=>$u,'units'=>$units,'history'=>$history,'access'=>$this->db->get_where('learn_game_user_access',['user_id'=>$uid,'module_code'=>$m])->row_array()];
    }
    public function set_access($uid,$m,$blocked,$reason,$admin){$data=['is_blocked'=>$blocked?1:0,'reason'=>$blocked?trim($reason):null,'blocked_by'=>$blocked?$admin:null,'blocked_at'=>$blocked?date('Y-m-d H:i:s'):null,'updated_at'=>date('Y-m-d H:i:s')];$row=$this->db->get_where('learn_game_user_access',['user_id'=>$uid,'module_code'=>$m])->row_array();if($row)return $this->db->where('id',$row['id'])->update('learn_game_user_access',$data);return $this->db->insert('learn_game_user_access',$data+['user_id'=>$uid,'module_code'=>$m]);}
    public function reset($m,$uid,$scope=null)
    {
        if($m==='english_course'){
            if($scope!==null)$this->db->where('level_id',$scope);
            $this->db->where('user_id',$uid)->delete('english_course_stage_review_attempts');
        }
        $this->db->trans_start();if($m==='flashcard'){if($scope!==null)$this->db->where('deck_id',$scope);$this->db->where('user_id',$uid)->delete('learn_flashcard_progress');}elseif($m==='story'){if($scope!==null)$this->db->where('passage_id',$scope);$this->db->where('user_id',$uid)->delete('learn_story_attempts');}elseif($m==='mini_games'){if($scope!==null&&$scope>=100000){$packed=$scope-100000;$type=(int)floor($packed/100);$level=$packed%100;$this->db->where('game_type_id',$type)->where("COALESCE(JSON_EXTRACT(config, '$.level'),0) = ".$level,null,false);}elseif($scope!==null)$this->db->where('content_set_id',$scope);$this->db->where('user_id',$uid)->delete('learn_game_sessions');}elseif($m==='battle'){$roomQuery=$this->db->select('r.id')->from('learn_battle_rooms r')->join('learn_battle_participants p','p.room_id=r.id')->where('p.user_id',$uid);if($scope!==null)$roomQuery->where('r.battle_session_id',$scope);$rooms=array_column($roomQuery->get()->result_array(),'id');if($rooms){$this->db->where('user_id',$uid)->where_in('room_id',$rooms)->delete('learn_battle_participants');$this->db->where('winner_user_id',$uid)->where_in('id',$rooms)->update('learn_battle_rooms',['winner_user_id'=>null]);}}elseif($m==='english_course'){if($scope!==null){$lessonIds=array_column($this->db->select('l.id')->from('english_course_lessons l')->join('english_course_units u','u.id=l.unit_id')->where('u.level_id',$scope)->get()->result_array(),'id');$unitIds=array_column($this->db->select('id')->get_where('english_course_units',['level_id'=>$scope])->result_array(),'id');$testIds=array_column($this->db->select('id')->get_where('english_course_tests',['level_id'=>$scope])->result_array(),'id');if($lessonIds){$this->db->where('user_id',$uid)->where_in('lesson_id',$lessonIds)->delete('english_course_activity_attempts');$this->db->where('user_id',$uid)->where_in('lesson_id',$lessonIds)->delete('english_course_lesson_progress');}if($unitIds)$this->db->where('user_id',$uid)->where_in('unit_id',$unitIds)->delete('english_course_checkpoint_attempts');if($testIds)$this->db->where('user_id',$uid)->where_in('test_id',$testIds)->delete('english_course_test_attempts');}else{$this->db->where('user_id',$uid)->delete('english_course_activity_attempts');$this->db->where('user_id',$uid)->delete('english_course_checkpoint_attempts');$this->db->where('user_id',$uid)->delete('english_course_lesson_progress');$this->db->where('user_id',$uid)->delete('english_course_test_attempts');}}else return false;$this->db->trans_complete();return $this->db->trans_status();
    }
}
