<?php defined('BASEPATH') OR exit('No direct script access allowed');
class Learn_progress_model extends CI_Model
{
 const MODULES=['english_rpg'=>'English RPG','mini_games'=>'Mini Games','flashcard'=>'Flashcard','story'=>'Story Quiz','battle'=>'Mode Battle'];
 public function users($q=''){$sql="SELECT u.id,u.full_name,u.username,(SELECT COUNT(*) FROM learn_game_sessions x WHERE x.user_id=u.id AND x.completed=1) mini_sessions,(SELECT COUNT(*) FROM learn_flashcard_progress x WHERE x.user_id=u.id) flashcards,(SELECT COUNT(*) FROM learn_story_attempts x WHERE x.user_id=u.id) stories,(SELECT COUNT(*) FROM learn_english_rpg_progress x WHERE x.user_id=u.id AND x.is_completed=1) rpg_chapters,(SELECT COUNT(*) FROM learn_battle_participants x WHERE x.user_id=u.id AND x.finished=1) battles FROM auth_user u WHERE (EXISTS(SELECT 1 FROM learn_game_sessions x WHERE x.user_id=u.id) OR EXISTS(SELECT 1 FROM learn_flashcard_progress x WHERE x.user_id=u.id) OR EXISTS(SELECT 1 FROM learn_story_attempts x WHERE x.user_id=u.id) OR EXISTS(SELECT 1 FROM learn_english_rpg_progress x WHERE x.user_id=u.id) OR EXISTS(SELECT 1 FROM learn_battle_participants x WHERE x.user_id=u.id))";$b=[];if($q!==''){$sql.=" AND (u.full_name LIKE ? OR u.username LIKE ?)";$b=['%'.$q.'%','%'.$q.'%'];}$rows=$this->db->query($sql.' ORDER BY u.full_name LIMIT 300',$b)->result_array();foreach($rows as &$r){$r['access']=[];foreach($this->db->where('user_id',$r['id'])->get('learn_game_user_access')->result_array() as $a)$r['access'][$a['module_code']]=$a;}return $rows;}
 public function detail($uid){$u=$this->db->get_where('auth_user',['id'=>(int)$uid])->row_array();if(!$u)return null;return ['user'=>$u,'access'=>$this->db->where('user_id',$uid)->get('learn_game_user_access')->result_array(),'rpg'=>$this->db->where('user_id',$uid)->order_by('updated_at','DESC')->get('learn_english_rpg_progress')->result_array(),'games'=>$this->db->select('s.*,t.name game_name,c.name set_name')->from('learn_game_sessions s')->join('learn_game_types t','t.id=s.game_type_id','left')->join('learn_game_content_sets c','c.id=s.content_set_id','left')->where('s.user_id',$uid)->order_by('s.played_at','DESC')->limit(100)->get()->result_array(),'flashcards'=>$this->db->select('p.*,d.name deck_name')->from('learn_flashcard_progress p')->join('learn_flashcard_decks d','d.id=p.deck_id','left')->where('p.user_id',$uid)->order_by('p.last_reviewed_at','DESC')->limit(100)->get()->result_array(),'stories'=>$this->db->select('a.*,p.title')->from('learn_story_attempts a')->join('learn_story_passages p','p.id=a.passage_id','left')->where('a.user_id',$uid)->order_by('a.created_at','DESC')->limit(100)->get()->result_array(),'battles'=>$this->db->select('p.*,r.code room_code,r.status')->from('learn_battle_participants p')->join('learn_battle_rooms r','r.id=p.room_id','left')->where('p.user_id',$uid)->order_by('p.joined_at','DESC')->limit(100)->get()->result_array()];}
 public function set_block($uid,$module,$blocked,$reason,$admin){if(!isset(self::MODULES[$module]))return false;$d=['is_blocked'=>$blocked?1:0,'reason'=>$blocked?trim($reason):null,'blocked_by'=>$blocked?(int)$admin:null,'blocked_at'=>$blocked?date('Y-m-d H:i:s'):null,'updated_at'=>date('Y-m-d H:i:s')];$r=$this->db->get_where('learn_game_user_access',['user_id'=>$uid,'module_code'=>$module])->row_array();if($r)return $this->db->where('id',$r['id'])->update('learn_game_user_access',$d);$d+=['user_id'=>(int)$uid,'module_code'=>$module];return $this->db->insert('learn_game_user_access',$d);}
 public function blocked($uid,$module){return $this->db->get_where('learn_game_user_access',['user_id'=>$uid,'module_code'=>$module,'is_blocked'=>1])->row_array()?:false;}
 public function reset($uid,$m){$uid=(int)$uid;$map=['mini_games'=>['learn_game_sessions'],'flashcard'=>['learn_flashcard_progress'],'story'=>['learn_story_attempts'],'battle'=>['learn_battle_participants'],'english_rpg'=>['learn_english_rpg_progress','learn_english_rpg_activity','learn_english_rpg_word_mastery','learn_english_rpg_review_log','learn_english_rpg_inventory','learn_english_rpg_story_choices','learn_english_rpg_user_quests','learn_english_rpg_profiles']];if(!isset($map[$m]))return false;$this->db->trans_start();foreach($map[$m] as $t)if($this->db->table_exists($t))$this->db->where('user_id',$uid)->delete($t);$this->db->trans_complete();return $this->db->trans_status();}
 public function rpg_episode_progress($episode_id){$e=$this->db->get_where('learn_english_rpg_episodes',['id'=>(int)$episode_id])->row_array();if(!$e)return null;$rows=$this->db->select('p.*,u.full_name,u.username,(SELECT COUNT(*) FROM learn_english_rpg_activity a WHERE a.user_id=p.user_id AND a.episode_code=p.episode_code) activity_count',false)->from('learn_english_rpg_progress p')->join('auth_user u','u.id=p.user_id','left')->where('p.episode_code',$e['code'])->order_by('p.updated_at','DESC')->get()->result_array();foreach($rows as &$r){$latest=$this->db->select('e.id')->from('learn_english_rpg_progress p')->join('learn_english_rpg_episodes e','e.code=p.episode_code')->where('p.user_id',$r['user_id'])->where('(p.current_scene>0 OR p.is_completed=1)',null,false)->order_by('e.id','DESC')->limit(1)->get()->row_array();$r['can_reset']=!$latest||(int)$latest['id']===(int)$e['id'];}return ['episode'=>$e,'players'=>$rows];}
 public function reset_rpg_episode($uid,$episode_id){$scope=$this->rpg_episode_progress($episode_id);if(!$scope)return ['ok'=>false,'message'=>'Chapter tidak ditemukan.'];$row=null;foreach($scope['players'] as $p)if((int)$p['user_id']===(int)$uid)$row=$p;if(!$row)return ['ok'=>false,'message'=>'Progres pengguna tidak ditemukan.'];if(empty($row['can_reset']))return ['ok'=>false,'message'=>'Hanya chapter terakhir pengguna yang boleh direset.'];$code=$scope['episode']['code'];$this->db->trans_start();$this->db->where(['user_id'=>(int)$uid,'episode_code'=>$code])->update('learn_english_rpg_progress',['current_scene'=>0,'xp'=>0,'hearts'=>3,'correct_answers'=>0,'wrong_answers'=>0,'vocabulary_json'=>'[]','is_completed'=>0,'completed_at'=>null,'updated_at'=>date('Y-m-d H:i:s')]);foreach(['learn_english_rpg_activity','learn_english_rpg_story_choices'] as $t)if($this->db->table_exists($t))$this->db->where(['user_id'=>(int)$uid,'episode_code'=>$code])->delete($t);$this->db->trans_complete();return ['ok'=>$this->db->trans_status(),'message'=>$this->db->trans_status()?'Chapter terakhir berhasil direset.':'Reset gagal.'];}
}
