<?php $tab='progress';include APPPATH.'views/learn/module_progress/_tabs.php';$r=$data['room'];$players=$data['players'];$duration=function($seconds){if($seconds===null)return '—';$minutes=floor($seconds/60);return sprintf('%02d:%06.3f',$minutes,$seconds-$minutes*60);}; ?>
<div class="container-xl">
  <div class="page-header mb-3"><div><div class="page-pretitle"><a href="<?= base_url('learn-battle/progress'); ?>">Progres Battle</a> · <?= html_escape($r['session_title']); ?></div><h2 class="page-title">Hasil Room <?= html_escape($r['code']); ?></h2><p class="text-secondary mb-0">Satu pelaksanaan dari sesi “<?= html_escape($r['session_title']); ?>” · <?= html_escape(date('d M Y H:i',strtotime($r['created_at']))); ?></p></div><div class="ms-auto btn-list"><?php if(in_array($r['status'],['waiting','playing'],true)): ?><button class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#stopBattleModal"><i class="ti ti-player-stop"></i> Hentikan Battle</button><?php endif; ?><a class="btn btn-outline-secondary" href="<?= base_url('learn-battle/progress'); ?>"><i class="ti ti-arrow-left"></i> Semua Pelaksanaan</a></div></div>
  <?php foreach(['success','error'] as $flash)if($this->session->flashdata($flash)): ?><div class="alert alert-<?= $flash==='success'?'success':'danger'; ?>"><i class="ti ti-<?= $flash==='success'?'circle-check':'alert-circle'; ?> me-1"></i><?= html_escape($this->session->flashdata($flash)); ?></div><?php endif; ?>
  <div class="row row-cards mb-3"><div class="col-md-3"><div class="card"><div class="card-body"><div class="subheader">Mode</div><div class="h2 mb-0"><?= ($r['play_mode']??'sprint')==='paced'?'🎮 Per Soal':'⚡ Sprint'; ?></div></div></div></div><div class="col-md-3"><div class="card"><div class="card-body"><div class="subheader">Peserta</div><div class="h2 mb-0"><?= count($players); ?></div></div></div></div><div class="col-md-3"><div class="card"><div class="card-body"><div class="subheader">Jumlah Soal</div><div class="h2 mb-0"><?= (int)$r['question_count']; ?></div></div></div></div><div class="col-md-3"><div class="card"><div class="card-body"><div class="subheader">Status</div><div class="h2 mb-0"><span class="badge bg-<?= ($r['end_reason']??'')==='stopped'?'warning':($r['status']==='finished'?'success':($r['status']==='playing'?'blue':'secondary')); ?>-lt"><?= ($r['end_reason']??'')==='stopped'?'Dihentikan':html_escape(ucfirst($r['status'])); ?></span></div></div></div></div></div>
  <div class="card"><div class="card-header"><div><h3 class="card-title"><i class="ti ti-podium me-2"></i>Peringkat dan Hasil Peserta</h3><p class="text-secondary mb-0"><?= ($r['play_mode']??'sprint')==='paced'?'Urutan berdasarkan akumulasi poin kecepatan per soal.':'Urutan berdasarkan skor benar tertinggi, lalu waktu selesai tercepat.'; ?></p></div></div><div class="table-responsive"><table class="table table-vcenter card-table"><thead><tr><th>Peringkat</th><th>Peserta</th><th>Jenis</th><th>Skor</th><th>Progres</th><th>Durasi</th><th>Selesai</th><th>Akun</th></tr></thead><tbody>
  <?php foreach($players as $p): ?><tr class="<?= $p['rank']===1?'bg-yellow-lt':''; ?>"><td><span style="font-size:1.5rem"><?= ['🥇','🥈','🥉'][$p['rank']-1]??'#'.$p['rank']; ?></span></td><td><strong><?= html_escape($p['player_name']); ?></strong><?= $p['is_winner']?'<span class="badge bg-yellow-lt ms-2">Juara</span>':''; ?></td><td><?= $p['user_id']===null?'<span class="badge bg-azure-lt">Tamu Publik</span>':'<span class="badge bg-purple-lt">Pengguna Terdaftar</span>'; ?></td><td><strong><?= number_format((int)$p['score'],0,',','.'); ?></strong><?= ($r['play_mode']??'sprint')==='paced'?' poin':' benar'; ?></td><td><?= (int)$p['progress']; ?>/<?= (int)$r['question_count']; ?></td><td><code><?= $duration($p['elapsed_seconds']); ?></code></td><td><?= $p['finished_at']?html_escape(date('d M Y H:i:s',strtotime($p['finished_at']))):'—'; ?></td><td><?php if($p['user_id']!==null): ?><a href="<?= base_url('learn-battle/progress/user/'.$p['user_id']); ?>"><?= html_escape($p['full_name']?:'@'.$p['username']); ?></a><?php else: ?>—<?php endif; ?></td></tr><?php endforeach; ?>
  </tbody></table></div><?php if(!$players): ?><div class="card-body text-center text-secondary py-5">Belum ada peserta pada pelaksanaan ini.</div><?php endif; ?></div>
</div>
<?php if(in_array($r['status'],['waiting','playing'],true)): ?><div class="modal modal-blur fade" id="stopBattleModal" tabindex="-1"><div class="modal-dialog modal-dialog-centered"><div class="modal-content"><div class="modal-header bg-danger text-white"><h3 class="modal-title text-white"><i class="ti ti-player-stop me-2"></i>Hentikan Battle?</h3><button class="btn-close btn-close-white" data-bs-dismiss="modal"></button></div><div class="modal-body"><p>Room <strong><?= html_escape($r['code']); ?></strong> sedang <?= $r['status']==='playing'?'dimainkan':'menunggu pemain'; ?>.</p><div class="alert alert-warning mb-0">Semua peserta akan ditandai selesai. Ranking akhir dihitung dari skor dan progres terakhir ketika tombol Stop ditekan.</div></div><div class="modal-footer"><button class="btn btn-link" data-bs-dismiss="modal">Batalkan</button><?= form_open('learn-battle/progress/run/'.$r['id'].'/stop'); ?><button class="btn btn-danger"><i class="ti ti-player-stop"></i> Ya, hentikan sekarang</button><?= form_close(); ?></div></div></div></div><?php endif; ?>
