<?php $this->load->view('learn/english_course/player/_head'); ?>
<?php if($this->session->flashdata('success')):?><div class="flash"><?=$this->session->flashdata('success')?></div><?php endif?>
<section class="hero"><div><div class="eyebrow">Belajar terarah · praktik nyata</div><h1><?=htmlspecialchars($settings['course_title']??'Kelas Bahasa Inggris')?></h1><p class="muted">Stage 1 membangun fondasi bahasa secara utuh: grammar, vocabulary, listening, pronunciation, reading, writing, dan speaking.</p><span class="tag">Stage 1 · 12 chapter · 60 lesson</span></div><div class="scene" aria-label="Guru dan siswa sedang belajar"><span>👩‍🏫</span><span>🧑‍🎓</span></div></section>
<section class="panel" style="margin-top:18px"><div class="eyebrow">Peta Kemampuanmu</div><h2 style="margin:5px 0 12px">Mastery Stage 1</h2><div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(130px,1fr))"><?php foreach($mastery as $skill=>$value):?><div style="padding:12px;background:#f8fafc;border-radius:13px"><strong><?=ucfirst(htmlspecialchars($skill))?></strong><div style="font-size:24px;font-weight:900;margin:5px 0"><?=$value['attempts']?$value['score'].'%':'—'?></div><div class="progress"><i style="width:<?=$value['score']?>%"></i></div><small class="muted"><?=$value['attempts']?> latihan</small></div><?php endforeach?></div></section>
<div class="grid" style="margin-top:22px">
<?php foreach($levels as $level): $pct=$level['lesson_total']?round($level['completed_lessons']/$level['lesson_total']*100):0; ?>
<section class="panel" style="opacity:<?=$level['unlocked']?'1':'.64'?>"><div style="display:flex;gap:16px;justify-content:space-between;align-items:start;flex-wrap:wrap"><div><span class="tag"><?=htmlspecialchars($level['cefr'])?></span><h2 style="margin:8px 0 4px"><?=htmlspecialchars($level['title'])?></h2><div class="muted"><?=htmlspecialchars($level['subtitle'])?></div></div><strong><?=$level['unlocked']?'🔓 Terbuka':'🔒 Terkunci'?></strong></div>
<div class="progress" style="margin:16px 0 6px"><i style="width:<?=$pct?>%"></i></div><small><?=$level['completed_lessons']?>/<?=$level['lesson_total']?> lesson selesai</small>
<?php if($level['unlocked']):?><div class="grid" style="grid-template-columns:repeat(auto-fit,minmax(240px,1fr));margin-top:16px"><?php foreach($level['units'] as $chapterNo=>$unit):?><div style="padding:16px;background:#f8fafc;border-radius:16px"><span class="eyebrow">Chapter <?=($chapterNo+1)?> · <?=$unit['progress']['completed']?>/<?=$unit['progress']['total']?> lesson</span><br><strong style="font-size:20px"><?=$unit['emoji']?> <?=htmlspecialchars($unit['title'])?></strong><p class="muted" style="margin:6px 0 12px"><?=htmlspecialchars($unit['description'])?></p><?php foreach($unit['lessons'] as $lesson):?><a class="btn light" style="width:100%;margin-top:7px" href="<?=site_url('belajar/bahasa-inggris/lesson/'.$lesson['id'])?>">▶ <?=htmlspecialchars($lesson['title'])?></a><?php endforeach?><?php if($unit['progress']['ready']):?><a class="btn green" style="width:100%;margin-top:10px" href="<?=site_url('belajar/bahasa-inggris/checkpoint/'.$unit['id'])?>">✓ Checkpoint Chapter<?=$unit['progress']['best']!==null?' · '.$unit['progress']['best']:''?></a><?php else:?><span class="btn light" style="width:100%;margin-top:10px;opacity:.6">🔒 Checkpoint</span><?php endif?></div><?php endforeach?></div>
<div style="display:flex;gap:10px;flex-wrap:wrap;margin-top:16px"><?php foreach([1=>'Review Chapter 1–6',2=>'Review Chapter 7–12'] as $part=>$label):?><?php if($level['reviews'][$part]['ready']):?><a class="btn light" href="<?=site_url('belajar/bahasa-inggris/review/'.$level['id'].'/'.$part)?>">🧭 <?=$label?><?=$level['reviews'][$part]['best']!==null?' · '.$level['reviews'][$part]['best']:''?></a><?php else:?><span class="btn light" style="opacity:.55">🔒 <?=$label?></span><?php endif?><?php endforeach?></div><?php if(!empty($level['test'])):?><div style="margin-top:16px;text-align:right"><?php if($level['test_ready']):?><a class="btn green" href="<?=site_url('belajar/bahasa-inggris/test/'.$level['id'])?>">📝 Final Assessment<?php if($level['best_test']!==null):?> · Terbaik <?=$level['best_test']?><?php endif?></a><?php else:?><span class="btn light" style="opacity:.65">🔒 Final Assessment · selesaikan <?=$level['lesson_total']?> lesson</span><?php endif?></div><?php endif?><?php endif?></section><?php endforeach?></div></main></body></html>
