<?php
require __DIR__.'/library_network_bootstrap.php';require __DIR__.'/iplm_task7_support.php';require APPPATH.'libraries/Catalog_xlsx.php';
$dir=$argv[1]??null;if($dir){network_check(preg_match('#^/tmp/pustaka_network_test_[a-zA-Z0-9_]+$#D',$dir)&&is_file($dir.'/connection.php'),'Private fixture required');$db=DB(require $dir.'/connection.php');}else{$db=DB();$dir=FCPATH.'docs/iplm';}
$report=json_decode(file_get_contents($dir.'/penyandingan-task7.json'),true,512,JSON_THROW_ON_ERROR);$master=array_column($db->get('libraries')->result_array(),null,'id');
$held=array_values(array_filter($report['legacy'],function($r){return $r['status']==='TAHAN_VERIFIKASI';}));$duplicates=array_values(array_filter($report['legacy'],function($r){return $r['status']==='TAHAN_GANDA';}));
$text="# Pertanyaan lanjutan task7\n\nTujuh keputusan sekolah pada task7 sudah diterapkan. Pertanyaan berikut hanya untuk data yang belum dapat dipastikan; baris sumber tetap diarsipkan dan tidak membuat unit duplikat.\n\n## A Pendataan tanpa padanan pasti\n\nAda **".count($held)." baris**. Nama dan NPSN dari pendataan bukan acuan untuk mengganti Dapodik. Bila sekolah sudah bergabung/berubah nama, diperlukan identitas sekolah tujuan yang resmi.\n\n";
foreach($held as$i=>$r){$s=$r['source'];$text.='### Kasus '.($i+1).' '.$s['Lembaga Induk']."\n\n- ID pendataan: **".$s['Id']."**; nama perpustakaan: **".$s['Nama']."**.\n- Wilayah sumber: ".$s['Kelurahan'].', '.$s['Kecamatan'].".\n- NPSN sumber: ".($s['NPSN']?:'kosong')."; belum dianggap benar tanpa kecocokan institusi.\n- Keadaan: belum memiliki padanan tunggal pada master Dapodik yang dipakai.\n\n**Pertanyaan: Apakah unit ini masih berdiri, bergabung, atau berubah nama? Mohon nama resmi dan NPSN sekolah tujuan bila ada.**\n\nJawaban Anda: …\n\n";}
$text.="## B Beberapa catatan pendataan menuju unit yang sama\n\nAda **".count($duplicates)." baris tambahan** yang menunjuk unit yang sudah memiliki catatan pendataan. Isian pertama disimpan; catatan lainnya tetap utuh di arsip tanpa menimpa formulir.\n\n";
foreach($duplicates as$i=>$r){$s=$r['source'];$m=$master[$r['library_id']];$others=[];foreach($report['legacy']as$o)if($o['library_id']===$r['library_id']&&$o['source']['Id']!==$s['Id'])$others[]=$o['source']['Id'];$text.='### Kasus '.($i+1).' '.$m['institution_name']."\n\n- ID perpustakaan: **".$m['id']."**, NPSN **".$m['code']."**.\n- Catatan tambahan: ID pendataan **".$s['Id']."**, nama **".$s['Nama']."**.\n- Catatan lain untuk unit sama: ".implode(', ',$others).".\n\n**Pertanyaan: Catatan pendataan mana yang paling baru dan benar untuk unit ini?**\n\nJawaban Anda: …\n\n";}
$gps=[];foreach($master as$m)if($m['source_system']==='dapodik_task7'&&!task7_gps($m['latitude'],$m['longitude']))$gps[]=[$m['id'],$m['code'],$m['institution_name'],$m['district'],$m['village'],$m['address'],'https://referensi.data.kemendikdasmen.go.id/pendidikan/npsn/'.$m['code'],'GPS resmi/backup kosong atau di luar Rembang; tidak dibuat titik perkiraan.'];
$text.="## C Koordinat sekolah baru belum valid\n\nMasih ada **".count($gps)." unit baru** tanpa GPS yang layak dipakai, setelah pemeriksaan portal resmi dan workbook cadangan. Alamat dan unit tetap terdaftar; peta tidak menampilkan titik nol atau titik di luar wilayah.\n\nDaftar: [GPS_PERLU_VERIFIKASI_TASK7.xlsx](GPS_PERLU_VERIFIKASI_TASK7.xlsx).\n\n**Pertanyaan: Untuk unit yang Anda kenali, mohon lokasi pin atau koordinat GPS yang benar.**\n\nJawaban Anda: NPSN …; lokasi/koordinat …\n\n## D Seleksi populasi IPLM\n\nSeluruh unit menunggu seleksi; jumlah sekolah bukan populasi. Pilih unit yang memiliki perpustakaan dan sesuai kewenangan pada Edit perpustakaan → Seleksi populasi IPLM. Setelah seleksi selesai, simpan pengaturan periode dalam mode otomatis, atau pilih manual dengan alasan. Snapshot lama 403 tetap tersimpan sampai periode disimpan ulang.\n";
file_put_contents($dir.'/PERTANYAAN_TASK7.md',$text);
$writer=new Catalog_xlsx();$file=$writer->build('GPS perlu verifikasi',['ID unit','NPSN','Institusi','Kecamatan','Desa','Alamat','Portal resmi','Keterangan'],$gps);copy($file,$dir.'/GPS_PERLU_VERIFIKASI_TASK7.xlsx');chmod($dir.'/GPS_PERLU_VERIFIKASI_TASK7.xlsx',0600);unlink($file);
$existing=['Provinsi'=>'Referensi Jawa Tengah','KabKota'=>'Referensi Kab. Rembang','Kecamatan'=>'Master wilayah Dapodik','Kelurahan'=>'Master desa','Id'=>'Arsip sumber (bukan isian pengelola)','Npp'=>'Profil master NPP','NPSN'=>'Master Dapodik (admin kabupaten)','Lembaga Induk'=>'Nama institusi master Dapodik','Nama'=>'Nama perpustakaan master','Jenis'=>'Jenis master','Subjenis'=>'Subjenis master','Alamat'=>'Profil lokal alamat','Telepon'=>'Profil lokal nomor HP aktif','Email'=>'Profil lokal email','Website'=>'Profil lokal website HTTPS','Latitude'=>'Koordinat master (admin kabupaten)','Longitude'=>'Koordinat master (admin kabupaten)','Status Lembaga'=>'Status institusi master','Jam Layanan'=>'Profil lokal jam layanan','Created At'=>'Arsip sumber','Updated At'=>'Arsip sumber'];
$mapping=task7_legacy_map();$rows=[];foreach(array_keys(task4_rows()[0])as$column){if($column==='_row')continue;network_check(isset($mapping[$column])||isset($existing[$column]),'Unmapped column '.$column);$rows[]=[$column,$mapping[$column]??$existing[$column],isset($mapping[$column])?'Pendataan tambahan lokal':'Profil / referensi / arsip','Tidak otomatis masuk perhitungan IPLM'];}
$file=$writer->build('Inventaris formulir task7',['Kolom pendataan lama','Tujuan','Lokasi','Hubungan IPLM'],$rows);copy($file,$dir.'/INVENTARIS_FORMULIR_TASK7.xlsx');chmod($dir.'/INVENTARIS_FORMULIR_TASK7.xlsx',0600);unlink($file);
echo json_encode(['columns_inventoried'=>count($rows),'additional_fields'=>count($mapping),'held_legacy'=>count($held),'duplicate_legacy'=>count($duplicates),'new_schools_without_gps'=>count($gps)],JSON_PRETTY_PRINT),"\n";
