<?php
/** Creates a styled, side-by-side review workbook. Does not write to any database. */
require __DIR__.'/library_network_bootstrap.php';
$db=DB('default');$db->db_debug=false;$folder=FCPATH.'docs/iplm/';
$mapping=json_decode(file_get_contents($folder.'pencocokan-pendataan-task2.json'),true,512,JSON_THROW_ON_ERROR);
$dom=new DOMDocument();$errors=libxml_use_internal_errors(true);network_check($dom->loadHTMLFile($folder.'pendataan.xls',LIBXML_NONET),'Cannot read source.');libxml_clear_errors();libxml_use_internal_errors($errors);$xp=new DOMXPath($dom);$headers=null;$sources=[];
foreach($xp->query('//tr')as$tr){$cells=[];foreach($xp->query('./th|./td',$tr)as$c)$cells[]=trim(preg_replace('/\s+/u',' ',$c->textContent));if(!$cells)continue;if($headers===null){$headers=$cells;continue;}$r=array_combine($headers,$cells);network_check(!isset($sources[$r['Id']]),'Duplicate source ID requires explicit handling.');$sources[$r['Id']]=$r;}
$libraries=network_query($db,'SELECT l.*,t.name type_name,t.code type_code,s.name subtype_name,COALESCE(d.name,l.district) district_name,COALESCE(v.name,l.village) village_name FROM libraries l JOIN library_types t ON t.id=l.library_type_id LEFT JOIN library_subtypes s ON s.id=l.library_subtype_id LEFT JOIN ref_districts d ON d.id=l.district_id LEFT JOIN ref_villages v ON v.id=l.village_id ORDER BY l.id')->result_array();$byId=array_column($libraries,null,'id');
function compare_master($l){if(!$l)return array_fill(0,14,'');return [$l['id'],$l['code'],$l['npp'],$l['name'],$l['institution_name'],$l['type_name'],$l['subtype_name'],$l['district_name'],$l['village_name'],$l['address'],$l['latitude'],$l['longitude'],$l['status'],$l['source_system']];}
function compare_source($r){if(!$r)return array_fill(0,14,'');return [$r['Id'],$r['NPSN'],$r['Npp'],$r['Nama'],$r['Lembaga Induk'],$r['Jenis'],$r['Subjenis'],$r['Kecamatan'],$r['Kelurahan'],$r['Alamat'],$r['Latitude'],$r['Longitude'],$r['Status Lembaga'],$r['Updated At']];}
$records=[];$displayed=[];$confirmed=[];$statusCounts=[];
$decisions=['352595'=>[92,'Nama SD Negeri Demaan dipasangkan; NPSN memakai database/Dapodik sesuai task3.'],'210305'=>[732,'Nama SMP Negeri 1 Bulu dipasangkan; NPSN memakai database/Dapodik sesuai task3.'],'50964'=>[2,'Pasangan Perpusda dikonfirmasi pengguna pada task3; NPP sumber 3317103E1000003 dicatat sebagai rujukan.']];
foreach($mapping as$m){
    $r=$sources[$m['source_id']]??null;network_check($r!==null,'Source changed since task2; remap before proceeding.');
    $id=$m['library_id']?:($m['candidate_ids'][0]??null);$status=$m['status'];$decision='Belum diputuskan pengguna';$note=$m['warning'];
    if(isset($decisions[$m['source_id']])){[$id,$note]=$decisions[$m['source_id']];$status='DIKONFIRMASI_TASK3';$decision='Gunakan pasangan ini; NPSN acuan database';}
    elseif($status==='COCOK'){$decision='Pasangan kuat berdasarkan identitas; periksa sebelum import';}
    elseif($status==='COCOK_GANDA'){$decision='Pasangan kuat, tetapi sumber ganda; tentukan baris utama';}
    elseif($status==='PERLU_VERIFIKASI'){$note=trim($note.'; Database di kiri adalah kandidat, BUKAN pasangan yang sudah disetujui. Alternatif ID: '.implode(', ',$m['candidate_ids']),'; ');}
    elseif($status==='BELUM_DITEMUKAN'){$status='HANYA_PENDATAAN';$id=null;$decision='Belum ada pasangan database; jangan import otomatis';}
    $l=$id?($byId[$id]??null):null;network_check(!$id||$l,'Mapped database ID no longer exists.');
    $npsnDiff=$l&&$l['type_code']==='sekolah'&&$r['NPSN']!==''&&$r['NPSN']!==$l['code'];
    if($npsnDiff)$note=trim($note.($status==='PERLU_VERIFIKASI'?'; HANYA JIKA pasangan dikonfirmasi: NPSN pendataan berbeda, pakai ':'; NPSN pendataan berbeda: pakai ').$l['code'].' dari database/Dapodik. Nilai sumber asli tetap ditampilkan dan diberi warna.','; ');
    if($id)$displayed[$id]=true;if($id&&in_array($status,['COCOK','COCOK_GANDA','DIKONFIRMASI_TASK3'],true))$confirmed[$id]=true;
    $records[]=['status'=>$status,'id'=>$id,'source_id'=>$r['Id'],'npsn_diff'=>$npsnDiff,'cells'=>array_merge(compare_master($l),compare_source($r),[$status,$decision,$note,implode(', ',$m['candidate_ids']),$m['row'],$l&&$l['type_code']==='sekolah'?$l['code']:''])];
}
foreach($libraries as$l)if(!isset($displayed[$l['id']]))$records[]=['status'=>'HANYA_DATABASE','id'=>$l['id'],'source_id'=>null,'npsn_diff'=>false,'cells'=>array_merge(compare_master($l),compare_source(null),['HANYA_DATABASE','Belum ditemukan di pendataan; usulan penambahan setelah konfirmasi','Sisi pendataan sengaja kosong. Tidak ada baris sumber yang diubah.','','',$l['type_code']==='sekolah'?$l['code']:''])];
$order=['DIKONFIRMASI_TASK3'=>0,'PERLU_VERIFIKASI'=>1,'COCOK_GANDA'=>2,'COCOK'=>3,'HANYA_DATABASE'=>4,'HANYA_PENDATAAN'=>5];
usort($records,function($a,$b)use($order){return [$order[$a['status']],$a['cells'][3]?:$a['cells'][17],$a['source_id']]<=>[$order[$b['status']],$b['cells'][3]?:$b['cells'][17],$b['source_id']];});foreach($records as$r)$statusCounts[$r['status']]=($statusCounts[$r['status']]??0)+1;
function compare_col($i){$out='';for($n=$i+1;$n>0;$n=intdiv($n-1,26))$out=chr(65+($n-1)%26).$out;return $out;}
function compare_row($xml,$number,$cells,$styles,$height=54){$xml->startElement('row');$xml->writeAttribute('r',(string)$number);$xml->writeAttribute('ht',(string)$height);$xml->writeAttribute('customHeight','1');foreach($cells as$i=>$value){$xml->startElement('c');$xml->writeAttribute('r',compare_col($i).$number);$xml->writeAttribute('s',(string)($styles[$i]??0));$xml->writeAttribute('t','inlineStr');$xml->startElement('is');$xml->startElement('t');$xml->writeAttribute('xml:space','preserve');$xml->text((string)$value);$xml->endElement();$xml->endElement();$xml->endElement();}$xml->endElement();}
$main='http://schemas.openxmlformats.org/spreadsheetml/2006/main';$office='http://schemas.openxmlformats.org/officeDocument/2006/relationships';$package='http://schemas.openxmlformats.org/package/2006/relationships';
$columnLabels=['ID database','NPSN / kode database','NPP database','Nama perpustakaan database','Lembaga induk database','Jenis database','Subjenis database','Kecamatan database','Desa database','Alamat database','Latitude database','Longitude database','Status database','Asal data database','ID pendataan','NPSN pendataan ASLI','NPP pendataan','Nama perpustakaan pendataan','Lembaga induk pendataan','Jenis pendataan','Subjenis pendataan','Kecamatan pendataan','Desa pendataan','Alamat pendataan','Latitude pendataan','Longitude pendataan','Status lembaga sumber','Diperbarui pada sumber','Status persandingan','Keputusan / tindakan','Catatan perbedaan','Kandidat ID database','Baris sumber XLS','NPSN acuan untuk koreksi'];
$xml=new XMLWriter();$xml->openMemory();$xml->startDocument('1.0','UTF-8');$xml->startElement('worksheet');$xml->writeAttribute('xmlns',$main);$xml->startElement('sheetViews');$xml->startElement('sheetView');$xml->writeAttribute('workbookViewId','0');$xml->writeAttribute('zoomScale','85');$xml->startElement('pane');foreach(['xSplit'=>'2','ySplit'=>'2','topLeftCell'=>'C3','state'=>'frozen']as$k=>$v)$xml->writeAttribute($k,$v);$xml->endElement();$xml->endElement();$xml->endElement();
$xml->startElement('cols');foreach($columnLabels as$i=>$label){$xml->startElement('col');$xml->writeAttribute('min',(string)($i+1));$xml->writeAttribute('max',(string)($i+1));$width=in_array($i,[3,4,17,18],true)?38:(in_array($i,[9,23,29,30],true)?48:20);$visible=[0=>9,1=>16,3=>34,7=>17,14=>9,15=>16,17=>34,21=>17,28=>23,30=>48];if(!isset($visible[$i])){$xml->writeAttribute('hidden','1');$xml->writeAttribute('outlineLevel','1');}else{$width=$visible[$i];}$xml->writeAttribute('width',(string)$width);$xml->writeAttribute('customWidth','1');$xml->endElement();}$xml->endElement();$xml->startElement('sheetData');
$top=array_fill(0,34,'');$top[0]='DATABASE APLIKASI — ACUAN NPSN & GPS';$top[14]='PENDATAAN.XLS — DATA TERUPDATE; NILAI SUMBER ASLI';$top[28]='HASIL PEMERIKSAAN / KEPUTUSAN';compare_row($xml,1,$top,array_merge(array_fill(0,14,1),array_fill(0,14,2),array_fill(0,6,3)),30);compare_row($xml,2,$columnLabels,array_merge(array_fill(0,14,1),array_fill(0,14,2),array_fill(0,6,3)),36);
$rowStyle=['COCOK'=>4,'DIKONFIRMASI_TASK3'=>4,'PERLU_VERIFIKASI'=>5,'COCOK_GANDA'=>6,'HANYA_DATABASE'=>7,'HANYA_PENDATAAN'=>8];
foreach($records as$i=>$r){$styles=array_fill(0,34,$rowStyle[$r['status']]);if($r['npsn_diff']){$styles[15]=9;$styles[33]=9;}compare_row($xml,$i+3,$r['cells'],$styles);}
$xml->endElement();$xml->startElement('autoFilter');$xml->writeAttribute('ref','A2:AH'.(count($records)+2));$xml->endElement();$xml->startElement('mergeCells');foreach(['A1:N1','O1:AB1','AC1:AH1']as$ref){$xml->startElement('mergeCell');$xml->writeAttribute('ref',$ref);$xml->endElement();}$xml->endElement();$xml->endElement();$xml->endDocument();$sheet1=$xml->outputMemory();
$xml->openMemory();$xml->startDocument('1.0','UTF-8');$xml->startElement('worksheet');$xml->writeAttribute('xmlns',$main);$xml->startElement('cols');foreach([1=>34,2=>115]as$col=>$width){$xml->startElement('col');foreach(['min'=>$col,'max'=>$col,'width'=>$width,'customWidth'=>1]as$k=>$v)$xml->writeAttribute($k,(string)$v);$xml->endElement();}$xml->endElement();$xml->startElement('sheetData');
$guide=[['Cara membaca','Database di A–N (kiri), pendataan di O–AB (kanan), keputusan di AC–AH. Tampilan awal diringkas ke ID, NPSN, nama, kecamatan, status dan catatan agar mudah disandingkan. Kolom detail tetap ada: pilih semua kolom lalu Unhide/Tampilkan kolom. Baris sejajar berarti pasangan kuat ATAU kandidat; baca status.'],['Hijau','COCOK / DIKONFIRMASI_TASK3: pasangan kuat atau dikonfirmasi pengguna. Tidak berarti seluruh atribut sama.'],['Kuning','PERLU_VERIFIKASI: sisi kiri adalah kandidat, belum disahkan. Kandidat alternatif dicantumkan; pilih ID yang benar sebelum import.'],['Jingga','COCOK_GANDA: beberapa baris sumber menuju master sama; jangan menghapus salah satunya tanpa keputusan.'],['Biru muda','HANYA_DATABASE: sisi pendataan kosong; usulan penambahan ke pendataan setelah konfirmasi.'],['Ungu muda','HANYA_PENDATAAN: sisi database kosong; usulan penambahan ke database setelah konfirmasi.'],['Merah','NPSN sumber berbeda; pakai database/Dapodik SESUDAH pasangan unit dikonfirmasi. Nilai sumber asli tidak dihapus, NPSN acuan ada pada kolom AH.'],['Penting','Tidak ada import atau perubahan master, NPP, GPS, akun, atau statistik. Data terupdate pendataan tidak otomatis dianggap angka tahun 2025.'],['Kandidat ditampilkan sekali','Jika suatu master sudah tampil di kiri sebagai kandidat, master tersebut tidak diulang sebagai HANYA_DATABASE. Karena itu jumlah HANYA_DATABASE berbeda dari jumlah master yang belum memiliki pasangan terkonfirmasi.'],['Cakupan','Semua 834 baris sumber muncul tepat sekali, seluruh 411 ID master muncul minimal sekali. Master boleh berulang untuk baris ganda/kandidat.'],['Konfirmasi berikutnya','Isi keputusan dengan ID sumber → ID database yang benar, atau lembaga berbeda/belum ada. Untuk sumber ganda, tentukan rujukan utama.'],['Snapshot','Dibuat '.date('Y-m-d H:i:s').' WIB. Hash pendataan: '.hash_file('sha256',$folder.'pendataan.xls')]];
foreach($statusCounts as$status=>$count)$guide[]=[$status,(string)$count.' baris'];$guide[]=['Master terkonfirmasi kuat',(string)count($confirmed)];$guide[]=['Master belum terkonfirmasi',(string)(count($libraries)-count($confirmed))];foreach($guide as$i=>$values)compare_row($xml,$i+1,$values,[3,0],48);$xml->endElement();$xml->endElement();$xml->endDocument();$sheet2=$xml->outputMemory();
$fills=['FFFFFFFF','FF1E3A8A','FF166534','FF334155','FFF0FDF4','FFFEF3C7','FFFFEDD5','FFE0F2FE','FFF3E8FF','FFFECACA'];$styles='<styleSheet xmlns="'.$main.'"><fonts count="2"><font><sz val="11"/><name val="Calibri"/></font><font><b/><sz val="11"/><color rgb="FFFFFFFF"/><name val="Calibri"/></font></fonts><fills count="11"><fill><patternFill patternType="none"/></fill><fill><patternFill patternType="gray125"/></fill>';
foreach(array_slice($fills,1)as$color)$styles.='<fill><patternFill patternType="solid"><fgColor rgb="'.$color.'"/><bgColor indexed="64"/></patternFill></fill>';
$styles.='</fills><borders count="1"><border><left/><right/><top/><bottom/><diagonal/></border></borders><cellStyleXfs count="1"><xf numFmtId="0" fontId="0" fillId="0" borderId="0"/></cellStyleXfs><cellXfs count="10">';for($i=0;$i<10;$i++)$styles.='<xf numFmtId="0" fontId="'.($i>=1&&$i<=3?1:0).'" fillId="'.($i===0?0:$i+1).'" borderId="0" xfId="0" applyAlignment="1"><alignment vertical="top" wrapText="1"/></xf>';$styles.='</cellXfs><cellStyles count="1"><cellStyle name="Normal" xfId="0" builtinId="0"/></cellStyles></styleSheet>';
$path=$folder.'PERSANDINGAN_DATABASE_PENDATAAN_TASK3.xlsx';$temp=tempnam(sys_get_temp_dir(),'iplm_compare_');$zip=new ZipArchive();network_check($zip->open($temp,ZipArchive::OVERWRITE)===true,'Cannot create workbook.');
try{
    $parts=['[Content_Types].xml'=>'<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/><Override PartName="/xl/styles.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml"/><Override PartName="/xl/worksheets/sheet1.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/><Override PartName="/xl/worksheets/sheet2.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/></Types>','_rels/.rels'=>'<Relationships xmlns="'.$package.'"><Relationship Id="rId1" Type="'.$office.'/officeDocument" Target="xl/workbook.xml"/></Relationships>','xl/workbook.xml'=>'<workbook xmlns="'.$main.'" xmlns:r="'.$office.'"><sheets><sheet name="Persandingan unit" sheetId="1" r:id="rId1"/><sheet name="Petunjuk dan ringkasan" sheetId="2" r:id="rId2"/></sheets></workbook>','xl/_rels/workbook.xml.rels'=>'<Relationships xmlns="'.$package.'"><Relationship Id="rId1" Type="'.$office.'/worksheet" Target="worksheets/sheet1.xml"/><Relationship Id="rId2" Type="'.$office.'/worksheet" Target="worksheets/sheet2.xml"/><Relationship Id="rId3" Type="'.$office.'/styles" Target="styles.xml"/></Relationships>','xl/worksheets/sheet1.xml'=>$sheet1,'xl/worksheets/sheet2.xml'=>$sheet2,'xl/styles.xml'=>$styles];foreach($parts as$name=>$data)network_check($zip->addFromString($name,$data),'Cannot write workbook part.');network_check($zip->close(),'Cannot finalize workbook.');network_check(copy($temp,$path),'Cannot save workbook.');chmod($path,0600);
}finally{if(is_file($temp))unlink($temp);}
$seenSource=array_filter(array_column($records,'source_id'));$seenMaster=array_unique(array_filter(array_column($records,'id')));network_check(count($seenSource)===count($sources)&&count(array_unique($seenSource))===count($sources),'Source coverage mismatch.');network_check(count($seenMaster)===count($libraries),'Master coverage mismatch.');
$summary=['created_at'=>date(DATE_ATOM),'source_rows'=>count($sources),'database_units'=>count($libraries),'comparison_rows'=>count($records),'statuses'=>$statusCounts,'confirmed_unique_units'=>count($confirmed),'not_yet_confirmed_units'=>count($libraries)-count($confirmed),'npsn_differences'=>count(array_filter($records,function($r){return $r['npsn_diff'];})),'source_sha256'=>hash_file('sha256',$folder.'pendataan.xls'),'workbook_sha256'=>hash_file('sha256',$path),'database_changed'=>false];file_put_contents($folder.'ringkasan-persandingan-task3.json',json_encode($summary,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE));echo json_encode($summary,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE),PHP_EOL;
