<?php
declare(strict_types=1);

$dbPassword = getenv('PUSTAKA_DB_PASSWORD');
if ($dbPassword === false || $dbPassword === '') die("Set PUSTAKA_DB_PASSWORD terlebih dahulu.\n");
$pdo = new PDO('mysql:host=127.0.0.1;dbname=pustaka;charset=utf8mb4', 'root', $dbPassword, [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
$contexts = [
    'lost_library' => ['A traveler is lost between the library shelves. What will you do?', ['I will guide the traveler to the right shelf.', 'I will scout the next aisle before we move.', 'I will read the old catalog for a useful clue.'], ['The guardian asks you to return the book. Which plan is best?', ['Let us return the book and thank the guardian together.', 'I will protect my friends while we cross the dark hall.', 'Let us read the inscription before opening the final door.']]],
    'market_mystery' => ['A seller drops a basket of fruit. How will you respond?', ['I will help gather the fruit and check the list.', 'I will watch the busy stall while the seller works.', 'I will count the clues near the market gate.'], ['The missing basket is found. Which choice will settle the market fairly?', ['Let us forgive the mistake and trade fairly.', 'I will protect the baskets until the seller is ready.', 'Let us solve the price riddle before we blame anyone.']]],
    'forest_rescue' => ['A young deer is hurt beside the forest path. What should your hero do?', ['I will help the deer and call the ranger.', 'I will scout the trail for a safe route.', 'I will study the tracks before moving the deer.'], ['The forest guardian blocks the rescue path. Which response is wisest?', ['Let us ask the guardian to help protect the forest.', 'I will stand bravely between danger and the deer.', 'Let us read the trail marks to find a peaceful way.']]],
    'space_station' => ['The station robot sends an alarm. What will you do first?', ['I will help repair the robot and listen carefully.', 'I will secure the corridor before the crew arrives.', 'I will check the station panel for the cause.'], ['The silent satellite opens one final hatch. What is your choice?', ['Let us repair it and share the station with everyone.', 'I will face the alarm and protect the crew.', 'Let us read the satellite code before we enter.']]],
    'school_festival' => ['A nervous friend forgets the festival lines. How will you respond?', ['I will encourage my friend and practice together.', 'I will check the stage so the show can continue.', 'I will read the schedule and find the missing cue.'], ['The final performance is delayed. Which plan helps the whole team?', ['Let us forgive the mistake and perform together.', 'I will protect the performers from the noisy crowd.', 'Let us solve the schedule puzzle before changing the show.']]],
    'ocean_treasure' => ['A sea turtle is trapped near the treasure reef. What will you do?', ['I will free the turtle and keep the reef safe.', 'I will scout the reef for a clear passage.', 'I will study the sea map before touching the treasure.'], ['The coral crown can open the vault. Which path will you choose?', ['Let us protect the reef and share the treasure.', 'I will face the current and guide my friends.', 'Let us read the tide marks before opening the vault.']]],
    'clockwork_castle' => ['The castle clock stops while the gates are closing. What will you do?', ['I will help turn the correct gear.', 'I will guard the hallway while the clock is repaired.', 'I will read the blueprint to find the missing gear.'], ['The castle machine offers one final route. What is your plan?', ['Let us repair the machine and work with its guardian.', 'I will face the moving gears and protect the team.', 'Let us solve the clock riddle before choosing a door.']]],
    'mountain_camp' => ['A climber slips near the mountain trail. How will you help?', ['I will hold the rope and guide the climber down.', 'I will scout a safer path around the cliff.', 'I will check the weather map before we continue.'], ['The storm closes the mountain pass. Which choice is best?', ['Let us forgive the guide and share the safe shelter.', 'I will face the storm and protect the camp.', 'Let us read the summit signs before choosing a route.']]],
    'dragon_academy' => ['A young dragon is frightened before its first lesson. What will you say?', ['I will calm the dragon and practice the lesson.', 'I will guard the training gate while it learns.', 'I will read the spellbook to find a gentle exercise.'], ['The academy guardian tests your courage. Which answer fits your team?', ['Let us befriend the guardian and learn together.', 'I will face the test and protect the young dragon.', 'Let us solve the old spell before using magic.']]],
    'pirate_islands' => ['A sailor is lost among the emerald islands. What will you do?', ['I will guide the sailor back to the friendly harbor.', 'I will scan the horizon for a safe channel.', 'I will read the captain’s chart for a hidden route.'], ['The island vault opens after one final choice. What will you do?', ['Let us share the treasure with the island village.', 'I will face the waves and protect the crew.', 'Let us solve the map riddle before taking the key.']]],
    'haunted_museum' => ['A museum guard is frightened by a moving statue. How will you respond?', ['I will stay with the guard and explain what I see.', 'I will light the hallway and check for danger.', 'I will study the museum label for the statue’s clue.'], ['The statue reveals a secret passage. Which response is right?', ['Let us forgive the spirit and restore the museum together.', 'I will face the dark passage and protect the visitors.', 'Let us read the inscription before entering the room.']]],
    'future_city' => ['A family is stuck during the city blackout. What will you do?', ['I will help the family find a safe light.', 'I will check the street for a clear route.', 'I will read the power map to locate the fault.'], ['The city core needs one final decision. Which plan helps everyone?', ['Let us share the power and rebuild the city together.', 'I will face the danger and protect the citizens.', 'Let us solve the energy code before restarting the core.']]],
    'sky_kingdom' => ['A cloud bird has lost its way above the kingdom. What will you do?', ['I will guide the bird back to its nest.', 'I will guard the bridge while the winds settle.', 'I will read the wind chart for a safe direction.'], ['The sky gate opens during a strong wind. Which choice is best?', ['Let us welcome the gatekeeper and share the sky road.', 'I will face the wind and protect my friends.', 'Let us solve the cloud symbols before we fly through.']]],
    'jungle_temple' => ['An explorer is trapped beneath a fallen vine. How will you help?', ['I will free the explorer and call for help.', 'I will watch the jungle path for more danger.', 'I will read the temple marks to find a safe tool.'], ['The emerald temple asks for one final answer. Which path will you take?', ['Let us respect the temple and protect its forest.', 'I will face the guardian and protect the explorers.', 'Let us solve the ancient inscription before touching the emerald.']]],
    'winter_village' => ['A villager is cold after the bell stops ringing. What will you do?', ['I will share a warm blanket and find the bell keeper.', 'I will clear the snowy path to the village hall.', 'I will read the village map to locate the bell.'], ['The frozen bell offers one last chance. What should your hero choose?', ['Let us forgive the bell keeper and restore the village together.', 'I will face the ice and protect the villagers.', 'Let us solve the bell message before striking it.']]],
];

$find = $pdo->prepare('SELECT s.id,e.title FROM learn_english_rpg_scenes s JOIN learn_english_rpg_episodes e ON e.id=s.episode_id WHERE e.code=? AND s.sort_order=?');
$update = $pdo->prepare('UPDATE learn_english_rpg_scenes SET prompt=?, choices_json=? WHERE id=?');
foreach ($contexts as $code => $data) {
    foreach ([7, 14] as $index => $sort) {
        $find->execute([$code, $sort]); $scene = $find->fetch(PDO::FETCH_ASSOC);
        if (!$scene) continue;
        $choices = $index === 0
            ? [['text'=>$data[1][0],'choice_code'=>'compassion','reputation_delta'=>2,'feedback'=>'Your kindness helps the people nearby.'],['text'=>$data[1][1],'choice_code'=>'courage','reputation_delta'=>1,'feedback'=>'Your courage makes the next step safer.'],['text'=>$data[1][2],'choice_code'=>'wisdom','reputation_delta'=>1,'feedback'=>'Your careful thinking reveals a useful clue.']]
            : [['text'=>$data[2][1][0],'choice_code'=>'mercy','reputation_delta'=>2,'feedback'=>'Working together opens a peaceful path.'],['text'=>$data[2][1][1],'choice_code'=>'valor','reputation_delta'=>1,'feedback'=>'Your brave choice protects the people with you.'],['text'=>$data[2][1][2],'choice_code'=>'insight','reputation_delta'=>1,'feedback'=>'The clue reveals a thoughtful way forward.']];
        $prompt = $index === 0 ? $data[0] : $data[2][0];
        $update->execute([$prompt, json_encode($choices, JSON_UNESCAPED_UNICODE), $scene['id']]);
    }
}

$dialogues = [
    ['mountain_camp',7,'A storm rolls over the mountain trail. Which meaning of “storm” will guide your next step?'],
    ['pirate_islands',7,'Dark clouds surround the emerald islands. Learn “storm” before the crew chooses a safe route.'],
    ['space_station',13,'The word “crew” flashes on the station console. Choose its meaning to break the dark spell.'],
    ['pirate_islands',13,'The captain calls out “crew” as the ship enters the mist. What does the word mean?'],
    ['ocean_treasure',8,'The reef guardian raises a shield and asks about “protect”. Answer to enter the coral court.'],
    ['dragon_academy',8,'A dragon guardian tests the word “protect” before opening the academy gate.'],
];
$updateDialogue = $pdo->prepare('UPDATE learn_english_rpg_scenes s JOIN learn_english_rpg_episodes e ON e.id=s.episode_id SET s.dialogue=? WHERE e.code=? AND s.sort_order=?');
foreach ($dialogues as $item) $updateDialogue->execute([$item[2], $item[0], $item[1]]);
echo "Updated ".count($contexts)." story chapters.\n";
