<?php
require __DIR__.'/library_network_bootstrap.php';require __DIR__.'/iplm_task4_support.php';require APPPATH.'libraries/Catalog_xlsx.php';
$dir=null;foreach($argv as$a)if(strpos($a,'--test=')===0)$dir=substr($a,7);
if($dir){network_check(preg_match('#^/tmp/pustaka_network_test_[a-zA-Z0-9_]+$#D',$dir)&&is_file($dir.'/connection.php'),'Isolated runtime required');$params=require $dir.'/connection.php';network_check(strpos($params['database'],'pustaka_network_test_')===0,'Test DB required');$db=DB($params);}else$db=DB();$db->db_debug=false;
$plan=task4_plan($db);$apply=in_array('--apply',$argv,true);$before=network_query($db,'SELECT * FROM libraries ORDER BY id')->result_array();$accountHash=hash('sha256',json_encode(network_query($db,'SELECT * FROM auth_user ORDER BY id')->result_array()));$formHash=hash('sha256',json_encode(network_query($db,'SELECT * FROM iplm_submissions ORDER BY id')->result_array()));$hash=hash_file('sha256',FCPATH.'docs/iplm/pendataan.xls');$stats=[];
if($apply){
    if(!$dir){$backup=network_backup($db,'sql/2026-10-05f_iplm_task4.sql');echo 'Backup: '.$backup.'.sql.gz',PHP_EOL;}
    foreach(preg_split('/;\s*(?:\r?\n|$)/',file_get_contents(FCPATH.'sql/2026-10-05f_iplm_task4.sql'))as$sql)if(trim($sql)!=='')network_query($db,$sql);
    $db->trans_begin();try{
        $before=network_query($db,'SELECT * FROM libraries ORDER BY id FOR UPDATE')->result_array();$plan=task4_plan($db);
        $accountHash=hash('sha256',json_encode(network_query($db,'SELECT * FROM auth_user ORDER BY id FOR UPDATE')->result_array()));$formHash=hash('sha256',json_encode(network_query($db,'SELECT * FROM iplm_submissions ORDER BY id FOR UPDATE')->result_array()));
        if(!$db->where('code','perguruan_tinggi')->count_all_results('library_types'))network_check($db->insert('library_types',['code'=>'perguruan_tinggi','name'=>'Perpustakaan Perguruan Tinggi','marker_color'=>'#b45309','sort_order'=>4]),'Taxonomy insert failed');
        $types=array_column($db->get('library_types')->result_array(),'id','code');foreach(task4_taxonomy()as$s)if(!$db->where('code',$s[1])->count_all_results('library_subtypes'))network_check($db->insert('library_subtypes',['library_type_id'=>$types[$s[0]],'code'=>$s[1],'name'=>$s[2],'iplm_eligible'=>$s[3],'sort_order'=>20,'description'=>'Pemetaan pendataan task4; kewenangan IPLM terpisah dari registrasi perpustakaan.']),'Subtype insert failed');
        $subs=array_column($db->get('library_subtypes')->result_array(),null,'code');$districts=array_column($db->where('regency_code','3317')->where('is_active',1)->get('ref_districts')->result_array(),null,'name');network_check(count($districts)===14,'Expected 14 Rembang districts');$coordCounts=[];foreach($plan as$r){$s=$r['source'];$k=$s['Latitude'].'|'.$s['Longitude'];$coordCounts[$k]=($coordCounts[$k]??0)+1;}$imported=[];
        foreach($plan as&$r){$s=$r['source'];$spec=$r['classification']['spec'];$old=$db->where(['source_system'=>'pendataan_task4','source_id'=>$s['Id']])->get('library_source_records')->row_array();
            if($old){network_check($old['source_sha256']===$hash,'Source changed after import; manual review required');$r['library_id']=$old['library_id'];$r['status']=$old['decision'];$r['note']=$old['note'];if($old['library_id'])$imported[$s['Id']]=$old['library_id'];continue;}
            if($r['status']==='IMPORT'){
                network_check($spec&&mb_strlen($s['Nama'])<=180&&mb_strlen($s['Lembaga Induk'])<=180,'Source identity too long');
                $district=null;foreach($districts as$d)if(task4_normal($d['name'])===task4_normal($s['Kecamatan']))$district=$d;
                $village=null;if($district)foreach($db->where('district_id',$district['id'])->get('ref_villages')->result_array()as$v)if(str_replace(' ','',task4_normal($v['name']))===str_replace(' ','',task4_normal($s['Kelurahan'])))$village=$v;
                $lat=$s['Latitude'];$lng=$s['Longitude'];$good=is_numeric($lat)&&is_numeric($lng)&&(float)$lat>=-7.4&&(float)$lat<=-6.4&&(float)$lng>=110.9&&(float)$lng<=112&&$coordCounts[$lat.'|'.$lng]<5;
                if(!$good)$r['note'].=' GPS kosong/tidak valid/berulang massal: koordinat master 0,0 (tidak ditampilkan sebagai titik); sumber asli tetap di arsip.';
                if(!$district||!$village)$r['note'].=' Wilayah belum cocok referensi; teks sumber dipertahankan.';
                $code=$r['classification']['ownership']&&preg_match('/^\d{8}$/D',$s['NPSN'])?$s['NPSN']:'PDT-'.$s['Id'];
                if($db->where('code',$code)->count_all_results('libraries')){$r['status']='TAHAN_KODE';$r['note'].=' Kode/NPSN sudah dipakai; tidak dibuat duplikat.';}
                else{
                    $data=['library_type_id'=>$types[$spec[0]],'library_subtype_id'=>$subs[$spec[1]]['id'],'code'=>$code,'name'=>$s['Nama'],'institution_name'=>$s['Lembaga Induk'],'institution_status'=>$r['classification']['ownership'],'npp'=>$s['Npp']?:null,'address'=>$s['Alamat'],'district_id'=>$district['id']??null,'village_id'=>$village['id']??null,'district'=>$s['Kecamatan'],'village'=>$s['Kelurahan'],'latitude'=>$good?$lat:0,'longitude'=>$good?$lng:0,'service_radius_meters'=>50,'opening_hours'=>$s['Jam Layanan']?:null,'description'=>'Perpustakaan '.$s['Nama'].'. Sumber pendataan terupdate; identitas dan lokasi perlu verifikasi pengelola.','status'=>'active','is_verified'=>0,'source_system'=>'pendataan_task4','source_id'=>$s['Id']];
                    network_check($db->insert('libraries',$data),'Library insert failed');$r['library_id']=(int)$db->insert_id();$imported[$s['Id']]=$r['library_id'];$r['note'].=' Ditambahkan; belum diverifikasi. Kontak/PIC sumber tersimpan privat, tidak dipublikasikan otomatis.';
                }
            }elseif($r['status']==='DUPLIKAT_SUMBER'){$r['library_id']=$imported[$r['duplicate_source']]??null;network_check($r['library_id'],'Duplicate primary missing');}
            if($r['library_id'])$imported[$s['Id']]=$r['library_id'];
            network_check($db->insert('library_source_records',['source_system'=>'pendataan_task4','source_id'=>$s['Id'],'library_id'=>$r['library_id'],'source_row'=>$s['_row'],'classification'=>$spec?$spec[0].'/'.$spec[1]:'perlu_verifikasi','decision'=>$r['status'],'note'=>$r['note'],'source_json'=>json_encode($s,JSON_UNESCAPED_UNICODE),'source_sha256'=>$hash]),'Source archive failed');
        }unset($r);
        // Establish ownership metadata without changing legacy identity, IDs, NPSN or coordinates.
        network_query($db,"UPDATE libraries SET institution_status=CASE WHEN UPPER(name) REGEXP '(^| )(NEGERI|NEGRI)( |$)' THEN 'negeri' ELSE 'belum_diketahui' END,updated_at=updated_at WHERE source_system='school_xlsx' AND institution_status IS NULL");
        $page=$db->where('code','library.activation')->get('sys_page')->row_array();if(!$page){network_check($db->insert('sys_page',['code'=>'library.activation','module'=>'Perpustakaan Terpadu','title'=>'Aktivasi Perpustakaan','route'=>'library-activation']),'Page failed');$pid=$db->insert_id();}else$pid=$page['id'];
        foreach($db->where_in('code',['ADMIN','SUPERADMIN'])->get('auth_role')->result_array()as$role)if(!$db->where(['role_id'=>$role['id'],'page_id'=>$pid])->count_all_results('auth_role_permission'))network_check($db->insert('auth_role_permission',['role_id'=>$role['id'],'page_id'=>$pid,'can_view'=>1,'can_create'=>1,'can_edit'=>1,'can_export'=>1]),'Permission failed');
        if(!$db->where('menu_key','library.activation')->count_all_results('sys_menu')){$parent=$db->where('menu_key','iplm.group')->get('sys_menu')->row_array();network_check($db->insert('sys_menu',['menu_area'=>'MAIN','menu_key'=>'library.activation','parent_id'=>$parent['id']??null,'page_id'=>$pid,'title'=>'Aktivasi Perpustakaan','url'=>'library-activation','icon'=>'ti ti-key','sort_order'=>30]),'Menu failed');}
    foreach($before as$l){$now=$db->where('id',$l['id'])->get('libraries')->row_array();foreach($l as$k=>$v)if($k!=='institution_status')network_check($now[$k]===$v,'Existing master changed: '.$l['id'].' '.$k);}
    network_check($accountHash===hash('sha256',json_encode(network_query($db,'SELECT * FROM auth_user ORDER BY id')->result_array())),'Accounts changed');network_check($formHash===hash('sha256',json_encode(network_query($db,'SELECT * FROM iplm_submissions ORDER BY id')->result_array())),'IPLM submissions changed');
        network_check((int)network_query($db,"SELECT COUNT(*) n FROM libraries l JOIN ref_districts d ON d.id=l.district_id WHERE l.source_system='pendataan_task4' AND d.regency_code!='3317'")->row()->n===0,'Wrong regency mapping');
        network_check($db->trans_status(),'Import transaction failed');$db->trans_commit();
    }catch(Throwable$e){$db->trans_rollback();throw$e;}

}
$master=array_column(network_query($db,'SELECT l.id,l.code,l.name,l.institution_name,l.npp,l.district,l.village,t.name type_name,s.name subtype_name FROM libraries l JOIN library_types t ON t.id=l.library_type_id LEFT JOIN library_subtypes s ON s.id=l.library_subtype_id')->result_array(),null,'id');$lines=[];$seen=[];
foreach($plan as$r){$stats[$r['status']]=($stats[$r['status']]??0)+1;$s=$r['source'];$m=$master[$r['library_id']??($r['candidates'][0]??0)]??null;if($m)$seen[$m['id']]=true;$lines[]=array_merge($m?array_values($m):array_fill(0,9,''),[$s['Id'],$s['NPSN'],$s['Nama'],$s['Lembaga Induk'],$s['Npp'],$s['Kecamatan'],$s['Kelurahan'],$s['Jenis'],$s['Subjenis'],$r['status'],$r['classification']['spec']?implode(' / ',array_slice($r['classification']['spec'],0,2)):'Perlu verifikasi',$r['classification']['ownership']??'',$r['note'],implode(', ',$r['candidates']),$s['_row']]);}
foreach($master as$m)if(!isset($seen[$m['id']]))$lines[]=array_merge(array_values($m),array_fill(0,9,''),['HANYA_DATABASE','','','Belum ditemukan pada pendataan; mungkin belum didata.','','']);
$folder=$dir?:FCPATH.'docs/iplm';usort($lines,function($a,$b){$rank=function($s){return strpos($s,'TAHAN')===0?0:($s==='PADANAN'?1:($s==='IMPORT'?2:3));};return [$rank($a[18]),$a[11]]<=>[$rank($b[18]),$b[11]];});$writer=new Catalog_xlsx();$file=$writer->build('Persandingan task4',['ID database','NPSN/kode database','Nama database','Induk database','NPP database','Kecamatan database','Desa database','Jenis database','Subjenis database','ID pendataan','NPSN sumber','Nama pendataan','Induk pendataan','NPP sumber','Kecamatan sumber','Desa sumber','Jenis sumber','Subjenis sumber','Keputusan','Klasifikasi aplikasi','Negeri/swasta','Catatan','Kandidat ID','Baris sumber'],$lines);task4_style_workbook($file);copy($file,$folder.'/PERSANDINGAN_TASK4.xlsx');chmod($folder.'/PERSANDINGAN_TASK4.xlsx',0600);unlink($file);
$summary=['applied'=>$apply,'source_rows'=>count($plan),'statuses'=>$stats,'master_before'=>count($before),'master_after'=>count($master),'source_sha256'=>$hash,'existing_master_preserved'=>true,'accounts_preserved'=>true,'iplm_values_preserved'=>true];file_put_contents($folder.'/ringkasan-task4.json',json_encode($summary,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE));echo json_encode($summary,JSON_PRETTY_PRINT),PHP_EOL;
