<?php
require __DIR__.'/library_network_bootstrap.php';require APPPATH.'models/Iplm_model.php';
$dir=$argv[1]??'';network_check(preg_match('#^/tmp/pustaka_network_test_[a-zA-Z0-9_]+$#D',$dir)&&is_file($dir.'/connection.php'),'Isolated runtime required.');$params=require $dir.'/connection.php';network_check(strpos($params['database'],'pustaka_network_test_')===0,'Test DB required.');$db=DB($params);$db->db_debug=false;$m=new Iplm_model();$m->db=$db;$checks=0;
function check3($ok,$text){global$checks;network_check($ok,'FAIL '.$text);$checks++;echo 'PASS '.$text,PHP_EOL;}
function reject3($fn,$text){$rejected=false;try{$fn();}catch(Throwable$e){$rejected=true;}check3($rejected,$text);}
$p=$m->periods()[0];$original=$p;$input=$p+['dates_confirmed'=>1];$input['population_mode']='manual';$input['population']='450';$input['population_note']='Fixture approved denominator';
$m->save_period($input,9000004);$p=$m->period($p['id']);check3((int)$p['population']===450&&$p['population_mode']==='manual'&&(int)$p['population_registry_count']===403,'Manual denominator and registry snapshot stored separately');
reject3(function()use($m,$input){$m->save_period($input,9000004);},'Stale population edit rejected');
$input['version']=$p['version'];foreach(['0','-2','1e3','10000001',[], '']as$bad){$badInput=$input;$badInput['population']=$bad;reject3(function()use($m,$badInput){$m->save_period($badInput,9000004);},'Invalid manual denominator rejected');}
$badInput=$input;$badInput['population_note']='';reject3(function()use($m,$badInput){$m->save_period($badInput,9000004);},'Manual reason required');
$m->save_period($input,9000004);$p=$m->period($p['id']);check3((int)$p['population']===450,'Manual value survives resave');
$input['version']=$p['version'];$input['population_mode']='auto';$m->save_period($input,9000004);$p=$m->period($p['id']);check3((int)$p['population']===403&&$p['population_mode']==='auto','Explicit auto mode restores registry total');
$audit=$db->where('event','period.saved')->order_by('id','DESC')->get('iplm_history')->row_array();$payload=json_decode($audit['payload_json'],true);check3($payload['before']['population_mode']==='manual'&&$payload['after']['population_mode']==='auto','Population transition audited');
$schema=[['code'=>'print_titles','kind'=>'number','label'=>'Titles','is_required'=>1,'evidence_required'=>1],['code'=>'evidence_url','kind'=>'url','label'=>'Folder','is_required'=>0,'evidence_required'=>0]];
$data=['f_print_titles'=>'10','f_evidence_url'=>'https://drive.google.com/fixture-folder'];[$v,$e]=$m->validate($schema,$data,true);check3($v['evidence_url']===$data['f_evidence_url'],'One folder satisfies indicator evidence requirement');
foreach(['','javascript:alert(1)','http://example.com']as$bad){$data['f_evidence_url']=$bad;reject3(function()use($m,$schema,$data){$m->validate($schema,$data,true);},'Missing or unsafe shared evidence rejected');}
$ids=json_decode(file_get_contents($dir.'/iplm-http.json'),true);$r=$m->find($ids['id'],4);$save=['version'=>$r['version'],'action'=>'draft'];foreach($r['schema']as$f)$save['f_'.$f['code']]=$r['values'][$f['code']]??'';$save['f_evidence_url']='https://drive.google.com/task3-folder';$before=$r['evidence'];$m->save($r['id'],4,9000000,$save);$after=$m->find($r['id'],4);check3($before===$after['evidence'],'Saving new form preserves all legacy evidence links');check3($after['values']['evidence_url']===$save['f_evidence_url'],'Shared folder persists');
$z=new ZipArchive();check3($z->open(FCPATH.'docs/iplm/PERSANDINGAN_DATABASE_PENDATAAN_TASK3.xlsx')===true,'Comparison is genuine XLSX');$xml=simplexml_load_string($z->getFromName('xl/worksheets/sheet1.xml'));$ns=['s'=>'http://schemas.openxmlformats.org/spreadsheetml/2006/main'];$xml->registerXPathNamespace('s',$ns['s']);$rows=$xml->xpath('//s:sheetData/s:row');check3(count($rows)===863,'Workbook contains 861 comparison rows plus headers');$source=[];$master=[];$emptyLeft=0;$emptyRight=0;$marked=0;foreach(array_slice($rows,2)as$row){$c=[];foreach($row->c as$cell)$c[(string)$cell['r']]=['v'=>(string)$cell->is->t,'s'=>(int)$cell['s']];$n=(string)$row['r'];$left=$c['A'.$n]['v'];$right=$c['O'.$n]['v'];if($left!=='')$master[$left]=true;if($right!=='')$source[]=$right;else{$emptyRight++;for($i=14;$i<28;$i++){ $col='';for($j=$i+1;$j>0;$j=intdiv($j-1,26))$col=chr(65+($j-1)%26).$col;network_check($c[$col.$n]['v']==='','Right side must be blank');}}if($left==='')$emptyLeft++;if($c['P'.$n]['s']===9)$marked++;if($right==='50964')network_check($left==='2'&&$c['Q'.$n]['v']==='3317103E1000003','Perpusda mapping incorrect');}
check3(count($source)===834&&count(array_unique($source))===834&&count($master)===411,'All source rows and master IDs covered');check3($emptyLeft===394&&$emptyRight===27,'One-sided units have empty opposite side');check3($marked===18,'Differing original NPSN cells marked red');$z->close();
file_put_contents($dir.'/iplm-task3-model.json',json_encode(['checks'=>$checks]));echo $checks," task3 checks passed.\n";
