<?php
require __DIR__.'/library_network_bootstrap.php';require __DIR__.'/iplm_task4_support.php';require APPPATH.'models/Library_activation_model.php';require APPPATH.'models/Auth_model.php';require APPPATH.'models/Iplm_model.php';
$dir=$argv[1]??'';network_check(preg_match('#^/tmp/pustaka_network_test_[a-zA-Z0-9_]+$#D',$dir)&&is_file($dir.'/connection.php'),'Isolated runtime required');$params=require $dir.'/connection.php';network_check(strpos($params['database'],'pustaka_network_test_')===0,'Test DB required');$db=DB($params);$db->db_debug=false;$m=new Library_activation_model();$m->db=$db;$auth=new Auth_model();$auth->db=$db;$iplm=new Iplm_model();$iplm->db=$db;$checks=0;
function ok4($v,$msg){global$checks;network_check($v,'FAIL '.$msg);$checks++;echo 'PASS '.$msg,PHP_EOL;}
function reject4($fn,$msg){$failed=false;try{$fn();}catch(Throwable$e){$failed=true;}ok4($failed,$msg);}
ok4($db->count_all('library_source_records')===834,'All 834 source rows archived, including held rows');
ok4((int)$db->query("SELECT COUNT(*) n FROM libraries l JOIN ref_districts d ON d.id=l.district_id WHERE l.source_system='pendataan_task4' AND d.regency_code!='3317'")->row()->n===0,'Imported district IDs are exclusively Kabupaten Rembang, not same-name districts elsewhere');
ok4((int)$db->query("SELECT COUNT(*) n FROM libraries l JOIN ref_villages v ON v.id=l.village_id WHERE l.source_system='pendataan_task4' AND v.district_id!=l.district_id")->row()->n===0,'Village IDs belong to selected district');
ok4((int)$db->where('library_id IS NULL',null,false)->count_all_results('library_source_records')===35,'35 unresolved school identities held instead of duplicated');
$lookup=function($id)use($db){return$db->select('l.*,s.code subtype_code,s.iplm_eligible')->from('library_source_records r')->join('libraries l','l.id=r.library_id')->join('library_subtypes s','s.id=l.library_subtype_id')->where('r.source_id',(string)$id)->get()->row_array();};
ok4((int)$lookup('50964')['id']===2&&(int)$db->query("SELECT COUNT(*) n FROM libraries l JOIN library_subtypes s ON s.id=l.library_subtype_id WHERE s.code='kabupaten'")->row()->n===1,'Exactly one Perpusda, original ID 2');
ok4($lookup('359007')['subtype_code']==='tbm','Aji Gineng is TBM, not school');ok4($lookup('359143')['subtype_code']==='pondok_pesantren','Al-Anwar 2 Putri is private pesantren subtype');ok4($lookup('45128')['subtype_code']==='smp'&&$lookup('45128')['institution_status']==='swasta','Maktabah is private SMP');
ok4(!$lookup('8862')['iplm_eligible']&&!$iplm->eligible($lookup('8862')['id']),'Higher education registered but excluded from district IPLM');
ok4($lookup('49457')['institution_status']==='negeri','SMA N 2 is negeri, not private');
foreach(['48720','48199']as$id)ok4($db->where('source_id',$id)->get('library_source_records')->row()->library_id===null,'Number mismatch held: '.$id);
ok4((int)$db->where('source_system','school_xlsx')->count_all_results('libraries')===410,'All existing schools preserved');
$perpus=$db->where('id',2)->get('libraries')->row_array();reject4(function()use($m){$m->issue(2,9000004);},'Central library cannot be claimed');
$issued=$m->issue(8,9000004);$stored=$db->where('library_id',8)->get('library_activation_codes')->row_array();ok4($stored['token_hash']===hash('sha256',str_replace('-','',$issued['code']))&&$stored['token_hash']!==$issued['code'],'Only token hash persisted');
reject4(function()use($m,$issued){$m->claim(10,$issued['code']);},'Code cannot activate another library');reject4(function()use($m){$m->claim(8,str_repeat('A',32));},'Wrong code rejected');
$new=$m->issue(8,9000004);reject4(function()use($m,$issued){$m->claim(8,$issued['code']);},'Reissue invalidates earlier token');$db->where('library_id',8)->update('library_activation_codes',['expires_at'=>'2000-01-01']);reject4(function()use($m,$new){$m->claim(8,$new['code']);},'Expired code rejected');
$new=$m->issue(8,9000004);$m->revoke(8,9000004);reject4(function()use($m,$new){$m->claim(8,$new['code']);},'Revoked code rejected');$new=$m->issue(8,9000004);$u=$m->claim(8,$new['code']);ok4((int)$u['library_id']===8&&$u['force_password_change']===1,'Valid code yields correct local account forced to set password');
reject4(function()use($m,$new){$m->claim(8,$new['code']);},'Used token cannot be replayed');reject4(function()use($m){$m->issue(8,9000004);},'Claimed library cannot be reissued');
$new=$m->issue(10,9000004);$uid=$db->where('library_id',10)->get('library_activation_codes')->row()->user_id;$db->where('id',$uid)->update('auth_user',['last_login_at'=>date('Y-m-d H:i:s')]);reject4(function()use($m,$new){$m->claim(10,$new['code']);},'Any prior login blocks ownership claim');
$new=$m->issue(12,9000004);$uid=$db->where('library_id',12)->get('library_activation_codes')->row()->user_id;$db->where('id',$uid)->update('auth_user',['force_password_change'=>0]);reject4(function()use($m,$new){$m->claim(12,$new['code']);},'Changed password blocks claim even if login timestamp absent');
$new=$m->issue(14,9000004);$uid=$db->where('library_id',14)->get('library_activation_codes')->row()->user_id;$db->where('id',$uid)->update('auth_user',['status'=>'inactive']);reject4(function()use($m,$new){$m->claim(14,$new['code']);},'Disabled user cannot claim');
$new=$m->issue(16,9000004);$uid=$db->where('library_id',16)->get('library_activation_codes')->row()->user_id;$role=$db->where('code','ADMIN')->get('auth_role')->row()->id;$db->insert('auth_user_role',['user_id'=>$uid,'role_id'=>$role]);reject4(function()use($m,$new){$m->claim(16,$new['code']);},'Mixed local/global roles cannot activate');
$new=$m->issue(18,9000004);$uid=$db->where('library_id',18)->get('library_activation_codes')->row()->user_id;$password='PrivateFixture!Activation';$db->where('id',$uid)->update('auth_user',['password_hash'=>password_hash($password,PASSWORD_BCRYPT)]);ok4($auth->attempt_login($new['username'],$password)===false,'Issuing code disables old initial-password login');
ok4(strpos(json_encode($db->get('network_audit')->result_array()),$new['code'])===false,'Audit contains no raw activation code');
$http=$m->issue(20,9000004);file_put_contents($dir.'/task4-activation.json',json_encode(['http'=>$http,'checks'=>$checks]));echo $checks," task4 checks passed.\n";
