<?php
require __DIR__.'/library_network_bootstrap.php';require APPPATH.'models/Library_services_model.php';require APPPATH.'models/Library_network_model.php';
$dir=$argv[1]??'';network_check(preg_match('#^/tmp/pustaka_network_test_[a-zA-Z0-9_]+$#D',$dir)&&is_file($dir.'/connection.php'),'Private test directory required.');$params=require $dir.'/connection.php';network_check(strpos($params['database'],'pustaka_network_test_')===0,'Isolated database required.');$db=DB($params);$db->db_debug=false;$s=new Library_services_model();$s->db=$db;$n=new Library_network_model();$n->db=$db;$checks=0;
function check_service($condition,$message){global $checks;network_check($condition,'FAIL '.$message);$checks++;echo 'PASS '.$message,PHP_EOL;}
function deny_service($fn,$message){$denied=false;try{$fn();}catch(Throwable $e){$denied=true;}check_service($denied,$message);}
$actor=9000000;$tag=bin2hex(random_bytes(4));$b=$n->save(4,'books',0,['title'=>'Stock fixture '.$tag,'format'=>'physical','status'=>'published'],$actor);$i=$n->save(4,'items',0,['book_id'=>$b,'barcode'=>'ST-'.$tag,'status'=>'available'],$actor);$i2=$n->save(4,'items',0,['book_id'=>$b,'barcode'=>'SL-'.$tag,'status'=>'available'],$actor);$ma=$n->save(4,'members',0,['full_name'=>'Service member '.$tag,'member_no'=>'SM-'.$tag,'status'=>'active'],$actor);$mb=$n->save(4,'members',0,['full_name'=>'Next member '.$tag,'member_no'=>'SN-'.$tag,'status'=>'active'],$actor);$loan=$n->issue(4,'SM-'.$tag,'SL-'.$tag,$actor);
$stock=$s->stock_create(4,'network','Stock test '.$tag,$actor);$entries=$s->stock_entries(4,'network',$stock);$indexed=array_column($entries,null,'item_id');check_service(isset($indexed[$i])&&$indexed[$i2]['on_loan']==1,'Snapshot includes physical items and marks active loans');
deny_service(function()use($s,$actor){$s->stock_create(4,'network','Duplicate',$actor);},'Only one active session per library/source');
check_service(!$s->stock(6,'network',$stock),'Foreign stock session unreadable');
deny_service(function()use($s,$stock,$tag){$s->stock_scan(6,'network',$stock,'ST-'.$tag,'good','',9000002);},'Foreign stock scan rejected');
$s->stock_scan(4,'network',$stock,'ST-'.$tag,'good','checked',$actor);$s->stock_scan(4,'network',$stock,'ST-'.$tag,'damaged','rechecked',$actor);check_service(count($s->stock_entries(4,'network',$stock))===count($entries),'Rescan does not duplicate snapshot');
$e=$db->where('session_id',$stock)->where('item_id',$i)->get('library_stock_entries')->row_array();check_service($e['observed']==='damaged'&&$n->find(4,'items',$i)['status']==='available','Observation does not mutate live inventory');
deny_service(function()use($s,$stock,$actor){$s->stock_scan(4,'network',$stock,'FOREIGN','good','',$actor);},'Unknown barcode not added to snapshot');
$s->stock_close(4,'network',$stock,'closed','Verified fixture',$actor);deny_service(function()use($s,$stock,$tag,$actor){$s->stock_scan(4,'network',$stock,'ST-'.$tag,'good','',$actor);},'Closed snapshot immutable');
$next=$s->stock_create(4,'network','Next fixture',$actor);check_service($next>$stock,'New session allowed after closure');$s->stock_close(4,'network',$next,'cancelled','Fixture cleanup',$actor);
$db->insert('books',['title'=>'Legacy stock '.$tag]);$lb=(int)$db->insert_id();$db->insert('book_items',['library_id'=>2,'book_id'=>$lb,'barcode'=>'LEG-'.$tag,'collection_type'=>'Buku']);$li=(int)$db->insert_id();$db->insert('book_items',['library_id'=>2,'book_id'=>$lb,'barcode'=>'DIG-'.$tag,'collection_type'=>'Ebook']);$db->insert('book_items',['library_id'=>6,'book_id'=>$lb,'barcode'=>'OTHER-'.$tag,'collection_type'=>'Buku']);
$ls=$s->stock_create(2,'legacy','Legacy stock',9000004);$le=$s->stock_entries(2,'legacy',$ls);$leByItem=array_column($le,null,'item_id');$leCodes=array_column($le,'barcode');check_service(isset($leByItem[$li])&&!in_array('DIG-'.$tag,$leCodes,true)&&!in_array('OTHER-'.$tag,$leCodes,true),'Legacy snapshot excludes digital and foreign items');$s->stock_scan(2,'legacy',$ls,'LEG-'.$tag,'good','',9000004);$s->stock_close(2,'legacy',$ls,'closed','Legacy verified',9000004);check_service($s->stock(2,'legacy',$ls)['status']==='closed','Legacy stock cycle complete');
$n->save_settings(4,['loan_days'=>7,'max_loans'=>3,'max_renewals'=>1],$actor);
$r=$s->reserve(4,'SN-'.$tag,$b,$actor);deny_service(function()use($s,$b,$tag,$actor){$s->reserve(4,'SN-'.$tag,$b,$actor);},'Duplicate active reservation rejected');
deny_service(function()use($s,$b,$tag){$s->reserve(6,'SN-'.$tag,$b,9000002);},'Foreign member/book reservation rejected');
$queueError='';try{$n->issue(4,'SM-'.$tag,'ST-'.$tag,$actor);}catch(Throwable $e){$queueError=$e->getMessage();}check_service(strpos($queueError,'antrean reservasi')!==false,'Other member cannot bypass reservation queue');
deny_service(function()use($n,$mb,$actor){$n->archive(4,'members',$mb,$actor);},'Reserved member cannot be archived');
$fulfilled=$n->issue(4,'SN-'.$tag,'ST-'.$tag,$actor);check_service($db->where('id',$r)->get('network_reservations')->row()->status==='fulfilled','Issue fulfills first reservation atomically');$n->loan_action(4,$fulfilled,'return',$actor);$n->loan_action(4,$loan,'return',$actor);
$r2=$s->reserve(4,'SN-'.$tag,$b,$actor);deny_service(function()use($s,$r2){$s->cancel_reservation(6,$r2,9000002);},'Foreign cancellation rejected');$s->cancel_reservation(4,$r2,$actor);check_service($db->where('id',$r2)->get('network_reservations')->row()->status==='cancelled','Cancellation releases queue');
$db->replace('network_membership_terms',['library_id'=>4,'member_id'=>$ma,'expires_on'=>'2020-01-01','updated_by'=>$actor]);deny_service(function()use($n,$tag,$actor){$n->issue(4,'SM-'.$tag,'ST-'.$tag,$actor);},'Expired local membership blocks new loan');deny_service(function()use($s,$b,$tag,$actor){$s->reserve(4,'SM-'.$tag,$b,$actor);},'Expired membership blocks reservation');
$token=$s->kiosk_create(4,$actor);$k=$s->kiosk($token);check_service($k&&(int)$k['library_id']===4&&$k['token_hash']!==$token,'Kiosk stored as hash with correct scope');deny_service(function()use($s,$k){$s->kiosk_revoke(6,$k['id'],9000002);},'Foreign kiosk revocation rejected');$s->kiosk_revoke(4,$k['id'],$actor);check_service(!$s->kiosk($token),'Revoked token immediately invalid');
$s->rate_limit('fixture-'.$tag,1);deny_service(function()use($s,$tag){$s->rate_limit('fixture-'.$tag,1);},'Public rate limiter cannot be bypassed by new session');
file_put_contents($dir.'/services.json',json_encode(compact('stock','ls','b','i','ma','mb','tag')));echo $checks," service model checks passed.\n";
