<?php
require __DIR__.'/test_library_network_http.php';$baseChecks=$checks;$fixtureX=json_decode(file_get_contents($directory.'/exchange.json'),true);login('test-school-a',$new);login('test-school-b',$fixture['password'],'b');
function exchange_csrf($path='/library-services/exchange',$who='a'){$r=request($path,null,$who);network_check($r['status']===200,'Form unavailable '.$path);network_check(preg_match('/name="service_csrf" value="([a-f0-9]+)"/',$r['body'],$m),'Service token missing '.$path);return $m[1];}
// Index only has a POST form after selecting a lender; fines always has one.
function fine_csrf($who='a'){return exchange_csrf('/library-services/fines',$who);}
foreach(['exchange','fines']as $module){$r=request('/library-services/'.$module);ok($r['status']===200&&strpos($r['body'],'A PHP Error')===false,'Local module renders '.$module);ok(request('/library-services/'.$module,null,'test-member')['status']===403,'Member cannot open '.$module);ok(request('/library-services/'.$module.'?library_id=6')['status']===403,'Local scope override denied '.$module);}
$discovery='/library-services/exchange?owner_id=6&asset_source=network&q='.urlencode($fixtureX['tag']);$r=request($discovery);ok($r['status']===200&&strpos($r['body'],'EX-'.$fixtureX['tag'])!==false&&strpos($r['body'],'Fixture B PRIVATE')===false,'Discovery shows available published collection, not drafts');
ok(request('/library-services/exchange',['owner_id'=>6])['status']===403,'Exchange requires CSRF');
$token=exchange_csrf($discovery);$r=request('/library-services/exchange',['service_csrf'=>$token,'owner_id'=>6,'asset_source'=>'network','item_id'=>$fixtureX['item'],'due_on'=>date('Y-m-d',strtotime('+10 days')),'note'=>'HTTP request <script>test</script>','borrower_id'=>8]);$row=$db->where('item_id',$fixtureX['item'])->where('state','requested')->order_by('id','DESC')->get('inter_library_loans')->row_array();ok($r['status']===302&&$row&&$row['borrower_id']==4&&$row['requested_by']==9000000,'Request uses session borrower and actor, not submitted owner override');$id=$row['id'];$detail='/library-services/exchange/'.$id;
ok(request('/library-services/exchange',['service_csrf'=>$token])['status']===403,'Exchange CSRF single use');$r=request($detail);ok(strpos($r['body'],'&lt;script&gt;test&lt;/script&gt;')!==false,'Exchange notes escaped');
request($detail,['service_csrf'=>exchange_csrf($detail),'action'=>'approve','note'=>'Wrong party']);ok($db->where('id',$id)->get('inter_library_loans')->row()->state==='requested','Borrower cannot consent for owner');
request($detail,['service_csrf'=>exchange_csrf($detail,'b'),'action'=>'approve','note'=>'Owner approval'],'b');ok($db->where('id',$id)->get('inter_library_loans')->row()->state==='approved','Owner approves through real form');
request($detail,['service_csrf'=>exchange_csrf($detail,'b'),'action'=>'dispatch','note'=>'Shipment proof'],'b');request($detail,['service_csrf'=>exchange_csrf($detail),'action'=>'receive','note'=>'Received proof']);ok($db->where('id',$id)->get('inter_library_loans')->row()->state==='received','Two-sided dispatch and receipt complete');
$r=request($detail.'/print');ok($r['status']===200&&strpos($r['body'],'Bukti Peminjaman')!==false,'Printable institutional handover');
$r=request('/library-services/exchange?format=xlsx');$path=$directory.'/exchange.xlsx';file_put_contents($path,$r['body']);$zip=new ZipArchive();ok($zip->open($path)===true,'Exchange download genuine Excel');$zip->close();
$r=request('/library-services/exchange?format=csv');ok($r['status']===200&&strpos($r['body'],'EX-'.$fixtureX['tag'])!==false,'Exchange CSV scoped and available');
request($detail,['service_csrf'=>exchange_csrf($detail),'action'=>'return','note'=>'Return sent']);request($detail,['service_csrf'=>exchange_csrf($detail,'b'),'action'=>'complete','note'=>'Owner received','condition'=>'good'],'b');ok($db->where('id',$id)->get('inter_library_loans')->row()->state==='returned'&&$db->where('id',$fixtureX['item'])->get('network_items')->row()->status==='available','HTTP full exchange cycle releases original item');
// A third institution gets no detail or receipt, even knowing the exact id.
$db->where('id',9000000)->update('auth_user',['library_id'=>8]);ok(request($detail)['status']===404&&request($detail.'/print')['status']===404,'Third institution cannot view transaction or handover');$db->where('id',9000000)->update('auth_user',['library_id'=>4]);
$loan=$fixtureX['netLoan']['id'];$before=$db->count_all('library_fines');$r=request('/library-services/fines',['service_csrf'=>fine_csrf(),'loan_source'=>'network','loan_id'=>$loan,'amount'=>'12000','reason'=>'Manual HTTP reason','library_id'=>6]);$fine=$db->where('reason','Manual HTTP reason')->order_by('id','DESC')->get('library_fines')->row_array();ok($r['status']===302&&$fine&&$fine['library_id']==4&&$db->count_all('library_fines')===$before+1,'Manual fine linked to scoped transaction');$fd='/library-services/fines/'.$fine['id'];
ok(request($fd,null,'b')['status']===404,'Other library cannot read member fine');
request($fd,['service_csrf'=>exchange_csrf($fd),'action'=>'payment','amount'=>'4000','reference'=>'R-HTTP','note'=>'Verified manually']);$r=request($fd);ok(strpos($r['body'],'8.000')!==false,'Partial payment changes remaining amount');
$count=$db->count_all('library_fine_events');request($fd,['service_csrf'=>exchange_csrf($fd),'action'=>'payment','amount'=>'9000','reference'=>'Over','note'=>'Must reject']);ok($db->count_all('library_fine_events')===$count,'Overpayment via HTTP not inserted');
request($fd,['service_csrf'=>exchange_csrf($fd),'action'=>'waiver','amount'=>'8000','reference'=>'W-HTTP','note'=>'Manual decision']);$r=request($fd);ok(strpos($r['body'],'Selesai')!==false,'Manual waiver settles remaining amount');
$event=$db->where('fine_id',$fine['id'])->where('kind','payment')->get('library_fine_events')->row_array();request($fd,['service_csrf'=>exchange_csrf($fd),'action'=>'reversal','event_id'=>$event['id'],'reference'=>'C-HTTP','note'=>'Correct wrong proof']);$r=request($fd);ok(strpos($r['body'],'4.000')!==false&&strpos($r['body'],'Sudah dikoreksi')!==false,'Correction preserves receipt and restores balance');
$r=request('/library-services/fines?format=csv');ok($r['status']===200&&strpos($r['body'],'Manual HTTP reason')!==false&&strpos($r['body'],'Manual damage decision')===false,'Fine CSV does not leak other creditor ledger');
$r=request('/library-services/fines?format=xlsx');$path=$directory.'/fines.xlsx';file_put_contents($path,$r['body']);$zip=new ZipArchive();ok($zip->open($path)===true,'Manual fine genuine Excel');$zip->close();
foreach(['/library-services/exchange','/library-services/fines'] as $path)ok(request($path,null,'test-central')['status']===200,'Central can select context '.$path);
$r=request('/library-services/exchange/'.$fixtureX['legacyId'].'?library_id=2&source=legacy',null,'test-central');ok($r['status']===200,'Central can inspect legacy exchange');
$p=$db->where('code','library.services')->get('sys_page')->row()->id;$role=$db->where('code','ADMIN')->get('auth_role')->row()->id;$db->where('role_id',$role)->where('page_id',$p)->update('auth_role_permission',['can_export'=>0,'can_approve'=>0]);request('/logout',null,'test-legacy');login('test-legacy',$fixture['password'],'test-legacy');
ok(request('/library-services/exchange?format=xlsx',null,'test-legacy')['status']===403,'Central exchange export permission enforced');ok(request('/library-services/fines?library_id=4&format=xlsx',null,'test-legacy')['status']===403,'Central fines export permission enforced');
$csrf=exchange_csrf('/library-services/fines?library_id=2','test-legacy');ok(request('/library-services/exchange/'.$fixtureX['legacyId'].'?library_id=2',['service_csrf'=>$csrf,'action'=>'approve','note'=>'No permission'],'test-legacy')['status']===403,'Owner consent requires central approve permission');$db->where('role_id',$role)->where('page_id',$p)->update('auth_role_permission',['can_export'=>1,'can_approve'=>1]);
file_put_contents($directory.'/exchange-http.json',json_encode(['exchange'=>$id,'fine'=>$fine['id']]));echo ($checks-$baseChecks)," new exchange/fine HTTP checks passed; ",$checks," including authentication regression.\n";
