<?php
require __DIR__.'/library_network_bootstrap.php';
$directory=$argv[1]??'';network_check(preg_match('#^/tmp/pustaka_network_test_[a-zA-Z0-9_]+$#D',$directory)&&is_file($directory.'/connection.php'),'Private fixture required.');$params=require $directory.'/connection.php';network_check(strpos($params['database'],'pustaka_network_test_')===0,'Test database required.');$db=DB($params);$db->db_debug=false;$fixture=json_decode(file_get_contents($directory.'/fixtures.json'),true);$meta=json_decode(file_get_contents($directory.'/iplm-model.json'),true);$checks=0;
function ok($v,$message){global$checks;network_check($v,'FAIL '.$message);$checks++;echo 'PASS '.$message,PHP_EOL;}
function req($path,$data=null,$who='local'){global$directory;$c=curl_init('http://127.0.0.1:8797'.$path);curl_setopt_array($c,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_HEADER=>true,CURLOPT_COOKIEJAR=>$directory.'/iplm-cookie-'.$who,CURLOPT_COOKIEFILE=>$directory.'/iplm-cookie-'.$who,CURLOPT_TIMEOUT=>30]);if($data!==null)curl_setopt_array($c,[CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>http_build_query($data)]);$raw=curl_exec($c);network_check($raw!==false,'HTTP failed.');$size=curl_getinfo($c,CURLINFO_HEADER_SIZE);$status=curl_getinfo($c,CURLINFO_RESPONSE_CODE);curl_close($c);return ['status'=>$status,'body'=>substr($raw,$size),'headers'=>substr($raw,0,$size)];}
function token($path,$who='local',$name='iplm_csrf'){$r=req($path,null,$who);network_check(preg_match('/name="'.$name.'" value="([a-f0-9]+)"/',$r['body'],$m),'Missing CSRF field: '.$path);return $m[1];}
foreach(['local'=>['test-school-a',$fixture['changed_password']],'central'=>['test-central',$fixture['password']],'member'=>['test-member',$fixture['password']],'admin'=>['test-legacy',$fixture['password']]]as$who=>$login){$r=req('/auth/do_login',['identifier'=>$login[0],'password'=>$login[1]],$who);ok(in_array($r['status'],[302,303,307]),'Fixture login '.$who);}
foreach(['local','central','admin']as$who){$r=req('/iplm',null,$who);ok($r['status']===200&&!str_contains($r['body'],'Severity:'),'IPLM dashboard renders for '.$who);}
ok(req('/iplm',null,'member')['status']===403,'Ordinary member cannot access IPLM');
foreach(['/iplm/settings','/iplm/analysis/'.$meta['period'],'/library-types']as$path)ok(req($path)['status']===403,'Local cannot access '.$path);
ok(req('/iplm/form/'.$meta['foreign'])['status']===404,'Foreign entry hidden through HTTP');
ok(req('/iplm/review/'.$meta['foreign'],['action'=>'verify'])['status']===403,'Local cannot approve entries');
ok(req('/iplm/create',[])['status']===403,'Missing CSRF rejected');
ok(req('/iplm/create')['status']===405,'GET cannot create entry');
$r=req('/iplm/create',['iplm_csrf'=>token('/iplm'),'period_id'=>$meta['period'],'library_id'=>6]);ok($r['status']===403,'Posted foreign library scope rejected');
$r=req('/iplm/create',['iplm_csrf'=>token('/iplm'),'period_id'=>$meta['period']]);ok(in_array($r['status'],[302,303,307]),'Local form created through POST');
$row=$db->where(['library_id'=>4,'period_id'=>$meta['period'],'active_slot'=>1])->get('iplm_submissions')->row_array();$id=$row['id'];$r=req('/iplm/form/'.$id);ok($r['status']===200&&str_contains($r['body'],'name="f_npsn"')&&str_contains($r['body'],'bukti_dukung.xlsx')&&str_contains($r['body'],'data-iplm-panel'),'Form contains identity and supporting-evidence instructions');
$schema=json_decode($row['schema_json'],true);$values=json_decode($row['values_json'],true);$data=['version'=>$row['version'],'action'=>'draft','iplm_csrf'=>token('/iplm/form/'.$id)];foreach($schema as$f)$data['f_'.$f['code']]=$values[$f['code']]??'';$data['f_library_name']='<script>alert("fixture")</script>';$data['e_print_titles']='https://drive.google.com/fixture-proof';
$r=req('/iplm/form/'.$id,$data);ok(in_array($r['status'],[302,303,307]),'Draft saved over HTTP');$r=req('/iplm/form/'.$id);ok(str_contains($r['body'],'&lt;script&gt;')&&!str_contains($r['body'],'<script>alert("fixture")'),'Untrusted input escaped');
$r=req('/iplm',null,'central');ok(str_contains($r['body'],'1 perbedaan'),'District dashboard shows identity warning');
$master=$db->where('id',4)->get('libraries')->row_array();ok($master['name']!==$data['f_library_name'],'Master remains unchanged through HTTP');
$r=req('/iplm/export/'.$meta['period'].'/xlsx');$file=$directory.'/iplm-export.xlsx';file_put_contents($file,$r['body']);$zip=new ZipArchive();ok($r['status']===200&&$zip->open($file)===true,'Genuine Excel export');$xml=$zip->getFromName('xl/worksheets/sheet1.xml');$zip->close();ok(!str_contains($xml,'Pengisi B'),'Local export excludes foreign submission');
foreach(['/iplm/settings','/iplm/analysis/'.$meta['period'],'/library-types','/libraries/create','/libraries/edit/4','/libraries']as$path){$r=req($path,null,'central');ok($r['status']===200&&!str_contains($r['body'],'Severity:')&&!str_contains($r['body'],'Database Error'),'District renders '.$path);}
$r=req('/libraries/create',null,'central');ok(str_contains($r['body'],'library_subtype_id')&&str_contains($r['body'],'Perpustakaan SMP'),'Libraries form uses dependent subtypes');
ok(req('/libraries/update/4',[], 'central')['status']===403,'Master-library update also requires CSRF');
ok(req('/libraries/store',null,'central')['status']===405,'GET cannot create a master library');
$before=$db->where('id',4)->get('libraries')->row_array();$edit=$before;$edit['libraries_csrf']=token('/libraries/edit/4','central','libraries_csrf');$edit['library_subtype_id']=$db->where('code','kabupaten')->get('library_subtypes')->row()->id;
req('/libraries/update/4',$edit,'central');ok($db->where('id',4)->get('libraries')->row_array()===$before,'Invalid master type/subtype pair leaves library unchanged');
$edit=$before;$edit['libraries_csrf']=token('/libraries/edit/4','central','libraries_csrf');$edit['npp']='FIXTURE-NPP-4';$updated=req('/libraries/update/4',$edit,'central');ok(in_array($updated['status'],[302,303,307])&&$db->where('id',4)->get('libraries')->row()->npp==='FIXTURE-NPP-4','Library identity update persists valid subtype and NPP');
$r=req('/admin',null,'central');ok(str_contains($r['body'],'IPLM: perbedaan identitas'),'Main admin inbox includes IPLM differences');
// Permission revocation must affect an existing session immediately.
$page=$db->where('code','iplm.local')->get('sys_page')->row()->id;$role=$db->where('code','LIBRARY_ADMIN')->get('auth_role')->row()->id;$db->where(['page_id'=>$page,'role_id'=>$role])->update('auth_role_permission',['can_view'=>0]);ok(req('/iplm')['status']===403,'Module permission revocation effective immediately');$db->where(['page_id'=>$page,'role_id'=>$role])->update('auth_role_permission',['can_view'=>1]);
file_put_contents($directory.'/iplm-http.json',json_encode(['id'=>$id,'checks'=>$checks,'period'=>$meta['period']]));echo $checks," IPLM HTTP checks passed.\n";
