<?php
require __DIR__.'/library_network_bootstrap.php';require APPPATH.'models/Library_activation_model.php';
$dir=$argv[1]??'';network_check(preg_match('#^/tmp/pustaka_network_test_[a-zA-Z0-9_]+$#D',$dir)&&is_file($dir.'/connection.php'),'Isolated runtime required');$params=require $dir.'/connection.php';network_check(strpos($params['database'],'pustaka_network_test_')===0,'Test DB required');$db=DB($params);$db->db_debug=false;$fixture=json_decode(file_get_contents($dir.'/fixtures.json'),true);$meta=json_decode(file_get_contents($dir.'/task4-activation.json'),true);$checks=0;
function check4($v,$m){global$checks;network_check($v,'FAIL '.$m);$checks++;echo 'PASS '.$m,PHP_EOL;}
function req4($path,$data=null,$who='public'){global$dir;$c=curl_init('http://127.0.0.1:8798'.$path);curl_setopt_array($c,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_HEADER=>true,CURLOPT_COOKIEJAR=>$dir.'/task4-cookie-'.$who,CURLOPT_COOKIEFILE=>$dir.'/task4-cookie-'.$who,CURLOPT_TIMEOUT=>30]);if($data!==null)curl_setopt_array($c,[CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>http_build_query($data)]);$raw=curl_exec($c);network_check($raw!==false,'Request failed');$n=curl_getinfo($c,CURLINFO_HEADER_SIZE);$r=['status'=>in_array(curl_getinfo($c,CURLINFO_RESPONSE_CODE),[302,303,307],true)?302:curl_getinfo($c,CURLINFO_RESPONSE_CODE),'headers'=>substr($raw,0,$n),'body'=>substr($raw,$n)];curl_close($c);return$r;}
function tok4($path,$name,$who='public'){$r=req4($path,null,$who);network_check(preg_match('/name="'.$name.'" value="([a-f0-9]+)"/',$r['body'],$m),'Missing CSRF '.$path);return$m[1];}
check4(req4('/library-activation')['status']===302,'Anonymous cannot issue codes');check4(req4('/aktivasi-perpustakaan/klaim')['status']===405,'GET cannot claim');check4(req4('/aktivasi-perpustakaan/klaim',[])['status']===403,'Missing CSRF cannot claim');
req4('/auth/do_login',['identifier'=>'test-central','password'=>$fixture['password']],'central');$r=req4('/library-activation',null,'central');check4($r['status']===200&&strpos($r['body'],'/aktivasi-perpustakaan')!==false&&strpos($r['body'],'library-activation')!==false,'District activation page with sidebar/public shortcut');
check4(req4('/library-activation/issue',['library_id'=>22],'central')['status']===403,'Issue requires CSRF');$t=tok4('/library-activation','activation_admin_csrf','central');$r=req4('/library-activation/issue',['activation_admin_csrf'=>$t,'library_id'=>22],'central');check4($r['status']===302,'District issues code');$r=req4('/library-activation',null,'central');check4(preg_match('/id="issued-code"[^>]*value="([A-F0-9-]+)"/',$r['body'],$matches)===1,'Code displayed once to district admin');$once=$matches[1];check4(strpos(req4('/library-activation',null,'central')['body'],$once)===false,'Secret not displayed again');
req4('/auth/do_login',['identifier'=>'test-member','password'=>$fixture['password']],'member');check4(req4('/library-activation',null,'member')['status']===403,'Member cannot view activation management');check4(req4('/library-activation/issue',['library_id'=>24],'member')['status']===403,'Member cannot issue');
$t=tok4('/aktivasi-perpustakaan','activation_csrf');$base=['library_id'=>20,'activation_code'=>$meta['http']['code'],'activation_csrf'=>$t,'ownership'=>1];$bad=$base;$bad['activation_code']=str_repeat('0',32);$r=req4('/aktivasi-perpustakaan/klaim',$bad);check4($r['status']===302&&str_contains(req4('/aktivasi-perpustakaan')['body'],'tidak valid'),'Wrong code rejected with message');
$base['activation_csrf']=tok4('/aktivasi-perpustakaan','activation_csrf');$r=req4('/aktivasi-perpustakaan/klaim',$base);check4($r['status']===302&&str_contains($r['headers'],'library-workspace/account'),'Valid code establishes forced-password session');
check4(req4('/library-workspace/records/books')['status']===302,'Activation session cannot skip password setup');check4(req4('/library-workspace/loans',[])['status']===403,'Activation session cannot mutate operations');$r=req4('/library-workspace/account');check4($r['status']===200&&!str_contains($r['body'],'name="current_password"'),'Verified activation does not need old password');
$t=tok4('/library-workspace/account','network_csrf');$password='SchoolPersonal!Task4';$r=req4('/library-workspace/account',['network_csrf'=>$t,'password'=>$password,'confirmation'=>$password]);check4($r['status']===302,'New password saved');$user=$db->where('username',$meta['http']['username'])->get('auth_user')->row_array();check4(password_verify($password,$user['password_hash'])&&(int)$user['force_password_change']===0,'Password is personal and activation completed');check4(req4('/library-workspace')['status']===200,'Operational dashboard available after setup');check4(req4('/library-activation')['status']===403,'Activated local account cannot issue codes');check4(str_contains(req4('/library-workspace/account')['body'],'name="current_password"'),'Activation bypass consumed; next password change requires current password');
req4('/logout');$t=tok4('/aktivasi-perpustakaan','activation_csrf');$r=req4('/aktivasi-perpustakaan/klaim',array_replace($base,['activation_csrf'=>$t]));check4($r['status']===302&&str_contains(req4('/aktivasi-perpustakaan')['body'],'sudah pernah digunakan'),'Reclaim rejected after logout');$r=req4('/auth/do_login',['identifier'=>$meta['http']['username'],'password'=>$password]);check4($r['status']===302&&str_contains($r['headers'],'library-workspace'),'Personal password login works');
req4('/logout');$t=tok4('/aktivasi-perpustakaan','activation_csrf');$r=req4('/aktivasi-perpustakaan/klaim',['library_id'=>2,'activation_code'=>$once,'ownership'=>1,'activation_csrf'=>$t]);check4(str_contains(req4('/aktivasi-perpustakaan')['body'],'tidak dapat diaktivasi'),'Central library blocked on public endpoint');
$t=tok4('/library-activation','activation_admin_csrf','central');req4('/library-activation/revoke',['library_id'=>22,'activation_admin_csrf'=>$t],'central');check4(strtotime($db->where('library_id',22)->get('library_activation_codes')->row()->expires_at)<=time(),'District revocation persisted');
$query=req4('/aktivasi-perpustakaan/cari?q=MAKTABAH');$json=json_decode($query['body'],true);check4($query['status']===200&&count($json['results'])===1&&!str_contains($query['body'],'password')&&!str_contains($query['body'],'token_hash'),'Imported private school searchable without exposing secrets');
$m=new Library_activation_model();$m->db=$db;$expired=$m->issue(24,9000004);$badUser=$db->where('library_id',24)->get('auth_user')->row_array();$db->where('id',$badUser['id'])->update('auth_user',['status'=>'inactive']);$t=tok4('/aktivasi-perpustakaan','activation_csrf');req4('/aktivasi-perpustakaan/klaim',['library_id'=>24,'activation_code'=>$expired['code'],'ownership'=>1,'activation_csrf'=>$t]);check4(req4('/library-workspace')['status']===302,'Disabled activation does not grant login');
$t=tok4('/library-activation','activation_admin_csrf','central');req4('/library-activation/issue',['library_id'=>20,'activation_admin_csrf'=>$t],'central');check4(!str_contains(req4('/library-activation',null,'central')['body'],'id="issued-code"'),'District cannot reissue a claimed school');
file_put_contents($dir.'/task4-http.json',json_encode(['checks'=>$checks,'username'=>$meta['http']['username'],'password'=>$password]));echo $checks," task4 HTTP checks passed.\n";
