<?php
require __DIR__.'/library_network_bootstrap.php';
$dir=$argv[1]??'';network_check(preg_match('#^/tmp/pustaka_network_test_[a-zA-Z0-9_]+$#D',$dir)&&is_file($dir.'/connection.php'),'Private fixture required');$params=require $dir.'/connection.php';network_check(strpos($params['database'],'pustaka_network_test_')===0,'Isolated DB required');$db=DB($params);$db->db_debug=false;$fixture=json_decode(file_get_contents($dir.'/fixtures.json'),true);$checks=0;$run=bin2hex(random_bytes(3));
$target=(int)$db->query("SELECT l.id FROM libraries l LEFT JOIN auth_user u ON u.library_id=l.id WHERE l.id>16 AND l.status='active' AND u.id IS NULL ORDER BY l.id LIMIT 1")->row()->id;
$adminPath='/library-activation?q='.rawurlencode($db->where('id',$target)->get('libraries')->row()->code);
function h6ok($v,$m){global$checks;network_check($v,'FAIL '.$m);$checks++;echo 'PASS '.$m.PHP_EOL;}
function h6req($path,$data=null,$who='public'){
 global$dir,$run;$c=curl_init('http://127.0.0.1:8797'.$path);curl_setopt_array($c,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_HEADER=>true,CURLOPT_COOKIEJAR=>$dir.'/task6-'.$run.'-cookie-'.$who,CURLOPT_COOKIEFILE=>$dir.'/task6-'.$run.'-cookie-'.$who,CURLOPT_TIMEOUT=>20]);if($data!==null)curl_setopt_array($c,[CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>http_build_query($data)]);$raw=curl_exec($c);network_check($raw!==false,'Local request failed');$size=curl_getinfo($c,CURLINFO_HEADER_SIZE);$status=curl_getinfo($c,CURLINFO_RESPONSE_CODE);curl_close($c);return['status'=>$status,'headers'=>substr($raw,0,$size),'body'=>substr($raw,$size)];
}
function h6token($path,$name,$who){$r=h6req($path,null,$who);network_check($r['status']===200&&preg_match('/name="'.preg_quote($name,'/').'" value="([a-f0-9]+)"/',$r['body'],$m),'Token missing '.$name);return$m[1];}
$input=['library_id'=>(string)$target,'registrant_name'=>'Pengelola HTTP Task6','registrant_phone'=>'081234567899','password'=>'SelfSignup!Task6','confirmation'=>'SelfSignup!Task6','ownership'=>'1'];
h6ok(h6req('/aktivasi-perpustakaan/klaim')['status']===405,'Claim is POST-only');h6ok(h6req('/aktivasi-perpustakaan/klaim',$input)['status']===403,'Missing public CSRF rejected');
$input['activation_csrf']=h6token('/aktivasi-perpustakaan','activation_csrf','public');$bad=$input;$bad['confirmation']='mismatch';h6req('/aktivasi-perpustakaan/klaim',$bad);h6ok($db->where('library_id',$target)->count_all_results('auth_user')===0,'Invalid HTTP input creates no account');
$input['activation_csrf']=h6token('/aktivasi-perpustakaan','activation_csrf','public');$r=h6req('/aktivasi-perpustakaan/klaim',$input);h6ok(in_array($r['status'],[302,303,307],true)&&strpos($r['headers'],'library-workspace')!==false,'Self-registration logs in without any county action');
$user=$db->where('library_id',$target)->get('auth_user')->row_array();h6ok($user&&$user['force_password_change']==='0','Personal password ready on first login');
$dashboard=h6req('/library-workspace');h6ok($dashboard['status']===200&&strpos($dashboard['body'],$user['username'])!==false,'Dashboard shows username after signup');
h6ok(h6req('/library-workspace?library_id='.($target+2))['status']===403,'Self-registered account cannot switch library');h6ok(h6req('/library-activation')['status']===403,'Local account cannot moderate');
$other=$input;$other['activation_csrf']=h6token('/aktivasi-perpustakaan','activation_csrf','other');h6req('/aktivasi-perpustakaan/klaim',$other,'other');h6ok($db->where('library_id',$target)->count_all_results('auth_user')===1,'Other browser cannot reclaim same library');
$search=h6req('/aktivasi-perpustakaan/cari?q='.rawurlencode('SD NEGERI'),null,'search');h6ok($search['status']===200&&strpos($search['body'],'registrant_phone')===false&&strpos($search['body'],'password')===false,'Public search never returns registration contacts/passwords');
h6req('/auth/do_login',['identifier'=>'test-central','password'=>$fixture['password']],'central');
$token=h6token($adminPath,'activation_admin_csrf','central');
h6ok(h6req('/library-activation/moderate',['library_id'=>$target,'user_id'=>$user['id'],'action'=>'reset','note'=>'Fixture check'],'central')['status']===403,'Moderation requires CSRF');
$r=h6req('/library-activation/moderate',['activation_admin_csrf'=>$token,'library_id'=>$target,'user_id'=>$user['id'],'action'=>'reset','note'=>'Fixture confirmed owner'],'central');h6ok(in_array($r['status'],[302,303,307],true),'County reset succeeds');
$reset=h6req('/library-activation',null,'central');network_check(preg_match('/id="reset-password"[^>]*value="([^"]+)"/',$reset['body'],$match),'Temporary password not displayed');$temporary=html_entity_decode($match[1],ENT_QUOTES,'UTF-8');
h6ok(strpos(h6req('/library-activation',null,'central')['body'],'id="reset-password"')===false,'Temporary password shown once only');
$oldSession=h6req('/library-workspace');h6ok(in_array($oldSession['status'],[302,303,307],true),'Reset invalidates previous local session');
$login=h6req('/auth/do_login',['identifier'=>$user['username'],'password'=>$temporary],'new');h6ok(strpos($login['headers'],'library-workspace/account')!==false,'Temporary password forces personal password change');
$token=h6token('/library-workspace/account','network_csrf','new');h6req('/library-workspace/account',['network_csrf'=>$token,'current_password'=>$temporary,'password'=>'Changed!Task6Personal','confirmation'=>'Changed!Task6Personal'],'new');h6ok(h6req('/library-workspace',null,'new')['status']===200,'Reset owner can set password and use scoped dashboard');
$token=h6token($adminPath,'activation_admin_csrf','central');h6req('/library-activation/moderate',['activation_admin_csrf'=>$token,'library_id'=>$target,'user_id'=>$user['id'],'action'=>'suspend','note'=>'Fixture disputed ownership'],'central');$blocked=h6req('/library-workspace',null,'new');h6ok($blocked['status']===403||(in_array($blocked['status'],[302,303,307],true)&&strpos($blocked['headers'],'/login')!==false),'Suspension stops an already authenticated session');
$other['activation_csrf']=h6token('/aktivasi-perpustakaan','activation_csrf','third');h6req('/aktivasi-perpustakaan/klaim',$other,'third');h6ok($db->where('id',$user['id'])->get('auth_user')->row()->status==='inactive','Public claim cannot undo suspension');
$token=h6token($adminPath,'activation_admin_csrf','central');h6req('/library-activation/moderate',['activation_admin_csrf'=>$token,'library_id'=>$target,'user_id'=>$user['id'],'action'=>'restore','note'=>'Fixture dispute resolved'],'central');h6ok($db->where('id',$user['id'])->get('auth_user')->row()->status==='active','County restore works');
$public=h6req('/aktivasi-perpustakaan',null,'fourth');h6ok(strpos($public['body'],'name="activation_code"')===false&&strpos($public['body'],'name="password"')!==false,'Public form no longer requests county code');
file_put_contents($dir.'/task6-http-results.json',json_encode(['checks'=>$checks]));echo $checks.' HTTP checks passed.'.PHP_EOL;
