<?php
require __DIR__.'/test_library_network_http.php';
$baseChecks=$checks;$service=json_decode(file_get_contents($directory.'/services.json'),true);login('test-school-a',$new);
function service_csrf($path='/library-services/stock',$who='a',$field='service_csrf'){$r=request($path,null,$who);network_check($r['status']===200,'Form unavailable '.$path);network_check(preg_match('/name="'.$field.'" value="([a-f0-9]+)"/',$r['body'],$m),'Token missing '.$path);return $m[1];}
ok(request('/jejaring/daftar/4')['status']===200,'Local operator can preview own public registration');
ok(request('/jejaring/daftar/6')['status']===403,'Local operator public form remains scoped');
foreach(['stock','labels','cards','registrations','reservations','kiosk']as $path){$r=request('/library-services/'.$path);ok($r['status']===200&&strpos($r['body'],'A PHP Error')===false&&strpos($r['body'],'An uncaught Exception')===false,'Local service renders '.$path);}
foreach(['/library-services/stock?library_id=6','/library-services/stock?source=legacy','/library-services/cards?library_id=6','/library_services/stock?source=legacy']as $path)ok(request($path)['status']===403,'Scope bypass rejected '.$path);
ok(request('/library-services/stock?library_id%5B%5D=6')['status']===400,'Malformed scope rejected');
ok(request('/library-services/stock',null,'test-member')['status']===403,'Ordinary member cannot access operator services');
ok(request('/library-services/stock',null,'fresh-anonymous')['status']===302,'Anonymous operator access redirects login');
ok(request('/library-services/stock',['title'=>'No CSRF'])['status']===403,'Stock CSRF required');
$r=request('/library-services/stock',['service_csrf'=>service_csrf(),'title'=>'HTTP snapshot','library_id'=>6,'source'=>'legacy']);$stock=$db->where('title','HTTP snapshot')->order_by('id','DESC')->get('library_stock_sessions')->row_array();ok($r['status']===302&&$stock&&$stock['library_id']==4&&$stock['source']==='network','Posted owner/source cannot reassign stock');
$detail='/library-services/stock/'.$stock['id'];$r=request($detail);ok($r['status']===200&&strpos($r['body'],'Belum ditemukan')!==false,'Stock detail renders counts');
ok(request($detail,['service_csrf'=>service_csrf($detail),'action'=>'scan','barcode'=>'ST-'.$service['tag'],'observed'=>'good','note'=>'HTTP scan'])['status']===302,'Stock scan form accepted');
$row=$db->where('session_id',$stock['id'])->where('item_id',$service['i'])->get('library_stock_entries')->row_array();ok($row['observed']==='good','Stock scan persisted');
$r=request($detail.'/csv');ok($r['status']===200&&strpos($r['body'],'ST-'.$service['tag'])!==false&&strpos($r['body'],'Fixture B PRIVATE')===false,'CSV snapshot export scoped');
$r=request($detail.'/xlsx');$path=$directory.'/stock.xlsx';file_put_contents($path,$r['body']);$z=new ZipArchive();ok($z->open($path)===true&&$z->locateName('xl/worksheets/sheet1.xml')!==false,'Stock export genuine XLSX');$z->close();
$r=request($detail.'/print');ok($r['status']===200&&strpos($r['body'],'Berita Acara Pemeriksaan')!==false,'Stock printable report');
ok(request('/library-services/stock/'.$service['ls'])['status']===404,'Legacy session ID inaccessible through local source');
request($detail,['service_csrf'=>service_csrf($detail),'action'=>'closed','note'=>'HTTP verified']);ok($db->where('id',$stock['id'])->get('library_stock_sessions')->row()->status==='closed','Stock session closed via HTTP');
foreach(['labels','cards']as $path){$r=request('/library-services/'.$path.'?print=1');ok($r['status']===200&&strpos($r['body'],'data-qr=')!==false&&strpos($r['body'],'PRIVATE')===false,'Scoped printable '.$path);}
$r=request('/library-services/cards?print=1');ok(strpos($r['body'],'birth_date')===false&&strpos($r['body'],'Status saat cetak')!==false,'Cards include status without extra private demographics');
// Public registration then review. No production personal data used.
$public='/jejaring/daftar/4';$token=service_csrf($public,'public','public_service_csrf');$r=request($public,['public_service_csrf'=>$token,'kind'=>'new','full_name'=>'Online <script>fixture</script>','birth_date'=>'2012-01-02','gender'=>'P','phone'=>'','email'=>'','address'=>'Fixture address','consent'=>'1','library_id'=>6],'public');
ok($r['status']===302,'Public registration accepted into review queue');$reg=$db->where('full_name','Online <script>fixture</script>')->order_by('id','DESC')->get('network_registrations')->row_array();ok($reg&&$reg['library_id']==4&&$reg['status']==='pending'&&!$reg['member_id'],'Registration scope fixed and member not auto-created');
ok(request($public,['public_service_csrf'=>$token,'kind'=>'new'],'public')['status']===403,'Public CSRF replay rejected');
$r=request('/library-services/registrations');ok(strpos($r['body'],'Online &lt;script&gt;fixture&lt;/script&gt;')!==false,'Registration XSS escaped');
login('test-school-b',$fixture['password'],'b');$r=request('/library-services/registrations',['service_csrf'=>service_csrf('/library-services/stock','b'),'id'=>$reg['id'],'decision'=>'approved','expires_on'=>date('Y-m-d',strtotime('+1 year')),'note'=>'Foreign review'],'b');ok($db->where('id',$reg['id'])->get('network_registrations')->row()->status==='pending','Foreign registration approval blocked');
$payload=['service_csrf'=>service_csrf(),'id'=>$reg['id'],'decision'=>'approved','expires_on'=>date('Y-m-d',strtotime('+1 year')),'note'=>'Identity checked'];request('/library-services/registrations',$payload);$reviewed=$db->where('id',$reg['id'])->get('network_registrations')->row_array();ok($reviewed['status']==='approved'&&$reviewed['member_id'],'Approval creates local membership');$member=$db->where('id',$reviewed['member_id'])->get('network_members')->row_array();ok($member['library_id']==4&&$db->where('library_id',4)->where('member_id',$member['id'])->count_all_results('network_membership_terms')===1,'Approved member gets explicit validity term');
$before=$db->count_all('network_members');request('/library-services/registrations',array_replace($payload,['service_csrf'=>service_csrf()]));ok($db->count_all('network_members')===$before,'Approval cannot be repeated to duplicate member');
$renew=['public_service_csrf'=>service_csrf($public,'public','public_service_csrf'),'kind'=>'renewal','member_no'=>$member['member_no'],'full_name'=>$member['full_name'],'birth_date'=>'2012-01-02','gender'=>'P','consent'=>'1'];request($public,$renew,'public');$renewal=$db->where('kind','renewal')->order_by('id','DESC')->get('network_registrations')->row_array();request('/library-services/registrations',['service_csrf'=>service_csrf(),'id'=>$renewal['id'],'decision'=>'approved','expires_on'=>date('Y-m-d',strtotime('+2 years')),'note'=>'Renewal identity checked']);ok($db->where('id',$renewal['id'])->get('network_registrations')->row()->status==='approved'&&$db->count_all('network_members')===$before,'Renewal extends existing membership without duplicate');
// Kiosk URL shown only immediately after creation, no public directory of members.
request('/library-services/kiosk',['service_csrf'=>service_csrf(),'action'=>'create']);$r=request('/library-services/kiosk');network_check(preg_match('#/jejaring/tamu/([a-f0-9]{64})#',$r['body'],$match),'Kiosk URL missing');$token=$match[1];$publicKiosk='/jejaring/tamu/'.$token;
$r=request($publicKiosk,null,'public');ok($r['status']===200&&strpos($r['body'],'Anggota Uji A')===false&&strpos($r['body'],'Fixture B PRIVATE')===false,'Public kiosk renders without member directory');
$guest='HTTP kiosk guest '.bin2hex(random_bytes(4));
$r=request($publicKiosk,['public_service_csrf'=>service_csrf($publicKiosk,'public','public_service_csrf'),'guest_name'=>$guest,'purpose'=>'Layanan digital','channel'=>'online','library_id'=>6],'public');$visit=$db->where('guest_name',$guest)->order_by('id','DESC')->get('network_visits')->row_array();ok($r['status']===302&&$visit&&$visit['library_id']==4&&$visit['channel']==='offline','Digital service kiosk forced offline and token-owned library');
$before=$db->count_all('network_visits');request($publicKiosk,['public_service_csrf'=>service_csrf($publicKiosk,'public','public_service_csrf'),'guest_name'=>$guest,'purpose'=>'Layanan digital'],'public');ok($db->count_all('network_visits')===$before,'Kiosk duplicate visit suppressed');
ok(request($publicKiosk)['status']===200,'Local operator can open own kiosk monitor');
ok(request($publicKiosk,null,'b')['status']===403,'Other local operator cannot use foreign kiosk token');
$k=$db->where('token_hash',hash('sha256',$token))->get('network_kiosks')->row_array();request('/library-services/kiosk',['service_csrf'=>service_csrf(),'action'=>'revoke','id'=>$k['id']]);ok(request($publicKiosk,null,'public')['status']===404,'Revoked public kiosk no longer usable');
$r=request('/library-services/stock?library_id=2&source=legacy',null,'test-central');ok($r['status']===200&&strpos($r['body'],'Legacy stock')!==false,'Central admin operates legacy collection stock');
$r=request('/library-services/stock',null,'test-legacy');ok($r['status']===200,'Kabupaten ADMIN has stock access');
$role=$db->where('code','ADMIN')->get('auth_role')->row()->id;$page=$db->where('code','library.services')->get('sys_page')->row()->id;
$db->where('role_id',$role)->where('page_id',$page)->update('auth_role_permission',['can_export'=>0]);request('/logout',null,'test-legacy');login('test-legacy',$fixture['password'],'test-legacy');ok(request('/library-services/stock/'.$service['ls'].'/xlsx?library_id=2&source=legacy',null,'test-legacy')['status']===403,'Export permission enforced separately');$db->where('role_id',$role)->where('page_id',$page)->update('auth_role_permission',['can_export'=>1]);
$db->where('id',9000008)->update('auth_user',['library_id'=>2]);request('/logout',null,'test-legacy');login('test-legacy',$fixture['password'],'test-legacy');ok(request('/library-services/stock?library_id=4',null,'test-legacy')['status']===403,'Assigned kabupaten operator cannot select foreign scope');$db->where('id',9000008)->update('auth_user',['library_id'=>null]);
$db->where('role_id',$role)->where('page_id',$page)->update('auth_role_permission',['can_approve'=>0]);request('/logout',null,'test-legacy');login('test-legacy',$fixture['password'],'test-legacy');
$approvalToken=service_csrf('/library-services/stock?library_id=4&source=network','test-legacy');ok(request('/library-services/registrations?library_id=4&source=network',['service_csrf'=>$approvalToken,'id'=>$reg['id'],'decision'=>'approved','note'=>'Should not execute'],'test-legacy')['status']===403,'Central approval requires approve permission, not only edit');$db->where('role_id',$role)->where('page_id',$page)->update('auth_role_permission',['can_approve'=>1]);
echo ($checks-$baseChecks)," new service HTTP checks passed; ",$checks," including authentication regression.\n";
