<?php
require __DIR__.'/library_network_bootstrap.php';foreach(['Library_exchange_model','Library_network_model','Library_fines_model'] as $class)require APPPATH.'models/'.$class.'.php';
$dir=$argv[1]??'';network_check(preg_match('#^/tmp/pustaka_network_test_[a-zA-Z0-9_]+$#D',$dir)&&is_file($dir.'/connection.php'),'Private test directory required.');$params=require $dir.'/connection.php';network_check(strpos($params['database'],'pustaka_network_test_')===0,'Only fixture database allowed.');$db=DB($params);$db->db_debug=false;$x=new Library_exchange_model();$n=new Library_network_model();$f=new Library_fines_model();foreach([$x,$n,$f] as $model)$model->db=$db;
if(($argv[2]??'')==='--worker'){
    while(microtime(true)<(float)$argv[3])usleep(1000);
    try{if($argv[4]==='approve')$x->act(6,(int)$argv[5],'approve','Concurrent approval','',9000002,true);elseif($argv[4]==='issue')$n->issue(6,$argv[5],$argv[6],9000002);else $f->act(4,(int)$argv[5],'payment','70','Concurrent proof '.$argv[6],'Verified payment',0,9000000,true);echo 'accepted';}catch(Throwable $e){echo 'rejected';}exit;
}
$parallel=function($tasks)use($dir){$start=microtime(true)+.4;$jobs=[];foreach($tasks as $task){$process=proc_open(array_merge([PHP_BINARY,__FILE__,$dir,'--worker',(string)$start],$task),[0=>['file','/dev/null','r'],1=>['pipe','w'],2=>['pipe','w']],$pipes);$jobs[]=[$process,$pipes];}$outputs=[];foreach($jobs as [$process,$pipes]){$outputs[]=stream_get_contents($pipes[1]);$error=stream_get_contents($pipes[2]);fclose($pipes[1]);fclose($pipes[2]);network_check(proc_close($process)===0&&$error==='','Worker failed.');}sort($outputs);network_check($outputs===['accepted','rejected'],'Concurrent writes not exclusive.');};
$tag=bin2hex(random_bytes(4));$book=$n->save(6,'books',0,['title'=>'Concurrency '.$tag,'format'=>'physical','status'=>'published'],9000002);$item=$n->save(6,'items',0,['book_id'=>$book,'barcode'=>'CX-'.$tag,'status'=>'available'],9000002);$due=date('Y-m-d',strtotime('+10 days'));
$a=$x->request(4,6,'network',$item,$due,'From A',9000000);$b=$x->request(8,6,'network',$item,$due,'Central on behalf of C',9000004);$parallel([['approve',(string)$a],['approve',(string)$b]]);$held=$db->where('item_id',$item)->where('source','network')->where('active_slot',1)->get('inter_library_loans')->result_array();network_check(count($held)===1,'Duplicate active hold.');$x->act(6,$held[0]['id'],'cancel','Test complete','',9000002,true);echo "PASS two approvals competing for one item: exactly one hold.\n";
$member='CM-'.$tag;$n->save(6,'members',0,['member_no'=>$member,'full_name'=>'Concurrent borrower','status'=>'active'],9000002);$item2=$n->save(6,'items',0,['book_id'=>$book,'barcode'=>'CY-'.$tag,'status'=>'available'],9000002);$c=$x->request(4,6,'network',$item2,$due,'Concurrent ordinary issue',9000000);$parallel([['approve',(string)$c],['issue',$member,'CY-'.$tag]]);$count=(int)$db->where('source','network')->where('item_id',$item2)->where('active_slot',1)->count_all_results('inter_library_loans')+(int)$db->where('library_id',6)->where('item_id',$item2)->where('returned_at IS NULL',null,false)->count_all_results('network_loans');network_check($count===1,'Institutional and ordinary circulation overlap.');echo "PASS ordinary issue versus institutional approval: no double loan.\n";
$loan=$db->where('library_id',4)->get('network_loans')->row_array();$fine=$f->create(4,'network',$loan['id'],100,'Concurrent ledger',9000000,true);$parallel([['pay',(string)$fine,'A'],['pay',(string)$fine,'B']]);$events=$f->events(4,$fine,true);network_check(count($events)===1&&(int)$events[0]['amount']===70,'Concurrent overpayment recorded.');echo "PASS simultaneous manual payments cannot exceed balance.\n";
echo "3 exchange/fine concurrency checks passed.\n";
