<?php
$status_labels=['PENDING'=>'Menunggu','SENDING'=>'Diproses','SENT'=>'Terkirim','FAILED'=>'Gagal','CANCELLED'=>'Dibatalkan'];
$status_classes=['PENDING'=>'bg-yellow-lt text-yellow','SENDING'=>'bg-blue-lt text-blue','SENT'=>'bg-green-lt text-green','FAILED'=>'bg-red-lt text-red','CANCELLED'=>'bg-secondary-lt text-secondary'];
?>
<div class="page-header"><div class="container-xl"><div class="page-pretitle">WA Center</div><h1 class="page-title">Antrian & Riwayat Pengiriman</h1><div class="text-secondary mt-1">Pesan otomatis dan manual dikirim oleh WA Engine secara berurutan. Pesan gagal menampilkan penyebabnya di bawah.</div></div></div>
<div class="page-body"><div class="container-xl">
  <?php if($this->session->flashdata('success')):?><div class="alert alert-success"><?=html_escape($this->session->flashdata('success'))?></div><?php endif?>
  <?php if($this->session->flashdata('error')):?><div class="alert alert-danger"><?=html_escape($this->session->flashdata('error'))?></div><?php endif?>
  <?php if(!empty($can_create)):?><div class="card mb-3"><div class="card-header"><h3 class="card-title"><i class="ti ti-send me-2"></i>Kirim pesan manual</h3></div><?=form_open('wa/outbox')?><div class="card-body"><div class="row g-3 align-items-end"><div class="col-md-3"><label class="form-label">Nomor WhatsApp</label><input class="form-control" name="phone" inputmode="tel" required placeholder="628xxxxxxxxxx"><div class="form-hint">Nomor Indonesia, tanpa tanda +.</div></div><div class="col-md-7"><label class="form-label">Isi pesan</label><textarea class="form-control" name="message" rows="2" required placeholder="Tulis pesan untuk pemustaka…"></textarea></div><div class="col-md-2"><button class="btn btn-primary w-100"><i class="ti ti-send-2 me-1"></i>Masukkan antrian</button></div></div></div><?=form_close()?></div><?php endif?>
  <div class="card"><div class="card-header"><h3 class="card-title"><i class="ti ti-history me-2"></i>200 pengiriman terbaru</h3><div class="card-actions"><a href="<?=base_url('wa/settings')?>" class="btn btn-outline-primary btn-sm"><i class="ti ti-settings me-1"></i>Pengaturan WA</a></div></div><div class="table-responsive"><table class="table table-vcenter card-table"><thead><tr><th>Waktu</th><th>Tujuan / Jenis</th><th>Pesan</th><th>Status</th><th>Catatan Engine</th></tr></thead><tbody>
  <?php if(empty($rows)):?><tr><td colspan="5" class="py-5 text-center text-secondary"><i class="ti ti-message-off fs-1 d-block mb-2"></i>Belum ada pesan dalam antrian atau riwayat pengiriman.</td></tr><?php endif?>
  <?php foreach($rows as $r):$state=$r['status']??'PENDING';?><tr><td class="text-nowrap"><div><?=!empty($r['sent_at'])?date('d M Y H:i',strtotime($r['sent_at'])):date('d M Y H:i',strtotime($r['created_at']))?></div><div class="text-secondary small"><?=!empty($r['sent_at'])?'terkirim':'dibuat'?></div></td><td><div class="fw-semibold"><?=html_escape($r['recipient_name']?:$r['phone_number'])?></div><div class="text-secondary small"><code><?=html_escape($r['phone_number'])?></code> · <?=html_escape($r['event_code'])?></div></td><td class="text-wrap" style="min-width:260px"><?=nl2br(html_escape(mb_strimwidth((string)$r['message'],0,220,'…')))?></td><td><span class="badge <?=$status_classes[$state]??'bg-secondary-lt text-secondary'?>"><?=html_escape($status_labels[$state]??$state)?></span><?php if((int)($r['retry_count']??0)>0):?><div class="text-secondary small mt-1"><?= (int)$r['retry_count']?>x percobaan</div><?php endif?></td><td class="small"><span class="<?=$state==='FAILED'?'text-danger':'text-secondary'?>"><?=html_escape($r['error_message']?:($state==='SENT'?'Pesan diterima WA Engine.':'—'))?></span></td></tr><?php endforeach?>
  </tbody></table></div></div>
</div></div>
