<?php
$this->load->view('iplm/header',get_defined_vars());
$editable=$may_edit&&$in_scope&&$period['state']!=='closed'&&(!$local||in_array($row['status'],['draft','revision'],true));
$type_names=array_column($types,'name','id');$sub_names=array_column($subtypes,'name','id');$labels=array_column($row['schema'],'label','code');
$display=function($key,$value)use($type_names,$sub_names){return $key==='library_type_id'?($type_names[$value]??$value):($key==='library_subtype_id'?($sub_names[$value]??$value):$value);};
$groups=[];foreach($sections as$section=>$title){$group=array_filter($row['schema'],function($f)use($section){return $f['section']===$section;});if($group)$groups[$section]=['title'=>$title,'fields'=>$group];}
?>
<?php if(!$in_scope): ?><div class="alert alert-warning">Perpustakaan di luar cakupan IPLM kabupaten. Isian lama hanya ditampilkan sebagai riwayat dan tidak masuk rekap/perhitungan.</div><?php endif; ?>
<div class="card card-body mb-3"><h2><?= html_escape($library['name']); ?></h2><div><?= html_escape($period['title'].' · '.$period['start_date'].' — '.$period['end_date']); ?> <span class="badge bg-blue-lt"><?= html_escape($row['status']); ?></span></div><p class="text-secondary mb-0 mt-2">Identitas otomatis berasal dari /libraries. Koreksi di sini tidak mengubah data induk. Kosong berarti belum diketahui, bukan nol. Nominal dalam rupiah penuh tanpa titik/koma. Bukti disimpan di Drive masing-masing; pastikan petugas verifikasi diberi izin membaca tanpa membuka data pribadi ke publik.</p><?php if($row['review_note']): ?><div class="alert alert-info mt-3 mb-0">Catatan petugas: <?= html_escape($row['review_note']); ?></div><?php endif; ?></div>
<?php if($differences): ?><div class="alert alert-warning"><strong>Ada perbedaan identitas.</strong> Pilihan yang benar harus diverifikasi petugas; data induk belum diubah.</div><div class="card mb-3"><div class="table-responsive"><table class="table"><thead><tr><th>Isian</th><th>Data induk saat ini</th><th>Usulan pada form</th><th>Verifikasi</th></tr></thead><tbody><?php foreach($differences as$k=>$d): ?><tr><td><?= html_escape($labels[$k]??$k); ?></td><td><?= html_escape($display($k,$d['master'])); ?></td><td><?= html_escape($display($k,$d['value'])); ?></td><td><?= $d['resolved']?'Sudah diverifikasi untuk laporan':'Belum diverifikasi'; ?><?php if(!$local&&$may_approve): ?><form method="post" action="<?= base_url('iplm/review/'.(int)$row['id']); ?>" class="mt-2"><input type="hidden" name="iplm_csrf" value="<?= html_escape($csrf); ?>"><input type="hidden" name="version" value="<?= (int)$row['version']; ?>"><input type="hidden" name="action" value="resolve"><input type="hidden" name="field" value="<?= html_escape($k); ?>"><select name="choice" class="form-select form-select-sm mb-2" required><option value="">Pilih hasil pemeriksaan</option><option value="form">Isian benar untuk laporan; induk tetap</option><option value="master">Data induk benar; koreksi isian</option></select><input class="form-control form-control-sm mb-2" name="note" placeholder="Dasar/bukti verifikasi" maxlength="2000" required><button class="btn btn-sm btn-warning">Catat keputusan</button></form><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div></div><?php endif; ?>
<form method="post" id="iplm-form"><input type="hidden" name="iplm_csrf" value="<?= html_escape($csrf); ?>"><input type="hidden" name="version" value="<?= (int)$row['version']; ?>">
<?php if(array_sum($reference)>0): ?><div class="alert alert-info d-block"><strong>Referensi koleksi tercatat di aplikasi saat ini</strong><div>Judul cetak: <?= (int)$reference['print_titles']; ?> · Eksemplar cetak: <?= (int)$reference['print_copies']; ?> · Judul digital: <?= (int)$reference['digital_titles']; ?></div><p class="mb-2 mt-1">Ini data katalog jejaring perpustakaan ini, belum tentu seluruh koleksi atau kondisi akhir periode. Penambahan tahunan dan lisensi/eksemplar digital tidak dapat disimpulkan dari tanggal input katalog.</p><?php if($editable): ?><button type="button" class="btn btn-sm btn-outline-primary" id="use-collection-reference">Gunakan angka tercatat setelah saya periksa</button><?php endif; ?></div><?php endif; ?>
<div class="iplm-tabs" role="tablist" aria-label="Bagian formulir IPLM" data-iplm-tabs><?php $first=true;foreach($groups as$section=>$group): ?><button type="button" role="tab" id="tab-<?= html_escape($section); ?>" aria-controls="panel-<?= html_escape($section); ?>" aria-selected="<?= $first?'true':'false'; ?>"><?= html_escape($group['title']); ?> <span class="ms-1 opacity-75"><?= count($group['fields']); ?></span></button><?php $first=false;endforeach; ?></div>
<?php foreach($groups as$section=>$group): ?>
<section class="card mb-3" id="panel-<?= html_escape($section); ?>" role="tabpanel" aria-labelledby="tab-<?= html_escape($section); ?>" data-iplm-panel><div class="card-header"><div><h3 class="card-title"><?= html_escape($group['title']); ?></h3><div class="iplm-section-caption">Isian di sebelah kiri · keterangan dokumen bukti di sebelah kanan</div></div></div><div class="card-body">
<?php if($section==='evidence'): ?><div class="alert alert-info">Cukup satu tautan folder Google Drive untuk seluruh indikator. Kelompokkan dokumen di dalam folder menurut Koleksi, Tenaga, Pelayanan, dan Pengelolaan; pastikan admin dapat membacanya.</div><?php endif; ?>
<?php if($section==='evidence'&&array_filter($row['evidence'])): ?><details class="mb-3"><summary>Arsip tautan lama (tidak perlu diisi ulang)</summary><ul><?php foreach($row['evidence'] as$legacy_key=>$legacy_url): if(!preg_match('#^https://#i',(string)$legacy_url))continue; ?><li><a href="<?= html_escape($legacy_url); ?>" target="_blank" rel="noopener noreferrer"><?= html_escape($labels[$legacy_key]??$legacy_key); ?></a></li><?php endforeach; ?></ul></details><?php endif; ?>
<?php foreach($group['fields'] as$f): $k=$f['code'];$value=$row['values'][$k]??'';$isnum=in_array($f['kind'],['number','money'],true); ?>
<div class="iplm-field-row"><div><label class="form-label" for="f_<?= html_escape($k); ?>"><?php if($f['excel_column']): ?><span class="badge bg-secondary-lt me-1"><?= html_escape($f['excel_column']); ?></span><?php endif; ?><?= html_escape($k==='evidence_url'?'Satu tautan folder bukti dukung':$f['label']); ?><?= $f['is_required']?' *':''; ?></label>
<?php if($f['kind']==='select'): ?>
<select id="f_<?= html_escape($k); ?>" name="f_<?= html_escape($k); ?>" class="form-select" <?= !$editable?'disabled':''; ?>><option value="">Belum diisi</option><?php
$options=[];if($k==='library_type_id')foreach($types as$t)$options[]=['value'=>$t['id'],'label'=>$t['name'],'parent'=>null];elseif($k==='library_subtype_id')foreach($subtypes as$t)$options[]=['value'=>$t['id'],'label'=>$t['name'].(!$t['iplm_eligible']?' (lokal)':''),'parent'=>$t['library_type_id']];else foreach(json_decode($f['options_json']??'[]',true)?:[]as$o)$options[]=['value'=>$o,'label'=>$o,'parent'=>null];
foreach($options as$o): ?><option value="<?= html_escape($o['value']); ?>" <?= (string)$value===(string)$o['value']?'selected':''; ?> <?= $o['parent']!==null?'data-type="'.(int)$o['parent'].'"':''; ?>><?= html_escape($o['label']); ?></option><?php endforeach; ?></select>
<?php else: ?><input id="f_<?= html_escape($k); ?>" class="form-control" name="f_<?= html_escape($k); ?>" type="<?= $isnum?'number':($f['kind']==='url'?'url':'text'); ?>" <?= $isnum?'min="0" max="999999999999999" step="1"':'maxlength="2000"'; ?> value="<?= html_escape($value); ?>" <?= !$editable?'readonly':''; ?>><?php endif; ?>
<?php if($f['definition']): ?><div class="form-hint mt-1" style="white-space:pre-line"><?= html_escape($f['definition']); ?></div><?php endif; ?>
</div><div><?php if($f['evidence_hint']||$f['evidence_required']): ?><div class="iplm-evidence"><div class="form-label"><i class="ti ti-files me-1" aria-hidden="true"></i>Jenis bukti dukung</div><p class="small mb-2">Simpan dokumen ini dalam satu folder bukti. Tautan folder cukup diisi sekali pada tab <strong>Bukti dukung</strong>.</p><details class="mt-3" open><summary>Dokumen yang perlu disiapkan</summary><p class="small text-secondary mb-0"><?= html_escape($f['evidence_hint']); ?></p></details></div><?php elseif($section==='identity'): ?><div class="form-hint">Identitas induk tetap aman. Perbedaan isian akan ditandai untuk verifikasi admin kabupaten.</div><?php endif; ?></div>
</div><?php endforeach; ?></div></section><?php endforeach; ?>
<?php if($editable): ?><div class="card card-body mb-3 iplm-form-footer"><div class="btn-list"><button name="action" value="draft" class="btn btn-outline-primary">Simpan draft</button><button name="action" value="submit" class="btn btn-primary" <?= $period['state']!=='open'||!$period['dates_confirmed']?'disabled':''; ?>>Simpan & kirim untuk verifikasi</button></div><small class="text-secondary mt-2">Semua tab disimpan sekaligus. Tanda * wajib saat dikirim. Berpindah tab tidak menyimpan atau menghilangkan isian.</small></div><?php endif; ?></form>
<?php if(!$local&&($may_approve||$may_delete)): ?><form class="card card-body mb-3" method="post" action="<?= base_url('iplm/review/'.(int)$row['id']); ?>"><h3>Tindakan admin kabupaten</h3><input type="hidden" name="iplm_csrf" value="<?= html_escape($csrf); ?>"><input type="hidden" name="version" value="<?= (int)$row['version']; ?>"><label class="form-label">Catatan/alasan pemeriksaan</label><textarea class="form-control mb-3" name="note" maxlength="2000" required></textarea><div class="btn-list"><?php if($may_approve): ?><button name="action" value="verify" class="btn btn-success">Verifikasi isian</button><button name="action" value="revision" class="btn btn-warning">Kembalikan untuk revisi</button><?php endif; ?><?php if($may_delete): ?><button name="action" value="delete" class="btn btn-outline-danger" onclick="return confirm('Arsipkan isian ini? Riwayat tetap disimpan.');">Hapus / arsipkan isian</button><?php endif; ?></div><small class="text-secondary mt-2">Keputusan berlaku pada laporan IPLM, tidak otomatis mengubah /libraries.</small></form><?php endif; ?>
<details class="card card-body mb-3"><summary>Riwayat tindakan (50 terakhir)</summary><ul class="mt-2"><?php foreach($history as$h): ?><li><?= html_escape($h['created_at'].' · '.$h['event'].' · petugas #'.$h['actor_id']); ?></li><?php endforeach; ?></ul></details>
</div></div>
<script>
document.addEventListener('DOMContentLoaded',function(){const button=document.getElementById('use-collection-reference');if(button)button.addEventListener('click',function(){if(!confirm('Pastikan data katalog lengkap dan sesuai akhir periode. Ganti tiga isian koleksi dengan angka tercatat?'))return;const values=<?= json_encode($reference,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT); ?>;for(const key in values){const field=document.getElementById('f_'+key);if(field)field.value=values[key];}});});
document.addEventListener('DOMContentLoaded',function(){const type=document.getElementById('f_library_type_id'),sub=document.getElementById('f_library_subtype_id');if(!type||!sub)return;function update(reset){for(const option of sub.options){const match=!option.value||option.dataset.type===type.value;option.hidden=!match;option.disabled=!match;}if(reset&&sub.selectedOptions[0]&&sub.selectedOptions[0].disabled)sub.value='';}update(false);type.addEventListener('change',()=>update(true));});
</script>
