<?php $this->load->view('iplm/header',get_defined_vars()); ?>
<form class="card card-body mb-3" method="get"><div class="row g-2 align-items-end"><div class="col-md-8"><label class="form-label" for="period">Periode pendataan</label><select id="period" name="period" class="form-select"><?php foreach($periods as$p): ?><option value="<?= (int)$p['id']; ?>" <?= ($period['id']??0)==$p['id']?'selected':''; ?>><?= html_escape($p['title'].' — '.$p['state']); ?></option><?php endforeach; ?></select></div><div class="col-auto"><button class="btn btn-primary">Tampilkan</button></div></div></form>
<?php if(!$in_scope): ?><div class="alert alert-info">Perpustakaan Anda di luar cakupan pendataan IPLM kabupaten. TK/SKB tetap terdaftar dan dapat memakai modul perpustakaan, tetapi tidak termasuk formulir, rekap, atau populasi IPLM.</div><?php endif; ?>
<?php if($period): ?>
<?php if(!$period['dates_confirmed']): ?><div class="alert alert-warning">Rentang pengukuran belum dikonfirmasi admin kabupaten. Tanggal <?= html_escape($period['start_date'].' s.d. '.$period['end_date']); ?> masih sementara; pengiriman dan verifikasi dikunci.</div><?php else: ?><div class="alert alert-info">Rentang data: <?= html_escape($period['start_date'].' s.d. '.$period['end_date']); ?>. Status periode: <?= html_escape($period['state']); ?>.</div><?php endif; ?>
<div class="row g-2 mb-3"><?php foreach(['draft'=>'Draft','submitted'=>'Menunggu verifikasi','revision'=>'Perlu revisi','verified'=>'Terverifikasi','differences'=>'Perbedaan belum selesai']as$key=>$label): ?><div class="col-6 col-lg"><div class="card card-body"><div class="text-secondary"><?= $label; ?></div><div class="h1 mb-0 <?= $key==='differences'&&$stats[$key]?'text-warning':''; ?>"><?= (int)$stats[$key]; ?></div></div></div><?php endforeach; ?></div>
<div class="d-flex flex-wrap gap-2 mb-3"><?php if(!$local): ?><a class="btn btn-outline-primary" href="<?= base_url('iplm/analysis/'.(int)$period['id']); ?>"><i class="ti ti-chart-bar me-1"></i>Analisis internal</a><?php endif; ?><?php if($may_export): ?><a class="btn btn-outline-blue" href="<?= base_url('iplm/export/'.(int)$period['id'].'/csv'); ?>"><i class="ti ti-download me-1"></i>CSV</a><a class="btn btn-outline-success" href="<?= base_url('iplm/export/'.(int)$period['id'].'/xlsx'); ?>"><i class="ti ti-download me-1"></i>Excel</a><?php endif; ?></div>
<?php if($may_create&&$in_scope&&$period['state']!=='closed'): ?><form method="post" action="<?= base_url('iplm/create'); ?>" class="card card-body mb-3"><input type="hidden" name="iplm_csrf" value="<?= html_escape($csrf); ?>"><input type="hidden" name="period_id" value="<?= (int)$period['id']; ?>"><div class="row g-2 align-items-end"><?php if(!$local): ?><div class="col-md-8"><label class="form-label">Perpustakaan</label><select name="library_id" class="form-select" required><option value="">Pilih perpustakaan</option><?php foreach($libraries as$l): ?><option value="<?= (int)$l['id']; ?>"><?= html_escape($l['code'].' — '.$l['name']); ?></option><?php endforeach; ?></select></div><?php endif; ?><div class="col-auto"><button class="btn btn-primary"><i class="ti ti-plus me-1"></i>Buat / lanjutkan isian</button></div></div><small class="text-secondary mt-2">Satu isian aktif per perpustakaan per periode. Identitas diisi dari data induk; perubahan hanya tersimpan pada isian IPLM.</small></form><?php endif; ?>
<div class="card"><div class="table-responsive"><table class="table table-vcenter"><thead><tr><th>Perpustakaan</th><th>Status</th><th>Identitas</th><th>Diperbarui</th><th></th></tr></thead><tbody><?php foreach($rows as$r): ?><tr><td><?= html_escape($r['library_name']); ?><small class="d-block text-secondary"><?= html_escape($r['code']); ?></small></td><td><span class="badge bg-blue-lt"><?= html_escape($r['status']); ?></span></td><td><?php if($r['differences']): ?><span class="badge bg-yellow-lt"><?= (int)$r['differences']; ?> perbedaan</span><?php else: ?>Tidak ada perbedaan tertunda<?php endif; ?></td><td><?= html_escape($r['updated_at']); ?></td><td><a class="btn btn-sm btn-outline-primary" href="<?= base_url('iplm/form/'.(int)$r['id']); ?>">Buka</a></td></tr><?php endforeach; ?><?php if(!$rows): ?><tr><td colspan="5" class="text-center text-secondary">Belum ada isian untuk periode ini.</td></tr><?php endif; ?></tbody></table></div></div>
<?php if(!$local): ?><details class="card card-body mt-3"><summary>Rekap indikator — hanya isian terverifikasi tanpa perbedaan tertunda</summary><p class="text-secondary mt-2">Penjumlahan isian per perpustakaan, bukan deduplikasi orang lintas perpustakaan. Data kosong tidak dianggap nol. Ini rekap, bukan skor IPLM.</p><div class="table-responsive"><table class="table"><thead><tr><th>Indikator</th><th>Jumlah dilaporkan</th><th>Isian terisi</th></tr></thead><tbody><?php foreach($totals as$t): ?><tr><td><?= html_escape($t['label']); ?></td><td><?= $t['sum']===null?'Belum tersedia':number_format($t['sum'],0,',','.'); ?></td><td><?= (int)$t['filled']; ?></td></tr><?php endforeach; ?></tbody></table></div></details><?php endif; ?>
<?php endif; ?></div></div>
