-- Pilot soal terkurasi SD Kelas 2 / Fase A.
-- Masing-masing mapel memiliki 3 soal mudah, 3 sedang, dan 3 menantang.
-- Tingkat "menantang" tetap berada dalam capaian Fase A, bukan materi kelas lebih tinggi.

SET @g := (SELECT id FROM quiz_grade_levels WHERE code = 'sd_2' LIMIT 1);
SET @mat := (SELECT id FROM quiz_subjects WHERE code = 'matematika' LIMIT 1);
SET @bin := (SELECT id FROM quiz_subjects WHERE code = 'bahasa_indonesia' LIMIT 1);
SET @pan := (SELECT id FROM quiz_subjects WHERE code = 'ppkn' LIMIT 1);
SET @sen := (SELECT id FROM quiz_subjects WHERE code = 'seni_budaya' LIMIT 1);
SET @pjok := (SELECT id FROM quiz_subjects WHERE code = 'penjaskes' LIMIT 1);

-- Matematika: Bilangan, operasi konkret, pola, dan data Fase A.
INSERT INTO quiz_questions (subject_id,grade_level_id,type,difficulty,question_text,explanation,correct_option_index,score_weight,is_active) VALUES (@mat,@g,'multiple_choice','easy','Bilangan terbesar di antara 72, 27, dan 70 adalah ....','72 memiliki tujuh puluhan dan dua satuan; nilainya paling besar.',0,1,1);
SET @q:=LAST_INSERT_ID(); INSERT INTO quiz_question_options(question_id,option_index,option_text) VALUES(@q,0,'72'),(@q,1,'27'),(@q,2,'70'),(@q,3,'Semua sama');
INSERT INTO quiz_questions (subject_id,grade_level_id,type,difficulty,question_text,explanation,correct_option_index,score_weight,is_active) VALUES (@mat,@g,'multiple_choice','easy','Hasil dari 20 - 6 adalah ....','Jika 6 diambil dari 20, sisanya 14.',2,1,1);
SET @q:=LAST_INSERT_ID(); INSERT INTO quiz_question_options(question_id,option_index,option_text) VALUES(@q,0,'12'),(@q,1,'13'),(@q,2,'14'),(@q,3,'16');
INSERT INTO quiz_questions (subject_id,grade_level_id,type,difficulty,question_text,explanation,correct_option_index,score_weight,is_active) VALUES (@mat,@g,'multiple_choice','easy','Urutan 12, 14, 16, .... Bilangan berikutnya adalah ....','Polanya bertambah 2 setiap kali. Setelah 16 adalah 18.',3,1,1);
SET @q:=LAST_INSERT_ID(); INSERT INTO quiz_question_options(question_id,option_index,option_text) VALUES(@q,0,'15'),(@q,1,'17'),(@q,2,'20'),(@q,3,'18');
INSERT INTO quiz_questions (subject_id,grade_level_id,type,difficulty,question_text,explanation,correct_option_index,score_weight,is_active) VALUES (@mat,@g,'multiple_choice','medium','Ada 15 permen. Tujuh permen dimakan, lalu tiga permen diberikan kepada adik. Sisa permen adalah ....','15 - 7 = 8, lalu 8 - 3 = 5.',1,1,1);
SET @q:=LAST_INSERT_ID(); INSERT INTO quiz_question_options(question_id,option_index,option_text) VALUES(@q,0,'4'),(@q,1,'5'),(@q,2,'8'),(@q,3,'11');
INSERT INTO quiz_questions (subject_id,grade_level_id,type,difficulty,question_text,explanation,correct_option_index,score_weight,is_active) VALUES (@mat,@g,'multiple_choice','medium','Lima belas buku disusun pada dua rak sama banyak. Banyak buku pada setiap rak adalah ....','15 tidak dapat dibagi menjadi dua bagian yang sama banyak tanpa sisa.',2,1,1);
SET @q:=LAST_INSERT_ID(); INSERT INTO quiz_question_options(question_id,option_index,option_text) VALUES(@q,0,'6 buku'),(@q,1,'7 buku'),(@q,2,'Tidak dapat dibagi sama banyak'),(@q,3,'8 buku');
INSERT INTO quiz_questions (subject_id,grade_level_id,type,difficulty,question_text,explanation,correct_option_index,score_weight,is_active) VALUES (@mat,@g,'multiple_choice','medium','Data warna kesukaan: merah 5 anak, biru 7 anak, kuning 4 anak. Selisih pemilih biru dan kuning adalah .... anak.','7 - 4 = 3.',0,1,1);
SET @q:=LAST_INSERT_ID(); INSERT INTO quiz_question_options(question_id,option_index,option_text) VALUES(@q,0,'3'),(@q,1,'4'),(@q,2,'11'),(@q,3,'12');
INSERT INTO quiz_questions (subject_id,grade_level_id,type,difficulty,question_text,explanation,correct_option_index,score_weight,is_active) VALUES (@mat,@g,'multiple_choice','hard','Siti memiliki 18 pensil. Ia memberikan 5 pensil, kemudian mendapat 4 pensil lagi. Pensil Siti sekarang berjumlah ....','18 - 5 = 13, lalu 13 + 4 = 17.',1,1,1);
SET @q:=LAST_INSERT_ID(); INSERT INTO quiz_question_options(question_id,option_index,option_text) VALUES(@q,0,'16'),(@q,1,'17'),(@q,2,'18'),(@q,3,'19');
INSERT INTO quiz_questions (subject_id,grade_level_id,type,difficulty,question_text,explanation,correct_option_index,score_weight,is_active) VALUES (@mat,@g,'multiple_choice','hard','Di meja ada 4 kelompok kancing. Setiap kelompok berisi 3 kancing. Dua kancing diambil. Kancing yang tersisa ada ....','Awalnya 3 + 3 + 3 + 3 = 12. Setelah diambil 2, sisanya 10.',2,1,1);
SET @q:=LAST_INSERT_ID(); INSERT INTO quiz_question_options(question_id,option_index,option_text) VALUES(@q,0,'8'),(@q,1,'9'),(@q,2,'10'),(@q,3,'14');
INSERT INTO quiz_questions (subject_id,grade_level_id,type,difficulty,question_text,explanation,correct_option_index,score_weight,is_active) VALUES (@mat,@g,'multiple_choice','hard','Rani memiliki 14 stiker. Bima memiliki 6 stiker lebih sedikit daripada Rani. Stiker Bima berjumlah ....','6 lebih sedikit dari 14 berarti 14 - 6 = 8.',3,1,1);
SET @q:=LAST_INSERT_ID(); INSERT INTO quiz_question_options(question_id,option_index,option_text) VALUES(@q,0,'6'),(@q,1,'7'),(@q,2,'9'),(@q,3,'8');

-- Bahasa Indonesia: menyimak/membaca teks pendek, kosakata, dan tanggapan sederhana.
INSERT INTO quiz_questions (subject_id,grade_level_id,type,difficulty,question_text,explanation,correct_option_index,score_weight,is_active) VALUES (@bin,@g,'multiple_choice','easy','Kata yang tepat untuk melengkapi kalimat "Ibu membaca ...." adalah ....','Buku adalah benda yang dapat dibaca.',1,1,1);
SET @q:=LAST_INSERT_ID(); INSERT INTO quiz_question_options(question_id,option_index,option_text) VALUES(@q,0,'sepatu'),(@q,1,'buku'),(@q,2,'bola'),(@q,3,'meja');
INSERT INTO quiz_questions (subject_id,grade_level_id,type,difficulty,question_text,explanation,correct_option_index,score_weight,is_active) VALUES (@bin,@g,'multiple_choice','easy','Tanda baca yang tepat di akhir kalimat tanya adalah ....','Kalimat tanya diakhiri tanda tanya.',2,1,1);
SET @q:=LAST_INSERT_ID(); INSERT INTO quiz_question_options(question_id,option_index,option_text) VALUES(@q,0,'.'),(@q,1,','),(@q,2,'?'),(@q,3,'!');
INSERT INTO quiz_questions (subject_id,grade_level_id,type,difficulty,question_text,explanation,correct_option_index,score_weight,is_active) VALUES (@bin,@g,'multiple_choice','easy','Lawan kata "panas" adalah ....','Lawan kata panas adalah dingin.',0,1,1);
SET @q:=LAST_INSERT_ID(); INSERT INTO quiz_question_options(question_id,option_index,option_text) VALUES(@q,0,'dingin'),(@q,1,'hangat'),(@q,2,'terang'),(@q,3,'cepat');
INSERT INTO quiz_questions (subject_id,grade_level_id,type,difficulty,question_text,explanation,correct_option_index,score_weight,is_active) VALUES (@bin,@g,'multiple_choice','medium','Bacalah: "Lani menyiram bunga setiap pagi." Kegiatan yang dilakukan Lani adalah ....','Kalimat menyatakan bahwa Lani menyiram bunga.',3,1,1);
SET @q:=LAST_INSERT_ID(); INSERT INTO quiz_question_options(question_id,option_index,option_text) VALUES(@q,0,'memetik bunga'),(@q,1,'menjual bunga'),(@q,2,'menanam pohon'),(@q,3,'menyiram bunga');
INSERT INTO quiz_questions (subject_id,grade_level_id,type,difficulty,question_text,explanation,correct_option_index,score_weight,is_active) VALUES (@bin,@g,'multiple_choice','medium','Kalimat yang ditulis dengan huruf kapital dan tanda titik yang tepat adalah ....','Nama orang dimulai huruf kapital dan kalimat berita diakhiri titik.',1,1,1);
SET @q:=LAST_INSERT_ID(); INSERT INTO quiz_question_options(question_id,option_index,option_text) VALUES(@q,0,'andi bermain bola'),(@q,1,'Andi bermain bola.'),(@q,2,'andi Bermain bola.'),(@q,3,'Andi bermain bola?');
INSERT INTO quiz_questions (subject_id,grade_level_id,type,difficulty,question_text,explanation,correct_option_index,score_weight,is_active) VALUES (@bin,@g,'multiple_choice','medium','Bacalah: "Pagi ini langit mendung. Dita membawa payung." Mengapa Dita membawa payung?','Langit mendung menjadi tanda kemungkinan hujan.',2,1,1);
SET @q:=LAST_INSERT_ID(); INSERT INTO quiz_question_options(question_id,option_index,option_text) VALUES(@q,0,'Agar bisa bermain bola'),(@q,1,'Agar payungnya dipinjam teman'),(@q,2,'Karena mungkin hujan'),(@q,3,'Karena cuaca sangat panas');
INSERT INTO quiz_questions (subject_id,grade_level_id,type,difficulty,question_text,explanation,correct_option_index,score_weight,is_active) VALUES (@bin,@g,'multiple_choice','hard','Bacalah: "Raka lupa membawa pensil. Sinta meminjamkan satu pensil kepadanya." Sikap Sinta adalah ....','Meminjamkan alat tulis kepada teman menunjukkan sikap suka menolong.',0,1,1);
SET @q:=LAST_INSERT_ID(); INSERT INTO quiz_question_options(question_id,option_index,option_text) VALUES(@q,0,'suka menolong'),(@q,1,'sombong'),(@q,2,'ceroboh'),(@q,3,'malas');
INSERT INTO quiz_questions (subject_id,grade_level_id,type,difficulty,question_text,explanation,correct_option_index,score_weight,is_active) VALUES (@bin,@g,'multiple_choice','hard','Urutan kata yang menjadi kalimat benar adalah ....','Susunan subjek, predikat, dan keterangan yang tepat membentuk kalimat jelas.',3,1,1);
SET @q:=LAST_INSERT_ID(); INSERT INTO quiz_question_options(question_id,option_index,option_text) VALUES(@q,0,'sekolah ke pergi Beni'),(@q,1,'pergi Beni sekolah ke'),(@q,2,'ke Beni sekolah pergi'),(@q,3,'Beni pergi ke sekolah');
INSERT INTO quiz_questions (subject_id,grade_level_id,type,difficulty,question_text,explanation,correct_option_index,score_weight,is_active) VALUES (@bin,@g,'multiple_choice','hard','Bacalah: "Di perpustakaan, Sari memilih buku cerita. Setelah selesai membaca, ia mengembalikan buku ke rak." Tempat kegiatan Sari adalah ....','Teks menyebutkan kegiatan dilakukan di perpustakaan.',1,1,1);
SET @q:=LAST_INSERT_ID(); INSERT INTO quiz_question_options(question_id,option_index,option_text) VALUES(@q,0,'kantin'),(@q,1,'perpustakaan'),(@q,2,'lapangan'),(@q,3,'pasar');

-- Pendidikan Pancasila: aturan sederhana, peduli, dan hidup rukun.
INSERT INTO quiz_questions (subject_id,grade_level_id,type,difficulty,question_text,explanation,correct_option_index,score_weight,is_active) VALUES (@pan,@g,'multiple_choice','easy','Sebelum makan, kita sebaiknya ....','Mencuci tangan membantu menjaga kebersihan sebelum makan.',2,1,1);
SET @q:=LAST_INSERT_ID(); INSERT INTO quiz_question_options(question_id,option_index,option_text) VALUES(@q,0,'berlari di rumah'),(@q,1,'membuang makanan'),(@q,2,'mencuci tangan'),(@q,3,'menyembunyikan piring');
INSERT INTO quiz_questions (subject_id,grade_level_id,type,difficulty,question_text,explanation,correct_option_index,score_weight,is_active) VALUES (@pan,@g,'multiple_choice','easy','Saat guru berbicara di kelas, sikap yang baik adalah ....','Mendengarkan guru adalah bentuk menghormati dan menaati aturan kelas.',0,1,1);
SET @q:=LAST_INSERT_ID(); INSERT INTO quiz_question_options(question_id,option_index,option_text) VALUES(@q,0,'mendengarkan dengan baik'),(@q,1,'berteriak-teriak'),(@q,2,'berjalan-jalan'),(@q,3,'mengganggu teman');
INSERT INTO quiz_questions (subject_id,grade_level_id,type,difficulty,question_text,explanation,correct_option_index,score_weight,is_active) VALUES (@pan,@g,'multiple_choice','easy','Contoh menjaga kebersihan kelas adalah ....','Membuang sampah pada tempatnya menjaga kelas tetap bersih.',1,1,1);
SET @q:=LAST_INSERT_ID(); INSERT INTO quiz_question_options(question_id,option_index,option_text) VALUES(@q,0,'mencoret meja'),(@q,1,'membuang sampah pada tempatnya'),(@q,2,'menendang kursi'),(@q,3,'merobek buku');
INSERT INTO quiz_questions (subject_id,grade_level_id,type,difficulty,question_text,explanation,correct_option_index,score_weight,is_active) VALUES (@pan,@g,'multiple_choice','medium','Dua teman ingin memakai satu bola pada waktu yang sama. Cara yang adil adalah ....','Bergantian memberi kesempatan yang sama kepada kedua teman.',3,1,1);
SET @q:=LAST_INSERT_ID(); INSERT INTO quiz_question_options(question_id,option_index,option_text) VALUES(@q,0,'merebut bola'),(@q,1,'menyembunyikan bola'),(@q,2,'membiarkan salah satu menangis'),(@q,3,'bergantian memakai bola');
INSERT INTO quiz_questions (subject_id,grade_level_id,type,difficulty,question_text,explanation,correct_option_index,score_weight,is_active) VALUES (@pan,@g,'multiple_choice','medium','Hak seorang siswa di kelas adalah ....','Siswa berhak belajar dengan aman dan nyaman.',1,1,1);
SET @q:=LAST_INSERT_ID(); INSERT INTO quiz_question_options(question_id,option_index,option_text) VALUES(@q,0,'mengganggu teman belajar'),(@q,1,'belajar dengan aman dan nyaman'),(@q,2,'melanggar aturan kelas'),(@q,3,'merusak alat sekolah');
INSERT INTO quiz_questions (subject_id,grade_level_id,type,difficulty,question_text,explanation,correct_option_index,score_weight,is_active) VALUES (@pan,@g,'multiple_choice','medium','Temanmu berbicara dengan bahasa daerah yang berbeda. Sikap yang tepat adalah ....','Perbedaan bahasa daerah perlu dihargai sebagai bagian dari keberagaman.',2,1,1);
SET @q:=LAST_INSERT_ID(); INSERT INTO quiz_question_options(question_id,option_index,option_text) VALUES(@q,0,'mengejeknya'),(@q,1,'menjauhinya'),(@q,2,'menghargainya'),(@q,3,'melarangnya berbicara');
INSERT INTO quiz_questions (subject_id,grade_level_id,type,difficulty,question_text,explanation,correct_option_index,score_weight,is_active) VALUES (@pan,@g,'multiple_choice','hard','Kamu melihat keran air di sekolah masih terbuka setelah dipakai. Yang sebaiknya kamu lakukan adalah ....','Menutup keran menghemat air dan menunjukkan tanggung jawab.',0,1,1);
SET @q:=LAST_INSERT_ID(); INSERT INTO quiz_question_options(question_id,option_index,option_text) VALUES(@q,0,'menutup keran'),(@q,1,'membiarkannya'),(@q,2,'menambah aliran air'),(@q,3,'bermain air');
INSERT INTO quiz_questions (subject_id,grade_level_id,type,difficulty,question_text,explanation,correct_option_index,score_weight,is_active) VALUES (@pan,@g,'multiple_choice','hard','Saat kerja kelompok, tugasmu sudah selesai sedangkan temanmu masih kesulitan. Sikap yang tepat adalah ....','Membantu teman sesuai kemampuan menunjukkan kerja sama.',1,1,1);
SET @q:=LAST_INSERT_ID(); INSERT INTO quiz_question_options(question_id,option_index,option_text) VALUES(@q,0,'mengejek teman'),(@q,1,'menawarkan bantuan'),(@q,2,'meninggalkan kelompok'),(@q,3,'menyembunyikan hasil kerja');
INSERT INTO quiz_questions (subject_id,grade_level_id,type,difficulty,question_text,explanation,correct_option_index,score_weight,is_active) VALUES (@pan,@g,'multiple_choice','hard','Kamu tidak sengaja menyenggol teman hingga bukunya jatuh. Langkah pertama yang tepat adalah ....','Meminta maaf menunjukkan tanggung jawab atas tindakan yang terjadi.',2,1,1);
SET @q:=LAST_INSERT_ID(); INSERT INTO quiz_question_options(question_id,option_index,option_text) VALUES(@q,0,'berlari pergi'),(@q,1,'menertawakan teman'),(@q,2,'meminta maaf'),(@q,3,'menyalahkan teman');

-- Seni Budaya: unsur seni, ekspresi, dan apresiasi sederhana.
INSERT INTO quiz_questions (subject_id,grade_level_id,type,difficulty,question_text,explanation,correct_option_index,score_weight,is_active) VALUES (@sen,@g,'multiple_choice','easy','Warna merah, kuning, dan biru dikenal sebagai warna ....','Merah, kuning, dan biru merupakan warna primer.',1,1,1);
SET @q:=LAST_INSERT_ID(); INSERT INTO quiz_question_options(question_id,option_index,option_text) VALUES(@q,0,'gelap'),(@q,1,'primer'),(@q,2,'netral'),(@q,3,'campuran');
INSERT INTO quiz_questions (subject_id,grade_level_id,type,difficulty,question_text,explanation,correct_option_index,score_weight,is_active) VALUES (@sen,@g,'multiple_choice','easy','Alat yang dapat digunakan untuk memberi warna pada gambar adalah ....','Krayon digunakan untuk mewarnai gambar.',2,1,1);
SET @q:=LAST_INSERT_ID(); INSERT INTO quiz_question_options(question_id,option_index,option_text) VALUES(@q,0,'penggaris'),(@q,1,'penghapus'),(@q,2,'krayon'),(@q,3,'lemari');
INSERT INTO quiz_questions (subject_id,grade_level_id,type,difficulty,question_text,explanation,correct_option_index,score_weight,is_active) VALUES (@sen,@g,'multiple_choice','easy','Bunyi tepukan tangan dapat dibuat lebih keras dengan ....','Tepukan yang lebih kuat menghasilkan bunyi lebih keras.',0,1,1);
SET @q:=LAST_INSERT_ID(); INSERT INTO quiz_question_options(question_id,option_index,option_text) VALUES(@q,0,'menepuk lebih kuat'),(@q,1,'diam saja'),(@q,2,'menutup telinga'),(@q,3,'menyimpan tangan');
INSERT INTO quiz_questions (subject_id,grade_level_id,type,difficulty,question_text,explanation,correct_option_index,score_weight,is_active) VALUES (@sen,@g,'multiple_choice','medium','Warna kuning dicampur dengan warna biru akan menghasilkan warna ....','Kuning dan biru dicampur menghasilkan hijau.',3,1,1);
SET @q:=LAST_INSERT_ID(); INSERT INTO quiz_question_options(question_id,option_index,option_text) VALUES(@q,0,'merah'),(@q,1,'ungu'),(@q,2,'oranye'),(@q,3,'hijau');
INSERT INTO quiz_questions (subject_id,grade_level_id,type,difficulty,question_text,explanation,correct_option_index,score_weight,is_active) VALUES (@sen,@g,'multiple_choice','medium','Urutan bunyi tepuk, tepuk, diam, tepuk, tepuk, diam merupakan pola ....','Kelompok bunyi yang sama berulang secara teratur.',1,1,1);
SET @q:=LAST_INSERT_ID(); INSERT INTO quiz_question_options(question_id,option_index,option_text) VALUES(@q,0,'acak'),(@q,1,'berulang'),(@q,2,'tidak terdengar'),(@q,3,'sangat pelan');
INSERT INTO quiz_questions (subject_id,grade_level_id,type,difficulty,question_text,explanation,correct_option_index,score_weight,is_active) VALUES (@sen,@g,'multiple_choice','medium','Saat teman menampilkan tarian di depan kelas, sikap yang baik adalah ....','Memberi perhatian dan apresiasi menghargai karya teman.',2,1,1);
SET @q:=LAST_INSERT_ID(); INSERT INTO quiz_question_options(question_id,option_index,option_text) VALUES(@q,0,'mengejek gerakannya'),(@q,1,'berbicara keras'),(@q,2,'menonton dengan tertib'),(@q,3,'membelakangi teman');
INSERT INTO quiz_questions (subject_id,grade_level_id,type,difficulty,question_text,explanation,correct_option_index,score_weight,is_active) VALUES (@sen,@g,'multiple_choice','hard','Kamu ingin membuat gambar taman tampak ceria. Pilihan warna yang paling tepat adalah ....','Warna cerah membantu memberi kesan ceria pada gambar taman.',0,1,1);
SET @q:=LAST_INSERT_ID(); INSERT INTO quiz_question_options(question_id,option_index,option_text) VALUES(@q,0,'warna cerah yang beragam'),(@q,1,'hanya hitam'),(@q,2,'hanya abu-abu'),(@q,3,'tanpa warna');
INSERT INTO quiz_questions (subject_id,grade_level_id,type,difficulty,question_text,explanation,correct_option_index,score_weight,is_active) VALUES (@sen,@g,'multiple_choice','hard','Agar gambar rumah lebih mudah dikenali, bagian yang penting ditambahkan adalah ....','Atap, dinding, pintu, dan jendela adalah ciri yang membantu orang mengenali gambar rumah.',3,1,1);
SET @q:=LAST_INSERT_ID(); INSERT INTO quiz_question_options(question_id,option_index,option_text) VALUES(@q,0,'hanya satu titik'),(@q,1,'garis tanpa bentuk'),(@q,2,'kertas kosong'),(@q,3,'atap, pintu, dan jendela');
INSERT INTO quiz_questions (subject_id,grade_level_id,type,difficulty,question_text,explanation,correct_option_index,score_weight,is_active) VALUES (@sen,@g,'multiple_choice','hard','Saat membuat kolase, bahan yang tepat untuk ditempel pada kertas adalah ....','Daun kering dapat ditempel untuk membuat kolase.',1,1,1);
SET @q:=LAST_INSERT_ID(); INSERT INTO quiz_question_options(question_id,option_index,option_text) VALUES(@q,0,'air minum'),(@q,1,'daun kering'),(@q,2,'asap'),(@q,3,'angin');

-- PJOK: gerak dasar, kebersihan, keselamatan, dan hidup sehat.
INSERT INTO quiz_questions (subject_id,grade_level_id,type,difficulty,question_text,explanation,correct_option_index,score_weight,is_active) VALUES (@pjok,@g,'multiple_choice','easy','Sebelum berolahraga, kita melakukan ....','Pemanasan menyiapkan tubuh sebelum bergerak.',2,1,1);
SET @q:=LAST_INSERT_ID(); INSERT INTO quiz_question_options(question_id,option_index,option_text) VALUES(@q,0,'tidur'),(@q,1,'makan permen'),(@q,2,'pemanasan'),(@q,3,'bermain gawai');
INSERT INTO quiz_questions (subject_id,grade_level_id,type,difficulty,question_text,explanation,correct_option_index,score_weight,is_active) VALUES (@pjok,@g,'multiple_choice','easy','Setelah bermain dan berkeringat, kita sebaiknya ....','Mandi atau membersihkan diri menjaga kebersihan tubuh.',0,1,1);
SET @q:=LAST_INSERT_ID(); INSERT INTO quiz_question_options(question_id,option_index,option_text) VALUES(@q,0,'membersihkan diri'),(@q,1,'memakai baju kotor'),(@q,2,'tidak minum sama sekali'),(@q,3,'membuang sampah sembarangan');
INSERT INTO quiz_questions (subject_id,grade_level_id,type,difficulty,question_text,explanation,correct_option_index,score_weight,is_active) VALUES (@pjok,@g,'multiple_choice','easy','Gerak berpindah tempat dengan cepat menggunakan kaki disebut ....','Berlari adalah gerak berpindah tempat menggunakan kaki dengan cepat.',1,1,1);
SET @q:=LAST_INSERT_ID(); INSERT INTO quiz_question_options(question_id,option_index,option_text) VALUES(@q,0,'duduk'),(@q,1,'berlari'),(@q,2,'tidur'),(@q,3,'membaca');
INSERT INTO quiz_questions (subject_id,grade_level_id,type,difficulty,question_text,explanation,correct_option_index,score_weight,is_active) VALUES (@pjok,@g,'multiple_choice','medium','Saat bermain di lapangan yang licin, kita harus ....','Berjalan hati-hati mengurangi risiko terpeleset.',3,1,1);
SET @q:=LAST_INSERT_ID(); INSERT INTO quiz_question_options(question_id,option_index,option_text) VALUES(@q,0,'berlari sekencang-kencangnya'),(@q,1,'saling mendorong'),(@q,2,'melompat tanpa melihat'),(@q,3,'berjalan hati-hati');
INSERT INTO quiz_questions (subject_id,grade_level_id,type,difficulty,question_text,explanation,correct_option_index,score_weight,is_active) VALUES (@pjok,@g,'multiple_choice','medium','Minuman yang baik diminum setelah berolahraga adalah ....','Air putih membantu mengganti cairan tubuh.',1,1,1);
SET @q:=LAST_INSERT_ID(); INSERT INTO quiz_question_options(question_id,option_index,option_text) VALUES(@q,0,'minuman sangat manis setiap saat'),(@q,1,'air putih'),(@q,2,'minuman yang sudah basi'),(@q,3,'air sabun');
INSERT INTO quiz_questions (subject_id,grade_level_id,type,difficulty,question_text,explanation,correct_option_index,score_weight,is_active) VALUES (@pjok,@g,'multiple_choice','medium','Saat melempar bola kepada teman, arah lemparan sebaiknya ....','Bola diarahkan ke teman agar aman dan mudah ditangkap.',2,1,1);
SET @q:=LAST_INSERT_ID(); INSERT INTO quiz_question_options(question_id,option_index,option_text) VALUES(@q,0,'ke arah jendela'),(@q,1,'ke arah orang yang tidak siap'),(@q,2,'ke arah teman yang siap menangkap'),(@q,3,'ke langit-langit kelas');
INSERT INTO quiz_questions (subject_id,grade_level_id,type,difficulty,question_text,explanation,correct_option_index,score_weight,is_active) VALUES (@pjok,@g,'multiple_choice','hard','Ketika teman jatuh saat bermain, tindakan pertama yang tepat adalah ....','Berhenti bermain dan memanggil guru membantu teman memperoleh pertolongan dengan aman.',0,1,1);
SET @q:=LAST_INSERT_ID(); INSERT INTO quiz_question_options(question_id,option_index,option_text) VALUES(@q,0,'berhenti bermain dan memanggil guru'),(@q,1,'menertawakan teman'),(@q,2,'membiarkan teman sendirian'),(@q,3,'tetap berlari di dekatnya');
INSERT INTO quiz_questions (subject_id,grade_level_id,type,difficulty,question_text,explanation,correct_option_index,score_weight,is_active) VALUES (@pjok,@g,'multiple_choice','hard','Dalam permainan beregu, timmu kalah. Sikap yang baik adalah ....','Menerima hasil dengan baik dan tetap bersemangat menunjukkan sportivitas.',3,1,1);
SET @q:=LAST_INSERT_ID(); INSERT INTO quiz_question_options(question_id,option_index,option_text) VALUES(@q,0,'menyalahkan teman'),(@q,1,'merusak alat permainan'),(@q,2,'menolak bermain lagi'),(@q,3,'tetap sportif dan bersemangat');
INSERT INTO quiz_questions (subject_id,grade_level_id,type,difficulty,question_text,explanation,correct_option_index,score_weight,is_active) VALUES (@pjok,@g,'multiple_choice','hard','Kamu merasa sangat lelah dan pusing saat berolahraga. Yang sebaiknya dilakukan adalah ....','Berhenti, beristirahat, dan memberi tahu guru adalah tindakan aman.',1,1,1);
SET @q:=LAST_INSERT_ID(); INSERT INTO quiz_question_options(question_id,option_index,option_text) VALUES(@q,0,'memaksa terus berlari'),(@q,1,'beristirahat dan memberi tahu guru'),(@q,2,'minum minuman yang tidak dikenal'),(@q,3,'bersembunyi sendiri');

-- Sesi publik: satu sesi untuk setiap mapel, memuat seluruh tingkat kesulitan pilot.
UPDATE quiz_sessions SET question_count=29, time_limit_minutes=40, status='open', is_published=1, is_paused=0 WHERE code='LAT-SD2-MAT-CP26';
INSERT INTO quiz_sessions (code,title,type,status,subject_id,grade_level_id,difficulty_filter,question_count,time_limit_minutes,shuffle_questions,shuffle_options,show_result_immediately,allow_review,max_attempts,passing_score,access_mode,is_published,is_paused,description,instructions) VALUES
('LAT-SD2-BIN-CP26','Bahasa Indonesia SD Kelas 2 — Membaca dan Menulis Awal','practice','open',@bin,@g,'mixed',9,20,1,1,1,1,0,60,'public',1,0,'Pilot Fase A: kosakata, kalimat, dan pemahaman teks pendek.','Baca teks dan pilihan jawaban dengan teliti. Pilih satu jawaban yang paling tepat.'),
('LAT-SD2-PAN-CP26','Pendidikan Pancasila SD Kelas 2 — Hidup Rukun','practice','open',@pan,@g,'mixed',9,20,1,1,1,1,0,60,'public',1,0,'Pilot Fase A: aturan, tanggung jawab, kepedulian, dan keberagaman.','Baca situasi dengan teliti. Pilih sikap yang paling baik.'),
('LAT-SD2-SEN-CP26','Seni Budaya SD Kelas 2 — Warna dan Ekspresi','practice','open',@sen,@g,'mixed',9,20,1,1,1,1,0,60,'public',1,0,'Pilot Fase A: unsur seni, pola bunyi, apresiasi, dan karya sederhana.','Baca setiap soal. Pilih satu jawaban yang paling tepat.'),
('LAT-SD2-PJK-CP26','PJOK SD Kelas 2 — Gerak dan Hidup Sehat','practice','open',@pjok,@g,'mixed',9,20,1,1,1,1,0,60,'public',1,0,'Pilot Fase A: gerak dasar, keselamatan, kebersihan, dan sportivitas.','Baca setiap situasi. Pilih tindakan yang paling aman dan tepat.');
