-- Konten awal game Susun Kata. Setiap set berisi 10 kata dengan petunjuk.
-- Aman dijalankan ulang.

INSERT INTO learn_game_categories (game_type_id, grade_level_id, subject_id, name, description, is_active)
SELECT gt.id,2,38,'Kata Benda Anak','Menyusun kata benda sederhana di sekitar anak.',1 FROM learn_game_types gt WHERE gt.code='word_scramble' AND NOT EXISTS (SELECT 1 FROM learn_game_categories c WHERE c.game_type_id=gt.id AND c.name='Kata Benda Anak');
INSERT INTO learn_game_categories (game_type_id, grade_level_id, subject_id, name, description, is_active)
SELECT gt.id,3,2,'Kosakata Sekolah','Menyusun kosakata yang sering dipakai di sekolah.',1 FROM learn_game_types gt WHERE gt.code='word_scramble' AND NOT EXISTS (SELECT 1 FROM learn_game_categories c WHERE c.game_type_id=gt.id AND c.name='Kosakata Sekolah');
INSERT INTO learn_game_categories (game_type_id, grade_level_id, subject_id, name, description, is_active)
SELECT gt.id,4,1,'Istilah Matematika Dasar','Menyusun istilah matematika sederhana.',1 FROM learn_game_types gt WHERE gt.code='word_scramble' AND NOT EXISTS (SELECT 1 FROM learn_game_categories c WHERE c.game_type_id=gt.id AND c.name='Istilah Matematika Dasar');
INSERT INTO learn_game_categories (game_type_id, grade_level_id, subject_id, name, description, is_active)
SELECT gt.id,5,39,'Alam dan Tumbuhan','Menyusun kosakata IPAS tentang alam dan tumbuhan.',1 FROM learn_game_types gt WHERE gt.code='word_scramble' AND NOT EXISTS (SELECT 1 FROM learn_game_categories c WHERE c.game_type_id=gt.id AND c.name='Alam dan Tumbuhan');
INSERT INTO learn_game_categories (game_type_id, grade_level_id, subject_id, name, description, is_active)
SELECT gt.id,9,4,'Istilah Sains Kelas 7','Menyusun istilah sains dasar dengan petunjuk singkat.',1 FROM learn_game_types gt WHERE gt.code='word_scramble' AND NOT EXISTS (SELECT 1 FROM learn_game_categories c WHERE c.game_type_id=gt.id AND c.name='Istilah Sains Kelas 7');

INSERT INTO learn_game_content_sets (category_id,name,difficulty,is_active) SELECT c.id,'Benda di Sekitarku','easy',1 FROM learn_game_categories c WHERE c.name='Kata Benda Anak' AND NOT EXISTS (SELECT 1 FROM learn_game_content_sets s WHERE s.category_id=c.id AND s.name='Benda di Sekitarku');
INSERT INTO learn_game_content_sets (category_id,name,difficulty,is_active) SELECT c.id,'Aku di Sekolah','easy',1 FROM learn_game_categories c WHERE c.name='Kosakata Sekolah' AND NOT EXISTS (SELECT 1 FROM learn_game_content_sets s WHERE s.category_id=c.id AND s.name='Aku di Sekolah');
INSERT INTO learn_game_content_sets (category_id,name,difficulty,is_active) SELECT c.id,'Kata Matematika','easy',1 FROM learn_game_categories c WHERE c.name='Istilah Matematika Dasar' AND NOT EXISTS (SELECT 1 FROM learn_game_content_sets s WHERE s.category_id=c.id AND s.name='Kata Matematika');
INSERT INTO learn_game_content_sets (category_id,name,difficulty,is_active) SELECT c.id,'Tumbuhan dan Lingkungan','medium',1 FROM learn_game_categories c WHERE c.name='Alam dan Tumbuhan' AND NOT EXISTS (SELECT 1 FROM learn_game_content_sets s WHERE s.category_id=c.id AND s.name='Tumbuhan dan Lingkungan');
INSERT INTO learn_game_content_sets (category_id,name,difficulty,is_active) SELECT c.id,'Sains di Sekitar Kita','medium',1 FROM learn_game_categories c WHERE c.name='Istilah Sains Kelas 7' AND NOT EXISTS (SELECT 1 FROM learn_game_content_sets s WHERE s.category_id=c.id AND s.name='Sains di Sekitar Kita');

INSERT INTO learn_game_content_items (set_id,term,definition,sort_order)
SELECT s.id,v.term,v.definition,v.sort_order FROM learn_game_content_sets s CROSS JOIN (SELECT 'BOLA' term,'Mainan berbentuk bulat' definition,1 sort_order UNION ALL SELECT 'BUKU','Dibaca untuk memperoleh cerita atau ilmu',2 UNION ALL SELECT 'MEJA','Perabot untuk meletakkan barang',3 UNION ALL SELECT 'KURSI','Tempat duduk',4 UNION ALL SELECT 'TOPI','Penutup kepala',5 UNION ALL SELECT 'TAS','Tempat membawa barang',6 UNION ALL SELECT 'IKAN','Hewan yang hidup di air',7 UNION ALL SELECT 'AYAM','Hewan yang berkokok',8 UNION ALL SELECT 'SUSU','Minuman berwarna putih yang bergizi',9 UNION ALL SELECT 'MATA','Bagian tubuh untuk melihat',10) v JOIN learn_game_categories c ON c.id=s.category_id WHERE c.name='Kata Benda Anak' AND s.name='Benda di Sekitarku' AND NOT EXISTS (SELECT 1 FROM learn_game_content_items i WHERE i.set_id=s.id AND i.term=v.term);

INSERT INTO learn_game_content_items (set_id,term,definition,sort_order)
SELECT s.id,v.term,v.definition,v.sort_order FROM learn_game_content_sets s CROSS JOIN (SELECT 'SEKOLAH' term,'Tempat belajar bersama guru dan teman' definition,1 sort_order UNION ALL SELECT 'GURU','Orang yang mengajar di kelas',2 UNION ALL SELECT 'TEMAN','Orang yang belajar atau bermain bersama',3 UNION ALL SELECT 'PENSIL','Alat untuk menulis',4 UNION ALL SELECT 'PENGHAPUS','Alat untuk menghapus tulisan pensil',5 UNION ALL SELECT 'KELAS','Ruang untuk belajar di sekolah',6 UNION ALL SELECT 'BELAJAR','Kegiatan untuk memperoleh pengetahuan',7 UNION ALL SELECT 'MEMBACA','Kegiatan memahami tulisan',8 UNION ALL SELECT 'MENULIS','Kegiatan membuat huruf atau kata',9 UNION ALL SELECT 'ISTIRAHAT','Waktu berhenti sejenak dari belajar',10) v JOIN learn_game_categories c ON c.id=s.category_id WHERE c.name='Kosakata Sekolah' AND s.name='Aku di Sekolah' AND NOT EXISTS (SELECT 1 FROM learn_game_content_items i WHERE i.set_id=s.id AND i.term=v.term);

INSERT INTO learn_game_content_items (set_id,term,definition,sort_order)
SELECT s.id,v.term,v.definition,v.sort_order FROM learn_game_content_sets s CROSS JOIN (SELECT 'ANGKA' term,'Lambang untuk menyatakan bilangan' definition,1 sort_order UNION ALL SELECT 'BILANGAN','Konsep untuk menyatakan banyaknya benda',2 UNION ALL SELECT 'TAMBAH','Operasi menggabungkan dua bilangan atau lebih',3 UNION ALL SELECT 'KURANG','Operasi mengambil sebagian dari suatu bilangan',4 UNION ALL SELECT 'KALI','Operasi penjumlahan berulang',5 UNION ALL SELECT 'BAGI','Operasi membagi sama banyak',6 UNION ALL SELECT 'GENAP','Bilangan yang habis dibagi dua',7 UNION ALL SELECT 'GANJIL','Bilangan yang tidak habis dibagi dua',8 UNION ALL SELECT 'WAKTU','Ukuran berlangsungnya suatu kejadian',9 UNION ALL SELECT 'BENTUK','Rupa atau wujud suatu benda',10) v JOIN learn_game_categories c ON c.id=s.category_id WHERE c.name='Istilah Matematika Dasar' AND s.name='Kata Matematika' AND NOT EXISTS (SELECT 1 FROM learn_game_content_items i WHERE i.set_id=s.id AND i.term=v.term);

INSERT INTO learn_game_content_items (set_id,term,definition,sort_order)
SELECT s.id,v.term,v.definition,v.sort_order FROM learn_game_content_sets s CROSS JOIN (SELECT 'AKAR' term,'Bagian tumbuhan yang menyerap air dari tanah' definition,1 sort_order UNION ALL SELECT 'BATANG','Bagian tumbuhan yang menopang tubuh tumbuhan',2 UNION ALL SELECT 'DAUN','Bagian tumbuhan tempat membuat makanan',3 UNION ALL SELECT 'BUNGA','Bagian tumbuhan untuk perkembangbiakan',4 UNION ALL SELECT 'BUAH','Bagian yang melindungi biji',5 UNION ALL SELECT 'BIJI','Bagian yang dapat tumbuh menjadi tumbuhan baru',6 UNION ALL SELECT 'TANAH','Tempat banyak tumbuhan tumbuh',7 UNION ALL SELECT 'HUJAN','Air yang turun dari awan',8 UNION ALL SELECT 'AWAN','Kumpulan titik air di langit',9 UNION ALL SELECT 'ANGIN','Udara yang bergerak',10) v JOIN learn_game_categories c ON c.id=s.category_id WHERE c.name='Alam dan Tumbuhan' AND s.name='Tumbuhan dan Lingkungan' AND NOT EXISTS (SELECT 1 FROM learn_game_content_items i WHERE i.set_id=s.id AND i.term=v.term);

INSERT INTO learn_game_content_items (set_id,term,definition,sort_order)
SELECT s.id,v.term,v.definition,v.sort_order FROM learn_game_content_sets s CROSS JOIN (SELECT 'SEL' term,'Unit terkecil penyusun makhluk hidup' definition,1 sort_order UNION ALL SELECT 'ORGAN','Bagian tubuh yang memiliki fungsi tertentu',2 UNION ALL SELECT 'ENERGI','Kemampuan untuk melakukan kerja',3 UNION ALL SELECT 'GAYA','Tarikan atau dorongan pada benda',4 UNION ALL SELECT 'SUHU','Ukuran panas atau dingin suatu benda',5 UNION ALL SELECT 'MASSA','Ukuran banyaknya materi dalam benda',6 UNION ALL SELECT 'VOLUME','Ukuran ruang yang ditempati benda',7 UNION ALL SELECT 'EKOSISTEM','Hubungan makhluk hidup dan lingkungannya',8 UNION ALL SELECT 'POPULASI','Kumpulan makhluk hidup sejenis di suatu tempat',9 UNION ALL SELECT 'HABITAT','Tempat hidup alami suatu makhluk hidup',10) v JOIN learn_game_categories c ON c.id=s.category_id WHERE c.name='Istilah Sains Kelas 7' AND s.name='Sains di Sekitar Kita' AND NOT EXISTS (SELECT 1 FROM learn_game_content_items i WHERE i.set_id=s.id AND i.term=v.term);
