CREATE TABLE IF NOT EXISTS inter_library_loans (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 owner_id BIGINT UNSIGNED NOT NULL,
 borrower_id BIGINT UNSIGNED NOT NULL,
 source ENUM('legacy','network') NOT NULL,
 item_id BIGINT UNSIGNED NOT NULL,
 book_id BIGINT UNSIGNED NOT NULL,
 barcode VARCHAR(150) NOT NULL,
 title VARCHAR(255) NOT NULL,
 state ENUM('requested','approved','dispatched','received','returning','returned','rejected','cancelled') NOT NULL DEFAULT 'requested',
 active_slot TINYINT UNSIGNED NULL,
 due_on DATE NOT NULL,
 requested_by BIGINT UNSIGNED NOT NULL,
 approved_by BIGINT UNSIGNED NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 returned_at DATETIME NULL,
 return_condition ENUM('good','damaged') NULL,
 UNIQUE KEY uq_inter_library_item_hold (source,item_id,active_slot),
 KEY idx_inter_library_owner (owner_id,id),
 KEY idx_inter_library_borrower (borrower_id,id),
 KEY idx_inter_library_book (source,book_id,active_slot),
 CONSTRAINT fk_inter_library_owner FOREIGN KEY (owner_id) REFERENCES libraries(id),
 CONSTRAINT fk_inter_library_borrower FOREIGN KEY (borrower_id) REFERENCES libraries(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS inter_library_events (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 loan_id BIGINT UNSIGNED NOT NULL,
 library_id BIGINT UNSIGNED NOT NULL,
 actor_id BIGINT UNSIGNED NOT NULL,
 action VARCHAR(40) NOT NULL,
 note VARCHAR(1000) NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 KEY idx_inter_library_events (loan_id,id),
 CONSTRAINT fk_inter_library_event FOREIGN KEY (loan_id) REFERENCES inter_library_loans(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS library_fines (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 library_id BIGINT UNSIGNED NOT NULL,
 source ENUM('legacy','network','interlibrary') NOT NULL,
 loan_id BIGINT UNSIGNED NOT NULL,
 borrower_label VARCHAR(255) NOT NULL,
 item_label VARCHAR(255) NOT NULL,
 amount BIGINT UNSIGNED NOT NULL,
 reason VARCHAR(1000) NOT NULL,
 state ENUM('open','void') NOT NULL DEFAULT 'open',
 created_by BIGINT UNSIGNED NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 void_by BIGINT UNSIGNED NULL,
 void_note VARCHAR(1000) NULL,
 void_at DATETIME NULL,
 KEY idx_fines_scope (library_id,source,id),
 CONSTRAINT fk_fine_library FOREIGN KEY (library_id) REFERENCES libraries(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
CREATE TABLE IF NOT EXISTS library_fine_events (
 id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
 fine_id BIGINT UNSIGNED NOT NULL,
 kind ENUM('payment','waiver','reversal') NOT NULL,
 amount BIGINT UNSIGNED NOT NULL,
 reference VARCHAR(180) NOT NULL,
 note VARCHAR(1000) NOT NULL,
 reverses_id BIGINT UNSIGNED NULL,
 actor_id BIGINT UNSIGNED NOT NULL,
 created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE KEY uq_fine_reversal (reverses_id),
 KEY idx_fine_events (fine_id,id),
 CONSTRAINT fk_fine_event FOREIGN KEY (fine_id) REFERENCES library_fines(id),
 CONSTRAINT fk_fine_reversal FOREIGN KEY (reverses_id) REFERENCES library_fine_events(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
