INSERT INTO learn_english_rpg_episodes(code,title,subtitle,description,is_active) VALUES
('market_mystery','Mystery at Sunny Market','Episode 2 · The Missing Basket','Belajar nama makanan, jumlah, harga, dan percakapan saat berbelanja.',1),
('forest_rescue','Rescue in Green Forest','Episode 3 · Save the Baby Deer','Belajar arah, anggota tubuh, cuaca, dan ungkapan meminta pertolongan.',1),
('space_station','Mission to Star Station','Episode 4 · The Silent Satellite','Belajar angka, waktu, instruksi, serta benda-benda di luar angkasa.',1),
('school_festival','The School Festival','Episode 5 · A Show to Remember','Belajar kegiatan sekolah, hobi, perasaan, dan kerja sama.',1),
('ocean_treasure','Treasure Under the Sea','Episode 6 · The Coral Crown','Belajar hewan laut, warna, posisi, dan menjaga lingkungan.',1)
ON DUPLICATE KEY UPDATE title=VALUES(title),subtitle=VALUES(subtitle),description=VALUES(description);

SET @ep=(SELECT id FROM learn_english_rpg_episodes WHERE code='market_mystery');
INSERT INTO learn_english_rpg_scenes(episode_id,sort_order,place,speaker,emoji,dialogue,translation,prompt,choices_json,vocabulary_word,vocabulary_meaning,is_active)
SELECT @ep,1,'Sunny Market','Lina','🧺','Oh no! My fruit basket is missing. Can you help me look for it?','Oh tidak! Keranjang buahku hilang. Bisakah kamu membantuku mencarinya?','Choose the helpful reply.','[{"text":"Of course. Let us find it!","correct":1,"feedback":"Great! You offered to help."},{"text":"The moon is cheese.","correct":0,"feedback":"Lina needs your help."},{"text":"I cannot see Monday.","correct":0,"feedback":"Choose a helpful response."}]','basket','keranjang',1 WHERE NOT EXISTS(SELECT 1 FROM learn_english_rpg_scenes WHERE episode_id=@ep AND sort_order=1);
INSERT INTO learn_english_rpg_scenes(episode_id,sort_order,place,speaker,emoji,dialogue,translation,prompt,choices_json,vocabulary_word,vocabulary_meaning,is_active)
SELECT @ep,2,'Fruit Stall','Mr. Budi','🍎','I saw three red apples fall near the bakery.','Aku melihat tiga apel merah jatuh dekat toko roti.','How many apples did he see?','[{"text":"Two apples","correct":0,"feedback":"Listen again: he said three."},{"text":"Three apples","correct":1,"feedback":"Correct! Three means tiga."},{"text":"Ten apples","correct":0,"feedback":"That is too many."}]','three','tiga',1 WHERE NOT EXISTS(SELECT 1 FROM learn_english_rpg_scenes WHERE episode_id=@ep AND sort_order=2);
INSERT INTO learn_english_rpg_scenes(episode_id,sort_order,place,speaker,emoji,dialogue,translation,prompt,choices_json,vocabulary_word,vocabulary_meaning,is_active)
SELECT @ep,3,'Bakery','Baker','🥖','The basket is behind the bread shelf. Please take it carefully.','Keranjangnya ada di belakang rak roti. Tolong ambil dengan hati-hati.','Where is the basket?','[{"text":"Behind the shelf","correct":1,"feedback":"Correct! Behind means di belakang."},{"text":"Above the sun","correct":0,"feedback":"Look near the bread shelf."},{"text":"Inside an apple","correct":0,"feedback":"A basket cannot fit there."}]','shelf','rak',1 WHERE NOT EXISTS(SELECT 1 FROM learn_english_rpg_scenes WHERE episode_id=@ep AND sort_order=3);

SET @ep=(SELECT id FROM learn_english_rpg_episodes WHERE code='forest_rescue');
INSERT INTO learn_english_rpg_scenes(episode_id,sort_order,place,speaker,emoji,dialogue,translation,prompt,choices_json,vocabulary_word,vocabulary_meaning,is_active)
SELECT @ep,1,'Ranger Cabin','Ranger Ana','🧭','A baby deer is lost in the forest. We must follow its footprints.','Seekor anak rusa tersesat di hutan. Kita harus mengikuti jejak kakinya.','What should you follow?','[{"text":"The footprints","correct":1,"feedback":"Yes! Footprints show where it went."},{"text":"The ceiling","correct":0,"feedback":"The deer is outside."},{"text":"A television","correct":0,"feedback":"Use the clue on the ground."}]','footprints','jejak kaki',1 WHERE NOT EXISTS(SELECT 1 FROM learn_english_rpg_scenes WHERE episode_id=@ep AND sort_order=1);
INSERT INTO learn_english_rpg_scenes(episode_id,sort_order,place,speaker,emoji,dialogue,translation,prompt,choices_json,vocabulary_word,vocabulary_meaning,is_active)
SELECT @ep,2,'River Path','Ranger Ana','🌧️','It is raining. Put on your raincoat before we cross the river.','Sedang hujan. Kenakan jas hujan sebelum kita menyeberangi sungai.','What should you wear?','[{"text":"A raincoat","correct":1,"feedback":"Correct! It keeps you dry."},{"text":"Swimming fins","correct":0,"feedback":"We are walking in the rain."},{"text":"A party hat","correct":0,"feedback":"Choose clothing for rain."}]','raincoat','jas hujan',1 WHERE NOT EXISTS(SELECT 1 FROM learn_english_rpg_scenes WHERE episode_id=@ep AND sort_order=2);
INSERT INTO learn_english_rpg_scenes(episode_id,sort_order,place,speaker,emoji,dialogue,translation,prompt,choices_json,vocabulary_word,vocabulary_meaning,is_active)
SELECT @ep,3,'Pine Hill','Baby Deer','🦌','My left leg hurts. Please call the ranger.','Kaki kiriku sakit. Tolong panggil penjaga hutan.','Which leg hurts?','[{"text":"Its left leg","correct":1,"feedback":"Right! The deer said left leg."},{"text":"Its right ear","correct":0,"feedback":"It did not mention an ear."},{"text":"Its tail","correct":0,"feedback":"Listen for the body part."}]','left','kiri',1 WHERE NOT EXISTS(SELECT 1 FROM learn_english_rpg_scenes WHERE episode_id=@ep AND sort_order=3);

SET @ep=(SELECT id FROM learn_english_rpg_episodes WHERE code='space_station');
INSERT INTO learn_english_rpg_scenes(episode_id,sort_order,place,speaker,emoji,dialogue,translation,prompt,choices_json,vocabulary_word,vocabulary_meaning,is_active)
SELECT @ep,1,'Launch Room','Captain Nova','🚀','The rocket leaves at nine o clock. We have ten minutes.','Roket berangkat pukul sembilan. Kita punya waktu sepuluh menit.','When does the rocket leave?','[{"text":"At nine o clock","correct":1,"feedback":"Correct! The launch is at nine."},{"text":"At lunchtime","correct":0,"feedback":"A specific time was given."},{"text":"Next year","correct":0,"feedback":"The rocket leaves today."}]','rocket','roket',1 WHERE NOT EXISTS(SELECT 1 FROM learn_english_rpg_scenes WHERE episode_id=@ep AND sort_order=1);
INSERT INTO learn_english_rpg_scenes(episode_id,sort_order,place,speaker,emoji,dialogue,translation,prompt,choices_json,vocabulary_word,vocabulary_meaning,is_active)
SELECT @ep,2,'Control Deck','Robot Zed','🤖','Press the green button, then pull the silver lever.','Tekan tombol hijau, lalu tarik tuas perak.','What should you do first?','[{"text":"Press the green button","correct":1,"feedback":"Yes. First, press the button."},{"text":"Pull the lever","correct":0,"feedback":"That happens after the button."},{"text":"Open the window","correct":0,"feedback":"Windows stay closed in space."}]','button','tombol',1 WHERE NOT EXISTS(SELECT 1 FROM learn_english_rpg_scenes WHERE episode_id=@ep AND sort_order=2);
INSERT INTO learn_english_rpg_scenes(episode_id,sort_order,place,speaker,emoji,dialogue,translation,prompt,choices_json,vocabulary_word,vocabulary_meaning,is_active)
SELECT @ep,3,'Star Station','Captain Nova','🛰️','The satellite is above us, but its antenna is broken.','Satelit berada di atas kita, tetapi antenanya rusak.','What is broken?','[{"text":"The antenna","correct":1,"feedback":"Correct! The antenna needs repair."},{"text":"The planet","correct":0,"feedback":"A planet is not broken."},{"text":"The captain","correct":0,"feedback":"Captain Nova is fine."}]','broken','rusak',1 WHERE NOT EXISTS(SELECT 1 FROM learn_english_rpg_scenes WHERE episode_id=@ep AND sort_order=3);

SET @ep=(SELECT id FROM learn_english_rpg_episodes WHERE code='school_festival');
INSERT INTO learn_english_rpg_scenes(episode_id,sort_order,place,speaker,emoji,dialogue,translation,prompt,choices_json,vocabulary_word,vocabulary_meaning,is_active)
SELECT @ep,1,'Classroom','Ms. Rani','🎪','Our class will perform at the festival. What can you do?','Kelas kita akan tampil di festival. Apa yang bisa kamu lakukan?','Choose a natural answer.','[{"text":"I can sing a song.","correct":1,"feedback":"Wonderful! That is a useful talent."},{"text":"I can yesterday.","correct":0,"feedback":"Use can plus an action word."},{"text":"I am five pencils.","correct":0,"feedback":"Tell the teacher an ability."}]','perform','tampil',1 WHERE NOT EXISTS(SELECT 1 FROM learn_english_rpg_scenes WHERE episode_id=@ep AND sort_order=1);
INSERT INTO learn_english_rpg_scenes(episode_id,sort_order,place,speaker,emoji,dialogue,translation,prompt,choices_json,vocabulary_word,vocabulary_meaning,is_active)
SELECT @ep,2,'Music Room','Dito','🎸','I feel nervous because many people will watch us.','Aku merasa gugup karena banyak orang akan menonton kita.','How does Dito feel?','[{"text":"Nervous","correct":1,"feedback":"Correct! Nervous means gugup."},{"text":"Hungry","correct":0,"feedback":"He is worried about performing."},{"text":"Sleepy","correct":0,"feedback":"He did not say he was tired."}]','nervous','gugup',1 WHERE NOT EXISTS(SELECT 1 FROM learn_english_rpg_scenes WHERE episode_id=@ep AND sort_order=2);
INSERT INTO learn_english_rpg_scenes(episode_id,sort_order,place,speaker,emoji,dialogue,translation,prompt,choices_json,vocabulary_word,vocabulary_meaning,is_active)
SELECT @ep,3,'Festival Stage','Ms. Rani','🎤','Work together, smile, and enjoy the show!','Bekerjalah bersama, tersenyum, dan nikmati pertunjukannya!','Which action shows teamwork?','[{"text":"Helping each other","correct":1,"feedback":"Exactly! A team helps one another."},{"text":"Hiding every instrument","correct":0,"feedback":"That stops the performance."},{"text":"Leaving your friends","correct":0,"feedback":"Stay and work with the team."}]','together','bersama',1 WHERE NOT EXISTS(SELECT 1 FROM learn_english_rpg_scenes WHERE episode_id=@ep AND sort_order=3);

SET @ep=(SELECT id FROM learn_english_rpg_episodes WHERE code='ocean_treasure');
INSERT INTO learn_english_rpg_scenes(episode_id,sort_order,place,speaker,emoji,dialogue,translation,prompt,choices_json,vocabulary_word,vocabulary_meaning,is_active)
SELECT @ep,1,'Coral Bay','Captain Coral','🐠','The golden map points to a cave beneath the blue coral.','Peta emas menunjuk ke gua di bawah karang biru.','Where is the cave?','[{"text":"Beneath the blue coral","correct":1,"feedback":"Correct! Beneath means di bawah."},{"text":"Above the clouds","correct":0,"feedback":"We are under the sea."},{"text":"Inside the boat","correct":0,"feedback":"Follow the golden map."}]','beneath','di bawah',1 WHERE NOT EXISTS(SELECT 1 FROM learn_english_rpg_scenes WHERE episode_id=@ep AND sort_order=1);
INSERT INTO learn_english_rpg_scenes(episode_id,sort_order,place,speaker,emoji,dialogue,translation,prompt,choices_json,vocabulary_word,vocabulary_meaning,is_active)
SELECT @ep,2,'Turtle Garden','Timo','🐢','A plastic bag is stuck on the coral. Please remove it gently.','Kantong plastik tersangkut di karang. Tolong lepaskan dengan lembut.','What should you remove?','[{"text":"The plastic bag","correct":1,"feedback":"Yes! Keep the ocean clean."},{"text":"The turtle shell","correct":0,"feedback":"Never remove a turtle shell."},{"text":"All the coral","correct":0,"feedback":"Coral belongs in the sea."}]','gently','dengan lembut',1 WHERE NOT EXISTS(SELECT 1 FROM learn_english_rpg_scenes WHERE episode_id=@ep AND sort_order=2);
INSERT INTO learn_english_rpg_scenes(episode_id,sort_order,place,speaker,emoji,dialogue,translation,prompt,choices_json,vocabulary_word,vocabulary_meaning,is_active)
SELECT @ep,3,'Pearl Cave','Captain Coral','🐚','The crown is inside the purple shell. We found the treasure!','Mahkotanya ada di dalam kerang ungu. Kita menemukan harta karunnya!','What color is the shell?','[{"text":"Purple","correct":1,"feedback":"Correct! The shell is purple."},{"text":"Orange","correct":0,"feedback":"Listen to the color again."},{"text":"Black","correct":0,"feedback":"The captain said purple."}]','treasure','harta karun',1 WHERE NOT EXISTS(SELECT 1 FROM learn_english_rpg_scenes WHERE episode_id=@ep AND sort_order=3);
