-- Katalog Story Quiz SD–SMA. Idempotent untuk passage dan soal bawaan ini.
UPDATE learn_story_passages SET subject_id=2,grade_level_id=3 WHERE code='semut_belalang';
INSERT INTO learn_story_passages(code,title,body,summary,subject_id,grade_level_id,icon,color,estimated_minutes,sort_order,is_active) VALUES
('payung_mila','Payung Merah Mila','Pagi itu hujan turun. Mila membawa payung merah ke sekolah. Di jalan, ia melihat Rani berdiri tanpa payung. Mila mengajak Rani berjalan bersama. Mereka tiba di sekolah dengan pakaian tetap kering.','Cerita sederhana tentang berbagi dan persahabatan.',2,3,'ti-umbrella','#ec4899',2,10,1),
('kebun_kelas','Kebun Kecil di Kelas','Murid kelas dua menanam kacang hijau. Setiap kelompok memberi air secukupnya dan meletakkan pot dekat jendela. Beberapa hari kemudian, akar muncul lalu batang tumbuh ke arah cahaya. Mereka mencatat perubahan setiap pagi.','Mengamati pertumbuhan tanaman melalui kegiatan kelas.',39,4,'ti-seeding','#16a34a',3,20,1),
('surat_dari_pantai','Surat dari Pantai Karangjahe','Dita mengunjungi Pantai Karangjahe bersama keluarganya. Ia melihat deretan cemara, pasir luas, dan nelayan yang merapikan perahu. Sebelum pulang, keluarga Dita memungut sampah di sekitar tempat duduk. Dita menulis surat kepada temannya tentang pentingnya menjaga pantai.','Perjalanan lokal yang mengajarkan kepedulian lingkungan.',2,5,'ti-beach','#0ea5e9',3,30,1),
('pasar_jujur','Kembalian di Pasar','Bimo membeli buah seharga Rp18.000 dan membayar dengan uang Rp20.000. Pedagang tidak sengaja memberikan kembalian Rp5.000. Bimo menghitung ulang lalu mengembalikan kelebihan uang tersebut. Pedagang berterima kasih atas kejujurannya.','Literasi numerasi dan sikap jujur dalam kehidupan sehari-hari.',1,6,'ti-building-store','#f59e0b',3,40,1),
('mangrove_penjaga','Mangrove Sang Penjaga Pesisir','Akar mangrove yang rapat memperlambat gelombang dan menahan lumpur. Hutan mangrove juga menjadi tempat hidup ikan kecil, kepiting, dan burung. Warga menanam bibit baru karena memahami bahwa mangrove melindungi pesisir sekaligus mendukung kehidupan nelayan.','Mengenal fungsi ekologis hutan mangrove.',39,7,'ti-tree','#059669',4,50,1),
('kode_rahasia','Kode Rahasia Perpustakaan','Laras menemukan pesan berpola 2, 4, 8, 16 di sebuah buku. Ia menyadari setiap bilangan merupakan dua kali bilangan sebelumnya. Angka berikutnya membuka laci katalog yang berisi peta koleksi langka. Laras menyerahkan temuannya kepada pustakawan.','Petualangan pola bilangan dan tanggung jawab.',1,8,'ti-lock-code','#7c3aed',4,60,1),
('air_desa','Perjalanan Setetes Air','Air laut menguap karena panas matahari. Uap naik, mendingin, lalu membentuk awan. Ketika titik air semakin berat, hujan turun ke perbukitan. Sebagian meresap menjadi air tanah dan sebagian mengalir melalui sungai kembali ke laut.','Siklus air dijelaskan melalui perjalanan setetes air.',4,9,'ti-droplet','#0284c7',4,70,1),
('jejak_digital','Jejak yang Tidak Mudah Hilang','Nara hampir mengunggah foto temannya tanpa izin. Ia teringat bahwa unggahan dapat disalin dan tersimpan lama. Nara meminta izin terlebih dahulu, menghapus informasi lokasi, lalu membatasi siapa yang dapat melihatnya. Temannya menghargai keputusan itu.','Literasi privasi dan tanggung jawab di ruang digital.',10,10,'ti-shield-lock','#0f766e',4,80,1),
('english_green_school','A Greener School','The student council noticed that many plastic cups were thrown away every day. They installed water refill stations and asked students to bring reusable bottles. After one month, plastic waste decreased significantly. The project succeeded because students changed a small daily habit together.','English reading about collective environmental action.',3,11,'ti-language','#2563eb',5,90,1),
('energi_surya','Ketika Atap Sekolah Menghasilkan Listrik','Panel surya mengubah energi cahaya menjadi energi listrik. Pada siang hari, listrik digunakan untuk membantu menyalakan komputer dan lampu sekolah. Produksi listrik berkurang ketika langit mendung, sehingga sekolah tetap terhubung dengan jaringan listrik. Data harian dipakai siswa untuk membandingkan cuaca dan energi.','Membaca data dan konsep perubahan energi surya.',15,12,'ti-solar-panel','#ea580c',5,100,1),
('sel_penjaga','Pasukan Penjaga Tubuh','Saat bakteri masuk melalui luka, sel darah putih bergerak menuju jaringan yang terinfeksi. Beberapa sel menelan patogen, sedangkan sel lain membantu membentuk respons imun khusus. Peradangan membuat daerah luka tampak merah dan hangat, tetapi proses itu merupakan bagian pertahanan tubuh.','Kisah ilmiah mengenai respons imun tubuh.',14,13,'ti-microscope','#16a34a',5,110,1),
('plastik_biodegradasi','Dilema Plastik Biodegradabel','Plastik biodegradabel dirancang agar dapat diuraikan mikroorganisme pada kondisi tertentu. Namun, tidak semua produk terurai cepat di laut atau tempat pembuangan biasa. Karena itu, label biodegradabel bukan alasan untuk memakai barang sekali pakai tanpa batas. Pengurangan konsumsi dan pengelolaan limbah tetap diperlukan.','Teks kritis tentang klaim bahan ramah lingkungan.',16,14,'ti-flask','#db2777',6,120,1)
ON DUPLICATE KEY UPDATE title=VALUES(title),body=VALUES(body),summary=VALUES(summary),subject_id=VALUES(subject_id),grade_level_id=VALUES(grade_level_id),icon=VALUES(icon),color=VALUES(color),estimated_minutes=VALUES(estimated_minutes),is_active=1;

DROP TEMPORARY TABLE IF EXISTS tmp_story_q;
CREATE TEMPORARY TABLE tmp_story_q(code VARCHAR(60),question VARCHAR(500),a VARCHAR(300),b VARCHAR(300),c VARCHAR(300),d VARCHAR(300),correct_option TINYINT,explanation VARCHAR(500),sort_order INT) DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
INSERT INTO tmp_story_q VALUES
('payung_mila','Mengapa pakaian Mila dan Rani tetap kering?','Mereka berlari','Mereka berbagi payung','Hujan berhenti','Mereka naik bus',1,'Mila mengajak Rani berjalan bersama di bawah payung.',1),('payung_mila','Sifat Mila dalam cerita adalah ...','Peduli','Ceroboh','Pemarah','Malas',0,'Mila peduli kepada teman yang tidak membawa payung.',2),
('kebun_kelas','Mengapa pot diletakkan dekat jendela?','Agar terkena cahaya','Agar tidak terlihat','Agar lebih berat','Agar cepat kering',0,'Tanaman memerlukan cahaya untuk tumbuh.',1),('kebun_kelas','Apa yang dilakukan murid setiap pagi?','Mengganti pot','Memetik daun','Mencatat perubahan','Membuang tanaman',2,'Mereka mengamati dan mencatat perubahan tanaman.',2),
('surat_dari_pantai','Apa tujuan keluarga Dita memungut sampah?','Menghias pantai','Menjaga kebersihan pantai','Mencari kerang','Membantu nelayan',1,'Tindakan tersebut menjaga lingkungan pantai.',1),('surat_dari_pantai','Media yang dipakai Dita menceritakan pengalaman adalah ...','Poster','Surat','Iklan','Puisi',1,'Dita menulis surat kepada temannya.',2),
('pasar_jujur','Kembalian yang seharusnya diterima Bimo adalah ...','Rp1.000','Rp2.000','Rp3.000','Rp5.000',1,'Rp20.000 dikurangi Rp18.000 sama dengan Rp2.000.',1),('pasar_jujur','Mengapa Bimo mengembalikan uang?','Uangnya rusak','Buahnya kurang','Kembaliannya berlebih','Pedagang memintanya',2,'Pedagang keliru memberi kembalian Rp5.000.',2),
('mangrove_penjaga','Bagaimana akar mangrove melindungi pesisir?','Mempercepat gelombang','Menahan lumpur dan memperlambat gelombang','Mengeringkan laut','Mengusir ikan',1,'Akar rapat meredam gelombang dan menahan sedimen.',1),('mangrove_penjaga','Mengapa mangrove penting bagi nelayan?','Menjadi habitat biota laut','Mengubah air menjadi tawar','Menghilangkan pasang','Membuat perahu',0,'Ikan kecil dan biota lain hidup di kawasan mangrove.',2),
('kode_rahasia','Angka berikutnya pada pola adalah ...','18','24','30','32',3,'Setiap bilangan dikali dua sehingga 16 menjadi 32.',1),('kode_rahasia','Apa yang dilakukan Laras setelah menemukan koleksi?','Menyembunyikannya','Menjualnya','Menyerahkannya kepada pustakawan','Membawanya pulang',2,'Laras menunjukkan sikap bertanggung jawab.',2),
('air_desa','Proses uap air mendingin dan membentuk awan disebut ...','Evaporasi','Kondensasi','Infiltrasi','Erosi',1,'Pendinginan uap menjadi titik air adalah kondensasi.',1),('air_desa','Ke mana air akhirnya kembali?','Laut','Awan saja','Matahari','Pepohonan saja',0,'Sungai mengalirkan air kembali menuju laut.',2),
('jejak_digital','Mengapa Nara meminta izin?','Agar fotonya viral','Untuk menghormati privasi teman','Agar mendapat hadiah','Karena ponselnya rusak',1,'Foto orang lain menyangkut privasi mereka.',1),('jejak_digital','Tindakan keamanan lain yang dilakukan Nara adalah ...','Menambah lokasi','Membuka akun','Menghapus informasi lokasi','Menyebarkan kata sandi',2,'Informasi lokasi dapat menimbulkan risiko privasi.',2),
('english_green_school','What caused plastic waste to decrease?','Students used more cups','Students brought reusable bottles','The school closed','Teachers removed water',1,'Reusable bottles replaced many disposable cups.',1),('english_green_school','What is the main message?','Small collective habits can create change','Plastic is always harmless','Only teachers can act','Refill stations waste water',0,'The project worked through a shared daily habit.',2),
('energi_surya','Perubahan energi pada panel surya adalah ...','Listrik menjadi cahaya','Cahaya menjadi listrik','Panas menjadi gerak','Kimia menjadi panas',1,'Panel surya mengubah energi cahaya menjadi listrik.',1),('energi_surya','Mengapa produksi menurun saat mendung?','Cahaya matahari berkurang','Komputer mati','Panel menjadi berat','Jaringan terputus',0,'Awan mengurangi cahaya yang mencapai panel.',2),
('sel_penjaga','Sel apa yang bergerak ke jaringan terinfeksi?','Sel darah merah','Sel darah putih','Sel tulang','Sel lemak',1,'Sel darah putih berperan dalam pertahanan tubuh.',1),('sel_penjaga','Peradangan pada bacaan merupakan ...','Bagian respons pertahanan','Tanda tubuh berhenti bekerja','Proses pencernaan','Pembentukan tulang',0,'Merah dan hangat dapat muncul dalam respons imun.',2),
('plastik_biodegradasi','Mengapa label biodegradabel tidak cukup?','Semua plastik langsung hilang','Penguraian memerlukan kondisi tertentu','Produk tidak punya warna','Mikroorganisme tidak ada',1,'Tidak semua lingkungan menyediakan kondisi penguraian yang sesuai.',1),('plastik_biodegradasi','Kesimpulan bacaan adalah ...','Pemakaian sekali pakai boleh tanpa batas','Pengurangan konsumsi tetap diperlukan','Semua sampah harus dibakar','Laut menguraikan semua plastik',1,'Bahan alternatif tetap harus disertai pengurangan dan pengelolaan limbah.',2);

DELETE q FROM learn_story_questions q JOIN learn_story_passages p ON p.id=q.passage_id JOIN (SELECT DISTINCT code FROM tmp_story_q) t ON t.code=p.code;
INSERT INTO learn_story_questions(passage_id,question,option_a,option_b,option_c,option_d,correct_option,explanation,sort_order,is_active)
SELECT p.id,t.question,t.a,t.b,t.c,t.d,t.correct_option,t.explanation,t.sort_order,1 FROM tmp_story_q t JOIN learn_story_passages p ON p.code=t.code;
DROP TEMPORARY TABLE tmp_story_q;
